Project Parsec: RunGrimoire Class Reference
RunGrimoire Class Reference
#include <runGrimoire.h>
Public Member Functions
RunGrimoire ()
bool init ()
bool load ()
void run ()
Protected Member Functions
void toggle (bool &myBool)
void getInput ()
void processInput ()
void update ()
void draw ()
Private Types
enum MENUSTATES {
TAB1, TAB2, TAB3, TAB4,
TAB5, TAB6, TAB7, TAB8,
TAB9, TAB10, TAB11, TAB12
}
Private Attributes
int menuState
Keyboard keyboard
Detailed Description
Definition at line 11 of file runGrimoire.h.
Member Enumeration Documentation
MENUSTATES
enum RunGrimoire::MENUSTATES private
Enumerator
TAB1
TAB2
TAB3
TAB4
TAB5
TAB6
TAB7
TAB8
TAB9
TAB10
TAB11
TAB12
Definition at line 13 of file runGrimoire.h.
Constructor & Destructor Documentation
RunGrimoire()
RunGrimoire::RunGrimoire ()
Definition at line 33 of file runGrimoire.h.
References keyboard, menuState, and TAB1.
Member Function Documentation
draw()
void RunGrimoire::draw () protected
Definition at line 175 of file runGrimoire.h.
getInput()
void RunGrimoire::getInput () protected
Definition at line 101 of file runGrimoire.h.
References Core::GameVars::controls, Core::GameVars::debug, Core::gameVars, keyboard, processInput(), and Core::GameVars::screen.
Referenced by run().
init()
bool RunGrimoire::init ()
Definition at line 38 of file runGrimoire.h.
load()
bool RunGrimoire::load ()
Definition at line 42 of file runGrimoire.h.
processInput()
void RunGrimoire::processInput () protected
Definition at line 122 of file runGrimoire.h.
References Core::GameVars::controls, Core::gameVars, keyboard, and Core::GameVars::screen.
Referenced by getInput().
run()
void RunGrimoire::run ()
Definition at line 46 of file runGrimoire.h.
References Battle, Core::GameVars::Screen::clear, RunBattle::draw(), Core::GameVars::font, Core::gameVars, getInput(), GL_TRUE, h, Core::GameVars::screen, Core::GameVars::Font::screenCoords, update(), _TheVoid::Update(), Core::GameVars::Font::vSize, w, world, x, and y.
toggle()
void RunGrimoire::toggle (bool & myBool) protected
Definition at line 179 of file runGrimoire.h.
update()
void RunGrimoire::update () protected
Definition at line 95 of file runGrimoire.h.
Referenced by run().
Member Data Documentation
keyboard
Keyboard RunGrimoire::keyboard private
Definition at line 15 of file runGrimoire.h.
Referenced by getInput(), processInput(), and RunGrimoire().
menuState
int RunGrimoire::menuState private
Definition at line 14 of file runGrimoire.h.
Referenced by RunGrimoire().
The documentation for this class was generated from the following file:
src/game/ref/runGrimoire.h