Project Parsec: RunConsole Class Reference
RunConsole Class Reference
#include <runConsole.h>
Public Member Functions
RunConsole ()
bool init ()
bool load ()
bool calc ()
void run ()
void input ()
Protected Member Functions
void start (int x, int y)
void stop ()
void update ()
void draw ()
void execScript ()
void showCommands ()
void shuffleBuffer (std::string command)
Private Types
typedef std::map< std::string, float * > FloatList
typedef std::map< std::string, int * > IntList
typedef std::map< std::string, bool * > BoolList
Private Attributes
GLuint index
GLfloat(* pArray)[2]
std::string loadFile
std::string theImage
std::string tempImage
int tempID
GLenum texture_format
GLint nOfColors
MemBlock memBlock
FloatList * floatList
IntList * intList
BoolList * boolList
Keyboard keyboard
Detailed Description
Definition at line 11 of file runConsole.h.
Member Typedef Documentation
BoolList
typedef std::map< std::string, bool* > RunConsole::BoolList private
Definition at line 24 of file runConsole.h.
FloatList
typedef std::map< std::string, float* > RunConsole::FloatList private
Definition at line 22 of file runConsole.h.
IntList
typedef std::map< std::string, int* > RunConsole::IntList private
Definition at line 23 of file runConsole.h.
Constructor & Destructor Documentation
RunConsole()
RunConsole::RunConsole ()
Definition at line 50 of file runConsole.h.
References boolList, floatList, GL_RGBA, intList, keyboard, nOfColors, pArray, tempID, and texture_format.
Member Function Documentation
calc()
bool RunConsole::calc ()
Definition at line 71 of file runConsole.h.
References Core::GameVars::Player::active, boolList, Core::GameVars::Screen::bpp, Core::GameVars::Screen::clear, Core::GameVars::controls, Core::GameVars::debug, floatList, Core::GameVars::Controls::fly, Core::GameVars::font, Core::GameVars::Screen::frameRate, Core::gameVars, GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, intList, Core::GameVars::Controls::moveSpeed, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameSys::CharSheet::Transform::rot, Core::GameVars::screen, Core::GameSys::CharSheet::transform, and Core::GameVars::Font::vSize.
draw()
void RunConsole::draw () protected
Definition at line 395 of file runConsole.h.
execScript()
void RunConsole::execScript () protected
Definition at line 399 of file runConsole.h.
References boolList, floatList, Core::gameVars, intList, Core::itoa(), keyboard, and shuffleBuffer().
Referenced by input().
init()
bool RunConsole::init ()
Definition at line 63 of file runConsole.h.
input()
void RunConsole::input ()
Definition at line 342 of file runConsole.h.
References execScript(), Core::gameVars, keyboard, Core::GameVars::screen, and showCommands().
Referenced by run().
load()
bool RunConsole::load ()
Definition at line 67 of file runConsole.h.
run()
void RunConsole::run ()
Definition at line 310 of file runConsole.h.
References Core::GameVars::controls, Core::GameVars::debug, Core::gameVars, GL_DEPTH_BUFFER_BIT, GL_TRUE, input(), keyboard, Core::GameVars::screen, and update().
showCommands()
void RunConsole::showCommands () protected
Definition at line 462 of file runConsole.h.
References boolList, floatList, intList, keyboard, and shuffleBuffer().
Referenced by input().
shuffleBuffer()
void RunConsole::shuffleBuffer (std::string command) protected
Definition at line 455 of file runConsole.h.
References keyboard.
Referenced by execScript(), and showCommands().
start()
void RunConsole::start (int x, int y) protected
Definition at line 294 of file runConsole.h.
References Core::GameVars::font, Core::gameVars, GL_DEPTH_TEST, GL_TRUE, Core::GLS_FONT, Core::GameVars::Font::screenCoords, and Core::GameVars::Font::vSize.
Referenced by update().
stop()
void RunConsole::stop () protected
Definition at line 304 of file runConsole.h.
References GL_DEPTH_TEST.
Referenced by update().
update()
void RunConsole::update () protected
Definition at line 357 of file runConsole.h.
References Core::GameVars::font, Core::gameVars, Core::GLS_FONT, keyboard, start(), stop(), _TheVoid::Update(), Core::GameVars::Font::vHalfSize, Core::GameVars::Font::vSize, and world.
Referenced by run().
Member Data Documentation
boolList
BoolList* RunConsole::boolList private
Definition at line 27 of file runConsole.h.
Referenced by calc(), execScript(), RunConsole(), and showCommands().
floatList
FloatList* RunConsole::floatList private
Definition at line 25 of file runConsole.h.
Referenced by calc(), execScript(), RunConsole(), and showCommands().
index
GLuint RunConsole::index private
Definition at line 13 of file runConsole.h.
intList
IntList* RunConsole::intList private
Definition at line 26 of file runConsole.h.
Referenced by calc(), execScript(), RunConsole(), and showCommands().
keyboard
Keyboard RunConsole::keyboard private
Definition at line 28 of file runConsole.h.
Referenced by execScript(), input(), run(), RunConsole(), showCommands(), shuffleBuffer(), and update().
loadFile
std::string RunConsole::loadFile private
Definition at line 15 of file runConsole.h.
memBlock
MemBlock RunConsole::memBlock private
Definition at line 21 of file runConsole.h.
nOfColors
GLint RunConsole::nOfColors private
Definition at line 20 of file runConsole.h.
Referenced by RunConsole().
pArray
GLfloat(* RunConsole::pArray)[2] private
Definition at line 14 of file runConsole.h.
Referenced by RunConsole().
tempID
int RunConsole::tempID private
Definition at line 18 of file runConsole.h.
Referenced by RunConsole().
tempImage
std::string RunConsole::tempImage private
Definition at line 17 of file runConsole.h.
texture_format
GLenum RunConsole::texture_format private
Definition at line 19 of file runConsole.h.
Referenced by RunConsole().
theImage
std::string RunConsole::theImage private
Definition at line 16 of file runConsole.h.
The documentation for this class was generated from the following file:
src/game/ref/runConsole.h