Project Parsec: E2D Class Reference
E2D Class Reference
#include <E2D.h>
Public Member Functions
bool load (int iShift)
void shift (int iShift)
bool calc (bool bUpdate)
void execute ()
void loadEvent (Vector4ui vEvent)
E2D (WorldMap &m, Atmosphere &a)
~E2D ()
Public Member Functions inherited from E2D_BASE
E2D_BASE (Atmosphere &a)
bool init ()
void clear ()
bool calc (bool bUpdate)
void draw (int iShader)
Private Attributes
WorldMap & map
Additional Inherited Members
Public Attributes inherited from E2D_BASE
E2dData data [9][9]
Atmosphere & atmosphere
Detailed Description
Definition at line 35 of file E2D.h.
Constructor & Destructor Documentation
E2D()
E2D::E2D (WorldMap & m, Atmosphere & a) inline
Definition at line 45 of file E2D.h.
~E2D()
E2D::~E2D () inline
Definition at line 46 of file E2D.h.
References cout.
Member Function Documentation
calc()
bool E2D::calc (bool bUpdate = false)
Definition at line 394 of file E2D.h.
References cout, Core::GameVars::debug, Core::gameVars, GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, Core::GameVars::screen, x, and z.
Referenced by _TheVoid::load(), and shift().
execute()
void E2D::execute ()
Definition at line 509 of file E2D.h.
References Core::GameVars::Player::active, Core::gameVars, loadEvent(), map, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::screen, Core::GameSys::CharSheet::transform, WorldMap::vBase, x, and z.
Referenced by _TheVoid::ProcessInput().
load()
bool E2D::load (int iShift = SHIFT_LAST)
Definition at line 123 of file E2D.h.
References Core::GameVars::Player::active, cout, Core::GameVars::debug, WorldMap::dir, Core::gameVars, map, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::readFile(), Core::GameVars::screen, Core::GameSys::CharSheet::transform, WorldMap::vBase, x, and z.
Referenced by _TheVoid::load(), and shift().
loadEvent()
void E2D::loadEvent (Vector4ui vEvent)
Definition at line 553 of file E2D.h.
References cout, Core::GameVars::debug, WorldMap::dir, Core::gameVars, id, map, Core::readFile(), xMap, and zMap.
Referenced by execute().
shift()
void E2D::shift (int iShift)
Definition at line 65 of file E2D.h.
References calc(), cout, Core::gameVars, load(), and Core::GameVars::screen.
Referenced by _TheVoid::reload().
Member Data Documentation
map
WorldMap& E2D::map private
Definition at line 37 of file E2D.h.
Referenced by execute(), load(), and loadEvent().
The documentation for this class was generated from the following file:
src/headers/gamesys/ref/E2D.h