Project Parsec: RunEndBattle Class Reference
RunEndBattle Class Reference
#include <runEndBattle.h>
Public Member Functions
RunEndBattle ()
bool init ()
bool load ()
void run ()
Protected Member Functions
void toggle (bool &myBool)
void getInput ()
void processInput ()
void update ()
void draw ()
Private Attributes
Keyboard keyboard
Detailed Description
Definition at line 11 of file runEndBattle.h.
Constructor & Destructor Documentation
RunEndBattle()
RunEndBattle::RunEndBattle ()
Definition at line 31 of file runEndBattle.h.
References keyboard.
Member Function Documentation
draw()
void RunEndBattle::draw () protected
Definition at line 234 of file runEndBattle.h.
getInput()
void RunEndBattle::getInput () protected
Definition at line 159 of file runEndBattle.h.
References Core::GameVars::controls, Core::GameVars::debug, Core::gameVars, keyboard, processInput(), and Core::GameVars::screen.
Referenced by run().
init()
bool RunEndBattle::init ()
Definition at line 35 of file runEndBattle.h.
load()
bool RunEndBattle::load ()
Definition at line 39 of file runEndBattle.h.
processInput()
void RunEndBattle::processInput () protected
Definition at line 180 of file runEndBattle.h.
References Core::GameVars::controls, Core::gameVars, keyboard, and Core::GameVars::screen.
Referenced by getInput().
run()
void RunEndBattle::run ()
Definition at line 43 of file runEndBattle.h.
References Core::GameVars::Player::active, Battle, Core::GameVars::Screen::clear, RunBattle::draw(), RunBattle::enemies, Core::GameVars::font, Core::gameVars, getInput(), GL_TRUE, h, RunBattle::numEnemy, Core::GameVars::player, Core::GameVars::screen, Core::GameVars::Font::screenCoords, update(), _TheVoid::Update(), Core::GameVars::Font::vSize, w, world, x, and y.
toggle()
void RunEndBattle::toggle (bool & myBool) protected
Definition at line 238 of file runEndBattle.h.
update()
void RunEndBattle::update () protected
Definition at line 153 of file runEndBattle.h.
Referenced by run().
Member Data Documentation
keyboard
Keyboard RunEndBattle::keyboard private
Definition at line 13 of file runEndBattle.h.
Referenced by getInput(), processInput(), and RunEndBattle().
The documentation for this class was generated from the following file:
src/game/ref/runEndBattle.h