Project Parsec: _Game Class Reference
_Game Class Reference
#include <runGame.h>
Public Member Functions
bool load ()
void Run ()
_Game ()
~_Game ()
Public Attributes
Core::Vector3f vDebugAttDelta
Core::Vector3f vDebugPosDelta
int iDebugLight
int iDebugObject
bool bDebugDrawMouseRay
Core::Vector3f vDebugRotation
Private Member Functions
void GetInput ()
void ProcessInput ()
void Update ()
Private Attributes
Core::_Keyboard keyboard
Core::GameSys::_WorldMap * world
Core::GameSys::AnimationSys * animation
bool bOneShot [64]
bool bHasFocus
float fTest_fScaleOld
Static Private Attributes
static const int iPlayerLight = 0
Friends
class _Admin
Detailed Description
Definition at line 17 of file runGame.h.
Constructor & Destructor Documentation
_Game()
_Game::_Game () inline
Definition at line 52 of file runGame.h.
References animation, Core::audioSys, bDebugDrawMouseRay, bHasFocus, bOneShot, Core::_Keyboard::calc(), Core::collision, Core::GameVars::Screen::fScale, fTest_fScaleOld, Core::gameVars, Core::helper, iDebugLight, iDebugObject, keyboard, Core::GameVars::screen, and world.
~_Game()
_Game::~_Game () inline
Definition at line 103 of file runGame.h.
References animation, and world.
Member Function Documentation
GetInput()
void _Game::GetInput () private
Definition at line 1081 of file runGame.h.
References bHasFocus, Core::_Keyboard::event, Core::gameVars, Core::GameVars::Screen::half, keyboard, Core::mouse, ProcessInput(), Core::GameVars::screen, Core::_Mouse::update(), Core::_Keyboard::update(), and Core::Vector2f::y.
Referenced by Run().
load()
bool _Game::load ()
Definition at line 114 of file runGame.h.
References animation, Core::GameSys::_WorldMap::calc(), Core::GameSys::AnimationSys::calc(), Core::_ParticleEmitter::calc(), Core::_ParticleEmitter::create(), Core::GameSys::_O3D::data, Core::GameVars::Screen::fScale, Core::gameVars, Core::_Lights::GetPos(), iDebugLight, iDebugObject, Core::_Mouse::init(), Core::GameSys::AnimationSys::init(), Core::GameSys::_O3D::_O3DCollection::items, Core::GameSys::_WorldMap::lights, Core::GameSys::_WorldMap::load(), Core::GameSys::AnimationSys::load(), Core::mouse, Core::GameSys::_WorldMap::o3d, Core::particles, Core::GameSys::_O3DData::posMod, Core::GameVars::screen, vDebugAttDelta, vDebugPosDelta, world, Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by main().
ProcessInput()
void _Game::ProcessInput () private
Definition at line 1093 of file runGame.h.
References Core::GameVars::Player::active, Core::GameVars::RunState::admin, bDebugDrawMouseRay, bHasFocus, Core::_Collision::bUpdateRequest, Core::collision, Core::GameVars::controls, Core::GameSys::_O3D::data, Core::GameVars::Timers::frameRate, Core::gameVars, Core::_Lights::GetNumLights(), Core::_Lights::GetPos(), Core::glinit, Core::GameVars::Screen::half, Core::GameSys::_O3D::_O3DCollection::idcount, iDebugLight, iDebugObject, iPlayerLight, Core::GameSys::_O3D::_O3DCollection::items, Core::GameVars::Controls::key, keyboard, Core::_Keyboard::keys, Core::GameSys::CharSheet::Transform::last, Core::GameSys::_WorldMap::lights, Core::GameVars::Controls::modSpeed, Core::mouse, Core::GameVars::Controls::_KeyBinding::mouse_down, Core::GameVars::Controls::_KeyBinding::mouse_left, Core::GameVars::Controls::_KeyBinding::mouse_right, Core::GameVars::Controls::_KeyBinding::mouse_up, Core::GameVars::Controls::_KeyBinding::move_back, Core::GameVars::Controls::_KeyBinding::move_down, Core::GameVars::Controls::_KeyBinding::move_forward, Core::GameVars::Controls::_KeyBinding::move_up, Core::GameVars::Controls::moveSpeed, Core::GameSys::_WorldMap::o3d, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameSys::_O3DData::posMod, Core::profiles, Core::GameVars::RunState::quit, Core::_Mouse::relX, Core::_Mouse::relY, Core::_Profile::reset(), Core::GameSys::CharSheet::Transform::rot, Core::GameVars::Controls::_KeyBinding::run, Core::GameVars::runState, Core::_Mouse::SaveRay(), Core::GameVars::screen, Core::_Lights::SetPos(), Core::GameVars::Controls::_KeyBinding::sneak, Core::Timer::split(), Core::GameVars::Controls::_KeyBinding::strafe_left, Core::GameVars::Controls::_KeyBinding::strafe_right, Core::GameVars::timer, Core::Radians::toDegrees(), Core::toggle(), Core::_Mouse::ToggleMouse(), Core::Degrees::toRadians(), Core::GameSys::CharSheet::transform, vDebugRotation, world, Core::Vector3f::x, Core::Vector2f::y, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by GetInput().
Run()
void _Game::Run ()
Definition at line 290 of file runGame.h.
References Core::GameVars::Player::active, Core::gameVars, GetInput(), Core::_Mouse::GetMouseRay(), Core::mouse, Core::particles, Core::GameVars::player, Core::profiles, Core::GameVars::Screen::res, Core::GameSys::CharSheet::Transform::rot, Core::_Profile::runProfile(), Core::GameVars::screen, Core::GameSys::CharSheet::transform, Update(), Core::_ParticleEmitter::update(), and Core::Vector2f::y.
Referenced by main().
Update()
void _Game::Update () private
Definition at line 362 of file runGame.h.
References Core::GameVars::Player::active, animation, Core::PostProcess::ApplyBrightness(), Core::PostProcess::ApplyBrightnessFilter(), Core::PostProcess::ApplyCombine(), Core::PostProcess::ApplyContrast(), Core::PostProcess::ApplyHBlur(), Core::PostProcess::ApplyRadialBlur(), Core::PostProcess::ApplyVBlur(), Core::GameSys::_WorldMap::atmosphere, Core::audioSys, bDebugDrawMouseRay, Core::GameSys::checkIcon(), Core::colors, Core::GUI::CONSTRAIN_LEFT, Core::GameVars::debug, Core::_Mouse::dir, Core::GameSys::_WorldMap::draw(), Core::_TextSys::draw(), Core::_Mouse::draw(), _Admin::draw(), Core::GameSys::Atmosphere::draw(), Core::_ParticleEmitter::draw(), Core::_TextSys::draw2(), Core::_Helper::drawLine(), Core::_Helper::drawPosition(), Core::GameSys::drawSprite(), Core::_TextSys::drawVar2(), Core::GameSys::AnimationSys::drawWorld(), Core::PostProcess::EndRenderLayer(), Core::GameVars::font, Core::framerate, Core::gameVars, Core::GameSys::_Satellite::getAlpha(), Core::_FrameRate::getFPS(), Core::_TimeSys::GetHour(), Core::_TimeSys::GetMinute(), Core::_Occlusion::GetRatio(), Core::_TimeSys::GetSecond(), Core::_FrameRate::getSplitTicks(), Core::_FrameRate::getStdDev(), GL_DEPTH_TEST, Core::glinit, Core::_Colors::green, Core::GameVars::Screen::half, Core::helper, Core::_TimeSys::iDay, iDebugLight, Core::_TimeSys::iYear, Core::matrix, MY_NAMESPACE::menuSys, Core::GameSys::Atmosphere::MODE_FLARES, Core::GameSys::Atmosphere::MODE_SATELLITE, Core::mouse, Core::GameVars::_Debug::noise, Core::occlusion, Core::particles, Core::GameVars::player, Core::AudioSys::playSound(), Core::Matrix_System::Pop(), Core::_Colors::PopFront(), Core::GameSys::CharSheet::Transform::pos, Core::postProcess, Core::profiles, Core::Matrix_System::Push(), Core::_Colors::PushFront(), Core::_Mouse::rays, Core::_Colors::red, Core::PostProcess::RenderLayer(), Core::PostProcess::RenderToScreen(), Core::PostProcess::RenderToWindow(), Core::GameVars::_Debug::_Noise::_Simplex::res, Core::GlInit_System::RestoreClearColor(), Core::GameSys::CharSheet::Transform::rot, Core::Matrix_System::Rotate(), Core::_Profile::runProfile(), Core::GameSys::Atmosphere::satellite, Core::GameVars::screen, Core::_Colors::SetActive(), Core::Matrix_System::SetIdentity(), Core::Matrix_System::SetProjection(), Core::Matrix_System::SetTransform(), Core::GameVars::_Debug::_Noise::simplex, MY_NAMESPACE::spriteSys, Core::GameSys::AnimationSys::startAnimation(), Core::textSys, Core::timeSys, to_string(), Core::GameSys::CharSheet::transform, Core::Matrix_System::Translate(), Core::GameVars::Font::vSize, MY_NAMESPACE::winSys, world, Core::_Mouse::x, Core::Vector2f::x, Core::Vector3f::x, Core::_Mouse::y, Core::Vector2f::y, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by Run().
Friends And Related Function Documentation
_Admin
friend class _Admin friend
Definition at line 38 of file runGame.h.
Member Data Documentation
animation
Core::GameSys::AnimationSys* _Game::animation private
Definition at line 25 of file runGame.h.
Referenced by _Game(), load(), Update(), and ~_Game().
bDebugDrawMouseRay
bool _Game::bDebugDrawMouseRay
Definition at line 45 of file runGame.h.
Referenced by _Game(), ProcessInput(), and Update().
bHasFocus
bool _Game::bHasFocus private
Definition at line 30 of file runGame.h.
Referenced by _Game(), GetInput(), and ProcessInput().
bOneShot
bool _Game::bOneShot[64] private
Definition at line 29 of file runGame.h.
Referenced by _Game().
fTest_fScaleOld
float _Game::fTest_fScaleOld private
Definition at line 32 of file runGame.h.
Referenced by _Game().
iDebugLight
int _Game::iDebugLight
Definition at line 43 of file runGame.h.
Referenced by _Game(), load(), ProcessInput(), _Admin::run(), and Update().
iDebugObject
int _Game::iDebugObject
Definition at line 44 of file runGame.h.
Referenced by _Game(), load(), ProcessInput(), and _Admin::run().
iPlayerLight
const int _Game::iPlayerLight = 0 static private
Definition at line 19 of file runGame.h.
Referenced by ProcessInput().
keyboard
Core::_Keyboard _Game::keyboard private
Definition at line 20 of file runGame.h.
Referenced by _Game(), GetInput(), and ProcessInput().
vDebugAttDelta
Core::Vector3f _Game::vDebugAttDelta
Definition at line 41 of file runGame.h.
Referenced by load().
vDebugPosDelta
Core::Vector3f _Game::vDebugPosDelta
Definition at line 42 of file runGame.h.
Referenced by load().
vDebugRotation
Core::Vector3f _Game::vDebugRotation
Definition at line 46 of file runGame.h.
Referenced by ProcessInput().
world
Core::GameSys::_WorldMap* _Game::world private
Definition at line 23 of file runGame.h.
Referenced by _Game(), load(), ProcessInput(), _Admin::run(), Update(), and ~_Game().
The documentation for this class was generated from the following file:
src/game/runGame.h