Project Parsec: _Skill Class Reference
_Skill Class Reference
#include <runSkill.h>
Public Member Functions
bool load ()
bool calc ()
void Run ()
float GetHeight ()
void Update ()
void Draw ()
_Skill ()
Private Member Functions
void GetInput ()
void ProcessInput ()
Private Attributes
Keyboard keyboard
VAO ** vao [7]
Detailed Description
Definition at line 11 of file runSkill.h.
Constructor & Destructor Documentation
_Skill()
_Skill::_Skill () inline
Definition at line 27 of file runSkill.h.
References keyboard, and vao.
Member Function Documentation
calc()
bool _Skill::calc ()
Definition at line 129 of file runSkill.h.
Draw()
void _Skill::Draw ()
Definition at line 160 of file runSkill.h.
Referenced by Update().
GetHeight()
float _Skill::GetHeight ()
GetInput()
void _Skill::GetInput () private
Definition at line 173 of file runSkill.h.
References Core::GameVars::controls, Core::GameVars::debug, Core::gameVars, keyboard, ProcessInput(), and Core::GameVars::screen.
Referenced by Run().
load()
bool _Skill::load ()
Definition at line 55 of file runSkill.h.
References GL_TRIANGLES, Core::GLA_INDEX, Core::GLA_NORMAL, Core::GLA_TEXTURE, Core::GLA_VERTEX, vao, x, and y.
ProcessInput()
void _Skill::ProcessInput () private
Definition at line 220 of file runSkill.h.
References Core::GameVars::Controls::_KeyBinding::activate, Core::GameVars::controls, Core::GameVars::debug, Core::gameVars, Core::GameVars::Controls::key, keyboard, Core::GameVars::Controls::_KeyBinding::move_back, Core::GameVars::Controls::_KeyBinding::move_down, Core::GameVars::Controls::_KeyBinding::move_forward, Core::GameVars::Controls::_KeyBinding::move_up, Core::GameVars::Controls::_KeyBinding::run, Core::GameVars::Controls::_KeyBinding::sneak, Core::GameVars::Controls::_KeyBinding::strafe_left, and Core::GameVars::Controls::_KeyBinding::strafe_right.
Referenced by GetInput().
Run()
void _Skill::Run ()
Definition at line 138 of file runSkill.h.
References GetInput(), and Update().
Update()
void _Skill::Update ()
Definition at line 147 of file runSkill.h.
References Draw().
Referenced by Run().
Member Data Documentation
keyboard
Keyboard _Skill::keyboard private
Definition at line 13 of file runSkill.h.
Referenced by _Skill(), GetInput(), and ProcessInput().
vao
VAO** _Skill::vao[7] private
Definition at line 17 of file runSkill.h.
Referenced by _Skill(), and load().
The documentation for this class was generated from the following file:
src/game/ref/runSkill.h