Project Parsec: Core::GUI::GUI::TextEditInterface Class Reference
Core::GUI::GUI::TextEditInterface Class Reference
#include <GUI.h>
Public Member Functions
void add (std::string guiName, std::string textEditName, Constraints_TextArea c)
void add (std::string guiName, std::string windowName, std::string textEditlName, Constraints_TextArea c)
void add (std::string guiName, std::string textEditName, Constraints_TextArea *c)
void add (std::string guiName, std::string windowName, std::string textEditlName, Constraints_TextArea *c)
Constraints_TextArea * get (std::string guiName, std::string textEditName)
TextEditInterface (GUI *parent)
Public Attributes
GUI * gui
Detailed Description
Definition at line 186 of file GUI.h.
Constructor & Destructor Documentation
TextEditInterface()
Core::GUI::GUI::TextEditInterface::TextEditInterface (GUI * parent) inline
Definition at line 194 of file GUI.h.
References gui.
Member Function Documentation
add() [1/4]
void Core::GUI::GUI::TextEditInterface::add (std::string guiName, std::string textEditName, Constraints_TextArea * c)
Definition at line 788 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::TextEdit::init().
add() [2/4]
void Core::GUI::GUI::TextEditInterface::add (std::string guiName, std::string textEditName, Constraints_TextArea c)
Definition at line 769 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::TextEdit::init().
add() [3/4]
void Core::GUI::GUI::TextEditInterface::add (std::string guiName, std::string windowName, std::string textEditlName, Constraints_TextArea * c)
Definition at line 797 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::TextEdit::init().
add() [4/4]
void Core::GUI::GUI::TextEditInterface::add (std::string guiName, std::string windowName, std::string textEditlName, Constraints_TextArea c)
Definition at line 778 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::TextEdit::init().
get()
Constraints_TextArea * Core::GUI::GUI::TextEditInterface::get (std::string guiName, std::string textEditName)
Definition at line 807 of file GUI.h.
References MY_NAMESPACE::gui.
Member Data Documentation
gui
GUI* Core::GUI::GUI::TextEditInterface::gui
Definition at line 193 of file GUI.h.
Referenced by TextEditInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI.h