Project Parsec: Core::RunningStat Class Reference
Core::RunningStat Class Reference
#include <RunningStat.h>
Public Member Functions
RunningStat ()
void Clear ()
int NumDataValues () const
float Mean () const
float Variance () const
float StandardDeviation () const
void Push (float x)
Private Attributes
int m_n
float m_oldM
float m_newM
float m_oldS
float m_newS
Detailed Description
Definition at line 15 of file RunningStat.h.
Constructor & Destructor Documentation
RunningStat()
Core::RunningStat::RunningStat () inline
Definition at line 18 of file RunningStat.h.
Member Function Documentation
Clear()
void Core::RunningStat::Clear () inline
Definition at line 20 of file RunningStat.h.
References m_n.
Referenced by Core::PTimer::ResetStdDev().
Mean()
float Core::RunningStat::Mean () const inline
Definition at line 22 of file RunningStat.h.
References m_n, and m_newM.
Referenced by Core::PTimer::GetAverage().
NumDataValues()
int Core::RunningStat::NumDataValues () const inline
Definition at line 21 of file RunningStat.h.
References m_n.
Push()
void Core::RunningStat::Push (float x) inline
Definition at line 26 of file RunningStat.h.
References m_n, m_newM, m_newS, m_oldM, m_oldS, and x.
Referenced by Core::PTimer::stop(), and Core::PTimer::update().
StandardDeviation()
float Core::RunningStat::StandardDeviation () const inline
Definition at line 24 of file RunningStat.h.
References Variance().
Referenced by Core::PTimer::GetStdDev().
Variance()
float Core::RunningStat::Variance () const inline
Definition at line 23 of file RunningStat.h.
References m_n, and m_newS.
Referenced by StandardDeviation().
Member Data Documentation
m_n
int Core::RunningStat::m_n private
Definition at line 48 of file RunningStat.h.
Referenced by Clear(), Mean(), NumDataValues(), Push(), and Variance().
m_newM
float Core::RunningStat::m_newM private
Definition at line 49 of file RunningStat.h.
Referenced by Mean(), and Push().
m_newS
float Core::RunningStat::m_newS private
Definition at line 49 of file RunningStat.h.
Referenced by Push(), and Variance().
m_oldM
float Core::RunningStat::m_oldM private
Definition at line 49 of file RunningStat.h.
Referenced by Push().
m_oldS
float Core::RunningStat::m_oldS private
Definition at line 49 of file RunningStat.h.
Referenced by Push().
The documentation for this class was generated from the following file:
src/headers/core/RunningStat.h