Project Parsec: WorldMap Class Reference
WorldMap Class Reference
#include <map.h>
Public Member Functions
WorldMap (Atmosphere *a, std::string d)
~WorldMap ()
bool init ()
bool init (int iSx, int iSz)
bool init (int iSx, int iSz, int iPx, int iPy, int iPz)
bool load (int iShift)
void shift (int iShift)
void stitch (unsigned int iStitch, int x, int z)
void updateNorms (int x, int z)
bool calc (bool bUpdate)
void modify (MOD_VAL eMod, float fNewVal)
void update (int iGridx, int iGridz)
void draw (int iShader)
void reset (Atmosphere *a, std::string d)
float getHeight (float x, float z)
float getHeight (float iX, float iZ, int gX, int gZ)
float * getHeight_Normal (float x, float z)
Public Attributes
std::string dir
Vector2i vStart
Vector2ui vBase
MapData mapData [9][9]
bool bSkip [81]
Atmosphere * atmosphere
Detailed Description
Definition at line 11 of file map.h.
Constructor & Destructor Documentation
WorldMap()
WorldMap::WorldMap (Atmosphere * a, std::string d) inline
Definition at line 17 of file map.h.
~WorldMap()
WorldMap::~WorldMap () inline
Definition at line 24 of file map.h.
References cout.
Member Function Documentation
calc()
bool WorldMap::calc (bool bUpdate = false)
Definition at line 1430 of file map.h.
References cout, Core::GameVars::debug, Core::gameVars, GL_TRIANGLES, Core::GLA_INDEX, Core::GLA_NORMAL, Core::GLA_TEXTURE, Core::GLA_VERTEX, mapData, Core::GameVars::screen, stitch(), x, and z.
Referenced by _TheVoid::load(), and shift().
draw()
void WorldMap::draw (int iShader)
Definition at line 1647 of file map.h.
References atmosphere, Core::gameVars, GL_TEXTURE0, GL_TEXTURE1, GL_TEXTURE2, GL_TEXTURE3, GL_TEXTURE4, GL_TEXTURE5, GL_TEXTURE6, GL_TEXTURE7, GL_TEXTURE8, Core::GLM_DRAW_ELEMENTS, mapData, Core::GameVars::screen, x, and z.
Referenced by _TheVoid::Draw().
getHeight() [1/2]
float WorldMap::getHeight (float iX, float iZ, int gX, int gZ)
Definition at line 52 of file map.h.
References h, mapData, p, t, and w.
getHeight() [2/2]
float WorldMap::getHeight (float x, float z)
Definition at line 133 of file map.h.
References h, mapData, p, t, and w.
Referenced by O2D::calc(), _NPC::calc(), RunBattle::processInput(), and _TheVoid::Run().
getHeight_Normal()
float * WorldMap::getHeight_Normal (float x, float z)
Definition at line 415 of file map.h.
References h, mapData, p, t, and w.
init() [1/3]
bool WorldMap::init ()
Definition at line 742 of file map.h.
References Core::GameVars::Player::active, cout, Core::GameVars::debug, dir, Core::gameVars, Core::itoa(), Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::readFile(), Core::GameVars::screen, Core::GameSys::CharSheet::transform, and vStart.
Referenced by _TheVoid::load().
init() [2/3]
bool WorldMap::init (int iSx, int iSz)
Definition at line 802 of file map.h.
References Core::GameVars::Player::active, Core::GameVars::debug, Core::gameVars, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::screen, Core::GameSys::CharSheet::transform, and vStart.
init() [3/3]
bool WorldMap::init (int iSx, int iSz, int iPx, int iPy, int iPz)
Definition at line 822 of file map.h.
References Core::GameVars::Player::active, Core::GameVars::debug, Core::gameVars, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::screen, Core::GameSys::CharSheet::transform, and vStart.
load()
bool WorldMap::load (int iShift = SHIFT_LAST)
Definition at line 839 of file map.h.
References cout, Core::GameVars::debug, dir, Core::gameVars, mapData, Core::readFile(), Core::GameVars::screen, vBase, vStart, x, and z.
Referenced by _TheVoid::load(), and shift().
modify()
void WorldMap::modify (MOD_VAL eMod, float fNewVal)
Definition at line 1639 of file map.h.
reset()
void WorldMap::reset (Atmosphere * a, std::string d)
Definition at line 727 of file map.h.
References atmosphere, cout, and dir.
Referenced by _TheVoid::load().
shift()
void WorldMap::shift (int iShift = SHIFT_LAST)
Definition at line 1053 of file map.h.
References calc(), Core::gameVars, load(), and Core::GameVars::screen.
Referenced by _TheVoid::reload().
stitch()
void WorldMap::stitch (unsigned int iStitch, int x, int z)
Definition at line 1106 of file map.h.
References cout, mapData, t, x, and z.
Referenced by calc().
update()
void WorldMap::update (int iGridx, int iGridz)
Definition at line 1643 of file map.h.
updateNorms()
void WorldMap::updateNorms (int x, int z)
Definition at line 1102 of file map.h.
Member Data Documentation
atmosphere
Atmosphere* WorldMap::atmosphere
Definition at line 49 of file map.h.
Referenced by draw(), and reset().
bSkip
bool WorldMap::bSkip[81]
Definition at line 33 of file map.h.
dir
std::string WorldMap::dir
Definition at line 29 of file map.h.
Referenced by init(), O2D::load(), load(), E2D::load(), _TheVoid::load(), E2D::loadEvent(), and reset().
mapData
MapData WorldMap::mapData[9][9]
Definition at line 32 of file map.h.
Referenced by calc(), draw(), getHeight(), getHeight_Normal(), NPC::height(), load(), _TheVoid::load(), and stitch().
vBase
Vector2ui WorldMap::vBase
Definition at line 31 of file map.h.
Referenced by E2D::execute(), O2D::load(), load(), E2D::load(), and _TheVoid::load().
vStart
Vector2i WorldMap::vStart
Definition at line 30 of file map.h.
Referenced by init(), load(), _TheVoid::load(), and _TheVoid::reload().
The documentation for this class was generated from the following file:
src/headers/gamesys/ref/map.h