Project Parsec: Core::_Profile Class Reference
Core::_Profile Class Reference
#include <profile.h>
Classes
struct _DefaultProfiles
Public Member Functions
_Profile ()
virtual ~_Profile ()
void addProfile (std::string s)
void startProfile (std::string s)
void stopProfile (std::string s)
uint getTime (std::string s)
float getAverage (std::string s, int n=10)
float getStdDev (std::string s)
uint getSamples (std::string s)
uint getMin (std::string s)
uint getMax (std::string s)
void addProfile (int p)
void startProfile (int p)
void stopProfile (int p)
void runProfile (int p, bool b)
uint getTime (int p)
float getAverage (int p, int n=10)
float getStdDev (int p)
uint getSamples (int p)
uint getMin (int p)
uint getMax (int p)
void reset ()
Public Attributes
struct Core::_Profile::_DefaultProfiles builtIn
bool bEnable
Private Attributes
Core::PTimer timer
Detailed Description
Definition at line 18 of file profile.h.
Constructor & Destructor Documentation
_Profile()
Core::_Profile::_Profile ()
Definition at line 13 of file profile.cpp.
References addProfile(), bEnable, builtIn, and Core::_Profile::_DefaultProfiles::Last.
~_Profile()
Core::_Profile::~_Profile () virtual
Definition at line 22 of file profile.cpp.
Member Function Documentation
addProfile() [1/2]
void Core::_Profile::addProfile (int p)
Definition at line 77 of file profile.cpp.
References Core::PTimer::addTimer(), builtIn, Core::_Profile::_DefaultProfiles::sNames, and timer.
addProfile() [2/2]
void Core::_Profile::addProfile (std::string s)
Definition at line 25 of file profile.cpp.
References Core::PTimer::addTimer(), and timer.
Referenced by _Profile().
getAverage() [1/2]
float Core::_Profile::getAverage (int p, int n = 10)
Definition at line 99 of file profile.cpp.
References bEnable, builtIn, Core::PTimer::GetAverage(), Core::_Profile::_DefaultProfiles::sNames, and timer.
getAverage() [2/2]
float Core::_Profile::getAverage (std::string s, int n = 10)
Definition at line 42 of file profile.cpp.
References bEnable, Core::PTimer::GetAverage(), and timer.
getMax() [1/2]
uint Core::_Profile::getMax (int p)
Definition at line 119 of file profile.cpp.
References bEnable, builtIn, Core::PTimer::GetMax(), Core::_Profile::_DefaultProfiles::sNames, and timer.
getMax() [2/2]
uint Core::_Profile::getMax (std::string s)
Definition at line 62 of file profile.cpp.
References bEnable, Core::PTimer::GetMax(), and timer.
getMin() [1/2]
uint Core::_Profile::getMin (int p)
Definition at line 114 of file profile.cpp.
References bEnable, builtIn, Core::PTimer::GetMin(), Core::_Profile::_DefaultProfiles::sNames, and timer.
getMin() [2/2]
uint Core::_Profile::getMin (std::string s)
Definition at line 57 of file profile.cpp.
References bEnable, Core::PTimer::GetMin(), and timer.
getSamples() [1/2]
uint Core::_Profile::getSamples (int p)
Definition at line 109 of file profile.cpp.
References bEnable, builtIn, Core::PTimer::GetSamples(), Core::_Profile::_DefaultProfiles::sNames, and timer.
getSamples() [2/2]
uint Core::_Profile::getSamples (std::string s)
Definition at line 52 of file profile.cpp.
References bEnable, Core::PTimer::GetSamples(), and timer.
getStdDev() [1/2]
float Core::_Profile::getStdDev (int p)
Definition at line 104 of file profile.cpp.
References bEnable, builtIn, Core::PTimer::GetStdDev(), Core::_Profile::_DefaultProfiles::sNames, and timer.
getStdDev() [2/2]
float Core::_Profile::getStdDev (std::string s)
Definition at line 47 of file profile.cpp.
References bEnable, Core::PTimer::GetStdDev(), and timer.
getTime() [1/2]
uint Core::_Profile::getTime (int p)
Definition at line 94 of file profile.cpp.
References bEnable, builtIn, Core::PTimer::getSplitTicks(), Core::_Profile::_DefaultProfiles::sNames, and timer.
getTime() [2/2]
uint Core::_Profile::getTime (std::string s)
Definition at line 37 of file profile.cpp.
References bEnable, Core::PTimer::getSplitTicks(), and timer.
Referenced by Core::GameSys::MapSys::load().
reset()
void Core::_Profile::reset ()
Definition at line 129 of file profile.cpp.
References Core::PTimer::ResetAverage(), Core::PTimer::ResetMax(), Core::PTimer::ResetMin(), Core::PTimer::ResetSamples(), Core::PTimer::ResetStdDev(), and timer.
Referenced by _Game::ProcessInput().
runProfile()
void Core::_Profile::runProfile (int p, bool b)
Definition at line 89 of file profile.cpp.
References builtIn, Core::_Profile::_DefaultProfiles::sNames, Core::PTimer::start(), Core::PTimer::stop(), and timer.
Referenced by _Game::Run(), and _Game::Update().
startProfile() [1/2]
void Core::_Profile::startProfile (int p)
Definition at line 81 of file profile.cpp.
References bEnable, builtIn, Core::_Profile::_DefaultProfiles::sNames, Core::PTimer::start(), and timer.
startProfile() [2/2]
void Core::_Profile::startProfile (std::string s)
Definition at line 29 of file profile.cpp.
References bEnable, Core::PTimer::start(), and timer.
Referenced by Core::GameSys::MapSys::load(), and main().
stopProfile() [1/2]
void Core::_Profile::stopProfile (int p)
Definition at line 85 of file profile.cpp.
References bEnable, builtIn, Core::_Profile::_DefaultProfiles::sNames, Core::PTimer::stop(), and timer.
stopProfile() [2/2]
void Core::_Profile::stopProfile (std::string s)
Definition at line 33 of file profile.cpp.
References bEnable, Core::PTimer::stop(), and timer.
Referenced by Core::GameSys::MapSys::load(), and main().
Member Data Documentation
bEnable
bool Core::_Profile::bEnable
Definition at line 74 of file profile.h.
Referenced by _Profile(), getAverage(), getMax(), getMin(), getSamples(), getStdDev(), getTime(), startProfile(), and stopProfile().
builtIn
struct Core::_Profile::_DefaultProfiles Core::_Profile::builtIn
Referenced by _Profile(), addProfile(), getAverage(), getMax(), getMin(), getSamples(), getStdDev(), getTime(), runProfile(), startProfile(), and stopProfile().
timer
Core::PTimer Core::_Profile::timer private
Definition at line 99 of file profile.h.
Referenced by addProfile(), getAverage(), getMax(), getMin(), getSamples(), getStdDev(), getTime(), reset(), runProfile(), startProfile(), and stopProfile().
The documentation for this class was generated from the following files:
src/headers/core/profile.h
src/headers/core/profile.cpp