Project Parsec: Core::Timer Class Reference
Core::Timer Class Reference
#include <timer.h>
Public Member Functions
Timer ()
void set (float fTime)
void start ()
void stop ()
void pause ()
void unpause ()
float split ()
float get_split ()
float get_splitdiff ()
void reset ()
float get_ticks ()
bool is_started ()
bool is_paused ()
Public Attributes
float startTicks
float rate
float rateMod
Private Attributes
float pausedTicks
bool paused
bool started
float splitTicks
Detailed Description
Definition at line 14 of file timer.h.
Constructor & Destructor Documentation
Timer()
Core::Timer::Timer ()
Definition at line 21 of file timer.cpp.
References paused, pausedTicks, rateMod, splitTicks, started, and startTicks.
Member Function Documentation
get_split()
float Core::Timer::get_split ()
Definition at line 120 of file timer.cpp.
References splitTicks.
get_splitdiff()
float Core::Timer::get_splitdiff ()
Definition at line 124 of file timer.cpp.
References get_ticks(), and splitTicks.
get_ticks()
float Core::Timer::get_ticks ()
Definition at line 89 of file timer.cpp.
References paused, pausedTicks, started, and startTicks.
Referenced by Core::GameSys::_MenuSys::checkInput(), Core::_Mouse::checkInput(), Core::_Mouse::checkState(), NPC::draw(), _NPC::draw(), Core::_ParticleEmitter::draw(), Core::_TextSys::drawMulti(), Core::GameSys::AnimationSys::drawWorld(), Core::_ParticleEmitter::emit(), get_splitdiff(), Core::_TimeSys::GetMinutes(), Core::_TimeSys::GetSeconds(), Core::GameSys::AnimationSys::startAnimation(), Core::GameSys::_Flora::update(), Core::_ParticleEmitter::update(), Core::_Particles::updateQuad(), and Core::_TimeSys::UpdateTime().
is_paused()
bool Core::Timer::is_paused ()
Definition at line 111 of file timer.cpp.
References paused.
is_started()
bool Core::Timer::is_started ()
Definition at line 107 of file timer.cpp.
References started.
pause()
void Core::Timer::pause ()
Definition at line 64 of file timer.cpp.
References paused, pausedTicks, started, and startTicks.
reset()
void Core::Timer::reset ()
Definition at line 128 of file timer.cpp.
References pausedTicks, splitTicks, and startTicks.
Referenced by Core::GameSys::_Satellite::update(), and Core::_TimeSys::UpdateDay().
set()
void Core::Timer::set (float fTime)
Definition at line 44 of file timer.cpp.
References paused, splitTicks, started, and startTicks.
split()
float Core::Timer::split ()
Definition at line 115 of file timer.cpp.
References splitTicks, and startTicks.
Referenced by _Game::ProcessInput().
start()
void Core::Timer::start ()
Definition at line 32 of file timer.cpp.
References paused, splitTicks, started, and startTicks.
Referenced by Core::GameSys::_MenuSys::_MenuSys(), Core::_Mouse::_Mouse(), Core::GameSys::AnimationSys::init(), main(), and MY_NAMESPACE::Setup().
stop()
void Core::Timer::stop ()
Definition at line 56 of file timer.cpp.
References paused, and started.
unpause()
void Core::Timer::unpause ()
Definition at line 75 of file timer.cpp.
References paused, pausedTicks, and startTicks.
Member Data Documentation
paused
bool Core::Timer::paused private
Definition at line 19 of file timer.h.
Referenced by get_ticks(), is_paused(), pause(), set(), start(), stop(), Timer(), and unpause().
pausedTicks
float Core::Timer::pausedTicks private
Definition at line 17 of file timer.h.
Referenced by get_ticks(), pause(), reset(), Timer(), and unpause().
rate
float Core::Timer::rate
Definition at line 25 of file timer.h.
rateMod
float Core::Timer::rateMod
Definition at line 25 of file timer.h.
Referenced by Timer().
splitTicks
float Core::Timer::splitTicks private
Definition at line 21 of file timer.h.
Referenced by get_split(), get_splitdiff(), reset(), set(), split(), start(), and Timer().
started
bool Core::Timer::started private
Definition at line 20 of file timer.h.
Referenced by get_ticks(), is_started(), pause(), set(), start(), stop(), and Timer().
startTicks
float Core::Timer::startTicks
Definition at line 24 of file timer.h.
Referenced by get_ticks(), pause(), reset(), set(), split(), start(), Timer(), and unpause().
The documentation for this class was generated from the following files:
src/headers/core/timer.h
src/headers/core/timer.cpp