Project Parsec: Core::_Lights Class Reference
Core::_Lights Class Reference
#include <lights.h>
Classes
struct _LightData
Public Types
enum _LightType {
LIGHT_NONE =0, LIGHT_DIRECTIONAL, LIGHT_OMNI, LIGHT_SPOT_HARD,
LIGHT_SPOT_SOFT
}
Public Member Functions
_Lights ()
~_Lights ()
void init ()
void load ()
void calc (float fScale)
uint AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, _LightType type=LIGHT_DIRECTIONAL)
uint AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, Degrees fInnerCone, Degrees fOuterCone, _LightType type=LIGHT_SPOT_SOFT)
uint AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, float attenuation, _LightType type=LIGHT_OMNI)
uint AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, Vector3f attenuation, _LightType type=LIGHT_OMNI)
uint AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, Vector3f ambient, Vector3f specular, Vector3f attenuation, Degrees fInnerCone, Degrees fOuterCone, _LightType type=LIGHT_OMNI)
_LightData * GetLightData ()
bool GetLightLoaded (uint num)
uint GetNumLights ()
Vector3f GetPos (uint num)
Vector3f GetPosPtr (uint num)
Vector3f GetDir (uint num)
Vector3f GetDirRad (uint num)
Vector3f GetDirPtr (uint num)
Vector3f GetDiffuse (uint num)
Vector3f GetAmbient (uint num)
Vector3f GetSpecular (uint num)
Vector3f GetAttenuation (uint num)
_LightType GetType (uint num)
void SetPos (uint num, Vector3f pos)
void SetDir (uint num, Vector3f dir)
void SetDiffuse (uint num, Vector3f dif)
void SetAmbient (uint num, Vector3f amb)
void SetSpecular (uint num, Vector3f spec)
void SetAttenuation (uint num, Vector3f att)
void SetType (uint num, _LightType type)
Private Attributes
uint uiNumLights
uint uiCurrentLights
_LightData * data
Detailed Description
Definition at line 35 of file lights.h.
Member Enumeration Documentation
_LightType
enum Core::_Lights::_LightType
Enumerator
LIGHT_NONE
LIGHT_DIRECTIONAL
LIGHT_OMNI
LIGHT_SPOT_HARD
LIGHT_SPOT_SOFT
Definition at line 37 of file lights.h.
Constructor & Destructor Documentation
_Lights()
Core::_Lights::_Lights ()
Definition at line 7 of file lights.cpp.
References cout, uiCurrentLights, and uiNumLights.
~_Lights()
Core::_Lights::~_Lights ()
Definition at line 16 of file lights.cpp.
References cout, and data.
Member Function Documentation
AddLight() [1/5]
uint Core::_Lights::AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, _LightType type = LIGHT_DIRECTIONAL)
Definition at line 80 of file lights.cpp.
Referenced by AddLight(), and calc().
AddLight() [2/5]
uint Core::_Lights::AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, Degrees fInnerCone, Degrees fOuterCone, _LightType type = LIGHT_SPOT_SOFT)
Definition at line 84 of file lights.cpp.
References AddLight().
AddLight() [3/5]
uint Core::_Lights::AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, float attenuation, _LightType type = LIGHT_OMNI)
Definition at line 88 of file lights.cpp.
References AddLight().
AddLight() [4/5]
uint Core::_Lights::AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, Vector3f ambient, Vector3f specular, Vector3f attenuation, Degrees fInnerCone, Degrees fOuterCone, _LightType type = LIGHT_OMNI)
Definition at line 96 of file lights.cpp.
References Core::Degrees::toRadians(), uiCurrentLights, Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
AddLight() [5/5]
uint Core::_Lights::AddLight (Vector3f pos, Vector3f dir, Vector3f diffuse, Vector3f attenuation, _LightType type = LIGHT_OMNI)
Definition at line 92 of file lights.cpp.
References AddLight().
calc()
void Core::_Lights::calc (float fScale)
Definition at line 39 of file lights.cpp.
References AddLight(), cout, LIGHT_DIRECTIONAL, LIGHT_OMNI, and Core::sOffset.
Referenced by Core::GameSys::_WorldMap::calc().
GetAmbient()
Vector3f Core::_Lights::GetAmbient (uint num) inline
Definition at line 84 of file lights.h.
Referenced by Core::Shader_System::getUniform().
GetAttenuation()
Vector3f Core::_Lights::GetAttenuation (uint num) inline
Definition at line 86 of file lights.h.
Referenced by Core::Shader_System::getUniform().
GetDiffuse()
Vector3f Core::_Lights::GetDiffuse (uint num) inline
Definition at line 83 of file lights.h.
Referenced by Core::Shader_System::getUniform().
GetDir()
Vector3f Core::_Lights::GetDir (uint num) inline
Definition at line 79 of file lights.h.
Referenced by Core::Shader_System::getUniform(), and _Admin::run().
GetDirPtr()
Vector3f Core::_Lights::GetDirPtr (uint num) inline
Definition at line 81 of file lights.h.
GetDirRad()
Vector3f Core::_Lights::GetDirRad (uint num)
Definition at line 130 of file lights.cpp.
GetLightData()
_LightData* Core::_Lights::GetLightData () inline
Definition at line 72 of file lights.h.
References data.
GetLightLoaded()
bool Core::_Lights::GetLightLoaded (uint num) inline
Definition at line 73 of file lights.h.
GetNumLights()
uint Core::_Lights::GetNumLights () inline
Definition at line 74 of file lights.h.
References uiCurrentLights.
Referenced by Core::Shader_System::getUniform(), and _Game::ProcessInput().
GetPos()
Vector3f Core::_Lights::GetPos (uint num) inline
Definition at line 76 of file lights.h.
Referenced by Core::Shader_System::getUniform(), _Game::load(), _Game::ProcessInput(), and _Admin::run().
GetPosPtr()
Vector3f Core::_Lights::GetPosPtr (uint num) inline
Definition at line 77 of file lights.h.
GetSpecular()
Vector3f Core::_Lights::GetSpecular (uint num) inline
Definition at line 85 of file lights.h.
Referenced by Core::Shader_System::getUniform().
GetType()
_LightType Core::_Lights::GetType (uint num) inline
Definition at line 87 of file lights.h.
References LIGHT_NONE.
Referenced by Core::Shader_System::getUniform().
init()
void Core::_Lights::init ()
Definition at line 23 of file lights.cpp.
References cout, LIGHT_NONE, Core::sOffset, and uiNumLights.
Referenced by Core::GameSys::_WorldMap::_WorldMap().
load()
void Core::_Lights::load ()
Definition at line 33 of file lights.cpp.
References cout, and Core::sOffset.
Referenced by Core::GameSys::_WorldMap::load().
SetAmbient()
void Core::_Lights::SetAmbient (uint num, Vector3f amb) inline
Definition at line 92 of file lights.h.
SetAttenuation()
void Core::_Lights::SetAttenuation (uint num, Vector3f att) inline
Definition at line 94 of file lights.h.
SetDiffuse()
void Core::_Lights::SetDiffuse (uint num, Vector3f dif) inline
Definition at line 91 of file lights.h.
SetDir()
void Core::_Lights::SetDir (uint num, Vector3f dir) inline
Definition at line 90 of file lights.h.
SetPos()
void Core::_Lights::SetPos (uint num, Vector3f pos) inline
Definition at line 89 of file lights.h.
Referenced by _Game::ProcessInput().
SetSpecular()
void Core::_Lights::SetSpecular (uint num, Vector3f spec) inline
Definition at line 93 of file lights.h.
SetType()
void Core::_Lights::SetType (uint num, _LightType type) inline
Definition at line 95 of file lights.h.
Member Data Documentation
data
_LightData* Core::_Lights::data private
Definition at line 59 of file lights.h.
Referenced by GetLightData(), and ~_Lights().
uiCurrentLights
uint Core::_Lights::uiCurrentLights private
Definition at line 57 of file lights.h.
Referenced by _Lights(), AddLight(), and GetNumLights().
uiNumLights
uint Core::_Lights::uiNumLights private
Definition at line 57 of file lights.h.
Referenced by _Lights(), and init().
The documentation for this class was generated from the following files:
src/headers/core/lights.h
src/headers/core/lights.cpp