Project Parsec: Core::PTimer Class Reference
Core::PTimer Class Reference
#include <ptimer.h>
Public Member Functions
PTimer ()
~PTimer ()
int addTimer (std::string s)
std::string getSplitTickString (uint id)
std::string getSplitTickString (std::string name)
uint getSplitTicks (uint id)
uint getSplitTicks (std::string name)
uint getTicks (uint id)
uint getTicks (std::string name)
void start (uint id)
void start (std::string name)
void update (uint id)
void update (std::string name)
uint stop (uint id, bool bReset=false)
uint stop (std::string name, bool bReset=false)
float GetMax (std::string name)
float GetMin (std::string name)
uint GetSamples (std::string name)
float GetStdDev (std::string name)
float GetAverage (std::string name, uint uiUpdateRate=500, uint uiUpdateTicks=500)
void ResetMin ()
void ResetMin (std::string name)
void ResetMax ()
void ResetMax (std::string name)
void ResetAverage ()
void ResetAverage (std::string name)
void ResetStdDev ()
void ResetStdDev (std::string name)
void ResetSamples ()
void ResetSamples (std::string name)
Public Attributes
Map_si TimerId
Protected Attributes
bool * started
uint * startTicks
uint * stopTicks
uint * splitTicks
float * splitAverage
float * splitMax
float * splitMin
uint * splitNum
uint iTimers
uint iMaxTimers
std::string * buffer
uint * uiSamples
uint * uiSamplesMem
float * fAverageMem
RunningStat * rsStdDev
uint * uiTicksMem
Detailed Description
Definition at line 28 of file ptimer.h.
Constructor & Destructor Documentation
PTimer()
Core::PTimer::PTimer ()
Definition at line 13 of file ptimer.cpp.
References cout, fAverageMem, iMaxTimers, iTimers, rsStdDev, splitAverage, splitMax, splitMin, splitNum, splitTicks, started, startTicks, stopTicks, uiSamples, uiSamplesMem, and uiTicksMem.
~PTimer()
Core::PTimer::~PTimer ()
Definition at line 37 of file ptimer.cpp.
References buffer, cout, fAverageMem, rsStdDev, splitAverage, splitMax, splitMin, splitNum, splitTicks, started, startTicks, stopTicks, uiSamples, uiSamplesMem, and uiTicksMem.
Member Function Documentation
addTimer()
int Core::PTimer::addTimer (std::string s)
Definition at line 58 of file ptimer.cpp.
References fAverageMem, iMaxTimers, iTimers, splitAverage, splitMax, splitMin, splitNum, splitTicks, started, startTicks, stopTicks, TimerId, uiSamples, uiSamplesMem, and uiTicksMem.
Referenced by Core::_FrameRate::_FrameRate(), and Core::_Profile::addProfile().
GetAverage()
float Core::PTimer::GetAverage (std::string name, uint uiUpdateRate = 500, uint uiUpdateTicks = 500)
Definition at line 202 of file ptimer.cpp.
References fAverageMem, id, Core::RunningStat::Mean(), rsStdDev, TimerId, uiSamples, uiSamplesMem, and uiTicksMem.
Referenced by Core::_Profile::getAverage().
GetMax()
float Core::PTimer::GetMax (std::string name)
Definition at line 187 of file ptimer.cpp.
References id, splitMax, and TimerId.
Referenced by Core::_Profile::getMax().
GetMin()
float Core::PTimer::GetMin (std::string name)
Definition at line 192 of file ptimer.cpp.
References id, splitMin, and TimerId.
Referenced by Core::_Profile::getMin().
GetSamples()
uint Core::PTimer::GetSamples (std::string name)
Definition at line 197 of file ptimer.cpp.
References id, TimerId, and uiSamples.
Referenced by Core::_FrameRate::getSamples(), and Core::_Profile::getSamples().
getSplitTicks() [1/2]
uint Core::PTimer::getSplitTicks (std::string name)
Definition at line 93 of file ptimer.cpp.
References getSplitTicks(), and TimerId.
getSplitTicks() [2/2]
uint Core::PTimer::getSplitTicks (uint id)
Definition at line 98 of file ptimer.cpp.
References id, and splitTicks.
Referenced by Core::_FrameRate::getSplitTicks(), getSplitTicks(), and Core::_Profile::getTime().
getSplitTickString() [1/2]
std::string Core::PTimer::getSplitTickString (std::string name)
Definition at line 84 of file ptimer.cpp.
References getSplitTickString(), and TimerId.
getSplitTickString() [2/2]
std::string Core::PTimer::getSplitTickString (uint id)
Definition at line 89 of file ptimer.cpp.
References id.
Referenced by getSplitTickString().
GetStdDev()
float Core::PTimer::GetStdDev (std::string name)
Definition at line 182 of file ptimer.cpp.
References id, rsStdDev, Core::RunningStat::StandardDeviation(), and TimerId.
Referenced by Core::_FrameRate::getStdDev(), and Core::_Profile::getStdDev().
getTicks() [1/2]
uint Core::PTimer::getTicks (std::string name)
Definition at line 102 of file ptimer.cpp.
References getTicks(), and TimerId.
getTicks() [2/2]
uint Core::PTimer::getTicks (uint id)
Definition at line 107 of file ptimer.cpp.
References id, and startTicks.
Referenced by Core::_FrameRate::getTicks(), and getTicks().
ResetAverage() [1/2]
void Core::PTimer::ResetAverage ()
Definition at line 251 of file ptimer.cpp.
References iTimers, and splitAverage.
Referenced by Core::_Profile::reset().
ResetAverage() [2/2]
void Core::PTimer::ResetAverage (std::string name)
Definition at line 257 of file ptimer.cpp.
References id, splitAverage, and TimerId.
ResetMax() [1/2]
void Core::PTimer::ResetMax ()
Definition at line 240 of file ptimer.cpp.
References iTimers, and splitMax.
Referenced by _TheVoid::ProcessInput(), and Core::_Profile::reset().
ResetMax() [2/2]
void Core::PTimer::ResetMax (std::string name)
Definition at line 246 of file ptimer.cpp.
References id, splitMax, and TimerId.
ResetMin() [1/2]
void Core::PTimer::ResetMin ()
Definition at line 229 of file ptimer.cpp.
References iTimers, and splitMin.
Referenced by Core::_Profile::reset().
ResetMin() [2/2]
void Core::PTimer::ResetMin (std::string name)
Definition at line 235 of file ptimer.cpp.
References id, splitMin, and TimerId.
ResetSamples() [1/2]
void Core::PTimer::ResetSamples ()
Definition at line 273 of file ptimer.cpp.
References iTimers, and uiSamples.
Referenced by Core::_Profile::reset().
ResetSamples() [2/2]
void Core::PTimer::ResetSamples (std::string name)
Definition at line 279 of file ptimer.cpp.
References id, TimerId, and uiSamples.
ResetStdDev() [1/2]
void Core::PTimer::ResetStdDev ()
Definition at line 262 of file ptimer.cpp.
References Core::RunningStat::Clear(), iTimers, and rsStdDev.
Referenced by Core::_Profile::reset().
ResetStdDev() [2/2]
void Core::PTimer::ResetStdDev (std::string name)
Definition at line 268 of file ptimer.cpp.
References Core::RunningStat::Clear(), id, rsStdDev, and TimerId.
start() [1/2]
void Core::PTimer::start (std::string name)
Definition at line 111 of file ptimer.cpp.
References start(), and TimerId.
start() [2/2]
void Core::PTimer::start (uint id)
Definition at line 116 of file ptimer.cpp.
References id, started, and startTicks.
Referenced by _TheVoid::Draw(), Core::_Profile::runProfile(), Core::_FrameRate::start(), start(), Core::_Profile::startProfile(), and _TheVoid::Update().
stop() [1/2]
uint Core::PTimer::stop (std::string name, bool bReset = false)
Definition at line 150 of file ptimer.cpp.
References stop(), and TimerId.
stop() [2/2]
uint Core::PTimer::stop (uint id, bool bReset = false)
Definition at line 155 of file ptimer.cpp.
References id, Core::itoa(), Core::RunningStat::Push(), rsStdDev, splitAverage, splitMax, splitMin, splitTicks, started, startTicks, and uiSamples.
Referenced by _TheVoid::Draw(), Core::_Profile::runProfile(), Core::_FrameRate::stop(), stop(), Core::_Profile::stopProfile(), Core::_FrameRate::update(), and _TheVoid::Update().
update() [1/2]
void Core::PTimer::update (std::string name)
Definition at line 127 of file ptimer.cpp.
References TimerId, and update().
update() [2/2]
void Core::PTimer::update (uint id)
Definition at line 132 of file ptimer.cpp.
References id, Core::itoa(), Core::RunningStat::Push(), rsStdDev, splitAverage, splitMax, splitMin, splitTicks, startTicks, and uiSamples.
Referenced by Core::_FrameRate::update(), and update().
Member Data Documentation
buffer
std::string* Core::PTimer::buffer protected
Definition at line 41 of file ptimer.h.
Referenced by ~PTimer().
fAverageMem
float* Core::PTimer::fAverageMem protected
Definition at line 44 of file ptimer.h.
Referenced by addTimer(), GetAverage(), PTimer(), and ~PTimer().
iMaxTimers
uint Core::PTimer::iMaxTimers protected
Definition at line 40 of file ptimer.h.
Referenced by addTimer(), and PTimer().
iTimers
uint Core::PTimer::iTimers protected
Definition at line 39 of file ptimer.h.
Referenced by addTimer(), PTimer(), ResetAverage(), ResetMax(), ResetMin(), ResetSamples(), and ResetStdDev().
rsStdDev
RunningStat* Core::PTimer::rsStdDev protected
Definition at line 45 of file ptimer.h.
Referenced by GetAverage(), GetStdDev(), PTimer(), ResetStdDev(), stop(), update(), and ~PTimer().
splitAverage
float* Core::PTimer::splitAverage protected
Definition at line 35 of file ptimer.h.
Referenced by addTimer(), PTimer(), ResetAverage(), stop(), update(), and ~PTimer().
splitMax
float* Core::PTimer::splitMax protected
Definition at line 36 of file ptimer.h.
Referenced by addTimer(), GetMax(), PTimer(), ResetMax(), stop(), update(), and ~PTimer().
splitMin
float* Core::PTimer::splitMin protected
Definition at line 37 of file ptimer.h.
Referenced by addTimer(), GetMin(), PTimer(), ResetMin(), stop(), update(), and ~PTimer().
splitNum
uint* Core::PTimer::splitNum protected
Definition at line 38 of file ptimer.h.
Referenced by addTimer(), PTimer(), and ~PTimer().
splitTicks
uint* Core::PTimer::splitTicks protected
Definition at line 34 of file ptimer.h.
Referenced by addTimer(), getSplitTicks(), PTimer(), stop(), update(), and ~PTimer().
started
bool* Core::PTimer::started protected
Definition at line 31 of file ptimer.h.
Referenced by addTimer(), PTimer(), start(), stop(), and ~PTimer().
startTicks
uint* Core::PTimer::startTicks protected
Definition at line 32 of file ptimer.h.
Referenced by addTimer(), getTicks(), PTimer(), start(), stop(), update(), and ~PTimer().
stopTicks
uint* Core::PTimer::stopTicks protected
Definition at line 33 of file ptimer.h.
Referenced by addTimer(), PTimer(), and ~PTimer().
TimerId
Map_si Core::PTimer::TimerId
Definition at line 52 of file ptimer.h.
Referenced by addTimer(), GetAverage(), GetMax(), GetMin(), GetSamples(), getSplitTicks(), getSplitTickString(), GetStdDev(), getTicks(), ResetAverage(), ResetMax(), ResetMin(), ResetSamples(), ResetStdDev(), start(), stop(), and update().
uiSamples
uint* Core::PTimer::uiSamples protected
Definition at line 42 of file ptimer.h.
Referenced by addTimer(), GetAverage(), GetSamples(), PTimer(), ResetSamples(), stop(), update(), and ~PTimer().
uiSamplesMem
uint* Core::PTimer::uiSamplesMem protected
Definition at line 43 of file ptimer.h.
Referenced by addTimer(), GetAverage(), PTimer(), and ~PTimer().
uiTicksMem
uint* Core::PTimer::uiTicksMem protected
Definition at line 46 of file ptimer.h.
Referenced by addTimer(), GetAverage(), PTimer(), and ~PTimer().
The documentation for this class was generated from the following files:
src/headers/core/ptimer.h
src/headers/core/ptimer.cpp