Project Parsec: _NPC Class Reference
_NPC Class Reference
#include <NPC.h>
Public Member Functions
_NPC (WorldMap &m)
bool init ()
bool load ()
bool calc ()
void draw (Atmosphere &a)
void draw (Atmosphere &a, CharSheet &sheet, bool bCard)
void draw (Atmosphere &a, CharSheet &sheet, CharSheet &lookAt, bool bCard)
void update ()
void reload ()
void reload (int x, int z)
float height (float iX, float iZ, int gX, int gZ)
int ApplyStatMod (int i)
void LoadNpc (int x, int z, int id)
Public Attributes
WorldMap & map
NPCSheet data [9][9]
bool bLoad
Private Attributes
float init_sx
float init_sz
Detailed Description
Definition at line 11 of file NPC.h.
Constructor & Destructor Documentation
_NPC()
_NPC::_NPC (WorldMap & m) inline
Definition at line 19 of file NPC.h.
References bLoad, init_sx, and init_sz.
Member Function Documentation
ApplyStatMod()
int _NPC::ApplyStatMod (int i) inline
Definition at line 87 of file NPC.h.
Referenced by LoadNpc().
calc()
bool _NPC::calc ()
Definition at line 1519 of file NPC.h.
References cout, Core::gameVars, WorldMap::getHeight(), GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, map, Core::GameVars::screen, x, and z.
Referenced by reload().
draw() [1/3]
void _NPC::draw (Atmosphere & a)
Definition at line 1615 of file NPC.h.
References Core::GameVars::Player::active, Core::gameVars, GL_CULL_FACE, Core::GLS_FONT, init(), Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::screen, Core::GameSys::CharSheet::transform, x, and z.
Referenced by _TheVoid::Draw(), and RunBattle::draw().
draw() [2/3]
void _NPC::draw (Atmosphere & a, CharSheet & sheet, bool bCard = false)
Definition at line 1685 of file NPC.h.
References Core::GameVars::font, Core::GameVars::Timers::frameRate, Core::gameVars, Core::Timer::get_ticks(), GL_CULL_FACE, GL_POLYGON_OFFSET_FILL, Core::GLS_FONT, Core::GameVars::screen, and Core::GameVars::timer.
draw() [3/3]
void _NPC::draw (Atmosphere & a, CharSheet & sheet, CharSheet & lookAt, bool bCard = true)
Definition at line 1823 of file NPC.h.
References Core::GameVars::Player::active, cout, Core::GameVars::Timers::frameRate, Core::gameVars, Core::Timer::get_ticks(), GL_CULL_FACE, GL_DEPTH_TEST, Core::GLS_FONT, Core::GameVars::player, Core::GameSys::CharSheet::Transform::rot, Core::GameVars::timer, and Core::GameSys::CharSheet::transform.
height()
float _NPC::height (float iX, float iZ, int gX, int gZ)
init()
bool _NPC::init ()
Definition at line 81 of file NPC.h.
References init_sx, and init_sz.
Referenced by draw().
load()
bool _NPC::load ()
Definition at line 1482 of file NPC.h.
References bLoad, Core::gameVars, init_sx, init_sz, LoadNpc(), and Core::GameVars::screen.
Referenced by reload().
LoadNpc()
void _NPC::LoadNpc (int x, int z, int id)
Definition at line 94 of file NPC.h.
References ApplyStatMod(), id, t, x, and z.
Referenced by load().
reload() [1/2]
void _NPC::reload ()
Definition at line 1582 of file NPC.h.
References calc(), Core::gameVars, load(), Core::GameVars::screen, x, and z.
Referenced by _TheVoid::load(), and _TheVoid::ProcessInput().
reload() [2/2]
void _NPC::reload (int x, int z)
Definition at line 1598 of file NPC.h.
References calc(), load(), x, and z.
update()
void _NPC::update ()
Definition at line 1578 of file NPC.h.
Member Data Documentation
bLoad
bool _NPC::bLoad
Definition at line 65 of file NPC.h.
Referenced by _NPC(), and load().
data
NPCSheet _NPC::data[9][9]
Definition at line 63 of file NPC.h.
Referenced by _TheVoid::ProcessInput().
init_sx
float _NPC::init_sx private
Definition at line 13 of file NPC.h.
Referenced by _NPC(), init(), and load().
init_sz
float _NPC::init_sz private
Definition at line 13 of file NPC.h.
Referenced by _NPC(), init(), and load().
map
WorldMap& _NPC::map
Definition at line 18 of file NPC.h.
Referenced by calc().
The documentation for this class was generated from the following file:
src/headers/gamesys/ref/NPC.h