Project Parsec: Core::_Keyboard Class Reference
Core::_Keyboard Class Reference
#include <InputSys.h>
Classes
struct _KeyArray
struct _KeyStruct
Public Types
typedef std::map< SDL_Keycode, uint > _KeyMap
Public Member Functions
_Keyboard ()
~_Keyboard ()
void AddKey (SDL_Keycode keyCode, bool bRepeat)
void calc (bool bNoRepeat=false)
void calc (SDL_Keycode iKey, bool bSetRepeat=true)
void editBuffer (std::string &buffer, bool bNumeric=false)
Simple editing mode for a buffer. Used for fields of numeric and text types.
void editBufferAt (std::string &buffer, bool bNumeric, int index, bool bOverwrite)
Edit a buffer at a specific position indicated by index.
void update ()
Public Attributes
_KeyArray keys
Static Public Attributes
const static Uint8 * event
Detailed Description
Definition at line 399 of file InputSys.h.
Member Typedef Documentation
_KeyMap
typedef std::map< SDL_Keycode, uint > Core::_Keyboard::_KeyMap
Definition at line 419 of file InputSys.h.
Constructor & Destructor Documentation
_Keyboard()
Core::_Keyboard::_Keyboard ()
Definition at line 489 of file InputSys.h.
References cout.
~_Keyboard()
Core::_Keyboard::~_Keyboard ()
Definition at line 497 of file InputSys.h.
References cout.
Member Function Documentation
AddKey()
void Core::_Keyboard::AddKey (SDL_Keycode keyCode, bool bRepeat)
Definition at line 503 of file InputSys.h.
References Core::_Keyboard::_KeyArray::insert(), and keys.
Referenced by calc().
calc() [1/2]
void Core::_Keyboard::calc (bool bNoRepeat = false)
Definition at line 507 of file InputSys.h.
References AddKey().
Referenced by _Admin::_Admin(), _Game::_Game(), Core::GUI::Object::FieldBase::FieldBase(), and Core::GUI::Object::TextEditBase::TextEditBase().
calc() [2/2]
void Core::_Keyboard::calc (SDL_Keycode iKey, bool bSetRepeat = true)
Definition at line 986 of file InputSys.h.
References keys.
editBuffer()
void Core::_Keyboard::editBuffer (std::string & buffer, bool bNumeric = false)
Simple editing mode for a buffer. Used for fields of numeric and text types.
Parameters
buffer Text to be edited
bNumeric Numeric editing only
Thus function allows a buffer to be edited but has no cursor position. It will edit from the end of the string only. In numeric mode the + and - keys can be used to toggle the sign state without erasing the entire buffer. The DEL key can be used to clear the buffer completely.
Definition at line 1001 of file InputSys.h.
References keys.
Referenced by Core::GUI::Object::TextEdit::execEdit().
editBufferAt()
void Core::_Keyboard::editBufferAt (std::string & buffer, bool bNumeric, int index, bool bOverwrite)
Edit a buffer at a specific position indicated by index.
Parameters
buffer Text to be edited
bNumeric Numeric editing only
index Cursor position, location to edit text at
bOverwrite Whether to overwrite text at position or insert
More advanced text editing function that allows editing at a cursor position either in insert or overwrite mode. Can still be specified as numeric only with the - and + keys used to toggle the sign of the value. DEL erases the entire buffer in Numeric mode only, in text mode it will erase the character AFTER the current cursor position.
Definition at line 1162 of file InputSys.h.
References keys.
update()
void Core::_Keyboard::update ()
Definition at line 1310 of file InputSys.h.
References Core::_Keyboard::_KeyArray::check(), keys, and Core::_Keyboard::_KeyArray::toggle().
Referenced by Core::GUI::Object::TextEdit::execEdit(), _Game::GetInput(), and _Admin::GetInput().
Member Data Documentation
event
const Uint8 * Core::_Keyboard::event static
Definition at line 417 of file InputSys.h.
Referenced by Core::GUI::Object::TextEdit::execEdit(), _Game::GetInput(), and _Admin::GetInput().
keys
_KeyArray Core::_Keyboard::keys
Definition at line 484 of file InputSys.h.
Referenced by AddKey(), calc(), editBuffer(), editBufferAt(), Core::GUI::Object::TextEdit::execEdit(), _Game::ProcessInput(), _Admin::ProcessInput(), and update().
The documentation for this class was generated from the following file:
src/headers/core/InputSys.h