Project Parsec: Core::GameSys::_WinSys Class Reference
Core::GameSys::_WinSys Class Reference
#include <WinSys.h>
Classes
struct _DRAWMODE
struct Coords
Public Member Functions
_WinSys ()
bool load ()
bool calc ()
void draw (int x, int y, int w, int h, bool textOffset, Color backColor, short int iBorder)
void drawT (int x, int y, int w, short int iBorder)
void drawT (int x, int y, int w, Color fontColor, short int iBorder)
void drawB (int x, int y, int w, short int iBorder)
void drawB (int x, int y, int w, Color fontColor, short int iBorder)
void drawL (int x, int y, int h, short int iBorder)
void drawL (int x, int y, int h, Color fontColor, short int iBorder)
void drawR (int x, int y, int h, short int iBorder)
void drawR (int x, int y, int h, Color fontColor, short int iBorder)
void drawTBorder (int x, int y, int w, short int iBorder)
void drawTBorder (int x, int y, int w, Color fontColor, short int iBorder)
void drawiBorder (int x, int y, int w, short int iBorder)
void drawiBorder (int x, int y, int w, Color fontColor, short int iBorder)
void drawLBorder (int x, int y, int h, short int iBorder)
void drawLBorder (int x, int y, int h, Color fontColor, short int iBorder)
void drawRBorder (int x, int y, int h, short int iBorder)
void drawRBorder (int x, int y, int h, Color fontColor, short int iBorder)
void drawHSpace (int x, int y, int w, short int iBorder)
void drawHSpace (int x, int y, int w, Color fontColor, short int iBorder)
void drawVSpace (int x, int y, int h, short int iBorder)
void drawVSpace (int x, int y, int h, Color fontColor, short int iBorder)
void drawHLine (int x, int y, int w, short int iBorder)
void drawHLine (int x, int y, int w, Color fontColor, short int iBorder)
void drawVLine (int x, int y, int w, short int iBorder)
void drawVLine (int x, int y, int w, Color fontColor, short int iBorder)
void drawH (int x, int y, int w, short int iBorder)
void drawH (int x, int y, int w, Color fontColor, short int iBorder)
void drawV (int x, int y, int w, short int iBorder)
void drawV (int x, int y, int w, Color fontColor, short int iBorder)
void drawHDiv (int x, int y, int w, short int iBorder)
void drawHDiv (int x, int y, int w, Color fontColor, short int iBorder)
void drawVDiv (int x, int y, int h, short int iBorder)
void drawVDiv (int x, int y, int h, Color fontColor, short int iBorder)
void drawSingle (int x, int y, int w, int h, int what, short int iBorder)
void drawSingle (int x, int y, int w, int h, int what, Color fontColor, short int iBorder)
Static Public Attributes
static struct Core::GameSys::_WinSys::_DRAWMODE DRAWMODE
Private Member Functions
void start (int x, int y, short int iBorder, Core::_Colors::_ACTIVE_COLOR eColor=Core::_Colors::COLOR_FRONT)
void update ()
void stop ()
Private Attributes
Vector4f currentColor
Vector4f cFrontColor
Vector4f cBackColor
uint uiNumTextures
uint uiRecordSize
std::string sFilename
std::string sDir
std::string sTexDir
GLuint index
GLfloat(* pArray)[2]
VAO vao [26]
Texture texture
float fMouseDelay
float fMouseDelayConst
struct Core::GameSys::_WinSys::Coords coords
Friends
class _GameSys
Detailed Description
Definition at line 21 of file WinSys.h.
Constructor & Destructor Documentation
_WinSys()
Core::GameSys::_WinSys::_WinSys ()
Definition at line 131 of file WinSys.h.
References fMouseDelay, fMouseDelayConst, pArray, sDir, sFilename, sTexDir, uiNumTextures, and uiRecordSize.
Member Function Documentation
calc()
bool Core::GameSys::_WinSys::calc ()
Definition at line 179 of file WinSys.h.
References Core::VAO::Begin(), Core::VAO::CopyData(), cout, Core::VAO::End(), Core::GameVars::font, Core::gameVars, GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, pArray, vao, and Core::GameVars::Font::vSize.
draw()
void Core::GameSys::_WinSys::draw (int x, int y, int w, int h, bool textOffset, Color backColor = Color{1.0, 1.0, 1.0, 1.0}, short int iBorder = DRAWMODE.NORMAL)
Definition at line 544 of file WinSys.h.
drawB() [1/2]
void Core::GameSys::_WinSys::drawB (int x, int y, int w, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 774 of file WinSys.h.
References Core::colors, drawB(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawB() [2/2]
void Core::GameSys::_WinSys::drawB (int x, int y, int w, short int iBorder = DRAWMODE.NORMAL)
Definition at line 780 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, index, start(), stop(), update(), vao, and w.
Referenced by drawB().
drawH() [1/2]
void Core::GameSys::_WinSys::drawH (int x, int y, int w, Color fontColor, short int iBorder)
drawH() [2/2]
void Core::GameSys::_WinSys::drawH (int x, int y, int w, short int iBorder)
drawHDiv() [1/2]
void Core::GameSys::_WinSys::drawHDiv (int x, int y, int w, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 982 of file WinSys.h.
References Core::colors, drawHDiv(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawHDiv() [2/2]
void Core::GameSys::_WinSys::drawHDiv (int x, int y, int w, short int iBorder = DRAWMODE.NORMAL)
Definition at line 988 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, index, start(), stop(), update(), vao, and w.
Referenced by drawHDiv().
drawHLine() [1/2]
void Core::GameSys::_WinSys::drawHLine (int x, int y, int w, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 946 of file WinSys.h.
References Core::colors, drawHLine(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawHLine() [2/2]
void Core::GameSys::_WinSys::drawHLine (int x, int y, int w, short int iBorder = DRAWMODE.NORMAL)
Definition at line 952 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, index, start(), stop(), update(), vao, and w.
Referenced by drawHLine().
drawHSpace() [1/2]
void Core::GameSys::_WinSys::drawHSpace (int x, int y, int w, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 906 of file WinSys.h.
References Core::colors, drawHSpace(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawHSpace() [2/2]
void Core::GameSys::_WinSys::drawHSpace (int x, int y, int w, short int iBorder = DRAWMODE.NORMAL)
Definition at line 912 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, index, start(), stop(), update(), vao, and w.
Referenced by drawHSpace().
drawiBorder() [1/2]
void Core::GameSys::_WinSys::drawiBorder (int x, int y, int w, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 852 of file WinSys.h.
References Core::colors, drawiBorder(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawiBorder() [2/2]
void Core::GameSys::_WinSys::drawiBorder (int x, int y, int w, short int iBorder = DRAWMODE.NORMAL)
Definition at line 858 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, index, start(), stop(), update(), vao, and w.
Referenced by drawiBorder().
drawL() [1/2]
void Core::GameSys::_WinSys::drawL (int x, int y, int h, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 794 of file WinSys.h.
References Core::colors, drawL(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawL() [2/2]
void Core::GameSys::_WinSys::drawL (int x, int y, int h, short int iBorder = DRAWMODE.NORMAL)
Definition at line 800 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, h, index, start(), stop(), update(), and vao.
Referenced by drawL().
drawLBorder() [1/2]
void Core::GameSys::_WinSys::drawLBorder (int x, int y, int h, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 870 of file WinSys.h.
References Core::colors, drawLBorder(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawLBorder() [2/2]
void Core::GameSys::_WinSys::drawLBorder (int x, int y, int h, short int iBorder = DRAWMODE.NORMAL)
Definition at line 876 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, h, index, start(), stop(), update(), and vao.
Referenced by drawLBorder().
drawR() [1/2]
void Core::GameSys::_WinSys::drawR (int x, int y, int h, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 814 of file WinSys.h.
References Core::colors, drawR(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawR() [2/2]
void Core::GameSys::_WinSys::drawR (int x, int y, int h, short int iBorder = DRAWMODE.NORMAL)
Definition at line 820 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, h, index, start(), stop(), update(), and vao.
Referenced by drawR().
drawRBorder() [1/2]
void Core::GameSys::_WinSys::drawRBorder (int x, int y, int h, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 888 of file WinSys.h.
References Core::colors, drawRBorder(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawRBorder() [2/2]
void Core::GameSys::_WinSys::drawRBorder (int x, int y, int h, short int iBorder = DRAWMODE.NORMAL)
Definition at line 894 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, h, index, start(), stop(), update(), and vao.
Referenced by drawRBorder().
drawSingle() [1/2]
void Core::GameSys::_WinSys::drawSingle (int x, int y, int w, int h, int what, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 520 of file WinSys.h.
References Core::colors, drawSingle(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawSingle() [2/2]
void Core::GameSys::_WinSys::drawSingle (int x, int y, int w, int h, int what, short int iBorder = DRAWMODE.NORMAL)
Definition at line 526 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, h, index, start(), stop(), update(), vao, and w.
Referenced by drawSingle().
drawT() [1/2]
void Core::GameSys::_WinSys::drawT (int x, int y, int w, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 754 of file WinSys.h.
References Core::colors, drawT(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawT() [2/2]
void Core::GameSys::_WinSys::drawT (int x, int y, int w, short int iBorder = DRAWMODE.NORMAL)
Definition at line 760 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, index, start(), stop(), update(), vao, and w.
Referenced by drawT().
drawTBorder() [1/2]
void Core::GameSys::_WinSys::drawTBorder (int x, int y, int w, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 834 of file WinSys.h.
References Core::colors, drawTBorder(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawTBorder() [2/2]
void Core::GameSys::_WinSys::drawTBorder (int x, int y, int w, short int iBorder = DRAWMODE.NORMAL)
Definition at line 840 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, index, start(), stop(), update(), vao, and w.
Referenced by drawTBorder().
drawV() [1/2]
void Core::GameSys::_WinSys::drawV (int x, int y, int w, Color fontColor, short int iBorder)
drawV() [2/2]
void Core::GameSys::_WinSys::drawV (int x, int y, int w, short int iBorder)
drawVDiv() [1/2]
void Core::GameSys::_WinSys::drawVDiv (int x, int y, int h, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 1010 of file WinSys.h.
References Core::colors, drawVDiv(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawVDiv() [2/2]
void Core::GameSys::_WinSys::drawVDiv (int x, int y, int h, short int iBorder = DRAWMODE.NORMAL)
Definition at line 1016 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, h, index, start(), stop(), update(), and vao.
Referenced by drawVDiv().
drawVLine() [1/2]
void Core::GameSys::_WinSys::drawVLine (int x, int y, int w, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 964 of file WinSys.h.
References Core::colors, drawVLine(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawVLine() [2/2]
void Core::GameSys::_WinSys::drawVLine (int x, int y, int w, short int iBorder = DRAWMODE.NORMAL)
Definition at line 970 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, h, index, start(), stop(), update(), and vao.
Referenced by drawVLine().
drawVSpace() [1/2]
void Core::GameSys::_WinSys::drawVSpace (int x, int y, int h, Color fontColor, short int iBorder = DRAWMODE.NORMAL)
Definition at line 926 of file WinSys.h.
References Core::colors, drawVSpace(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawVSpace() [2/2]
void Core::GameSys::_WinSys::drawVSpace (int x, int y, int h, short int iBorder = DRAWMODE.NORMAL)
Definition at line 932 of file WinSys.h.
References Core::VAO::Draw(), Core::gameVars, h, index, start(), stop(), update(), and vao.
Referenced by drawVSpace().
load()
bool Core::GameSys::_WinSys::load ()
Definition at line 149 of file WinSys.h.
References Core::MemBlock::buffer, cout, Core::readFile(), sDir, sFilename, Core::MemBlock::size, sTexDir, uiNumTextures, and uiRecordSize.
start()
void Core::GameSys::_WinSys::start (int x, int y, short int iBorder, Core::_Colors::_ACTIVE_COLOR eColor = Core::_Colors::COLOR_FRONT) private
Definition at line 485 of file WinSys.h.
References Core::colors, Core::GameVars::font, Core::gameVars, GL_DEPTH_TEST, GL_TRUE, Core::GLS_FONT, Core::GameVars::Font::screenCoords, Core::_Colors::SetActive(), and Core::GameVars::Font::vSize.
Referenced by drawB(), drawHDiv(), drawHLine(), drawHSpace(), drawiBorder(), drawL(), drawLBorder(), drawR(), drawRBorder(), drawSingle(), drawT(), drawTBorder(), drawVDiv(), drawVLine(), and drawVSpace().
stop()
void Core::GameSys::_WinSys::stop () private
Definition at line 514 of file WinSys.h.
References GL_DEPTH_TEST.
Referenced by drawB(), drawHDiv(), drawHLine(), drawHSpace(), drawiBorder(), drawL(), drawLBorder(), drawR(), drawRBorder(), drawSingle(), drawT(), drawTBorder(), drawVDiv(), drawVLine(), and drawVSpace().
update()
void Core::GameSys::_WinSys::update () private
Definition at line 507 of file WinSys.h.
References Core::GLS_FONT.
Referenced by drawB(), drawHDiv(), drawHLine(), drawHSpace(), drawiBorder(), drawL(), drawLBorder(), drawR(), drawRBorder(), drawSingle(), drawT(), drawTBorder(), drawVDiv(), drawVLine(), and drawVSpace().
Friends And Related Function Documentation
_GameSys
friend class _GameSys friend
Definition at line 73 of file WinSys.h.
Member Data Documentation
cBackColor
Vector4f Core::GameSys::_WinSys::cBackColor private
Definition at line 26 of file WinSys.h.
cFrontColor
Vector4f Core::GameSys::_WinSys::cFrontColor private
Definition at line 26 of file WinSys.h.
coords
struct Core::GameSys::_WinSys::Coords Core::GameSys::_WinSys::coords private
currentColor
Vector4f Core::GameSys::_WinSys::currentColor private
Definition at line 26 of file WinSys.h.
DRAWMODE
struct Core::GameSys::_WinSys::_DRAWMODE Core::GameSys::_WinSys::DRAWMODE static
fMouseDelay
float Core::GameSys::_WinSys::fMouseDelay private
Definition at line 38 of file WinSys.h.
Referenced by _WinSys().
fMouseDelayConst
float Core::GameSys::_WinSys::fMouseDelayConst private
Definition at line 38 of file WinSys.h.
Referenced by _WinSys().
index
GLuint Core::GameSys::_WinSys::index private
Definition at line 34 of file WinSys.h.
Referenced by drawB(), drawHDiv(), drawHLine(), drawHSpace(), drawiBorder(), drawL(), drawLBorder(), drawR(), drawRBorder(), drawSingle(), drawT(), drawTBorder(), drawVDiv(), drawVLine(), and drawVSpace().
pArray
GLfloat(* Core::GameSys::_WinSys::pArray)[2] private
Definition at line 35 of file WinSys.h.
Referenced by _WinSys(), and calc().
sDir
std::string Core::GameSys::_WinSys::sDir private
Definition at line 31 of file WinSys.h.
Referenced by _WinSys(), and load().
sFilename
std::string Core::GameSys::_WinSys::sFilename private
Definition at line 31 of file WinSys.h.
Referenced by _WinSys(), and load().
sTexDir
std::string Core::GameSys::_WinSys::sTexDir private
Definition at line 31 of file WinSys.h.
Referenced by _WinSys(), and load().
texture
Texture Core::GameSys::_WinSys::texture private
Definition at line 37 of file WinSys.h.
uiNumTextures
uint Core::GameSys::_WinSys::uiNumTextures private
Definition at line 29 of file WinSys.h.
Referenced by _WinSys(), and load().
uiRecordSize
uint Core::GameSys::_WinSys::uiRecordSize private
Definition at line 29 of file WinSys.h.
Referenced by _WinSys(), and load().
vao
VAO Core::GameSys::_WinSys::vao[26] private
Definition at line 36 of file WinSys.h.
Referenced by calc(), drawB(), drawHDiv(), drawHLine(), drawHSpace(), drawiBorder(), drawL(), drawLBorder(), drawR(), drawRBorder(), drawSingle(), drawT(), drawTBorder(), drawVDiv(), drawVLine(), and drawVSpace().
The documentation for this class was generated from the following file:
src/headers/gamesys/WinSys.h