Project Parsec: RunBattleScroll Class Reference
RunBattleScroll Class Reference
#include <runBattleScroll.h>
Public Member Functions
RunBattleScroll ()
bool init ()
bool load ()
void run ()
Protected Member Functions
void toggle (bool &myBool)
void getInput ()
void processInput ()
void update ()
void draw ()
Private Types
enum MENUSTATES { BSSTATE_INIT = 0, BSSTATE_HISTORY = 1 }
Private Attributes
int menuState
int menuSelection
Keyboard keyboard
Detailed Description
Definition at line 11 of file runBattleScroll.h.
Member Enumeration Documentation
MENUSTATES
enum RunBattleScroll::MENUSTATES private
Enumerator
BSSTATE_INIT
BSSTATE_HISTORY
Definition at line 13 of file runBattleScroll.h.
Constructor & Destructor Documentation
RunBattleScroll()
RunBattleScroll::RunBattleScroll ()
Definition at line 34 of file runBattleScroll.h.
References BSSTATE_INIT, keyboard, menuSelection, and menuState.
Member Function Documentation
draw()
void RunBattleScroll::draw () protected
Definition at line 537 of file runBattleScroll.h.
getInput()
void RunBattleScroll::getInput () protected
Definition at line 459 of file runBattleScroll.h.
References Core::GameVars::controls, Core::gameVars, keyboard, processInput(), and Core::GameVars::screen.
Referenced by run().
init()
bool RunBattleScroll::init ()
Definition at line 40 of file runBattleScroll.h.
load()
bool RunBattleScroll::load ()
Definition at line 44 of file runBattleScroll.h.
processInput()
void RunBattleScroll::processInput () protected
Definition at line 480 of file runBattleScroll.h.
References BSSTATE_HISTORY, BSSTATE_INIT, Core::GameVars::controls, Core::gameVars, keyboard, menuState, and Core::GameVars::screen.
Referenced by getInput().
run()
void RunBattleScroll::run ()
Definition at line 48 of file runBattleScroll.h.
References Core::GameVars::Player::active, Battle, BSSTATE_HISTORY, BSSTATE_INIT, Core::GameVars::Screen::clear, RunBattle::draw(), RunBattle::enemies, Core::GameVars::font, Core::gameVars, getInput(), GL_TRUE, h, menuSelection, menuState, RunBattle::numEnemy, Core::GameVars::player, Core::GameVars::screen, Core::GameVars::Font::screenCoords, update(), _TheVoid::Update(), Core::GameVars::Font::vSize, w, world, x, and y.
toggle()
void RunBattleScroll::toggle (bool & myBool) protected
Definition at line 541 of file runBattleScroll.h.
update()
void RunBattleScroll::update () protected
Definition at line 450 of file runBattleScroll.h.
References Core::GameVars::controls, and Core::gameVars.
Referenced by run().
Member Data Documentation
keyboard
Keyboard RunBattleScroll::keyboard private
Definition at line 16 of file runBattleScroll.h.
Referenced by getInput(), processInput(), and RunBattleScroll().
menuSelection
int RunBattleScroll::menuSelection private
Definition at line 14 of file runBattleScroll.h.
Referenced by run(), and RunBattleScroll().
menuState
int RunBattleScroll::menuState private
Definition at line 14 of file runBattleScroll.h.
Referenced by processInput(), run(), and RunBattleScroll().
The documentation for this class was generated from the following file:
src/game/ref/runBattleScroll.h