Project Parsec: Core::_SystemTextures Class Reference
Core::_SystemTextures Class Reference
#include <SystemTextures.h>
Public Types
enum eTexList {
TEX_TESTPATTERN = 0, TEX_WATER, TEX_DIRT, TEX_GRASSYDIRT,
TEX_GRASS, TEX_GRASSYROCK, TEX_ROCK, TEX_CLIFF,
TEX_LAST
}
Public Member Functions
_SystemTextures ()
virtual ~_SystemTextures ()
bool load ()
bool calc ()
void set (eTexList e)
Private Attributes
Texture texture
uint uiNumTextures
uint uiRecordSize
std::string sFilename
std::string sDir
std::string sTexDir
Detailed Description
Definition at line 18 of file SystemTextures.h.
Member Enumeration Documentation
eTexList
enum Core::_SystemTextures::eTexList
Enumerator
TEX_TESTPATTERN
TEX_WATER
TEX_DIRT
TEX_GRASSYDIRT
TEX_GRASS
TEX_GRASSYROCK
TEX_ROCK
TEX_CLIFF
TEX_LAST
Definition at line 23 of file SystemTextures.h.
Constructor & Destructor Documentation
_SystemTextures()
Core::_SystemTextures::_SystemTextures ()
Definition at line 12 of file SystemTextures.cpp.
References sDir, sFilename, sTexDir, uiNumTextures, and uiRecordSize.
~_SystemTextures()
Core::_SystemTextures::~_SystemTextures () virtual
Definition at line 20 of file SystemTextures.cpp.
Member Function Documentation
calc()
bool Core::_SystemTextures::calc ()
Definition at line 67 of file SystemTextures.cpp.
References cout.
load()
bool Core::_SystemTextures::load ()
Definition at line 23 of file SystemTextures.cpp.
References Core::MemBlock::buffer, cout, Core::readFile(), sDir, sFilename, Core::MemBlock::size, sTexDir, to_string(), uiNumTextures, and uiRecordSize.
Referenced by MY_NAMESPACE::Setup().
set()
void Core::_SystemTextures::set (eTexList e)
Definition at line 80 of file SystemTextures.cpp.
Referenced by Core::GameSys::_Satellite::draw(), and Core::GameSys::MapSys::draw().
Member Data Documentation
sDir
std::string Core::_SystemTextures::sDir private
Definition at line 46 of file SystemTextures.h.
Referenced by _SystemTextures(), and load().
sFilename
std::string Core::_SystemTextures::sFilename private
Definition at line 45 of file SystemTextures.h.
Referenced by _SystemTextures(), and load().
sTexDir
std::string Core::_SystemTextures::sTexDir private
Definition at line 47 of file SystemTextures.h.
Referenced by _SystemTextures(), and load().
texture
Texture Core::_SystemTextures::texture private
Definition at line 42 of file SystemTextures.h.
uiNumTextures
uint Core::_SystemTextures::uiNumTextures private
Definition at line 43 of file SystemTextures.h.
Referenced by _SystemTextures(), and load().
uiRecordSize
uint Core::_SystemTextures::uiRecordSize private
Definition at line 44 of file SystemTextures.h.
Referenced by _SystemTextures(), and load().
The documentation for this class was generated from the following files:
src/headers/core/SystemTextures.h
src/headers/core/SystemTextures.cpp