Project Parsec: Core::_ParticleEmitter Class Reference
Core::_ParticleEmitter Class Reference
#include <ParticleEmitter.h>
Classes
struct compareEmitterDistance
struct compareParticleDistance
Public Member Functions
_ParticleEmitter ()
~_ParticleEmitter ()
bool init ()
bool create (_ParticleEmitterData *newData)
void remove (std::string name)
void remove (int id)
void calc ()
void calc (std::string name)
void calc (int id)
void update (bool bSort=true)
void update (std::string name)
void update (int id)
void emit (std::string name)
void emit (int id)
void move (int id, int n)
void draw ()
void draw (std::string name)
void draw (int id)
Private Attributes
std::vector< _ParticleEmitterData * > emitters
Static Private Attributes
static bool bTexLoaded = false
static Texture tex = Texture()
static const uint MAX_TEXTURES = 32
static const uint RECORD_SIZE = 32
static const std::string DIR = "./system/"
static const std::string FILENAME = "particle_emitter.bin"
static const std::string TEXDIR = "./texture/particle_emitter/"
static const bool bDebug = false
Detailed Description
Definition at line 288 of file ParticleEmitter.h.
Constructor & Destructor Documentation
_ParticleEmitter()
Core::_ParticleEmitter::_ParticleEmitter ()
Definition at line 20 of file ParticleEmitter.cpp.
~_ParticleEmitter()
Core::_ParticleEmitter::~_ParticleEmitter ()
Definition at line 24 of file ParticleEmitter.cpp.
Member Function Documentation
calc() [1/3]
void Core::_ParticleEmitter::calc ()
Definition at line 126 of file ParticleEmitter.cpp.
References cout, and emitters.
Referenced by calc(), and _Game::load().
calc() [2/3]
void Core::_ParticleEmitter::calc (int id)
Definition at line 147 of file ParticleEmitter.cpp.
References emit(), emitters, and id.
calc() [3/3]
void Core::_ParticleEmitter::calc (std::string name)
Definition at line 138 of file ParticleEmitter.cpp.
References calc(), and emitters.
create()
bool Core::_ParticleEmitter::create (_ParticleEmitterData * newData)
Definition at line 76 of file ParticleEmitter.cpp.
References cout, emitters, Core::_ParticleEmitterData::sName, and Core::sOffset.
Referenced by _Game::load().
draw() [1/3]
void Core::_ParticleEmitter::draw ()
Definition at line 363 of file ParticleEmitter.cpp.
References cout, and emitters.
Referenced by draw(), and _Game::Update().
draw() [2/3]
void Core::_ParticleEmitter::draw (int id)
Definition at line 386 of file ParticleEmitter.cpp.
References Core::GlInit_System::DisableAdditiveBlending(), Core::VAO::Draw(), emitters, Core::GlInit_System::EnableAdditiveBlending(), Core::Timer::get_ticks(), GL_TEXTURE0, Core::glinit, Core::_Helper::GLPOINT_SQUARE_ALPHA, Core::GLS_PARTICLE_SPRITE, Core::helper, id, Core::particles, Core::Texture::Set(), tex, Core::timeSys, and Core::_Helper::vaoPoint.
draw() [3/3]
void Core::_ParticleEmitter::draw (std::string name)
Definition at line 377 of file ParticleEmitter.cpp.
References draw(), and emitters.
emit() [1/2]
void Core::_ParticleEmitter::emit (int id)
Definition at line 337 of file ParticleEmitter.cpp.
References emitters, Core::_ParticleData::fElapsedLife, Core::_ParticleData::fGravityEffect, Core::_ParticleData::fLifeTime, Core::_ParticleData::fRotation, Core::_ParticleData::fRotationSpeed, Core::_ParticleData::fSize, Core::_ParticleData::fStartTime, Core::Timer::get_ticks(), id, move(), Core::Vector3f::normal(), Core::particles, Core::roll(), Core::timeSys, Core::_ParticleData::vColor, Core::_ParticleData::vPosition, and Core::_ParticleData::vVelocity.
emit() [2/2]
void Core::_ParticleEmitter::emit (std::string name)
Definition at line 328 of file ParticleEmitter.cpp.
References emitters.
Referenced by calc(), and update().
init()
bool Core::_ParticleEmitter::init ()
Definition at line 31 of file ParticleEmitter.cpp.
References Core::Texture::Begin(), bTexLoaded, Core::MemBlock::buffer, cout, DIR, FILENAME, GL_NEAREST, GL_REPEAT, id, Core::Texture::Load(), Core::PopStr(), Core::readFile(), RECORD_SIZE, Core::MemBlock::size, Core::sOffset, tex, and TEXDIR.
Referenced by MY_NAMESPACE::Setup().
move()
void Core::_ParticleEmitter::move (int id, int n)
Definition at line 317 of file ParticleEmitter.cpp.
References emitters, Core::_State::fGravity, id, and Core::state.
Referenced by emit(), and update().
remove() [1/2]
void Core::_ParticleEmitter::remove (int id)
Definition at line 121 of file ParticleEmitter.cpp.
References emitters, and id.
remove() [2/2]
void Core::_ParticleEmitter::remove (std::string name)
Definition at line 111 of file ParticleEmitter.cpp.
References emitters.
Referenced by update().
update() [1/3]
void Core::_ParticleEmitter::update (bool bSort = true)
Definition at line 162 of file ParticleEmitter.cpp.
References Core::GameVars::Player::active, cout, emitters, Core::gameVars, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::Vector3f::sudoLength(), and Core::GameSys::CharSheet::transform.
Referenced by _Game::Run(), and update().
update() [2/3]
void Core::_ParticleEmitter::update (int id)
Definition at line 198 of file ParticleEmitter.cpp.
References Core::GameVars::Player::active, emit(), emitters, Core::GameVars::Screen::fFar, Core::gameVars, Core::Timer::get_ticks(), id, Core::Vector3f::length(), move(), Core::particles, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, remove(), Core::GameVars::screen, Core::timeSys, and Core::GameSys::CharSheet::transform.
update() [3/3]
void Core::_ParticleEmitter::update (std::string name)
Definition at line 189 of file ParticleEmitter.cpp.
References emitters, and update().
Member Data Documentation
bDebug
const bool Core::_ParticleEmitter::bDebug = false static private
Definition at line 345 of file ParticleEmitter.h.
bTexLoaded
bool Core::_ParticleEmitter::bTexLoaded = false static private
Definition at line 338 of file ParticleEmitter.h.
Referenced by init().
DIR
const std::string Core::_ParticleEmitter::DIR = "./system/" static private
Definition at line 342 of file ParticleEmitter.h.
Referenced by init().
emitters
std::vector<_ParticleEmitterData*> Core::_ParticleEmitter::emitters private
Definition at line 317 of file ParticleEmitter.h.
Referenced by calc(), create(), draw(), emit(), move(), remove(), and update().
FILENAME
const std::string Core::_ParticleEmitter::FILENAME = "particle_emitter.bin" static private
Definition at line 343 of file ParticleEmitter.h.
Referenced by init().
MAX_TEXTURES
const uint Core::_ParticleEmitter::MAX_TEXTURES = 32 static private
Definition at line 340 of file ParticleEmitter.h.
RECORD_SIZE
const uint Core::_ParticleEmitter::RECORD_SIZE = 32 static private
Definition at line 341 of file ParticleEmitter.h.
Referenced by init().
tex
Texture Core::_ParticleEmitter::tex = Texture() static private
Definition at line 339 of file ParticleEmitter.h.
Referenced by draw(), and init().
TEXDIR
const std::string Core::_ParticleEmitter::TEXDIR = "./texture/particle_emitter/" static private
Definition at line 344 of file ParticleEmitter.h.
Referenced by init().
The documentation for this class was generated from the following files:
src/headers/core/ParticleEmitter.h
src/headers/core/ParticleEmitter.cpp