Project Parsec: Core::GameSys::_MenuSys Class Reference
Core::GameSys::_MenuSys Class Reference
#include <MenuSys.h>
Public Member Functions
_MenuSys (_TextSys &t)
uint draw (int x, int y, std::string buffer)
uint draw (int x, int y, std::string buffer, Color fontColor1)
uint draw (int x, int y, std::string buffer, Color fontColor1, Color fontColor2)
bool draw (int x, int y, int z, std::string buffer, float *fPtr, bool drawDec)
bool draw (int x, int y, int z, std::string buffer, int *iPtr)
bool draw (int x, int y, int z, std::string buffer, bool *bPtr)
bool draw (int x, int y, int z, std::string buffer, std::string *sPtr)
bool draw (int x, int y, int z, std::string buffer, float *fPtr, Color fontColor, bool drawDec)
bool draw (int x, int y, int z, std::string buffer, int *iPtr, Color fontColor)
bool draw (int x, int y, int z, std::string buffer, bool *bPtr, Color fontColor)
bool draw (int x, int y, int z, std::string buffer, std::string *sPtr, Color fontColor)
bool draw (int x, int y, int z, std::string buffer, float *fPtr, Color fontColor, Color hlColor, bool drawDec)
bool draw (int x, int y, int z, std::string buffer, int *iPtr, Color fontColor, Color hlColor)
bool draw (int x, int y, int z, std::string buffer, bool *bPtr, Color fontColor, Color hlColor)
bool draw (int x, int y, int z, std::string buffer, std::string *sPtr, Color fontColor, Color hlColor)
Public Attributes
bool gettingInput
bool isFloat
bool isInt
bool isString
int * iPtrTemp
float * fPtrTemp
std::string * sPtrTemp
Vector4f v4f_defFontCol
float fMouseDelay
float fMouseDelayConst
std::string sBuffer
Timer timer
Protected Member Functions
uint checkInput (int x, int y, int bufferLength, Vector2f fontSize)
uint checkOver (int x, int y, int bufferLength, Vector2f fontSize)
Private Attributes
_TextSys * textSys
Detailed Description
Definition at line 16 of file MenuSys.h.
Constructor & Destructor Documentation
_MenuSys()
Core::GameSys::_MenuSys::_MenuSys (_TextSys & t)
Definition at line 58 of file MenuSys.h.
References fMouseDelay, fMouseDelayConst, fPtrTemp, gettingInput, iPtrTemp, isFloat, isInt, isString, sPtrTemp, Core::Timer::start(), t, textSys, and timer.
Member Function Documentation
checkInput()
uint Core::GameSys::_MenuSys::checkInput (int x, int y, int bufferLength, Vector2f fontSize) protected
Definition at line 267 of file MenuSys.h.
References fMouseDelay, fMouseDelayConst, Core::GameVars::font, Core::gameVars, Core::Timer::get_ticks(), Core::gmath, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_LEFT, Core::_Mouse::MOUSE_NONE, timer, and Core::GameVars::Font::vSize.
Referenced by draw().
checkOver()
uint Core::GameSys::_MenuSys::checkOver (int x, int y, int bufferLength, Vector2f fontSize) protected
Definition at line 303 of file MenuSys.h.
References Core::GameVars::font, Core::gameVars, Core::gmath, Core::mouse, Core::_Mouse::MOUSE_NONE, and Core::GameVars::Font::vSize.
Referenced by draw().
draw() [1/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, bool * bPtr)
Definition at line 208 of file MenuSys.h.
References checkInput(), Core::_TextSys::draw(), Core::GameVars::font, Core::gameVars, gettingInput, Core::mouse, textSys, to_string(), and Core::GameVars::Font::vSize.
draw() [2/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, bool * bPtr, Color fontColor)
Definition at line 201 of file MenuSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
draw() [3/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, bool * bPtr, Color fontColor, Color hlColor)
Definition at line 192 of file MenuSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), Core::_Colors::PopFrontHighlight(), Core::_Colors::PushFront(), and Core::_Colors::PushFrontHighlight().
draw() [4/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, float * fPtr, bool drawDec = true)
Definition at line 120 of file MenuSys.h.
References checkInput(), Core::_TextSys::draw(), Core::GameVars::font, fPtrTemp, Core::gameVars, gettingInput, isFloat, Core::itoa(), Core::mouse, sBuffer, textSys, to_string(), and Core::GameVars::Font::vSize.
draw() [5/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, float * fPtr, Color fontColor, bool drawDec = true)
Definition at line 113 of file MenuSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
draw() [6/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, float * fPtr, Color fontColor, Color hlColor, bool drawDec = true)
Definition at line 104 of file MenuSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), Core::_Colors::PopFrontHighlight(), Core::_Colors::PushFront(), and Core::_Colors::PushFrontHighlight().
draw() [7/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, int * iPtr)
Definition at line 168 of file MenuSys.h.
References checkInput(), Core::_TextSys::draw(), Core::GameVars::font, Core::gameVars, gettingInput, iPtrTemp, isInt, Core::itoa(), Core::mouse, sBuffer, textSys, to_string(), and Core::GameVars::Font::vSize.
draw() [8/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, int * iPtr, Color fontColor)
Definition at line 161 of file MenuSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
draw() [9/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, int * iPtr, Color fontColor, Color hlColor)
Definition at line 152 of file MenuSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), Core::_Colors::PopFrontHighlight(), Core::_Colors::PushFront(), and Core::_Colors::PushFrontHighlight().
draw() [10/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, std::string * sPtr)
Definition at line 242 of file MenuSys.h.
References checkInput(), Core::_TextSys::draw(), Core::GameVars::font, Core::gameVars, gettingInput, isString, Core::mouse, sBuffer, sPtrTemp, textSys, and Core::GameVars::Font::vSize.
draw() [11/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, std::string * sPtr, Color fontColor)
Definition at line 235 of file MenuSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
draw() [12/15]
bool Core::GameSys::_MenuSys::draw (int x, int y, int z, std::string buffer, std::string * sPtr, Color fontColor, Color hlColor)
Definition at line 226 of file MenuSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), Core::_Colors::PopFrontHighlight(), Core::_Colors::PushFront(), and Core::_Colors::PushFrontHighlight().
draw() [13/15]
uint Core::GameSys::_MenuSys::draw (int x, int y, std::string buffer)
Definition at line 75 of file MenuSys.h.
Referenced by draw().
draw() [14/15]
uint Core::GameSys::_MenuSys::draw (int x, int y, std::string buffer, Color fontColor1)
Definition at line 81 of file MenuSys.h.
References draw().
draw() [15/15]
uint Core::GameSys::_MenuSys::draw (int x, int y, std::string buffer, Color fontColor1, Color fontColor2)
Definition at line 86 of file MenuSys.h.
References checkInput(), checkOver(), Core::_TextSys::draw(), Core::GameVars::font, Core::gameVars, Core::mouse, textSys, and Core::GameVars::Font::vSize.
Member Data Documentation
fMouseDelay
float Core::GameSys::_MenuSys::fMouseDelay
Definition at line 32 of file MenuSys.h.
Referenced by _MenuSys(), and checkInput().
fMouseDelayConst
float Core::GameSys::_MenuSys::fMouseDelayConst
Definition at line 32 of file MenuSys.h.
Referenced by _MenuSys(), and checkInput().
fPtrTemp
float* Core::GameSys::_MenuSys::fPtrTemp
Definition at line 29 of file MenuSys.h.
Referenced by _MenuSys(), and draw().
gettingInput
bool Core::GameSys::_MenuSys::gettingInput
Definition at line 26 of file MenuSys.h.
Referenced by _MenuSys(), and draw().
iPtrTemp
int* Core::GameSys::_MenuSys::iPtrTemp
Definition at line 28 of file MenuSys.h.
Referenced by _MenuSys(), and draw().
isFloat
bool Core::GameSys::_MenuSys::isFloat
Definition at line 27 of file MenuSys.h.
Referenced by _MenuSys(), and draw().
isInt
bool Core::GameSys::_MenuSys::isInt
Definition at line 27 of file MenuSys.h.
Referenced by _MenuSys(), and draw().
isString
bool Core::GameSys::_MenuSys::isString
Definition at line 27 of file MenuSys.h.
Referenced by _MenuSys(), and draw().
sBuffer
std::string Core::GameSys::_MenuSys::sBuffer
Definition at line 33 of file MenuSys.h.
Referenced by draw().
sPtrTemp
std::string* Core::GameSys::_MenuSys::sPtrTemp
Definition at line 30 of file MenuSys.h.
Referenced by _MenuSys(), and draw().
textSys
_TextSys* Core::GameSys::_MenuSys::textSys private
Definition at line 18 of file MenuSys.h.
Referenced by _MenuSys(), and draw().
timer
Timer Core::GameSys::_MenuSys::timer
Definition at line 34 of file MenuSys.h.
Referenced by _MenuSys(), and checkInput().
v4f_defFontCol
Vector4f Core::GameSys::_MenuSys::v4f_defFontCol
Definition at line 31 of file MenuSys.h.
The documentation for this class was generated from the following file:
src/headers/gamesys/MenuSys.h