Project Parsec: Core::GameSys::Atmosphere Class Reference
Core::GameSys::Atmosphere Class Reference
#include <atmosphere.h>
Classes
struct _SKYBOX
Public Types
enum _MODES {
MODE_SKYBOX, MODE_TROPOSPHERE, MODE_STRATOSPHERE, MODE_MESOSPHERE,
MODE_THERMOSPHERE, MODE_EXOSPHERE, MODE_SATELLITE, MODE_FLARES,
MODE_FLORA, MODE_LAST
}
Public Member Functions
bool init ()
bool load ()
bool calc ()
void update (uint mode)
void draw (uint mode,...)
uint AddSatellite ()
Atmosphere ()
~Atmosphere ()
Public Attributes
_Satellite * satellite
_Particles * particlesOld
struct Core::GameSys::Atmosphere::_SKYBOX skybox
Private Member Functions
bool calc (uint mode)
bool calc (uint mode, bool bUpdate)
void start (int x, int y, float w, float h, std::string sTex, Vector4f fontColor, bool textOffset)
void stop ()
Static Private Attributes
static const int NUM_TEXTURES = 32
Detailed Description
Definition at line 130 of file atmosphere.h.
Member Enumeration Documentation
_MODES
enum Core::GameSys::Atmosphere::_MODES
Enumerator
MODE_SKYBOX
MODE_TROPOSPHERE
MODE_STRATOSPHERE
MODE_MESOSPHERE
MODE_THERMOSPHERE
MODE_EXOSPHERE
MODE_SATELLITE
MODE_FLARES
MODE_FLORA
MODE_LAST
Definition at line 184 of file atmosphere.h.
Constructor & Destructor Documentation
Atmosphere()
Core::GameSys::Atmosphere::Atmosphere () inline
Definition at line 315 of file atmosphere.h.
References Core::GameVars::Screen::fScale, Core::gameVars, particlesOld, satellite, and Core::GameVars::screen.
~Atmosphere()
Core::GameSys::Atmosphere::~Atmosphere () inline
Definition at line 319 of file atmosphere.h.
References cout, particlesOld, and satellite.
Member Function Documentation
AddSatellite()
uint Core::GameSys::Atmosphere::AddSatellite ()
calc() [1/3]
bool Core::GameSys::Atmosphere::calc ()
Definition at line 1847 of file atmosphere.h.
References cout, MODE_LAST, Core::PopStr(), and Core::sOffset.
calc() [2/3]
bool Core::GameSys::Atmosphere::calc (uint mode) private
Definition at line 1865 of file atmosphere.h.
References Core::_Particles::calc(), Core::GameSys::_Satellite::calc(), MODE_FLORA, MODE_SATELLITE, MODE_SKYBOX, particlesOld, and satellite.
Referenced by Core::GameSys::_WorldMap::calc(), and Core::GameSys::Atmosphere::_SKYBOX::calc().
calc() [3/3]
bool Core::GameSys::Atmosphere::calc (uint mode, bool bUpdate) private
draw()
void Core::GameSys::Atmosphere::draw (uint mode, ...)
Definition at line 1898 of file atmosphere.h.
References Core::GameVars::Player::active, cout, Core::VAO::Draw(), Core::_Particles::draw(), Core::GameSys::_Satellite::draw(), Core::GameSys::_Satellite::drawFlare(), Core::GameSys::Atmosphere::_SKYBOX::exosphere, Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::fScale, Core::gameVars, Core::GameSys::_Satellite::getPosition(), GL_CULL_FACE, GL_TEXTURE0, Core::GLM_DRAW_ELEMENTS, Core::GLS_EXOSPHERE, Core::GLS_FLORA, MODE_EXOSPHERE, MODE_FLARES, MODE_FLORA, MODE_SATELLITE, particlesOld, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, satellite, Core::Texture::Set(), Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::sImage, skybox, Core::GameSys::Atmosphere::_SKYBOX::tex, Core::timeSys, Core::GameSys::CharSheet::transform, and Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::vao.
Referenced by Core::GameSys::Atmosphere::_SKYBOX::_TROPOSPHERE::draw(), Core::GameSys::Atmosphere::_SKYBOX::_STRATOSPHERE::draw(), Core::GameSys::Atmosphere::_SKYBOX::_MESOSPHERE::draw(), Core::GameSys::Atmosphere::_SKYBOX::_THERMOSPHERE::draw(), Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::draw(), Core::GameSys::Atmosphere::_SKYBOX::draw(), and _Game::Update().
init()
bool Core::GameSys::Atmosphere::init ()
Definition at line 331 of file atmosphere.h.
References Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::bCubeMap, cout, Core::GameSys::Atmosphere::_SKYBOX::exosphere, Core::GameSys::Atmosphere::_SKYBOX::_TROPOSPHERE::fScale, Core::GameSys::Atmosphere::_SKYBOX::_STRATOSPHERE::fScale, Core::GameSys::Atmosphere::_SKYBOX::_MESOSPHERE::fScale, Core::GameSys::Atmosphere::_SKYBOX::_THERMOSPHERE::fScale, Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::fScale, Core::GameSys::Atmosphere::_SKYBOX::mesosphere, Core::GameSys::Atmosphere::_SKYBOX::_STRATOSPHERE::sBump, Core::GameSys::Atmosphere::_SKYBOX::_STRATOSPHERE::sCloud, Core::GameSys::Atmosphere::_SKYBOX::_TROPOSPHERE::sImage, Core::GameSys::Atmosphere::_SKYBOX::_MESOSPHERE::sImage, Core::GameSys::Atmosphere::_SKYBOX::_THERMOSPHERE::sImage, Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::sImage, skybox, Core::sOffset, Core::GameSys::Atmosphere::_SKYBOX::stratosphere, Core::GameSys::Atmosphere::_SKYBOX::thermosphere, and Core::GameSys::Atmosphere::_SKYBOX::troposphere.
Referenced by Core::GameSys::_WorldMap::_WorldMap().
load()
bool Core::GameSys::Atmosphere::load ()
Definition at line 1226 of file atmosphere.h.
References Core::GameVars::Player::active, Core::_Particles::add(), Core::GameSys::_Satellite::add(), Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::bCubeMap, Core::VAO::Begin(), Core::Texture::Begin(), Core::MemBlock::buffer, Core::VAO::CopyData(), cout, Core::EMITTER_STATIC, Core::VAO::End(), Core::GameSys::Atmosphere::_SKYBOX::exosphere, Core::gameVars, GL_NONE, GL_REPEAT, GL_TRIANGLES, Core::GLA_INDEX, Core::GLA_NORMAL, Core::GLA_TEXTURE, Core::GLA_VERTEX, Core::PLY_Loader::load(), Core::Texture::Load(), NUM_TEXTURES, Core::PLY_Loader::numDrawVerts, Core::PLY_Loader::numVerts, Core::PARTICLE_QUAD, particlesOld, Core::GameVars::player, Core::PopStr(), Core::GameSys::CharSheet::Transform::pos, Core::readFile(), satellite, Core::MemBlock::size, skybox, Core::sOffset, Core::GameSys::Atmosphere::_SKYBOX::stratosphere, Core::GameSys::Atmosphere::_SKYBOX::tex, Core::GameSys::Atmosphere::_SKYBOX::thermosphere, Core::GameSys::CharSheet::transform, Core::GameSys::Atmosphere::_SKYBOX::troposphere, Core::GameSys::Atmosphere::_SKYBOX::_TROPOSPHERE::vao, Core::GameSys::Atmosphere::_SKYBOX::_STRATOSPHERE::vao, Core::GameSys::Atmosphere::_SKYBOX::_THERMOSPHERE::vao, Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::vao, Core::PLY_Loader::vCoords, Core::PLY_Loader::vIndex, Core::PLY_Loader::vNorms, and Core::PLY_Loader::vVerts.
Referenced by Core::GameSys::_WorldMap::load().
start()
void Core::GameSys::Atmosphere::start (int x, int y, float w, float h, std::string sTex, Vector4f fontColor, bool textOffset) private
stop()
void Core::GameSys::Atmosphere::stop () private
update()
void Atmosphere::update (uint mode)
Definition at line 1885 of file atmosphere.h.
References MODE_FLORA, MODE_SATELLITE, MODE_SKYBOX, particlesOld, satellite, Core::_Particles::update(), and Core::GameSys::_Satellite::update().
Referenced by Core::GameSys::_WorldMap::draw(), Core::GameSys::Atmosphere::_SKYBOX::_TROPOSPHERE::update(), Core::GameSys::Atmosphere::_SKYBOX::_STRATOSPHERE::update(), Core::GameSys::Atmosphere::_SKYBOX::_MESOSPHERE::update(), Core::GameSys::Atmosphere::_SKYBOX::_THERMOSPHERE::update(), Core::GameSys::Atmosphere::_SKYBOX::_EXOSPHERE::update(), and Core::GameSys::Atmosphere::_SKYBOX::update().
Member Data Documentation
NUM_TEXTURES
const int Core::GameSys::Atmosphere::NUM_TEXTURES = 32 static private
Definition at line 140 of file atmosphere.h.
Referenced by load().
particlesOld
_Particles* Core::GameSys::Atmosphere::particlesOld
Definition at line 167 of file atmosphere.h.
Referenced by Atmosphere(), calc(), draw(), load(), update(), and ~Atmosphere().
satellite
_Satellite* Core::GameSys::Atmosphere::satellite
Definition at line 165 of file atmosphere.h.
Referenced by Atmosphere(), calc(), draw(), load(), _Game::Update(), update(), and ~Atmosphere().
skybox
struct Core::GameSys::Atmosphere::_SKYBOX Core::GameSys::Atmosphere::skybox
Referenced by draw(), init(), and load().
The documentation for this class was generated from the following files:
src/headers/gamesys/atmosphere.h
src/headers/gamesys/ref/Atmosphere_Particles.h