Project Parsec: Core::PostProcess Class Reference
Core::PostProcess Class Reference
#include <post_process.h>
Public Member Functions
PostProcess ()
~PostProcess ()
void init (int iW, int iH, uint uiMultisamples)
void RenderLayer (std::string name)
GLuint EndRenderLayer ()
GLuint Draw (std::string name)
GLuint ApplyContrast (GLuint tex, float fContrast)
GLuint ApplyUnderwater (GLuint tex)
GLuint ApplyBrightness (GLuint tex, Core::Vector3f vBrightness)
GLuint ApplyBrightnessFilter (GLuint tex, Core::Vector3f vFactor, float fMax)
GLuint ApplyRadialBlur (GLuint tex)
GLuint ApplyHBlur (GLuint tex)
GLuint ApplyVBlur (GLuint tex)
GLuint ApplyGaussian (GLuint tex)
GLuint ApplyRayBlur (GLuint tex)
GLuint ApplyBloom (GLuint tex)
GLuint ApplyDepthOfField (GLuint tex, std::string sDepthName)
GLuint ApplyVinette (GLuint tex)
GLuint ApplyLensFlare (GLuint tex)
GLuint ApplyCartoon (GLuint tex)
GLuint ApplyPixelate (GLuint tex)
GLuint ApplyCombine (GLuint tex0, GLuint tex1, float fIntensity)
GLuint ApplyContrast (float fContrast)
GLuint ApplyUnderwater ()
GLuint ApplyBrightness (Core::Vector3f vBrightness)
GLuint ApplyBrightnessFilter (Core::Vector3f vFactor, float fMax)
GLuint ApplyRadialBlur ()
GLuint ApplyHBlur ()
GLuint ApplyVBlur ()
GLuint ApplyGaussian ()
GLuint ApplyRayBlur ()
GLuint ApplyBloom ()
GLuint ApplyDepthOfField (std::string sDepthName)
GLuint ApplyVinette ()
GLuint ApplyLensFlare ()
GLuint ApplyCartoon ()
GLuint ApplyPixelate ()
GLuint ApplyCombine (GLuint tex, float fIntensity)
void RenderToWindow (GLuint tex, Vector3f vTranslate, float fScale=0.25f)
void RenderToScreen (GLuint tex)
void RenderToScreen ()
Public Attributes
bool bEnable
Private Member Functions
void Render ()
void Render (SHADER_PROGRAMS uiShader)
void Render2 (SHADER_PROGRAMS uiShader, Vector3f vTranslate=Vector3f(), float fScale=0.25f)
void RenderQuad (int x, int y, int w, int h, SHADER_PROGRAMS uiShader=Core::GLS_FONT, bool bCenter=false, bool bClear=false)
Private Attributes
VAO vao
GLuint texResult
bool bResult
std::string name
Vector2ui vuiScreenSize
Detailed Description
Definition at line 17 of file post_process.h.
Constructor & Destructor Documentation
PostProcess()
Core::PostProcess::PostProcess ()
Definition at line 91 of file post_process.h.
References bEnable, bResult, and texResult.
~PostProcess()
Core::PostProcess::~PostProcess ()
Definition at line 102 of file post_process.h.
References cout.
Member Function Documentation
ApplyBloom() [1/2]
GLuint Core::PostProcess::ApplyBloom () inline
Definition at line 75 of file post_process.h.
References ApplyBloom(), bResult, and texResult.
Referenced by ApplyBloom().
ApplyBloom() [2/2]
GLuint Core::PostProcess::ApplyBloom (GLuint tex)
ApplyBrightness() [1/2]
GLuint Core::PostProcess::ApplyBrightness (Core::Vector3f vBrightness) inline
Definition at line 68 of file post_process.h.
References ApplyBrightness(), bResult, and texResult.
Referenced by ApplyBrightness().
ApplyBrightness() [2/2]
GLuint Core::PostProcess::ApplyBrightness (GLuint tex, Core::Vector3f vBrightness)
Definition at line 313 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, Core::_FBO::GetTexture(), GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_PP_BRIGHTNESS, Render(), texResult, and Core::_FBO::UnbindFbo().
Referenced by _Game::Update(), and _TheVoid::Update().
ApplyBrightnessFilter() [1/2]
GLuint Core::PostProcess::ApplyBrightnessFilter (Core::Vector3f vFactor, float fMax) inline
Definition at line 69 of file post_process.h.
References ApplyBrightnessFilter(), bResult, and texResult.
Referenced by ApplyBrightnessFilter().
ApplyBrightnessFilter() [2/2]
GLuint Core::PostProcess::ApplyBrightnessFilter (GLuint tex, Core::Vector3f vFactor, float fMax)
Definition at line 326 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, Core::_FBO::GetTexture(), GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_PP_BRIGHTNESS_FILTER, Render(), texResult, and Core::_FBO::UnbindFbo().
Referenced by _Game::Update().
ApplyCartoon() [1/2]
GLuint Core::PostProcess::ApplyCartoon () inline
Definition at line 80 of file post_process.h.
References ApplyCartoon(), bResult, and texResult.
Referenced by ApplyCartoon().
ApplyCartoon() [2/2]
GLuint Core::PostProcess::ApplyCartoon (GLuint tex)
ApplyCombine() [1/2]
GLuint Core::PostProcess::ApplyCombine (GLuint tex, float fIntensity) inline
Definition at line 82 of file post_process.h.
References ApplyCombine(), bResult, and texResult.
Referenced by ApplyCombine().
ApplyCombine() [2/2]
GLuint Core::PostProcess::ApplyCombine (GLuint tex0, GLuint tex1, float fIntensity)
Definition at line 378 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, Core::_FBO::GetTexture(), GL_TEXTURE0, GL_TEXTURE1, GL_TEXTURE_2D, Core::GLS_PP_COMBINE, Render(), texResult, and Core::_FBO::UnbindFbo().
Referenced by _Game::Update(), and _TheVoid::Update().
ApplyContrast() [1/2]
GLuint Core::PostProcess::ApplyContrast (float fContrast) inline
Definition at line 66 of file post_process.h.
References ApplyContrast(), bResult, and texResult.
Referenced by ApplyContrast().
ApplyContrast() [2/2]
GLuint Core::PostProcess::ApplyContrast (GLuint tex, float fContrast)
Definition at line 289 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, Core::_FBO::GetTexture(), GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_PP_CONTRAST, Render(), texResult, and Core::_FBO::UnbindFbo().
Referenced by _Game::Update(), and _TheVoid::Update().
ApplyDepthOfField() [1/2]
GLuint Core::PostProcess::ApplyDepthOfField (GLuint tex, std::string sDepthName)
ApplyDepthOfField() [2/2]
GLuint Core::PostProcess::ApplyDepthOfField (std::string sDepthName) inline
Definition at line 76 of file post_process.h.
References ApplyDepthOfField(), bResult, and texResult.
Referenced by ApplyDepthOfField().
ApplyGaussian() [1/2]
GLuint Core::PostProcess::ApplyGaussian () inline
Definition at line 73 of file post_process.h.
References ApplyGaussian(), bResult, and texResult.
Referenced by ApplyGaussian().
ApplyGaussian() [2/2]
GLuint Core::PostProcess::ApplyGaussian (GLuint tex)
ApplyHBlur() [1/2]
GLuint Core::PostProcess::ApplyHBlur () inline
Definition at line 71 of file post_process.h.
References ApplyHBlur(), bResult, and texResult.
Referenced by ApplyHBlur().
ApplyHBlur() [2/2]
GLuint Core::PostProcess::ApplyHBlur (GLuint tex)
Definition at line 352 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, Core::_FBO::GetTexture(), GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_PP_HBLUR, Render(), texResult, and Core::_FBO::UnbindFbo().
Referenced by _Game::Update(), and _TheVoid::Update().
ApplyLensFlare() [1/2]
GLuint Core::PostProcess::ApplyLensFlare ()
Definition at line 393 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, Core::_FBO::GetTexture(), GL_BLEND, GL_ONE, GL_ONE_MINUS_SRC_ALPHA, GL_SRC_ALPHA, GL_TEXTURE0, GL_TEXTURE_2D, Render(), texResult, and Core::_FBO::UnbindFbo().
ApplyLensFlare() [2/2]
GLuint Core::PostProcess::ApplyLensFlare (GLuint tex)
Referenced by _TheVoid::Update().
ApplyPixelate() [1/2]
GLuint Core::PostProcess::ApplyPixelate () inline
Definition at line 81 of file post_process.h.
References ApplyPixelate(), bResult, and texResult.
Referenced by ApplyPixelate().
ApplyPixelate() [2/2]
GLuint Core::PostProcess::ApplyPixelate (GLuint tex)
ApplyRadialBlur() [1/2]
GLuint Core::PostProcess::ApplyRadialBlur () inline
Definition at line 70 of file post_process.h.
References ApplyRadialBlur(), bResult, and texResult.
Referenced by ApplyRadialBlur().
ApplyRadialBlur() [2/2]
GLuint Core::PostProcess::ApplyRadialBlur (GLuint tex)
Definition at line 339 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, Core::_FBO::GetTexture(), GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_PP_RADIALBLUR, Render(), texResult, and Core::_FBO::UnbindFbo().
Referenced by _Game::Update().
ApplyRayBlur() [1/2]
GLuint Core::PostProcess::ApplyRayBlur () inline
Definition at line 74 of file post_process.h.
References ApplyRayBlur(), bResult, and texResult.
Referenced by ApplyRayBlur().
ApplyRayBlur() [2/2]
GLuint Core::PostProcess::ApplyRayBlur (GLuint tex)
ApplyUnderwater() [1/2]
GLuint Core::PostProcess::ApplyUnderwater () inline
Definition at line 67 of file post_process.h.
References ApplyUnderwater(), bResult, and texResult.
Referenced by ApplyUnderwater().
ApplyUnderwater() [2/2]
GLuint Core::PostProcess::ApplyUnderwater (GLuint tex)
Referenced by _TheVoid::Update().
ApplyVBlur() [1/2]
GLuint Core::PostProcess::ApplyVBlur () inline
Definition at line 72 of file post_process.h.
References ApplyVBlur(), bResult, and texResult.
Referenced by ApplyVBlur().
ApplyVBlur() [2/2]
GLuint Core::PostProcess::ApplyVBlur (GLuint tex)
Definition at line 365 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, Core::_FBO::GetTexture(), GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_PP_VBLUR, Render(), texResult, and Core::_FBO::UnbindFbo().
Referenced by _Game::Update(), and _TheVoid::Update().
ApplyVinette() [1/2]
GLuint Core::PostProcess::ApplyVinette () inline
Definition at line 77 of file post_process.h.
References ApplyVinette(), bResult, and texResult.
Referenced by ApplyVinette().
ApplyVinette() [2/2]
GLuint Core::PostProcess::ApplyVinette (GLuint tex)
Draw()
GLuint Core::PostProcess::Draw (std::string name)
EndRenderLayer()
GLuint Core::PostProcess::EndRenderLayer ()
Definition at line 279 of file post_process.h.
References bResult, Core::fbo, Core::_FBO::GetTexture(), Core::_FBO::ResolveFBO(), texResult, and Core::_FBO::UnbindFbo().
Referenced by _Game::Update(), and _TheVoid::Update().
init()
void Core::PostProcess::init (int iW, int iH, uint uiMultisamples)
Definition at line 110 of file post_process.h.
References Core::_FBO::AddColorAttachment(), Core::_FBO::AddDepthBuffer(), Core::_FBO::AddDepthTexture(), Core::VAO::Begin(), Core::VAO::CopyData(), cout, Core::_FBO::CreateFbo(), Core::VAO::End(), Core::fbo, Core::_FBO::FinishFbo(), GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, vao, and vuiScreenSize.
Referenced by MY_NAMESPACE::Setup().
Render() [1/2]
void Core::PostProcess::Render () private
Definition at line 615 of file post_process.h.
References Core::colors, Core::VAO::Draw(), GL_DEPTH_TEST, Core::_Colors::PopFront(), Core::_Colors::PushFront(), Core::_Colors::SetActive(), vao, vuiScreenSize, Core::Vector2ui::x, and Core::Vector2ui::y.
Referenced by ApplyBrightness(), ApplyBrightnessFilter(), ApplyCombine(), ApplyContrast(), ApplyHBlur(), ApplyLensFlare(), ApplyRadialBlur(), ApplyVBlur(), Render(), and RenderToScreen().
Render() [2/2]
void Core::PostProcess::Render (SHADER_PROGRAMS uiShader) private
Definition at line 609 of file post_process.h.
References Render().
Render2()
void Core::PostProcess::Render2 (SHADER_PROGRAMS uiShader, Vector3f vTranslate = Vector3f(), float fScale = 0.25f) private
Definition at line 641 of file post_process.h.
References Core::colors, Core::VAO::Draw(), GL_DEPTH_TEST, Core::_Colors::PopFront(), Core::_Colors::PushFront(), Core::_Colors::SetActive(), vao, vuiScreenSize, Core::Vector2ui::x, and Core::Vector2ui::y.
Referenced by RenderToWindow().
RenderLayer()
void Core::PostProcess::RenderLayer (std::string name) inline
Definition at line 45 of file post_process.h.
References Core::_FBO::BindFbo(), Core::fbo, and name.
Referenced by _Game::Update(), and _TheVoid::Update().
RenderQuad()
void Core::PostProcess::RenderQuad (int x, int y, int w, int h, SHADER_PROGRAMS uiShader = Core::GLS_FONT, bool bCenter = false, bool bClear = false) private
Definition at line 573 of file post_process.h.
References Core::VAO::Draw(), GL_DEPTH_TEST, vao, vuiScreenSize, x, Core::Vector2ui::x, y, and Core::Vector2ui::y.
RenderToScreen() [1/2]
void Core::PostProcess::RenderToScreen () inline
Definition at line 86 of file post_process.h.
References GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_FONT, Render(), and texResult.
RenderToScreen() [2/2]
void Core::PostProcess::RenderToScreen (GLuint tex) inline
Definition at line 85 of file post_process.h.
References GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_FONT, and Render().
Referenced by _Game::Update(), and _TheVoid::Update().
RenderToWindow()
void Core::PostProcess::RenderToWindow (GLuint tex, Vector3f vTranslate, float fScale = 0.25f) inline
Definition at line 84 of file post_process.h.
References GL_TEXTURE0, GL_TEXTURE_2D, Core::GLS_FONT, and Render2().
Referenced by _Game::Update().
Member Data Documentation
bEnable
bool Core::PostProcess::bEnable
Definition at line 40 of file post_process.h.
Referenced by PostProcess(), and _TheVoid::Update().
bResult
bool Core::PostProcess::bResult private
Definition at line 30 of file post_process.h.
Referenced by ApplyBloom(), ApplyBrightness(), ApplyBrightnessFilter(), ApplyCartoon(), ApplyCombine(), ApplyContrast(), ApplyDepthOfField(), ApplyGaussian(), ApplyHBlur(), ApplyPixelate(), ApplyRadialBlur(), ApplyRayBlur(), ApplyUnderwater(), ApplyVBlur(), ApplyVinette(), EndRenderLayer(), and PostProcess().
name
std::string Core::PostProcess::name private
Definition at line 32 of file post_process.h.
Referenced by RenderLayer().
texResult
GLuint Core::PostProcess::texResult private
Definition at line 28 of file post_process.h.
Referenced by ApplyBloom(), ApplyBrightness(), ApplyBrightnessFilter(), ApplyCartoon(), ApplyCombine(), ApplyContrast(), ApplyDepthOfField(), ApplyGaussian(), ApplyHBlur(), ApplyLensFlare(), ApplyPixelate(), ApplyRadialBlur(), ApplyRayBlur(), ApplyUnderwater(), ApplyVBlur(), ApplyVinette(), EndRenderLayer(), PostProcess(), and RenderToScreen().
vao
VAO Core::PostProcess::vao private
Definition at line 27 of file post_process.h.
Referenced by init(), Render(), Render2(), and RenderQuad().
vuiScreenSize
Vector2ui Core::PostProcess::vuiScreenSize private
Definition at line 33 of file post_process.h.
Referenced by init(), Render(), Render2(), and RenderQuad().
The documentation for this class was generated from the following file:
src/headers/core/post_process.h