Project Parsec: Core::GameSys::_O2D Class Reference
Core::GameSys::_O2D Class Reference
#include <O2D.h>
Public Member Functions
_O2D (Matrix_System &m, Shader_System &s)
~_O2D ()
bool init ()
bool load ()
bool calc ()
void draw (SHADER_PROGRAMS iShader, Core::_Lights &lights, bool bBB, bool bSort)
Private Attributes
Matrix_System * matrix
Shader_System * shader
_O2DData data
_O2DGroup group
uint uiRecordSize
std::string sTexDir
Detailed Description
Definition at line 89 of file O2D.h.
Constructor & Destructor Documentation
_O2D()
Core::GameSys::_O2D::_O2D (Matrix_System & m, Shader_System & s)
Definition at line 115 of file O2D.h.
References sTexDir, and uiRecordSize.
~_O2D()
Core::GameSys::_O2D::~_O2D ()
Definition at line 122 of file O2D.h.
References cout.
Member Function Documentation
calc()
bool Core::GameSys::_O2D::calc ()
Definition at line 219 of file O2D.h.
References cout, Core::GameVars::Screen::fScale, Core::gameVars, GL_TRIANGLE_STRIP, Core::GLA_TEXTURE, Core::GLA_VERTEX, Core::GameVars::screen, and Core::sOffset.
Referenced by Core::GameSys::_WorldMap::calc().
draw()
void Core::GameSys::_O2D::draw (SHADER_PROGRAMS iShader, Core::_Lights & lights, bool bBB = true, bool bSort = false)
Definition at line 502 of file O2D.h.
References Core::GameVars::Player::active, Core::GameVars::Screen::fScale, Core::gameVars, GL_CULL_FACE, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::screen, and Core::GameSys::CharSheet::transform.
Referenced by Core::GameSys::_WorldMap::draw().
init()
bool Core::GameSys::_O2D::init ()
Definition at line 127 of file O2D.h.
References cout, and Core::sOffset.
load()
bool Core::GameSys::_O2D::load ()
Definition at line 134 of file O2D.h.
References Core::MemBlock::buffer, cout, Core::readFile(), Core::MemBlock::size, Core::sOffset, sTexDir, and uiRecordSize.
Referenced by Core::GameSys::_WorldMap::load().
Member Data Documentation
data
_O2DData Core::GameSys::_O2D::data private
Definition at line 93 of file O2D.h.
group
_O2DGroup Core::GameSys::_O2D::group private
Definition at line 94 of file O2D.h.
matrix
Matrix_System* Core::GameSys::_O2D::matrix private
Definition at line 91 of file O2D.h.
shader
Shader_System* Core::GameSys::_O2D::shader private
Definition at line 92 of file O2D.h.
sTexDir
std::string Core::GameSys::_O2D::sTexDir private
Definition at line 101 of file O2D.h.
Referenced by _O2D(), and load().
uiRecordSize
uint Core::GameSys::_O2D::uiRecordSize private
Definition at line 100 of file O2D.h.
Referenced by _O2D(), and load().
The documentation for this class was generated from the following file:
src/headers/gamesys/O2D.h