Project Parsec: Core::GUI::GUI::FieldInterface Class Reference
Core::GUI::GUI::FieldInterface Class Reference
#include <GUI.h>
Public Member Functions
template<typename T >
void add (std::string guiName, std::string fieldName, T *ptr, Constraints_Field c)
template<typename T >
void add (std::string guiName, std::string windowName, std::string fieldName, T *ptr, Constraints_Field c)
template<typename T >
void add (std::string guiName, std::string fieldName, T *ptr, Constraints_Field *c)
template<typename T >
void add (std::string guiName, std::string windowName, std::string fieldName, T *ptr, Constraints_Field *c)
Constraints_Field * get (std::string guiName, std::string fieldName)
FieldInterface (GUI *parent)
Public Attributes
GUI * gui
Detailed Description
Definition at line 162 of file GUI.h.
Constructor & Destructor Documentation
FieldInterface()
Core::GUI::GUI::FieldInterface::FieldInterface (GUI * parent) inline
Definition at line 170 of file GUI.h.
References gui.
Member Function Documentation
add() [1/4]
template<typename T > void Core::GUI::GUI::FieldInterface::add (std::string guiName, std::string fieldName, T * ptr, Constraints_Field * c)
Definition at line 688 of file GUI.h.
References MY_NAMESPACE::gui, Core::GUI::Object::AnyField::init(), and Core::GUI::Object::AnyField::set().
add() [2/4]
template<typename T > void Core::GUI::GUI::FieldInterface::add (std::string guiName, std::string fieldName, T * ptr, Constraints_Field c)
Definition at line 667 of file GUI.h.
References MY_NAMESPACE::gui, Core::GUI::Object::AnyField::init(), and Core::GUI::Object::AnyField::set().
add() [3/4]
template<typename T > void Core::GUI::GUI::FieldInterface::add (std::string guiName, std::string windowName, std::string fieldName, T * ptr, Constraints_Field * c)
Definition at line 698 of file GUI.h.
References MY_NAMESPACE::gui, Core::GUI::Object::AnyField::init(), and Core::GUI::Object::AnyField::set().
add() [4/4]
template<typename T > void Core::GUI::GUI::FieldInterface::add (std::string guiName, std::string windowName, std::string fieldName, T * ptr, Constraints_Field c)
Definition at line 677 of file GUI.h.
References MY_NAMESPACE::gui, Core::GUI::Object::AnyField::init(), and Core::GUI::Object::AnyField::set().
get()
Constraints_Field * Core::GUI::GUI::FieldInterface::get (std::string guiName, std::string fieldName)
Definition at line 709 of file GUI.h.
References MY_NAMESPACE::gui.
Member Data Documentation
gui
GUI* Core::GUI::GUI::FieldInterface::gui
Definition at line 169 of file GUI.h.
Referenced by FieldInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI.h