Project Parsec: Core::GameSys::_Flora Class Reference
Core::GameSys::_Flora Class Reference
#include <flora.h>
Public Member Functions
_Flora (Atmosphere &f)
~_Flora ()
bool add (_FloraData data)
bool calc (bool bUpdate=false)
bool calc (std::string name, bool bUpdate=false)
bool calc (uint id, bool bUpdate=false)
void update ()
void update (std::string name)
void update (int id)
void draw ()
void draw (std::string name)
void draw (int id)
Public Attributes
_FloraData * data
Private Member Functions
bool init ()
Private Attributes
Atmosphere & parent
Core::Map_si map
Core::Map_is rmap
bool bErrorONS [32]
int iNumObjects
Static Private Attributes
static bool bTexLoaded = false
static Texture tex = Texture()
static const uint MAX_TEXTURES = 32
static const int MAX_OBJECTS = 16
static const uint RECORD_SIZE = 32
static const std::string DIR = "./system/"
static const std::string FILENAME = "flora.bin"
static const std::string TEXDIR = "./texture/atmosphere/flora/"
Detailed Description
Definition at line 89 of file flora.h.
Constructor & Destructor Documentation
_Flora()
Core::GameSys::_Flora::_Flora (Atmosphere & f)
Definition at line 133 of file flora.h.
References bErrorONS, init(), iNumObjects, and MAX_OBJECTS.
~_Flora()
Core::GameSys::_Flora::~_Flora ()
Definition at line 142 of file flora.h.
References data.
Member Function Documentation
add()
bool Core::GameSys::_Flora::add (_FloraData data)
Definition at line 194 of file flora.h.
References cout, iNumObjects, map, MAX_OBJECTS, rmap, and Core::GameSys::_FloraData::sName.
calc() [1/3]
bool Core::GameSys::_Flora::calc (bool bUpdate = false)
Definition at line 206 of file flora.h.
References cout, and iNumObjects.
Referenced by calc().
calc() [2/3]
bool Core::GameSys::_Flora::calc (std::string name, bool bUpdate = false)
Definition at line 219 of file flora.h.
References calc(), and map.
calc() [3/3]
bool Core::GameSys::_Flora::calc (uint id, bool bUpdate = false)
Definition at line 223 of file flora.h.
References Core::GameVars::Player::active, cout, Core::GameVars::Screen::fScale, Core::gameVars, GL_LINES, Core::GLA_NORMAL, Core::GLA_VERTEX, id, Core::Texture::iLoaded, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, rmap, Core::roll(), Core::GameVars::screen, t, tex, Core::Degrees::toRadians(), and Core::GameSys::CharSheet::transform.
draw() [1/3]
void Core::GameSys::_Flora::draw ()
Definition at line 461 of file flora.h.
References cout, and iNumObjects.
Referenced by draw().
draw() [2/3]
void Core::GameSys::_Flora::draw (int id)
Definition at line 482 of file flora.h.
References GL_TEXTURE0, id, Core::Texture::iLoaded, Core::Texture::Set(), and tex.
draw() [3/3]
void Core::GameSys::_Flora::draw (std::string name)
Definition at line 478 of file flora.h.
References draw(), and map.
init()
bool Core::GameSys::_Flora::init () private
Definition at line 152 of file flora.h.
References Core::Texture::Begin(), bTexLoaded, Core::MemBlock::buffer, cout, DIR, FILENAME, GL_NEAREST, GL_REPEAT, id, Core::Texture::Load(), Core::readFile(), RECORD_SIZE, Core::MemBlock::size, Core::sOffset, tex, and TEXDIR.
Referenced by _Flora().
update() [1/3]
void Core::GameSys::_Flora::update ()
Definition at line 369 of file flora.h.
References cout, and iNumObjects.
Referenced by update().
update() [2/3]
void Core::GameSys::_Flora::update (int id)
Definition at line 385 of file flora.h.
References Core::GameVars::Player::active, Core::distanceXZpn(), Core::GameVars::Screen::fScale, Core::gameVars, Core::Timer::get_ticks(), Core::GLA_NORMAL, Core::GLA_VERTEX, id, Core::Texture::iLoaded, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::roll(), Core::GameVars::screen, t, tex, Core::timeSys, Core::Degrees::toRadians(), and Core::GameSys::CharSheet::transform.
update() [3/3]
void Core::GameSys::_Flora::update (std::string name)
Definition at line 381 of file flora.h.
References map, and update().
Member Data Documentation
bErrorONS
bool Core::GameSys::_Flora::bErrorONS[32] private
Definition at line 116 of file flora.h.
Referenced by _Flora().
bTexLoaded
bool Core::GameSys::_Flora::bTexLoaded = false static private
Definition at line 111 of file flora.h.
Referenced by init().
data
_FloraData* Core::GameSys::_Flora::data
Definition at line 91 of file flora.h.
Referenced by ~_Flora().
DIR
const std::string Core::GameSys::_Flora::DIR = "./system/" static private
Definition at line 121 of file flora.h.
Referenced by init().
FILENAME
const std::string Core::GameSys::_Flora::FILENAME = "flora.bin" static private
Definition at line 122 of file flora.h.
Referenced by init().
iNumObjects
int Core::GameSys::_Flora::iNumObjects private
Definition at line 117 of file flora.h.
Referenced by _Flora(), add(), calc(), draw(), and update().
map
Core::Map_si Core::GameSys::_Flora::map private
Definition at line 114 of file flora.h.
Referenced by add(), calc(), draw(), and update().
MAX_OBJECTS
const int Core::GameSys::_Flora::MAX_OBJECTS = 16 static private
Definition at line 119 of file flora.h.
Referenced by _Flora(), and add().
MAX_TEXTURES
const uint Core::GameSys::_Flora::MAX_TEXTURES = 32 static private
Definition at line 118 of file flora.h.
parent
Atmosphere& Core::GameSys::_Flora::parent private
Definition at line 110 of file flora.h.
RECORD_SIZE
const uint Core::GameSys::_Flora::RECORD_SIZE = 32 static private
Definition at line 120 of file flora.h.
Referenced by init().
rmap
Core::Map_is Core::GameSys::_Flora::rmap private
Definition at line 115 of file flora.h.
Referenced by add(), and calc().
tex
Texture Core::GameSys::_Flora::tex = Texture() static private
Definition at line 112 of file flora.h.
Referenced by calc(), draw(), init(), and update().
TEXDIR
const std::string Core::GameSys::_Flora::TEXDIR = "./texture/atmosphere/flora/" static private
Definition at line 123 of file flora.h.
Referenced by init().
The documentation for this class was generated from the following file:
src/headers/gamesys/atmosphere/flora.h