Project Parsec: Core::GameSys::AnimationSys Class Reference
Core::GameSys::AnimationSys Class Reference
#include <animations.h>
Classes
struct _AnimationList
struct _RunningAnimations
Public Member Functions
AnimationSys (AudioSys &a)
~AnimationSys ()
bool init ()
bool load ()
bool calc ()
void startAnimation (float w, float h, Vector3f camera, Vector3f target, int iA, int loop, uint rate, int iSample, bool bMoveOrigin)
void startAnimation (Vector2f size, Vector3f camera, Vector3f target, int iA, int loop, uint rate, int iSample, bool bMoveOrigin)
bool drawWorld (float fScale, bool bVerticalBB=false)
bool drawWorld (int iA, float fScale, bool bVerticalBB=false)
bool isAnimating (bool bWorld=false)
Private Attributes
Timer timer
Texture texture
int iLoaded
AudioSys * audioSys
uint uiNumTextures
uint uiRecordSize
std::string sFilename
std::string sDir
std::string sTexDir
struct Core::GameSys::AnimationSys::_AnimationList animation [128]
struct Core::GameSys::AnimationSys::_RunningAnimations running [32]
struct Core::GameSys::AnimationSys::_RunningAnimations world [128]
Friends
class GameSys
Detailed Description
Definition at line 27 of file animations.h.
Constructor & Destructor Documentation
AnimationSys()
Core::GameSys::AnimationSys::AnimationSys (AudioSys & a)
Definition at line 134 of file animations.h.
References audioSys, iLoaded, sDir, sFilename, sTexDir, uiNumTextures, and uiRecordSize.
~AnimationSys()
Core::GameSys::AnimationSys::~AnimationSys ()
Definition at line 152 of file animations.h.
References animation, iLoaded, and Core::GameSys::AnimationSys::_AnimationList::vao.
Member Function Documentation
calc()
bool Core::GameSys::AnimationSys::calc ()
Definition at line 224 of file animations.h.
References animation, Core::VAO::Begin(), Core::VAO::CopyData(), cout, Core::VAO::End(), Core::GameSys::AnimationSys::_AnimationList::frames, GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, iLoaded, and Core::GameSys::AnimationSys::_AnimationList::vao.
Referenced by _Game::load().
drawWorld() [1/2]
bool Core::GameSys::AnimationSys::drawWorld (float fScale, bool bVerticalBB = false)
Definition at line 321 of file animations.h.
References animation, audioSys, Core::GameSys::AnimationSys::_RunningAnimations::bActive, Core::GameSys::AnimationSys::_RunningAnimations::currentFrame, Core::Timer::get_ticks(), Core::GameSys::AnimationSys::_RunningAnimations::id, Core::GameSys::AnimationSys::_RunningAnimations::loop, Core::AudioSys::playSound(), Core::GameSys::AnimationSys::_AnimationList::rate, running, Core::GameSys::AnimationSys::_RunningAnimations::ticks, and timer.
Referenced by _Game::Update().
drawWorld() [2/2]
bool Core::GameSys::AnimationSys::drawWorld (int iA, float fScale, bool bVerticalBB = false)
Definition at line 349 of file animations.h.
References Core::GameVars::Player::active, animation, Core::GameSys::AnimationSys::_RunningAnimations::camera, Core::_gmath::Cross(), Core::GameSys::AnimationSys::_RunningAnimations::currentFrame, Core::VAO::Draw(), Core::gameVars, GL_CULL_FACE, Core::GLS_FONT, Core::gmath, Core::GameSys::AnimationSys::_RunningAnimations::id, Core::_gmath::Normalize(), Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, running, Core::GameSys::AnimationSys::_RunningAnimations::target, Core::GameSys::CharSheet::transform, and Core::GameSys::AnimationSys::_AnimationList::vao.
init()
bool Core::GameSys::AnimationSys::init ()
Definition at line 169 of file animations.h.
References cout, iLoaded, Core::Timer::start(), timer, and uiNumTextures.
Referenced by _Game::load().
isAnimating()
bool Core::GameSys::AnimationSys::isAnimating (bool bWorld = false)
Definition at line 158 of file animations.h.
References running.
load()
bool Core::GameSys::AnimationSys::load ()
Definition at line 179 of file animations.h.
References animation, Core::MemBlock::buffer, cout, Core::GameSys::AnimationSys::_AnimationList::frames, GL_NEAREST, Core::GameSys::AnimationSys::_AnimationList::id, iLoaded, Core::GameSys::AnimationSys::_AnimationList::image, Core::readFile(), sDir, sFilename, Core::MemBlock::size, sTexDir, and uiRecordSize.
Referenced by _Game::load().
startAnimation() [1/2]
void Core::GameSys::AnimationSys::startAnimation (float w, float h, Vector3f camera, Vector3f target, int iA, int loop, uint rate, int iSample = 999, bool bMoveOrigin = true)
Definition at line 293 of file animations.h.
References w.
Referenced by _Game::Update().
startAnimation() [2/2]
void Core::GameSys::AnimationSys::startAnimation (Vector2f size, Vector3f camera, Vector3f target, int iA, int loop, uint rate, int iSample = 999, bool bMoveOrigin = false)
Definition at line 298 of file animations.h.
References animation, Core::GameSys::AnimationSys::_RunningAnimations::bActive, Core::GameSys::AnimationSys::_RunningAnimations::camera, Core::GameSys::AnimationSys::_RunningAnimations::currentFrame, Core::Timer::get_ticks(), Core::GameSys::AnimationSys::_RunningAnimations::id, Core::GameSys::AnimationSys::_AnimationList::iSample, Core::GameSys::AnimationSys::_RunningAnimations::loop, Core::GameSys::AnimationSys::_AnimationList::rate, running, Core::GameSys::AnimationSys::_RunningAnimations::size, Core::GameSys::AnimationSys::_RunningAnimations::target, Core::GameSys::AnimationSys::_RunningAnimations::ticks, and timer.
Friends And Related Function Documentation
GameSys
friend class GameSys friend
Definition at line 82 of file animations.h.
Member Data Documentation
animation
struct Core::GameSys::AnimationSys::_AnimationList Core::GameSys::AnimationSys::animation[128] private
Referenced by calc(), drawWorld(), load(), startAnimation(), and ~AnimationSys().
audioSys
AudioSys* Core::GameSys::AnimationSys::audioSys private
Definition at line 33 of file animations.h.
Referenced by AnimationSys(), and drawWorld().
iLoaded
int Core::GameSys::AnimationSys::iLoaded private
Definition at line 32 of file animations.h.
Referenced by AnimationSys(), calc(), init(), load(), and ~AnimationSys().
running
struct Core::GameSys::AnimationSys::_RunningAnimations Core::GameSys::AnimationSys::running[32] private
Referenced by drawWorld(), isAnimating(), and startAnimation().
sDir
std::string Core::GameSys::AnimationSys::sDir private
Definition at line 36 of file animations.h.
Referenced by AnimationSys(), and load().
sFilename
std::string Core::GameSys::AnimationSys::sFilename private
Definition at line 36 of file animations.h.
Referenced by AnimationSys(), and load().
sTexDir
std::string Core::GameSys::AnimationSys::sTexDir private
Definition at line 36 of file animations.h.
Referenced by AnimationSys(), and load().
texture
Texture Core::GameSys::AnimationSys::texture private
Definition at line 31 of file animations.h.
timer
Timer Core::GameSys::AnimationSys::timer private
Definition at line 30 of file animations.h.
Referenced by drawWorld(), init(), and startAnimation().
uiNumTextures
uint Core::GameSys::AnimationSys::uiNumTextures private
Definition at line 34 of file animations.h.
Referenced by AnimationSys(), and init().
uiRecordSize
uint Core::GameSys::AnimationSys::uiRecordSize private
Definition at line 34 of file animations.h.
Referenced by AnimationSys(), and load().
world
struct Core::GameSys::AnimationSys::_RunningAnimations Core::GameSys::AnimationSys::world[128] private
The documentation for this class was generated from the following file:
src/headers/gamesys/animations.h