Project Parsec: src/Project_Parsec.cpp File Reference
Project_Parsec.cpp File Reference
#include "./headers/core.h"
#include "./game/runGame.h"
#include "./game/runAdmin.h"
Functions
int main (int argc, char *argv[])
Function Documentation
main()
int main (int argc, char * argv[])
Definition at line 58 of file Project_Parsec.cpp.
References MY_NAMESPACE::Cleanup(), Core::_Mouse::_Wheel::down, Core::framerate, Core::gameVars, Core::glinit, MY_NAMESPACE::glReport(), Core::_Mouse::_Wheel::left, _Game::load(), Core::mouse, Core::profiles, Core::GameVars::RunState::quit, Core::_Mouse::_Wheel::right, _Game::Run(), _Admin::run(), Core::GameVars::runState, Core::sdlEvent, MY_NAMESPACE::Setup(), Core::_FrameRate::start(), Core::Timer::start(), Core::_Profile::startProfile(), Core::_Profile::stopProfile(), Core::timeSys, Core::_Mouse::_Wheel::up, Core::_FrameRate::update(), Core::_TimeSys::Update(), and Core::_Mouse::wheel.