Project Parsec: Core::GUI::Object::CheckBox Class Reference
Core::GUI::Object::CheckBox Class Reference
#include <GUI_CheckBox.h>
Public Member Functions
CheckBox ()
CheckBox (std::string n, bool b, Props_CheckBox c)
CheckBox (Props &p, std::string n, bool b, Props_CheckBox c)
CheckBox (std::string n, bool b, Props_CheckBox *c)
CheckBox (Props &p, std::string n, bool b, Props_CheckBox *c)
CheckBox (std::string n, bool *b, Props_CheckBox c)
CheckBox (Props &p, std::string n, bool *b, Props_CheckBox c)
CheckBox (std::string n, bool *b, Props_CheckBox *c)
CheckBox (Props &p, std::string n, bool *b, Props_CheckBox *c)
virtual ~CheckBox ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
void updateNoFocus ()
Public Member Functions inherited from Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >
Interactive ()
Interactive & operator= (const Interactive &src)
bool getPtrValue ()
void setPointer (bool *ptr)
bool * getPointer ()
void init (Props_Addon_ReturnState *ptr)
int getState (int n=0)
bool valueChanged ()
void updateValuePtr ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_CheckBox >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Member Functions inherited from Core::GUI::Object::Base::Interactive_Base
Interactive_Base ()
~Interactive_Base ()
Public Member Functions inherited from Core::GUI::Object::Base::AudioFeedback
void initSound (int iChannel, int iSampleOn, int iSampleOff, int iLoopOn, int iLoopOff, bool bOverlapOn, bool bOverlapOff)
void Sound_PlayOn ()
void Sound_AbortState ()
void Sound_PlayOff ()
void Sound_PlayAuto (iState eState, bool bRepeat=false)
AudioFeedback ()
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_CheckBox >
int border
Props_CheckBox * con
Props * parent
Public Attributes inherited from Core::GUI::Object::Base::AudioFeedback
bool bRising
bool bOneShotOn
bool bOneShotOff
int iSampleOn
int iSampleOff
int iLoopOn
int iLoopOff
bool bOverlapOn
bool bOverlapOff
int iChannel
Private Member Functions
void update ()
void updateObjectState (iState eExternState)
Private Attributes
Window box
Window check
Label * label
Additional Inherited Members
Static Public Attributes inherited from Core::GUI::Object::Base::Interactive_Base
static bool bFocusPresent = false
static std::string sActiveObject = ""
static std::string sGroupObject [32] = { "" }
Protected Attributes inherited from Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >
bool * valuePtr
bool bLocalValue
bool bReturnInit
bool bValueChanged
Timer debounceTimer
Props_Addon_ReturnState * returnState
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_CheckBox >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 25 of file GUI_CheckBox.h.
Constructor & Destructor Documentation
CheckBox() [1/9]
Core::GUI::Object::CheckBox::CheckBox ()
Definition at line 53 of file GUI_CheckBox.h.
CheckBox() [2/9]
Core::GUI::Object::CheckBox::CheckBox (std::string n, bool b, Props_CheckBox c)
Definition at line 57 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
CheckBox() [3/9]
Core::GUI::Object::CheckBox::CheckBox (Props & p, std::string n, bool b, Props_CheckBox c)
Definition at line 75 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, p, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
CheckBox() [4/9]
Core::GUI::Object::CheckBox::CheckBox (std::string n, bool b, Props_CheckBox * c)
Definition at line 93 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
CheckBox() [5/9]
Core::GUI::Object::CheckBox::CheckBox (Props & p, std::string n, bool b, Props_CheckBox * c)
Definition at line 110 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, p, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
CheckBox() [6/9]
Core::GUI::Object::CheckBox::CheckBox (std::string n, bool * b, Props_CheckBox c)
Definition at line 127 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
CheckBox() [7/9]
Core::GUI::Object::CheckBox::CheckBox (Props & p, std::string n, bool * b, Props_CheckBox c)
Definition at line 145 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, p, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
CheckBox() [8/9]
Core::GUI::Object::CheckBox::CheckBox (std::string n, bool * b, Props_CheckBox * c)
Definition at line 163 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
CheckBox() [9/9]
Core::GUI::Object::CheckBox::CheckBox (Props & p, std::string n, bool * b, Props_CheckBox * c)
Definition at line 180 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, p, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
~CheckBox()
Core::GUI::Object::CheckBox::~CheckBox () virtual
Definition at line 197 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, label, and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr.
Member Function Documentation
exec()
void Core::GUI::Object::CheckBox::exec (iState eExternState = STATE_NONE)
Definition at line 301 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bInit, Core::GUI::Props::ToolTip::bShow, Core::GUI::Props_Addon_Label::bShowLabel, check, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, Core::GUI::Object::Window::exec(), Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, toolTip, Core::GUI::Props::toolTip, update(), Core::GUI::Object::ToolTip::updateObjectState(), updateObjectState(), Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr, and Core::GUI::Props::visibility.
execToolTip()
void Core::GUI::Object::CheckBox::execToolTip ()
Definition at line 322 of file GUI_CheckBox.h.
References Core::GUI::Object::ToolTip::exec(), and toolTip.
init()
void Core::GUI::Object::CheckBox::init ()
Definition at line 203 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_CheckBox >::bInit, check, Core::GUI::Props_CheckBox::check, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, Core::GUI::CONSTRAIN_CENTER, Core::GUI::Props::disablePadding(), Core::GUI::Props::exec(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::Window::init(), Core::GUI::Object::Base::AudioFeedback::initSound(), Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::Label, Core::GUI::Props_Addon_Label::label, Core::GUI::Object::Base::Generic< Props_CheckBox >::parent, Core::GUI::Props::setAnchor(), Core::GUI::Props_Window::setBorder(), Core::GUI::Props::setHeight(), Core::GUI::Props::setOrigin(), Core::GUI::Props::setWidth(), Core::GUI::SIZE_CONSTRAINT_RELATIVE, toolTip, and update().
update()
void Core::GUI::Object::CheckBox::update () private
Update constraints
Definition at line 236 of file GUI_CheckBox.h.
References Core::GUI::Props_CheckBox::check, Core::GUI::Object::Base::Generic< Props_CheckBox >::con, Core::GUI::Props_Window::radius, Core::GUI::Props_Window::setRadius(), Core::GUI::Props::size, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec(), and init().
updateNoFocus()
void Core::GUI::Object::CheckBox::updateNoFocus ()
Definition at line 330 of file GUI_CheckBox.h.
References Core::GUI::STATE_UPDATE, updateObjectState(), and Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::updateValuePtr().
updateObjectState()
void Core::GUI::Object::CheckBox::updateObjectState (iState eExternState) private
Definition at line 244 of file GUI_CheckBox.h.
References Core::GUI::Object::Base::Generic< Props_CheckBox >::bIsGrouped, Core::GUI::Props_Addon_Toggle::bToggle, Core::_Mouse::checkInput(), Core::GUI::Object::Base::Generic< Props_CheckBox >::con, Core::GUI::Object::Base::Generic< Props_CheckBox >::enabled(), Core::gameVars, Core::GameVars::Screen::half, Core::GUI::Props_Addon_Group::iGroup, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_LEFT, Core::_Mouse::MOUSE_NONE, Core::GUI::Object::Base::Generic< Props_CheckBox >::mState, Core::GUI::Object::Base::Generic< Props_CheckBox >::name, Core::GUI::Props::pos, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::returnState, Core::GameVars::screen, Core::GUI::Object::Base::Interactive_Base::sGroupObject, Core::GUI::Props::size, Core::GUI::Object::Base::AudioFeedback::Sound_AbortState(), Core::GUI::Object::Base::AudioFeedback::Sound_PlayOff(), Core::GUI::Object::Base::AudioFeedback::Sound_PlayOn(), Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::GUI::Object::Base::Interactive< Props_CheckBox, bool >::valuePtr, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec(), and updateNoFocus().
Member Data Documentation
box
Window Core::GUI::Object::CheckBox::box private
Definition at line 46 of file GUI_CheckBox.h.
check
Window Core::GUI::Object::CheckBox::check private
Definition at line 47 of file GUI_CheckBox.h.
Referenced by exec(), and init().
label
Label* Core::GUI::Object::CheckBox::label private
Definition at line 48 of file GUI_CheckBox.h.
Referenced by ~CheckBox().
toolTip
ToolTip Core::GUI::Object::CheckBox::toolTip
Definition at line 39 of file GUI_CheckBox.h.
Referenced by exec(), execToolTip(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_CheckBox.h