Project Parsec: O3D_Dungeon Class Reference
O3D_Dungeon Class Reference
#include <O3DD.h>
Public Member Functions
O3D_Dungeon ()
bool init ()
bool load ()
bool calc ()
void draw (Atmosphere &a, bool bShadow)
Public Attributes
O3dData o3dData [9]
Detailed Description
Definition at line 11 of file O3DD.h.
Constructor & Destructor Documentation
O3D_Dungeon()
O3D_Dungeon::O3D_Dungeon ()
Definition at line 25 of file O3DD.h.
Member Function Documentation
calc()
bool O3D_Dungeon::calc ()
Definition at line 159 of file O3DD.h.
References cout, Core::GameVars::debug, Core::gameVars, GL_TRIANGLES, Core::GLA_INDEX, Core::GLA_NORMAL, Core::GLA_TEXTURE, Core::GLA_VERTEX, and o3dData.
Referenced by RunDungeon::load().
draw()
void O3D_Dungeon::draw (Atmosphere & a, bool bShadow = false)
Definition at line 194 of file O3DD.h.
References Core::gameVars, GL_CULL_FACE, Core::GLM_DRAW_ELEMENTS, and o3dData.
Referenced by RunDungeon::update().
init()
bool O3D_Dungeon::init ()
Definition at line 28 of file O3DD.h.
load()
bool O3D_Dungeon::load ()
Definition at line 32 of file O3DD.h.
References cout, Core::GameVars::debug, Core::gameVars, o3dData, and Core::readFile().
Referenced by RunDungeon::load().
Member Data Documentation
o3dData
O3dData O3D_Dungeon::o3dData[9]
Definition at line 18 of file O3DD.h.
Referenced by calc(), draw(), and load().
The documentation for this class was generated from the following file:
src/headers/gamesys/ref/O3DD.h