Project Parsec: Core::GUI::GUI::CheckBoxInterface Class Reference
Core::GUI::GUI::CheckBoxInterface Class Reference
#include <GUI.h>
Public Member Functions
void add (std::string guiName, std::string checkBoxName, Constraints_CheckBox c)
void add (std::string guiName, std::string windowName, std::string checkBoxName, Constraints_CheckBox c)
void add (std::string guiName, std::string checkBoxName, Constraints_CheckBox *c)
void add (std::string guiName, std::string windowName, std::string checkBoxName, Constraints_CheckBox *c)
Constraints_CheckBox * get (std::string guiName, std::string checkBoxName)
CheckBoxInterface (GUI *parent)
Public Attributes
GUI * gui
Detailed Description
Definition at line 210 of file GUI.h.
Constructor & Destructor Documentation
CheckBoxInterface()
Core::GUI::GUI::CheckBoxInterface::CheckBoxInterface (GUI * parent) inline
Definition at line 218 of file GUI.h.
References gui.
Member Function Documentation
add() [1/4]
void Core::GUI::GUI::CheckBoxInterface::add (std::string guiName, std::string checkBoxName, Constraints_CheckBox * c)
Definition at line 886 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::CheckBox::init().
add() [2/4]
void Core::GUI::GUI::CheckBoxInterface::add (std::string guiName, std::string checkBoxName, Constraints_CheckBox c)
Definition at line 867 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::CheckBox::init().
add() [3/4]
void Core::GUI::GUI::CheckBoxInterface::add (std::string guiName, std::string windowName, std::string checkBoxName, Constraints_CheckBox * c)
Definition at line 895 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::CheckBox::init().
add() [4/4]
void Core::GUI::GUI::CheckBoxInterface::add (std::string guiName, std::string windowName, std::string checkBoxName, Constraints_CheckBox c)
Definition at line 876 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::CheckBox::init().
get()
Constraints_CheckBox * Core::GUI::GUI::CheckBoxInterface::get (std::string guiName, std::string checkBoxName)
Definition at line 905 of file GUI.h.
References MY_NAMESPACE::gui.
Member Data Documentation
gui
GUI* Core::GUI::GUI::CheckBoxInterface::gui
Definition at line 217 of file GUI.h.
Referenced by CheckBoxInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI.h