Project Parsec: Core::VAO Class Reference
Core::VAO Class Reference
#include <vao.h>
Public Member Functions
VAO ()
~VAO ()
void Begin (GLenum primitive, long uiNum, long uiDraw, GLuint nTextureUnits=1, GLuint uiInstances=1)
void Reset ()
void CopyData (GLenum eAttrib, Core::Data3f *vVerts)
void ReplaceData (GLenum eAttrib, Core::Data3f *vVerts)
void ReplaceData (GLenum eAttrib, Core::Data4f *vVerts)
void ReplaceData (GLenum eAttrib, Core::Data2f *vData, GLuint uiLayer)
void ReplaceData (GLenum eAttrib, GLushort *uiIndex, long lNumIndex=0)
void CopyData (GLenum eAttrib, Core::Data4f *vVerts)
void CopyData (GLenum eAttrib, Core::Data2f *vData, GLuint uiLayer)
void CopyData (GLenum eAttrib, GLuint *uiIndex, long lNumIndex=0)
bool AddData (GLenum eAttrib, Core::Data3f *vData)
void AddData (GLenum eAttrib, Core::Data2f *vData, GLuint uiLayer)
void Clean ()
void End ()
void Draw (GLenum eMode=Core::GLM_DRAW_ARRAYS, GLint iStart=0, GLint iEnd=0)
Public Attributes
GLenum primitiveType
GLuint uiVertexArray
GLuint uiNormalArray
GLuint uiColorArray
GLuint uiIndexArray
GLuint * uiTextureArray
GLuint uiPositionArray
GLuint uiExtraArray
bool bStarted
Protected Attributes
GLuint uiVertexSize
GLuint uiNormalSize
GLuint uiExtraSize
GLuint uiPositionSize
GLuint uiVertexOffset
GLuint uiNormalOffset
GLuint uiColorOffset
GLuint uiIndexOffset
GLuint uiTextureOffset
GLuint uiPositionOffset
GLuint uiExtraOffset
GLuint uiMaxInstances
GLuint uiVertexLength
GLuint uiNormalLength
GLuint uiColorLength
GLuint uiIndexLength
GLuint uiPositionLength
GLuint uiExtraLength
GLuint uiTextureLength
long uiNumDrawVerts
long uiNumVerts
GLuint uiTextureUnits
GLuint vaoPrime [2]
bool bPrime
bool bFinished
Detailed Description
Definition at line 13 of file vao.h.
Constructor & Destructor Documentation
VAO()
Core::VAO::VAO ()
Definition at line 11 of file vao.cpp.
References vaoPrime.
~VAO()
Core::VAO::~VAO ()
Definition at line 49 of file vao.cpp.
References uiColorArray, uiIndexArray, uiNormalArray, uiTextureArray, uiTextureUnits, uiVertexArray, and vaoPrime.
Member Function Documentation
AddData() [1/2]
void Core::VAO::AddData (GLenum eAttrib, Core::Data2f * vData, GLuint uiLayer)
Definition at line 517 of file vao.cpp.
References bFinished, CopyData(), GL_ARRAY_BUFFER, Core::GLA_TEXTURE, uiNumVerts, uiTextureArray, and uiTextureOffset.
AddData() [2/2]
bool Core::VAO::AddData (GLenum eAttrib, Core::Data3f * vData)
Definition at line 474 of file vao.cpp.
References CopyData(), GL_ARRAY_BUFFER, Core::GLA_NORMAL, Core::GLA_POSITION, Core::GLA_VERTEX, uiMaxInstances, uiNormalArray, uiNormalOffset, uiNumVerts, uiPositionArray, uiPositionOffset, uiVertexArray, and uiVertexOffset.
Begin()
void Core::VAO::Begin (GLenum primitive, long uiNum, long uiDraw, GLuint nTextureUnits = 1, GLuint uiInstances = 1)
Definition at line 87 of file vao.cpp.
References bFinished, bPrime, bStarted, primitiveType, uiMaxInstances, uiNumDrawVerts, uiNumVerts, uiTextureArray, uiTextureUnits, and vaoPrime.
Referenced by Core::_IconSys::calc(), Core::_SpriteSys::calc(), Core::GameSys::_WinSys::calc(), Core::GameSys::AnimationSys::calc(), Core::GameSys::MapSys::calc(), Core::_Helper::init(), Core::PostProcess::init(), Core::GUI::Object::Window::init(), Core::_TextSys::init(), Core::GameSys::Atmosphere::load(), Core::_Helper::SetLine(), and Core::GameSys::MapSys::update().
Clean()
void Core::VAO::Clean ()
CopyData() [1/4]
void Core::VAO::CopyData (GLenum eAttrib, Core::Data2f * vData, GLuint uiLayer)
Definition at line 248 of file vao.cpp.
References bFinished, GL_ARRAY_BUFFER, GL_DYNAMIC_DRAW, Core::GLA_TEXTURE, uiNumVerts, uiTextureArray, and uiTextureLength.
CopyData() [2/4]
void Core::VAO::CopyData (GLenum eAttrib, Core::Data3f * vVerts)
Definition at line 129 of file vao.cpp.
References bFinished, cout, GL_ARRAY_BUFFER, GL_DYNAMIC_DRAW, Core::GLA_EXTRA, Core::GLA_NORMAL, Core::GLA_POSITION, Core::GLA_VERTEX, uiExtraArray, uiExtraLength, uiExtraOffset, uiExtraSize, uiMaxInstances, uiNormalArray, uiNormalLength, uiNormalSize, uiNumVerts, uiPositionArray, uiPositionLength, uiPositionOffset, uiPositionSize, uiVertexArray, uiVertexLength, and uiVertexSize.
Referenced by AddData(), Core::_IconSys::calc(), Core::_SpriteSys::calc(), Core::GameSys::_WinSys::calc(), Core::GameSys::AnimationSys::calc(), Core::GameSys::MapSys::calc(), Core::_Helper::init(), Core::PostProcess::init(), Core::GUI::Object::Window::init(), Core::_TextSys::init(), Core::GameSys::Atmosphere::load(), Core::_Helper::SetLine(), and Core::GameSys::MapSys::update().
CopyData() [3/4]
void Core::VAO::CopyData (GLenum eAttrib, Core::Data4f * vVerts)
Definition at line 267 of file vao.cpp.
References bFinished, cout, GL_ARRAY_BUFFER, GL_DYNAMIC_DRAW, Core::GLA_COLOR, Core::GLA_EXTRA, Core::GLA_NORMAL, Core::GLA_POSITION, Core::GLA_VERTEX, uiColorArray, uiColorLength, uiExtraArray, uiExtraLength, uiExtraOffset, uiExtraSize, uiMaxInstances, uiNormalArray, uiNormalLength, uiNormalSize, uiNumVerts, uiPositionArray, uiPositionLength, uiPositionOffset, uiPositionSize, uiVertexArray, uiVertexLength, and uiVertexSize.
CopyData() [4/4]
void Core::VAO::CopyData (GLenum eAttrib, GLuint * uiIndex, long lNumIndex = 0)
Definition at line 226 of file vao.cpp.
References bFinished, GL_DYNAMIC_DRAW, GL_ELEMENT_ARRAY_BUFFER, Core::GLA_INDEX, uiIndexArray, uiIndexLength, and uiNumDrawVerts.
Draw()
void Core::VAO::Draw (GLenum eMode = Core::GLM_DRAW_ARRAYS, GLint iStart = 0, GLint iEnd = 0)
Definition at line 536 of file vao.cpp.
References bFinished, bPrime, BUFFER_OFFSET, GL_ARRAY_BUFFER, GL_ELEMENT_ARRAY_BUFFER, GL_FALSE, GL_FLOAT, GL_UNSIGNED_INT, Core::GLA_COLOR, Core::GLA_EXTRA, Core::GLA_INDEX, Core::GLA_NORMAL, Core::GLA_POSITION, Core::GLA_TEXTURE0, Core::GLA_VERTEX, Core::GLM_DRAW_ARRAYS, Core::GLM_DRAW_ARRAYS_INSTANCED, Core::GLM_DRAW_ELEMENTS, Core::GLM_DRAW_RANGE, Core::GLM_DRAW_RANGE_ELEMENTS, primitiveType, uiColorArray, uiExtraArray, uiExtraSize, uiIndexArray, uiNormalArray, uiNormalSize, uiNumDrawVerts, uiPositionArray, uiPositionSize, uiTextureArray, uiTextureUnits, uiVertexArray, uiVertexSize, and vaoPrime.
Referenced by Core::_SpriteSys::draw(), Core::_IconSys::draw(), Core::GameSys::Atmosphere::draw(), Core::GameSys::MapSys::draw(), Core::_ParticleEmitter::draw(), Core::GameSys::_WinSys::drawB(), Core::_Helper::drawBox(), Core::_Helper::drawCylinder(), Core::GameSys::_WinSys::drawHDiv(), Core::GameSys::_WinSys::drawHLine(), Core::GameSys::_WinSys::drawHSpace(), Core::GameSys::_WinSys::drawiBorder(), Core::GameSys::_WinSys::drawL(), Core::GameSys::_WinSys::drawLBorder(), Core::_Helper::drawLine(), Core::_Helper::drawPoint(), Core::_Helper::drawPointSprite(), Core::_Helper::drawPosition(), Core::GameSys::_WinSys::drawR(), Core::GameSys::_WinSys::drawRBorder(), Core::GameSys::_WinSys::drawSingle(), Core::_Helper::drawSphere(), Core::GameSys::_WinSys::drawT(), Core::GameSys::_WinSys::drawTBorder(), Core::_TextSys::drawText(), Core::GameSys::_WinSys::drawVDiv(), Core::GameSys::_WinSys::drawVLine(), Core::GameSys::_WinSys::drawVSpace(), Core::GameSys::AnimationSys::drawWorld(), Core::GUI::Object::Window::exec(), Core::PostProcess::Render(), Core::PostProcess::Render2(), and Core::PostProcess::RenderQuad().
End()
void Core::VAO::End ()
Definition at line 532 of file vao.cpp.
References bFinished.
Referenced by Core::_IconSys::calc(), Core::_SpriteSys::calc(), Core::GameSys::_WinSys::calc(), Core::GameSys::AnimationSys::calc(), Core::GameSys::MapSys::calc(), Core::_Helper::init(), Core::PostProcess::init(), Core::GUI::Object::Window::init(), Core::_TextSys::init(), Core::GameSys::Atmosphere::load(), Core::_Helper::SetLine(), and Core::GameSys::MapSys::update().
ReplaceData() [1/4]
void Core::VAO::ReplaceData (GLenum eAttrib, Core::Data2f * vData, GLuint uiLayer)
Definition at line 397 of file vao.cpp.
References bFinished, GL_ARRAY_BUFFER, GL_DYNAMIC_DRAW, Core::GLA_TEXTURE, uiNumVerts, and uiTextureArray.
ReplaceData() [2/4]
void Core::VAO::ReplaceData (GLenum eAttrib, Core::Data3f * vVerts)
Definition at line 363 of file vao.cpp.
References bFinished, GL_ARRAY_BUFFER, GL_DYNAMIC_DRAW, Core::GLA_NORMAL, Core::GLA_POSITION, Core::GLA_VERTEX, uiMaxInstances, uiNormalArray, uiNumVerts, uiPositionArray, uiPositionSize, and uiVertexArray.
ReplaceData() [3/4]
void Core::VAO::ReplaceData (GLenum eAttrib, Core::Data4f * vVerts)
Definition at line 382 of file vao.cpp.
References bFinished, GL_ARRAY_BUFFER, GL_DYNAMIC_DRAW, Core::GLA_COLOR, Core::GLA_VERTEX, uiColorArray, uiNumVerts, and uiVertexArray.
ReplaceData() [4/4]
void Core::VAO::ReplaceData (GLenum eAttrib, GLushort * uiIndex, long lNumIndex = 0)
Definition at line 407 of file vao.cpp.
References bFinished, GL_DYNAMIC_DRAW, GL_ELEMENT_ARRAY_BUFFER, Core::GLA_INDEX, uiIndexArray, and uiNumDrawVerts.
Reset()
void Core::VAO::Reset ()
Definition at line 418 of file vao.cpp.
References bFinished, bPrime, cout, GL_ARRAY_BUFFER, GL_DYNAMIC_DRAW, GL_ELEMENT_ARRAY_BUFFER, uiColorArray, uiColorLength, uiIndexArray, uiIndexLength, uiNormalArray, uiNormalLength, uiTextureUnits, uiVertexArray, uiVertexLength, and vaoPrime.
Member Data Documentation
bFinished
bool Core::VAO::bFinished protected
Definition at line 45 of file vao.h.
Referenced by AddData(), Begin(), CopyData(), Draw(), End(), ReplaceData(), and Reset().
bPrime
bool Core::VAO::bPrime protected
Definition at line 44 of file vao.h.
Referenced by Begin(), Draw(), and Reset().
bStarted
bool Core::VAO::bStarted
Definition at line 59 of file vao.h.
Referenced by Begin().
primitiveType
GLenum Core::VAO::primitiveType
Definition at line 48 of file vao.h.
Referenced by Begin(), and Draw().
uiColorArray
GLuint Core::VAO::uiColorArray
Definition at line 51 of file vao.h.
Referenced by CopyData(), Draw(), ReplaceData(), Reset(), and ~VAO().
uiColorLength
GLuint Core::VAO::uiColorLength protected
Definition at line 31 of file vao.h.
Referenced by CopyData(), and Reset().
uiColorOffset
GLuint Core::VAO::uiColorOffset protected
Definition at line 23 of file vao.h.
uiExtraArray
GLuint Core::VAO::uiExtraArray
Definition at line 55 of file vao.h.
Referenced by CopyData(), and Draw().
uiExtraLength
GLuint Core::VAO::uiExtraLength protected
Definition at line 31 of file vao.h.
Referenced by CopyData().
uiExtraOffset
GLuint Core::VAO::uiExtraOffset protected
Definition at line 27 of file vao.h.
Referenced by CopyData().
uiExtraSize
GLuint Core::VAO::uiExtraSize protected
Definition at line 18 of file vao.h.
Referenced by CopyData(), and Draw().
uiIndexArray
GLuint Core::VAO::uiIndexArray
Definition at line 52 of file vao.h.
Referenced by CopyData(), Draw(), ReplaceData(), Reset(), and ~VAO().
uiIndexLength
GLuint Core::VAO::uiIndexLength protected
Definition at line 31 of file vao.h.
Referenced by CopyData(), and Reset().
uiIndexOffset
GLuint Core::VAO::uiIndexOffset protected
Definition at line 24 of file vao.h.
uiMaxInstances
GLuint Core::VAO::uiMaxInstances protected
Definition at line 29 of file vao.h.
Referenced by AddData(), Begin(), CopyData(), and ReplaceData().
uiNormalArray
GLuint Core::VAO::uiNormalArray
Definition at line 50 of file vao.h.
Referenced by AddData(), CopyData(), Draw(), ReplaceData(), Reset(), and ~VAO().
uiNormalLength
GLuint Core::VAO::uiNormalLength protected
Definition at line 31 of file vao.h.
Referenced by CopyData(), and Reset().
uiNormalOffset
GLuint Core::VAO::uiNormalOffset protected
Definition at line 22 of file vao.h.
Referenced by AddData().
uiNormalSize
GLuint Core::VAO::uiNormalSize protected
Definition at line 17 of file vao.h.
Referenced by CopyData(), and Draw().
uiNumDrawVerts
long Core::VAO::uiNumDrawVerts protected
Definition at line 39 of file vao.h.
Referenced by Begin(), CopyData(), Draw(), and ReplaceData().
uiNumVerts
long Core::VAO::uiNumVerts protected
Definition at line 40 of file vao.h.
Referenced by AddData(), Begin(), CopyData(), and ReplaceData().
uiPositionArray
GLuint Core::VAO::uiPositionArray
Definition at line 54 of file vao.h.
Referenced by AddData(), CopyData(), Draw(), and ReplaceData().
uiPositionLength
GLuint Core::VAO::uiPositionLength protected
Definition at line 31 of file vao.h.
Referenced by CopyData().
uiPositionOffset
GLuint Core::VAO::uiPositionOffset protected
Definition at line 26 of file vao.h.
Referenced by AddData(), and CopyData().
uiPositionSize
GLuint Core::VAO::uiPositionSize protected
Definition at line 19 of file vao.h.
Referenced by CopyData(), Draw(), and ReplaceData().
uiTextureArray
GLuint* Core::VAO::uiTextureArray
Definition at line 53 of file vao.h.
Referenced by AddData(), Begin(), CopyData(), Draw(), ReplaceData(), and ~VAO().
uiTextureLength
GLuint Core::VAO::uiTextureLength protected
Definition at line 31 of file vao.h.
Referenced by CopyData().
uiTextureOffset
GLuint Core::VAO::uiTextureOffset protected
Definition at line 25 of file vao.h.
Referenced by AddData().
uiTextureUnits
GLuint Core::VAO::uiTextureUnits protected
Definition at line 41 of file vao.h.
Referenced by Begin(), Draw(), Reset(), and ~VAO().
uiVertexArray
GLuint Core::VAO::uiVertexArray
Definition at line 49 of file vao.h.
Referenced by AddData(), CopyData(), Draw(), ReplaceData(), Reset(), and ~VAO().
uiVertexLength
GLuint Core::VAO::uiVertexLength protected
Definition at line 31 of file vao.h.
Referenced by CopyData(), and Reset().
uiVertexOffset
GLuint Core::VAO::uiVertexOffset protected
Definition at line 21 of file vao.h.
Referenced by AddData().
uiVertexSize
GLuint Core::VAO::uiVertexSize protected
Definition at line 16 of file vao.h.
Referenced by CopyData(), and Draw().
vaoPrime
GLuint Core::VAO::vaoPrime[2] protected
Definition at line 43 of file vao.h.
Referenced by Begin(), Draw(), Reset(), VAO(), and ~VAO().
The documentation for this class was generated from the following files:
src/headers/core/vao.h
src/headers/core/vao.cpp