Project Parsec: Core::GUI::Object::Slider< T > Class Template Reference
Core::GUI::Object::Slider< T > Class Template Reference
#include <GUI_Constraint.h>
Public Member Functions
Slider ()
Slider (std::string n, T *ptr, Props_Slider c)
Slider (std::string n, T *ptr, Props_Slider *c)
Slider (Props &p, std::string n, T *ptr, Props_Slider c)
Slider (Props &p, std::string n, T *ptr, Props_Slider *c)
Slider (std::string n, T t, Props_Slider c)
Slider (std::string n, T t, Props_Slider *c)
Slider (Props &p, std::string n, T t, Props_Slider c)
Slider (Props &p, std::string n, T t, Props_Slider *c)
virtual ~Slider ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
void updateNoFocus ()
Public Member Functions inherited from Core::GUI::Object::Base::Interactive< Props_Slider, T >
Interactive ()
Interactive & operator= (const Interactive &src)
T getPtrValue ()
void setPointer (T *ptr)
T * getPointer ()
void init (Props_Addon_ReturnState *ptr)
int getState (int n=0)
bool valueChanged ()
void updateValuePtr ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Slider >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Member Functions inherited from Core::GUI::Object::Base::Interactive_Base
Interactive_Base ()
~Interactive_Base ()
Public Member Functions inherited from Core::GUI::Object::Base::AudioFeedback
void initSound (int iChannel, int iSampleOn, int iSampleOff, int iLoopOn, int iLoopOff, bool bOverlapOn, bool bOverlapOff)
void Sound_PlayOn ()
void Sound_AbortState ()
void Sound_PlayOff ()
void Sound_PlayAuto (iState eState, bool bRepeat=false)
AudioFeedback ()
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Slider >
int border
Props_Slider * con
Props * parent
Public Attributes inherited from Core::GUI::Object::Base::AudioFeedback
bool bRising
bool bOneShotOn
bool bOneShotOff
int iSampleOn
int iSampleOff
int iLoopOn
int iLoopOff
bool bOverlapOn
bool bOverlapOff
int iChannel
Protected Member Functions
void update ()
void setValue ()
void setValue (T f)
void updateScrollMouse ()
void updateObjectState (iState eExternState)
float getNormalized (T fCurrent, float fMin, float fMax)
float getValueFromPos (float f)
float getPosFromValue (T f)
void updateControlPos ()
Protected Attributes
Window slider
Window control
Object::Field< T > * field
Show field value and allow editing if enabled.
Object::Label * label
Show slider name if enabled.
float minPos
Exact screen coordinate for minimum position.
float maxPos
Exact screen coordinate for maximum position.
float spanPos
Difference of min and max positions.
float spanValue
Difference ofmin and max values (from constraints)
T lastValue
Value at the last cycle, used to determine bValueChanged.
Vector2f currentPos
Current slider position based on currentValue.
bool bHasFocus
Protected Attributes inherited from Core::GUI::Object::Base::Interactive< Props_Slider, T >
T * valuePtr
bool bLocalValue
bool bReturnInit
bool bValueChanged
Timer debounceTimer
Props_Addon_ReturnState * returnState
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Slider >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Friends
class AnySlider
Additional Inherited Members
Static Public Attributes inherited from Core::GUI::Object::Base::Interactive_Base
static bool bFocusPresent = false
static std::string sActiveObject = ""
static std::string sGroupObject [32] = { "" }
Detailed Description
template<typename T>
class Core::GUI::Object::Slider< T >
Definition at line 47 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Slider() [1/9]
template<class T > Slider::Slider ()
Definition at line 76 of file GUI_Slider.h.
Slider() [2/9]
template<class T> Slider::Slider (std::string n, T * ptr, Props_Slider< T > c)
Definition at line 87 of file GUI_Slider.h.
Slider() [3/9]
template<class T> Slider::Slider (std::string n, T * ptr, Props_Slider< T > * c)
Definition at line 109 of file GUI_Slider.h.
Slider() [4/9]
template<class T> Slider::Slider (Props & p, std::string n, T * ptr, Props_Slider< T > c)
Definition at line 130 of file GUI_Slider.h.
Slider() [5/9]
template<class T> Slider::Slider (Props & p, std::string n, T * ptr, Props_Slider< T > * c)
Definition at line 152 of file GUI_Slider.h.
Slider() [6/9]
template<class T> Slider::Slider (std::string n, T t, Props_Slider< T > c)
Definition at line 173 of file GUI_Slider.h.
Slider() [7/9]
template<class T> Slider::Slider (std::string n, T t, Props_Slider< T > * c)
Definition at line 195 of file GUI_Slider.h.
Slider() [8/9]
template<class T> Slider::Slider (Props & p, std::string n, T t, Props_Slider< T > c)
Definition at line 216 of file GUI_Slider.h.
Slider() [9/9]
template<class T> Slider::Slider (Props & p, std::string n, T t, Props_Slider< T > * c)
Definition at line 238 of file GUI_Slider.h.
~Slider()
template<class T > Slider::~Slider () virtual
Definition at line 259 of file GUI_Slider.h.
Member Function Documentation
exec()
template<class T > void Slider::exec (iState eExternState = STATE_NONE)
Definition at line 552 of file GUI_Slider.h.
Referenced by Core::GUI::Object::TextArea::exec(), Core::GUI::Object::ColorSwatch::exec(), Core::GUI::Object::TextEdit::exec(), and Core::GUI::Object::AnySlider::exec().
execToolTip()
template<class T > void Slider::execToolTip ()
Definition at line 605 of file GUI_Slider.h.
Referenced by Core::GUI::Object::ColorSwatch::execToolTip(), and Core::GUI::Object::AnySlider::execToolTip().
getNormalized()
template<class T> float Slider::getNormalized (T fCurrent, float fMin, float fMax) protected
Definition at line 353 of file GUI_Slider.h.
getPosFromValue()
template<class T> float Slider::getPosFromValue (T f) protected
Definition at line 391 of file GUI_Slider.h.
getValueFromPos()
template<class T > float Slider::getValueFromPos (float f) protected
Definition at line 358 of file GUI_Slider.h.
init()
template<class T > void Slider::init ()
Definition at line 266 of file GUI_Slider.h.
Referenced by Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::TextEdit::init(), and Core::GUI::Object::AnySlider::init().
setValue() [1/2]
template<class T > void Slider::setValue () protected
Definition at line 409 of file GUI_Slider.h.
setValue() [2/2]
template<class T> void Slider::setValue (T f) protected
Definition at line 413 of file GUI_Slider.h.
update()
template<class T > void Slider::update () protected
Definition at line 338 of file GUI_Slider.h.
updateControlPos()
template<class T > void Slider::updateControlPos () protected
Definition at line 427 of file GUI_Slider.h.
updateNoFocus()
template<class T > void Slider::updateNoFocus ()
Definition at line 614 of file GUI_Slider.h.
Referenced by Core::GUI::Object::AnySlider::updateNoFocus().
updateObjectState()
template<class T > void Slider::updateObjectState (iState eExternState) protected
Definition at line 503 of file GUI_Slider.h.
updateScrollMouse()
template<class T > void Slider::updateScrollMouse () protected
Definition at line 446 of file GUI_Slider.h.
Friends And Related Function Documentation
AnySlider
template<typename T> friend class AnySlider friend
Definition at line 34 of file GUI_Slider.h.
Member Data Documentation
bHasFocus
template<typename T> bool Core::GUI::Object::Slider< T >::bHasFocus protected
Definition at line 64 of file GUI_Slider.h.
control
template<typename T> Window Core::GUI::Object::Slider< T >::control protected
Definition at line 55 of file GUI_Slider.h.
currentPos
template<typename T> Vector2f Core::GUI::Object::Slider< T >::currentPos protected
Current slider position based on currentValue.
Definition at line 63 of file GUI_Slider.h.
field
template<typename T> Object::Field<T>* Core::GUI::Object::Slider< T >::field protected
Show field value and allow editing if enabled.
Definition at line 56 of file GUI_Slider.h.
Referenced by Core::GUI::Object::AnySlider::setPointer().
label
template<typename T> Object::Label* Core::GUI::Object::Slider< T >::label protected
Show slider name if enabled.
Definition at line 57 of file GUI_Slider.h.
lastValue
template<typename T> T Core::GUI::Object::Slider< T >::lastValue protected
Value at the last cycle, used to determine bValueChanged.
Definition at line 62 of file GUI_Slider.h.
maxPos
template<typename T> float Core::GUI::Object::Slider< T >::maxPos protected
Exact screen coordinate for maximum position.
Definition at line 58 of file GUI_Slider.h.
minPos
template<typename T> float Core::GUI::Object::Slider< T >::minPos protected
Exact screen coordinate for minimum position.
Definition at line 58 of file GUI_Slider.h.
slider
template<typename T> Window Core::GUI::Object::Slider< T >::slider protected
Definition at line 55 of file GUI_Slider.h.
spanPos
template<typename T> float Core::GUI::Object::Slider< T >::spanPos protected
Difference of min and max positions.
Definition at line 58 of file GUI_Slider.h.
spanValue
template<typename T> float Core::GUI::Object::Slider< T >::spanValue protected
Difference ofmin and max values (from constraints)
Definition at line 58 of file GUI_Slider.h.
toolTip
template<typename T> ToolTip Core::GUI::Object::Slider< T >::toolTip
Definition at line 48 of file GUI_Slider.h.
The documentation for this class was generated from the following files:
src/headers/gamesys/GUI/GUI_Constraint.h
src/headers/gamesys/GUI/GUI_Slider.h