Project Parsec: Core::_IconSys Class Reference
Core::_IconSys Class Reference
#include <IconSys.h>
Public Member Functions
_IconSys ()
bool load ()
bool calc ()
void draw (uint x, uint y, float w, float h, uint id, std::string sTex, bool textOffset)
void draw (uint x, uint y, float w, float h, uint id, std::string sTex, bool textOffset, Color fontColor)
void draw (Core::GUI::Props *con, std::string sTex, uint id, uint scale)
Private Member Functions
void start (int x, int y, float w, float h, std::string sTex, bool textOffset, Core::_Colors::_ACTIVE_COLOR eColor=Core::_Colors::COLOR_FRONT)
void update ()
void stop ()
Private Attributes
Texture texture
VAO vao [64]
Vector4f tempColor
Vector4f currentColor
Vector4f gridCoord [64]
uint uiNumTextures
uint uiRecordSize
std::string sFilename
std::string sDir
std::string sTexDir
float fMouseDelay
float fMouseDelayConst
Detailed Description
Definition at line 19 of file IconSys.h.
Constructor & Destructor Documentation
_IconSys()
Core::_IconSys::_IconSys ()
Definition at line 49 of file IconSys.h.
References fMouseDelay, fMouseDelayConst, sDir, sFilename, sTexDir, tempColor, uiNumTextures, and uiRecordSize.
Member Function Documentation
calc()
bool Core::_IconSys::calc ()
Definition at line 96 of file IconSys.h.
References Core::VAO::Begin(), Core::VAO::CopyData(), cout, Core::VAO::End(), GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, gridCoord, and vao.
draw() [1/3]
void Core::_IconSys::draw (Core::GUI::Props * con, std::string sTex, uint id, uint scale)
Parameters
con
sTex
id
scale
Definition at line 327 of file IconSys.h.
References Core::Vector4i::bottom, Core::colors, Core::VAO::Draw(), GL_DEPTH_TEST, GL_TRUE, Core::GLS_ICON, id, Core::Vector4i::left, Core::GUI::Props::pos, Core::Vector4i::right, Core::_Colors::SetActive(), Core::GUI::Props::size, Core::Vector4i::top, vao, Core::GUI::Props::vPadding, Core::Vector2f::x, and Core::Vector2f::y.
draw() [2/3]
void Core::_IconSys::draw (uint x, uint y, float w, float h, uint id, std::string sTex, bool textOffset)
Definition at line 312 of file IconSys.h.
References Core::VAO::Draw(), id, start(), stop(), update(), and vao.
Referenced by Core::GameSys::checkIcon(), draw(), Core::GameSys::drawIcon(), and Core::GUI::Object::Icon::exec().
draw() [3/3]
void Core::_IconSys::draw (uint x, uint y, float w, float h, uint id, std::string sTex, bool textOffset, Color fontColor)
Definition at line 306 of file IconSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
load()
bool Core::_IconSys::load ()
Definition at line 65 of file IconSys.h.
References Core::MemBlock::buffer, cout, GL_NEAREST, Core::readFile(), sDir, sFilename, Core::MemBlock::size, sTexDir, uiNumTextures, and uiRecordSize.
start()
void Core::_IconSys::start (int x, int y, float w, float h, std::string sTex, bool textOffset, Core::_Colors::_ACTIVE_COLOR eColor = Core::_Colors::COLOR_FRONT) private
Definition at line 226 of file IconSys.h.
References Core::colors, Core::GameVars::font, Core::gameVars, GL_DEPTH_TEST, GL_TRUE, Core::GLS_ICON, Core::GameVars::Screen::half, Core::GameVars::Screen::origin, Core::GameVars::screen, Core::_Colors::SetActive(), Core::GameVars::Font::vSize, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by draw().
stop()
void Core::_IconSys::stop () private
Definition at line 251 of file IconSys.h.
References GL_DEPTH_TEST.
Referenced by draw().
update()
void Core::_IconSys::update () private
Definition at line 246 of file IconSys.h.
References Core::GLS_ICON.
Referenced by draw().
Member Data Documentation
currentColor
Vector4f Core::_IconSys::currentColor private
Definition at line 23 of file IconSys.h.
fMouseDelay
float Core::_IconSys::fMouseDelay private
Definition at line 31 of file IconSys.h.
Referenced by _IconSys().
fMouseDelayConst
float Core::_IconSys::fMouseDelayConst private
Definition at line 31 of file IconSys.h.
Referenced by _IconSys().
gridCoord
Vector4f Core::_IconSys::gridCoord[64] private
Definition at line 23 of file IconSys.h.
Referenced by calc().
sDir
std::string Core::_IconSys::sDir private
Definition at line 28 of file IconSys.h.
Referenced by _IconSys(), and load().
sFilename
std::string Core::_IconSys::sFilename private
Definition at line 28 of file IconSys.h.
Referenced by _IconSys(), and load().
sTexDir
std::string Core::_IconSys::sTexDir private
Definition at line 28 of file IconSys.h.
Referenced by _IconSys(), and load().
tempColor
Vector4f Core::_IconSys::tempColor private
Definition at line 23 of file IconSys.h.
Referenced by _IconSys().
texture
Texture Core::_IconSys::texture private
Definition at line 21 of file IconSys.h.
uiNumTextures
uint Core::_IconSys::uiNumTextures private
Definition at line 26 of file IconSys.h.
Referenced by _IconSys(), and load().
uiRecordSize
uint Core::_IconSys::uiRecordSize private
Definition at line 26 of file IconSys.h.
Referenced by _IconSys(), and load().
vao
VAO Core::_IconSys::vao[64] private
Definition at line 22 of file IconSys.h.
Referenced by calc(), and draw().
The documentation for this class was generated from the following file:
src/headers/gamesys/IconSys.h