Project Parsec: Core::GUI::Object::TextArea Class Reference
Core::GUI::Object::TextArea Class Reference
#include <GUI_TextArea.h>
Public Member Functions
TextArea ()
TextArea (std::string n, Props_TextArea c)
TextArea (Props &p, std::string n, Props_TextArea c)
TextArea (std::string n, Props_TextArea *c)
TextArea (Props &p, std::string n, Props_TextArea *c)
virtual ~TextArea ()
void init ()
void exec (iState eExternState=STATE_NONE)
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_TextArea >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_TextArea >
int border
Props_TextArea * con
Props * parent
Protected Member Functions
void updateObjectState (iState eExternState)
Protected Attributes
Window win
Text text
Window * scrollBarContainer
Button * scrollUp
Button * scrollDown
Label * label
Slider< float > * scrollBar
bool bScrollOneShot
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_TextArea >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 25 of file GUI_TextArea.h.
Constructor & Destructor Documentation
TextArea() [1/5]
Core::GUI::Object::TextArea::TextArea ()
Definition at line 49 of file GUI_TextArea.h.
References bScrollOneShot, scrollBar, scrollBarContainer, scrollDown, and scrollUp.
TextArea() [2/5]
Core::GUI::Object::TextArea::TextArea (std::string n, Props_TextArea c)
Definition at line 58 of file GUI_TextArea.h.
References Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, bScrollOneShot, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, and scrollUp.
TextArea() [3/5]
Core::GUI::Object::TextArea::TextArea (Props & p, std::string n, Props_TextArea c)
Definition at line 76 of file GUI_TextArea.h.
References Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, bScrollOneShot, Core::GUI::Object::Base::Generic< Props_TextArea >::con, p, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, and scrollUp.
TextArea() [4/5]
Core::GUI::Object::TextArea::TextArea (std::string n, Props_TextArea * c)
Definition at line 94 of file GUI_TextArea.h.
References Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, bScrollOneShot, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, and scrollUp.
TextArea() [5/5]
Core::GUI::Object::TextArea::TextArea (Props & p, std::string n, Props_TextArea * c)
Definition at line 111 of file GUI_TextArea.h.
References Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, bScrollOneShot, Core::GUI::Object::Base::Generic< Props_TextArea >::con, p, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, and scrollUp.
~TextArea()
Core::GUI::Object::TextArea::~TextArea () virtual
Definition at line 128 of file GUI_TextArea.h.
References Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, Core::GUI::Object::Base::Generic< Props_TextArea >::con, label, scrollBar, scrollBarContainer, scrollDown, and scrollUp.
Member Function Documentation
exec()
void Core::GUI::Object::TextArea::exec (iState eExternState = STATE_NONE)
Definition at line 253 of file GUI_TextArea.h.
References Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bInit, bScrollOneShot, Core::GUI::Props::ToolTip::bShow, Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::Props::_Size::constraint, Core::GUI::Props_TextArea::enableScrolling, Core::GUI::Object::Text::exec(), Core::GUI::Object::Slider< T >::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Core::GUI::Object::Base::Interactive< C, T >::getState(), Core::GUI::Props_Text::iMaxLines, Core::GUI::Props::_Size::isAutoSet(), Core::GUI::Props_TextArea::iScrollSize, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, Core::GUI::Props_Text::scrollDown(), scrollUp, Core::GUI::Props_Text::scrollUp(), Core::GUI::Props::setHeight(), Core::GUI::Props_Slider::setMinMax(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_NONE, text, Core::GUI::Props_TextArea::text, toolTip, Core::GUI::Props::toolTip, Core::GUI::Object::ToolTip::updateObjectState(), updateObjectState(), Core::GUI::Props::visibility, win, Core::Vector2f::x, and Core::Vector2f::y.
init()
void Core::GUI::Object::TextArea::init ()
Definition at line 137 of file GUI_TextArea.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::Props_Window::Colors::back, Core::GUI::Props_Button::Colors::back(), Core::GUI::GUI_ColorB::base, Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bInit, Core::GUI::Props_Button::Colors::border(), Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Object::Base::Generic< Props_TextArea >::Button, Core::GUI::BUTTON_DEBOUNCE, Core::GUI::Props_Window::color, Core::GUI::Props_Button::color, Core::colors, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_CENTER, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, Core::GUI::CONSTRAIN_TOP, Core::GUI::Props::_Size::constraint, Core::GUI::Props_Slider::control, Core::GUI::Props::disablePadding(), Core::GUI::Props_TextArea::enableScrolling, Core::GUI::Props::exec(), Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::Props_Addon_Field::hideField(), Core::GUI::Props_Addon_Label::hideLabel(), Core::GUI::GUI_ColorH::highlight, Core::GUI::Props_Text::iMaxLines, Core::GUI::Object::ToolTip::init(), Core::GUI::Object::Text::init(), Core::GUI::Object::Slider< T >::init(), Core::GUI::Object::Button::init(), Core::GUI::Object::Window::init(), Core::GUI::Props_TextArea::iScrollSize, Core::GUI::Object::Base::Generic< Props_TextArea >::Label, Core::GUI::Props_Addon_Label::label, Core::GameVars::pallette, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, Core::GUI::Props_Text::scrollPosition, scrollUp, Core::GUI::Props::setAnchor(), Core::GUI::Props_Window::setBorder(), Core::GUI::Props_Button::setButtonType(), Core::GUI::Props::setHeight(), Core::GUI::Props_Slider::setMinMax(), Core::GUI::Props::setOrigin(), Core::GUI::Props::setPadding(), Core::GUI::Props::setPos(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props_Slider::setScrollSpeed(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::SIZE_CONSTRAINT_RELATIVE, Core::GUI::SLIDER_VERTICAL, text, Core::GUI::Object::Base::Generic< Props_TextArea >::Text, Core::GUI::Props_Button::Colors::text, Core::GUI::Props_TextArea::text, Core::GameVars::_Pallette::textArea, toolTip, Core::GUI::Props::vPadding, win, Core::GUI::Object::Base::Generic< Props_TextArea >::Window, Core::Vector2f::x, Core::GUI::Props::_Size::_SizeConstraint::xType, and Core::Vector2f::y.
updateObjectState()
void Core::GUI::Object::TextArea::updateObjectState (iState eExternState) protected
Definition at line 236 of file GUI_TextArea.h.
References Core::_Mouse::checkInput(), Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< Props_TextArea >::enabled(), Core::gameVars, Core::GameVars::Screen::half, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_NONE, Core::GUI::Object::Base::Generic< Props_TextArea >::mState, Core::GUI::Props::pos, Core::GameVars::screen, Core::GUI::Props::size, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
Member Data Documentation
bScrollOneShot
bool Core::GUI::Object::TextArea::bScrollOneShot protected
Definition at line 45 of file GUI_TextArea.h.
Referenced by exec(), and TextArea().
label
Label* Core::GUI::Object::TextArea::label protected
Definition at line 43 of file GUI_TextArea.h.
Referenced by ~TextArea().
scrollBar
Slider<float>* Core::GUI::Object::TextArea::scrollBar protected
Definition at line 44 of file GUI_TextArea.h.
Referenced by exec(), init(), TextArea(), and ~TextArea().
scrollBarContainer
Window* Core::GUI::Object::TextArea::scrollBarContainer protected
Definition at line 40 of file GUI_TextArea.h.
Referenced by exec(), init(), TextArea(), and ~TextArea().
scrollDown
Button* Core::GUI::Object::TextArea::scrollDown protected
Definition at line 42 of file GUI_TextArea.h.
Referenced by exec(), init(), TextArea(), and ~TextArea().
scrollUp
Button* Core::GUI::Object::TextArea::scrollUp protected
Definition at line 41 of file GUI_TextArea.h.
Referenced by exec(), init(), TextArea(), and ~TextArea().
text
Text Core::GUI::Object::TextArea::text protected
Definition at line 39 of file GUI_TextArea.h.
Referenced by exec(), and init().
toolTip
ToolTip Core::GUI::Object::TextArea::toolTip
Definition at line 33 of file GUI_TextArea.h.
Referenced by exec(), and init().
win
Window Core::GUI::Object::TextArea::win protected
Definition at line 38 of file GUI_TextArea.h.
Referenced by exec(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_TextArea.h