Project Parsec: SimplexNoise Class Reference
SimplexNoise Class Reference
A Perlin Simplex Noise C++ Implementation (1D, 2D, 3D, 4D).
#include <SimplexNoise.h>
Public Member Functions
float fractal (size_t octaves, float x) const
float fractal (size_t octaves, float x, float y) const
float fractal (size_t octaves, float x, float y, float z) const
SimplexNoise (float frequency=1.0f, float amplitude=1.0f, float lacunarity=2.0f, float persistence=0.5f)
Static Public Member Functions
static float noise (float x)
static float noise (float x, float y)
static float noise (float x, float y, float z)
Private Attributes
float mFrequency
Frequency ("width") of the first octave of noise (default to 1.0)
float mAmplitude
Amplitude ("height") of the first octave of noise (default to 1.0)
float mLacunarity
Lacunarity specifies the frequency multiplier between successive octaves (default to 2.0).
float mPersistence
Persistence is the loss of amplitude between successive octaves (usually 1/lacunarity)
Detailed Description
A Perlin Simplex Noise C++ Implementation (1D, 2D, 3D, 4D).
Definition at line 17 of file SimplexNoise.h.
Constructor & Destructor Documentation
SimplexNoise()
SimplexNoise::SimplexNoise (float frequency = 1.0f, float amplitude = 1.0f, float lacunarity = 2.0f, float persistence = 0.5f) inline explicit
Constructor of to initialize a fractal noise summation
Parameters
[in] frequency Frequency ("width") of the first octave of noise (default to 1.0)
[in] amplitude Amplitude ("height") of the first octave of noise (default to 1.0)
[in] lacunarity Lacunarity specifies the frequency multiplier between successive octaves (default to 2.0).
[in] persistence Persistence is the loss of amplitude between successive octaves (usually 1/lacunarity)
Definition at line 39 of file SimplexNoise.h.
Member Function Documentation
fractal() [1/3]
float SimplexNoise::fractal (size_t octaves, float x) const
Fractal/Fractional Brownian Motion (fBm) summation of 1D Perlin Simplex noise
Parameters
[in] octaves number of fraction of noise to sum
[in] x float coordinate
Returns
Noise value in the range[-1; 1], value of 0 on all integer coordinates.
Definition at line 407 of file SimplexNoise.cpp.
References mAmplitude, mFrequency, mLacunarity, mPersistence, and noise().
Referenced by Core::GameSys::MapSys::getSimplexElevation().
fractal() [2/3]
float SimplexNoise::fractal (size_t octaves, float x, float y) const
Fractal/Fractional Brownian Motion (fBm) summation of 2D Perlin Simplex noise
Parameters
[in] octaves number of fraction of noise to sum
[in] x x float coordinate
[in] y y float coordinate
Returns
Noise value in the range[-1; 1], value of 0 on all integer coordinates.
Definition at line 433 of file SimplexNoise.cpp.
References mAmplitude, mFrequency, mLacunarity, mPersistence, and noise().
fractal() [3/3]
float SimplexNoise::fractal (size_t octaves, float x, float y, float z) const
Fractal/Fractional Brownian Motion (fBm) summation of 3D Perlin Simplex noise
Parameters
[in] octaves number of fraction of noise to sum
[in] x x float coordinate
[in] y y float coordinate
[in] z z float coordinate
Returns
Noise value in the range[-1; 1], value of 0 on all integer coordinates.
Definition at line 460 of file SimplexNoise.cpp.
References mAmplitude, mFrequency, mLacunarity, mPersistence, and noise().
noise() [1/3]
float SimplexNoise::noise (float x) static
1D Perlin simplex noise
Takes around 74ns on an AMD APU.
Parameters
[in] x float coordinate
Returns
Noise value in the range[-1; 1], value of 0 on all integer coordinates.
Definition at line 175 of file SimplexNoise.cpp.
References fastfloor(), grad(), and hash().
Referenced by fractal().
noise() [2/3]
float SimplexNoise::noise (float x, float y) static
2D Perlin simplex noise
Takes around 150ns on an AMD APU.
Parameters
[in] x float coordinate
[in] y float coordinate
Returns
Noise value in the range[-1; 1], value of 0 on all integer coordinates.
Definition at line 214 of file SimplexNoise.cpp.
References fastfloor(), grad(), hash(), t, and y.
noise() [3/3]
float SimplexNoise::noise (float x, float y, float z) static
3D Perlin simplex noise
Parameters
[in] x float coordinate
[in] y float coordinate
[in] z float coordinate
Returns
Noise value in the range[-1; 1], value of 0 on all integer coordinates.
Definition at line 302 of file SimplexNoise.cpp.
References fastfloor(), grad(), hash(), t, and z.
Member Data Documentation
mAmplitude
float SimplexNoise::mAmplitude private
Amplitude ("height") of the first octave of noise (default to 1.0)
Definition at line 52 of file SimplexNoise.h.
Referenced by fractal().
mFrequency
float SimplexNoise::mFrequency private
Frequency ("width") of the first octave of noise (default to 1.0)
Definition at line 51 of file SimplexNoise.h.
Referenced by fractal().
mLacunarity
float SimplexNoise::mLacunarity private
Lacunarity specifies the frequency multiplier between successive octaves (default to 2.0).
Definition at line 53 of file SimplexNoise.h.
Referenced by fractal().
mPersistence
float SimplexNoise::mPersistence private
Persistence is the loss of amplitude between successive octaves (usually 1/lacunarity)
Definition at line 54 of file SimplexNoise.h.
Referenced by fractal().
The documentation for this class was generated from the following files:
src/headers/core/SimplexNoise.h
src/headers/core/SimplexNoise.cpp