Project Parsec: Core::GameSys::_Satellite Class Reference
Core::GameSys::_Satellite Class Reference
#include <satellite.h>
Public Member Functions
_Satellite (Atmosphere &f)
~_Satellite ()
bool add (_SatelliteData data)
bool calc ()
bool calc (std::string name)
bool calc (uint id)
void update (bool bLensFlare=false)
void update (std::string name, bool bLensFlare=false)
void update (int id, bool bLensFlare=false)
void draw (bool bOcclusion=false)
void draw (std::string name, bool bOcclusion=false)
void draw (int id, bool bOcclusion=false)
void drawFlare (std::string name)
void drawFlare (int id)
Vector3f & getPosition (std::string name)
Vector3f & getPosition (int id)
void setPosition (std::string name, Vector3f v)
void setPosition (int id, Vector3f v)
float getAlpha (std::string name)
float getAlpha (int id)
float getScale (std::string name)
float getScale (int id)
Core::Degrees getZenith (std::string name)
Core::Degrees getZenith (int id)
Public Attributes
_SatelliteData * data
Private Member Functions
bool init ()
Private Attributes
Atmosphere & parent
Core::Map_si map
Core::Map_is rmap
bool bErrorONS [32]
int iNumObjects
Static Private Attributes
static bool bTexLoaded = false
static Texture tex = Texture()
static const uint MAX_TEXTURES = 32
static const int MAX_OBJECTS = 16
static const uint RECORD_SIZE = 32
static const std::string DIR = "./system/"
static const std::string FILENAME = "satellite.bin"
static const std::string TEXDIR = "./texture/atmosphere/satellite/"
static const bool bDebug = false
Detailed Description
Definition at line 149 of file satellite.h.
Constructor & Destructor Documentation
_Satellite()
Core::GameSys::_Satellite::_Satellite (Atmosphere & f)
Definition at line 220 of file satellite.h.
References bErrorONS, init(), iNumObjects, and MAX_OBJECTS.
~_Satellite()
Core::GameSys::_Satellite::~_Satellite ()
Definition at line 229 of file satellite.h.
References data.
Member Function Documentation
add()
bool Core::GameSys::_Satellite::add (_SatelliteData data)
Definition at line 288 of file satellite.h.
References Core::_Occlusion::Add(), cout, GL_SAMPLES_PASSED, iNumObjects, map, MAX_OBJECTS, Core::occlusion, rmap, Core::GameSys::_SatelliteData::sName, and Core::sOffset.
Referenced by Core::GameSys::Atmosphere::load().
calc() [1/3]
bool Core::GameSys::_Satellite::calc ()
Definition at line 303 of file satellite.h.
References cout, and iNumObjects.
Referenced by Core::GameSys::Atmosphere::calc(), and calc().
calc() [2/3]
bool Core::GameSys::_Satellite::calc (std::string name)
Definition at line 316 of file satellite.h.
References calc(), and map.
calc() [3/3]
bool Core::GameSys::_Satellite::calc (uint id)
Definition at line 320 of file satellite.h.
References Core::GameVars::Screen::bpp, cout, Core::GameVars::Screen::fDistanceAspect, Core::GameVars::Screen::fScreenAspect, Core::gameVars, GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, id, Core::GameVars::Screen::MultiSample, Core::occlusion, rmap, Core::GameVars::screen, Core::_Occlusion::SetSamples(), and Core::sOffset.
draw() [1/3]
void Core::GameSys::_Satellite::draw (bool bOcclusion = false)
Definition at line 587 of file satellite.h.
References cout, and iNumObjects.
Referenced by Core::GameSys::Atmosphere::draw(), and draw().
draw() [2/3]
void Core::GameSys::_Satellite::draw (int id, bool bOcclusion = false)
Definition at line 603 of file satellite.h.
References bErrorONS, bTexLoaded, Core::colors, cout, Core::_Helper::drawPointSprite(), Core::_Occlusion::EndQuery(), Core::_Colors::GetActive(), GL_SAMPLES_PASSED, GL_TEXTURE0, Core::_Helper::GLPOINT_SQUARE, Core::helper, Core::occlusion, Core::_SystemTextures::set(), Core::Texture::Set(), Core::_Occlusion::StartQuery(), Core::sysTex, tex, and Core::_SystemTextures::TEX_TESTPATTERN.
draw() [3/3]
void Core::GameSys::_Satellite::draw (std::string name, bool bOcclusion = false)
Definition at line 599 of file satellite.h.
References draw(), and map.
drawFlare() [1/2]
void Core::GameSys::_Satellite::drawFlare (int id)
Definition at line 628 of file satellite.h.
References bDebug, cout, Core::GlInit_System::DisableAdditiveBlending(), Core::_Helper::drawPointSprite(), Core::GlInit_System::EnableAdditiveBlending(), GL_TEXTURE0, Core::glinit, Core::_Helper::GLPOINT_CIRCLE, Core::helper, id, Core::matrix, Core::Texture::Set(), Core::Matrix_System::SetIdentity(), Core::Matrix_System::SetProjection(), and tex.
drawFlare() [2/2]
void Core::GameSys::_Satellite::drawFlare (std::string name)
Definition at line 624 of file satellite.h.
References map.
Referenced by Core::GameSys::Atmosphere::draw().
getAlpha() [1/2]
float Core::GameSys::_Satellite::getAlpha (int id) inline
Definition at line 182 of file satellite.h.
References id.
getAlpha() [2/2]
float Core::GameSys::_Satellite::getAlpha (std::string name) inline
Definition at line 181 of file satellite.h.
References getAlpha(), and map.
Referenced by getAlpha(), and _Game::Update().
getPosition() [1/2]
Vector3f& Core::GameSys::_Satellite::getPosition (int id) inline
Definition at line 175 of file satellite.h.
References id.
getPosition() [2/2]
Vector3f& Core::GameSys::_Satellite::getPosition (std::string name) inline
Definition at line 174 of file satellite.h.
References getPosition(), and map.
Referenced by Core::GameSys::Atmosphere::draw(), and getPosition().
getScale() [1/2]
float Core::GameSys::_Satellite::getScale (int id) inline
Definition at line 188 of file satellite.h.
References id.
getScale() [2/2]
float Core::GameSys::_Satellite::getScale (std::string name) inline
Definition at line 187 of file satellite.h.
References getScale(), and map.
Referenced by getScale().
getZenith() [1/2]
Core::Degrees Core::GameSys::_Satellite::getZenith (int id) inline
Definition at line 191 of file satellite.h.
getZenith() [2/2]
Core::Degrees Core::GameSys::_Satellite::getZenith (std::string name) inline
Definition at line 190 of file satellite.h.
References getZenith(), and map.
Referenced by getZenith().
init()
bool Core::GameSys::_Satellite::init () private
Definition at line 239 of file satellite.h.
References bDebug, Core::Texture::Begin(), bTexLoaded, Core::MemBlock::buffer, cout, DIR, FILENAME, GL_NEAREST, GL_REPEAT, id, Core::Texture::Load(), Core::readFile(), RECORD_SIZE, Core::MemBlock::size, Core::sOffset, tex, and TEXDIR.
Referenced by _Satellite().
setPosition() [1/2]
void Core::GameSys::_Satellite::setPosition (int id, Vector3f v) inline
Definition at line 178 of file satellite.h.
References id.
setPosition() [2/2]
void Core::GameSys::_Satellite::setPosition (std::string name, Vector3f v) inline
Definition at line 177 of file satellite.h.
References map, and setPosition().
Referenced by setPosition().
update() [1/3]
void Core::GameSys::_Satellite::update (bool bLensFlare = false)
Definition at line 357 of file satellite.h.
References cout, and iNumObjects.
Referenced by Core::GameSys::Atmosphere::update(), and update().
update() [2/3]
void Core::GameSys::_Satellite::update (int id, bool bLensFlare = false)
Definition at line 373 of file satellite.h.
References bDebug, cout, Core::_Helper::drawLine(), Core::_TimeSys::fTimeRaw, Core::gameVars, Core::_Occlusion::GetRatio(), Core::GameVars::Screen::half, Core::helper, id, Core::Vector2f::length(), Core::Vector3f::length(), Core::matrix, Core::occlusion, Core::Matrix_System::Pop(), Core::Matrix_System::Push(), Core::GameVars::Screen::res, Core::Timer::reset(), Core::Matrix44f::Rotate(), Core::GameVars::screen, Core::Matrix_System::SetProjection(), Core::timeSys, to_string(), Core::Degrees::toRadians(), Core::Vector4f::w, Core::Vector2f::x, Core::Vector3f::x, Core::Vector4f::x, Core::Vector2f::y, Core::Vector3f::y, Core::Vector4f::y, and Core::Vector4f::z.
update() [3/3]
void Core::GameSys::_Satellite::update (std::string name, bool bLensFlare = false)
Definition at line 369 of file satellite.h.
References map, and update().
Member Data Documentation
bDebug
const bool Core::GameSys::_Satellite::bDebug = false static private
Definition at line 209 of file satellite.h.
Referenced by drawFlare(), init(), and update().
bErrorONS
bool Core::GameSys::_Satellite::bErrorONS[32] private
Definition at line 201 of file satellite.h.
Referenced by _Satellite(), and draw().
bTexLoaded
bool Core::GameSys::_Satellite::bTexLoaded = false static private
Definition at line 195 of file satellite.h.
Referenced by draw(), and init().
data
_SatelliteData* Core::GameSys::_Satellite::data
Definition at line 152 of file satellite.h.
Referenced by ~_Satellite().
DIR
const std::string Core::GameSys::_Satellite::DIR = "./system/" static private
Definition at line 206 of file satellite.h.
Referenced by init().
FILENAME
const std::string Core::GameSys::_Satellite::FILENAME = "satellite.bin" static private
Definition at line 207 of file satellite.h.
Referenced by init().
iNumObjects
int Core::GameSys::_Satellite::iNumObjects private
Definition at line 202 of file satellite.h.
Referenced by _Satellite(), add(), calc(), draw(), and update().
map
Core::Map_si Core::GameSys::_Satellite::map private
Definition at line 198 of file satellite.h.
Referenced by add(), calc(), draw(), drawFlare(), getAlpha(), getPosition(), getScale(), getZenith(), setPosition(), and update().
MAX_OBJECTS
const int Core::GameSys::_Satellite::MAX_OBJECTS = 16 static private
Definition at line 204 of file satellite.h.
Referenced by _Satellite(), and add().
MAX_TEXTURES
const uint Core::GameSys::_Satellite::MAX_TEXTURES = 32 static private
Definition at line 203 of file satellite.h.
parent
Atmosphere& Core::GameSys::_Satellite::parent private
Definition at line 191 of file satellite.h.
RECORD_SIZE
const uint Core::GameSys::_Satellite::RECORD_SIZE = 32 static private
Definition at line 205 of file satellite.h.
Referenced by init().
rmap
Core::Map_is Core::GameSys::_Satellite::rmap private
Definition at line 199 of file satellite.h.
Referenced by add(), and calc().
tex
Texture Core::GameSys::_Satellite::tex = Texture() static private
Definition at line 196 of file satellite.h.
Referenced by draw(), drawFlare(), and init().
TEXDIR
const std::string Core::GameSys::_Satellite::TEXDIR = "./texture/atmosphere/satellite/" static private
Definition at line 208 of file satellite.h.
Referenced by init().
The documentation for this class was generated from the following file:
src/headers/gamesys/atmosphere/satellite.h