Project Parsec: Core::GUI::GUI::ButtonInterface Class Reference
Core::GUI::GUI::ButtonInterface Class Reference
#include <GUI.h>
Public Member Functions
void add (std::string guiName, std::string buttonName, Constraints_Button c)
void add (std::string guiName, std::string buttonName, Constraints_Button *c)
void add (std::string guiName, std::string buttonName, bool *b, Constraints_Button c)
void add (std::string guiName, std::string buttonName, bool *b, Constraints_Button *c)
void add (std::string guiName, std::string windowName, std::string buttonName, Constraints_Button c)
void add (std::string guiName, std::string windowName, std::string buttonName, Constraints_Button *c)
void add (std::string guiName, std::string windowName, std::string buttonName, bool *b, Constraints_Button c)
void add (std::string guiName, std::string windowName, std::string buttonName, bool *b, Constraints_Button *c)
bool active (std::string guiName, std::string buttonName)
bool state (std::string guiName, std::string buttonName)
Constraints_Button * get (std::string guiName, std::string buttonName)
ButtonInterface (GUI *parent)
Public Attributes
GUI * gui
Detailed Description
Definition at line 103 of file GUI.h.
Constructor & Destructor Documentation
ButtonInterface()
Core::GUI::GUI::ButtonInterface::ButtonInterface (GUI * parent) inline
Definition at line 131 of file GUI.h.
References gui.
Member Function Documentation
active()
bool Core::GUI::GUI::ButtonInterface::active (std::string guiName, std::string buttonName)
Definition at line 518 of file GUI.h.
References MY_NAMESPACE::gui.
add() [1/8]
void Core::GUI::GUI::ButtonInterface::add (std::string guiName, std::string buttonName, bool * b, Constraints_Button * c)
Definition at line 493 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::Button::init().
add() [2/8]
void Core::GUI::GUI::ButtonInterface::add (std::string guiName, std::string buttonName, bool * b, Constraints_Button c)
Definition at line 474 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::Button::init().
add() [3/8]
void Core::GUI::GUI::ButtonInterface::add (std::string guiName, std::string buttonName, Constraints_Button * c)
Definition at line 455 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::Button::init().
add() [4/8]
void Core::GUI::GUI::ButtonInterface::add (std::string guiName, std::string buttonName, Constraints_Button c)
Definition at line 436 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::Button::init().
add() [5/8]
void Core::GUI::GUI::ButtonInterface::add (std::string guiName, std::string windowName, std::string buttonName, bool * b, Constraints_Button * c)
Definition at line 502 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::Button::init().
add() [6/8]
void Core::GUI::GUI::ButtonInterface::add (std::string guiName, std::string windowName, std::string buttonName, bool * b, Constraints_Button c)
Definition at line 483 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::Button::init().
add() [7/8]
void Core::GUI::GUI::ButtonInterface::add (std::string guiName, std::string windowName, std::string buttonName, Constraints_Button * c)
Definition at line 464 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::Button::init().
add() [8/8]
void Core::GUI::GUI::ButtonInterface::add (std::string guiName, std::string windowName, std::string buttonName, Constraints_Button c)
Definition at line 445 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::Button::init().
get()
Constraints_Button * Core::GUI::GUI::ButtonInterface::get (std::string guiName, std::string buttonName)
Definition at line 530 of file GUI.h.
References MY_NAMESPACE::gui.
state()
bool Core::GUI::GUI::ButtonInterface::state (std::string guiName, std::string buttonName)
Definition at line 524 of file GUI.h.
References MY_NAMESPACE::gui.
Member Data Documentation
gui
GUI* Core::GUI::GUI::ButtonInterface::gui
Definition at line 130 of file GUI.h.
Referenced by ButtonInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI.h