Project Parsec: Core::GUI::Object::AnyField Class Reference
Core::GUI::Object::AnyField Class Reference
#include <GUI_Field.h>
Public Member Functions
AnyField ()
void set (std::string n, float *fPtr, Props_Field c)
void set (std::string n, float *fPtr, Props_Field *c)
void set (std::string n, float fVal, Props_Field *c)
void set (std::string n, int *iPtr, Props_Field c)
void set (std::string n, int *iPtr, Props_Field *c)
void set (std::string n, int iVal, Props_Field *c)
void set (std::string n, std::string *sPtr, Props_Field c)
void set (std::string n, std::string *sPtr, Props_Field *c)
void set (std::string n, std::string sVal, Props_Field *c)
void set (Props &p, std::string n, float *fPtr, Props_Field c)
void set (Props &p, std::string n, float *fPtr, Props_Field *c)
void set (Props &p, std::string n, float fVal, Props_Field *c)
void set (Props &p, std::string n, int *iPtr, Props_Field c)
void set (Props &p, std::string n, int *iPtr, Props_Field *c)
void set (Props &p, std::string n, int iVal, Props_Field *c)
void set (Props &p, std::string n, std::string *sPtr, Props_Field c)
void set (Props &p, std::string n, std::string *sPtr, Props_Field *c)
void set (Props &p, std::string n, std::string sVal, Props_Field *c)
Object::Field< float > * getF ()
Object::Field< int > * getI ()
Object::Field< std::string > * getS ()
template<typename T >
Object::Field< T > * get ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
void updateNoFocus ()
void setPointer (float *fPtr)
void setPointer (int *iPtr)
int state ()
~AnyField ()
Private Types
enum { NONE, FLOAT, INT, STRING }
Private Attributes
enum Core::GUI::Object::AnyField:: { ... } tag =NONE
union {
Object::Field< float > * f
Object::Field< int > * i
Object::Field< std::string > * s
};
Detailed Description
Definition at line 433 of file GUI_Field.h.
Member Enumeration Documentation
anonymous enum
anonymous enum private
Enumerator
NONE
FLOAT
INT
STRING
Definition at line 435 of file GUI_Field.h.
Constructor & Destructor Documentation
AnyField()
Core::GUI::Object::AnyField::AnyField () inline
Definition at line 443 of file GUI_Field.h.
~AnyField()
Core::GUI::Object::AnyField::~AnyField () inline
Definition at line 529 of file GUI_Field.h.
Member Function Documentation
exec()
void Core::GUI::Object::AnyField::exec (iState eExternState = STATE_NONE) inline
Definition at line 486 of file GUI_Field.h.
Referenced by Core::GUI::Object::ProgressBar::exec().
execToolTip()
void Core::GUI::Object::AnyField::execToolTip () inline
Definition at line 494 of file GUI_Field.h.
get()
template<typename T > Object::Field<T>* Core::GUI::Object::AnyField::get () inline
Definition at line 469 of file GUI_Field.h.
getF()
Object::Field<float>* Core::GUI::Object::AnyField::getF () inline
Definition at line 465 of file GUI_Field.h.
getI()
Object::Field<int>* Core::GUI::Object::AnyField::getI () inline
Definition at line 466 of file GUI_Field.h.
getS()
Object::Field<std::string>* Core::GUI::Object::AnyField::getS () inline
Definition at line 467 of file GUI_Field.h.
init()
void Core::GUI::Object::AnyField::init () inline
Definition at line 478 of file GUI_Field.h.
Referenced by Core::GUI::Object::ProgressBar::init().
set() [1/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, float * fPtr, Props_Field * c) inline
Definition at line 456 of file GUI_Field.h.
set() [2/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, float * fPtr, Props_Field c) inline
Definition at line 455 of file GUI_Field.h.
set() [3/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, float fVal, Props_Field * c) inline
Definition at line 457 of file GUI_Field.h.
set() [4/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, int * iPtr, Props_Field * c) inline
Definition at line 459 of file GUI_Field.h.
set() [5/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, int * iPtr, Props_Field c) inline
Definition at line 458 of file GUI_Field.h.
set() [6/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, int iVal, Props_Field * c) inline
Definition at line 460 of file GUI_Field.h.
set() [7/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, std::string * sPtr, Props_Field * c) inline
Definition at line 462 of file GUI_Field.h.
set() [8/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, std::string * sPtr, Props_Field c) inline
Definition at line 461 of file GUI_Field.h.
set() [9/18]
void Core::GUI::Object::AnyField::set (Props & p, std::string n, std::string sVal, Props_Field * c) inline
Definition at line 463 of file GUI_Field.h.
set() [10/18]
void Core::GUI::Object::AnyField::set (std::string n, float * fPtr, Props_Field * c) inline
Definition at line 445 of file GUI_Field.h.
set() [11/18]
void Core::GUI::Object::AnyField::set (std::string n, float * fPtr, Props_Field c) inline
Definition at line 444 of file GUI_Field.h.
Referenced by Core::GUI::GUI_Container::FieldInterface::add(), and Core::GUI::Object::ProgressBar::init().
set() [12/18]
void Core::GUI::Object::AnyField::set (std::string n, float fVal, Props_Field * c) inline
Definition at line 446 of file GUI_Field.h.
set() [13/18]
void Core::GUI::Object::AnyField::set (std::string n, int * iPtr, Props_Field * c) inline
Definition at line 448 of file GUI_Field.h.
set() [14/18]
void Core::GUI::Object::AnyField::set (std::string n, int * iPtr, Props_Field c) inline
Definition at line 447 of file GUI_Field.h.
set() [15/18]
void Core::GUI::Object::AnyField::set (std::string n, int iVal, Props_Field * c) inline
Definition at line 449 of file GUI_Field.h.
set() [16/18]
void Core::GUI::Object::AnyField::set (std::string n, std::string * sPtr, Props_Field * c) inline
Definition at line 451 of file GUI_Field.h.
set() [17/18]
void Core::GUI::Object::AnyField::set (std::string n, std::string * sPtr, Props_Field c) inline
Definition at line 450 of file GUI_Field.h.
set() [18/18]
void Core::GUI::Object::AnyField::set (std::string n, std::string sVal, Props_Field * c) inline
Definition at line 452 of file GUI_Field.h.
setPointer() [1/2]
void Core::GUI::Object::AnyField::setPointer (float * fPtr) inline
Definition at line 508 of file GUI_Field.h.
Referenced by Core::GUI::Object::ProgressBar::setPointer().
setPointer() [2/2]
void Core::GUI::Object::AnyField::setPointer (int * iPtr) inline
Definition at line 514 of file GUI_Field.h.
state()
int Core::GUI::Object::AnyField::state () inline
Definition at line 520 of file GUI_Field.h.
updateNoFocus()
void Core::GUI::Object::AnyField::updateNoFocus () inline
Definition at line 501 of file GUI_Field.h.
Member Data Documentation
@61
union { ... }
f
Object::Field<float>* Core::GUI::Object::AnyField::f
Definition at line 437 of file GUI_Field.h.
i
Object::Field<int>* Core::GUI::Object::AnyField::i
Definition at line 438 of file GUI_Field.h.
s
Object::Field<std::string>* Core::GUI::Object::AnyField::s
Definition at line 439 of file GUI_Field.h.
tag
enum { ... } Core::GUI::Object::AnyField::tag
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Field.h