Project Parsec: Core::_Occlusion Class Reference
Core::_Occlusion Class Reference
#include <occlusion.h>
Classes
struct _OcclusionData
Public Member Functions
_Occlusion ()
~_Occlusion ()
void Init ()
void SetSamples (std::string name, uint uiSamples)
uint GetSamples (std::string name)
float GetRatio (std::string name)
GLuint Add (std::string name, int type)
void StartQuery (std::string name, GLuint type=GL_SAMPLES_PASSED)
bool ReadAvailable (std::string name)
bool GetAvailable (std::string name)
GLuint ReadResultui (std::string name)
bool ReadResultb (std::string name)
GLuint GetResultui (std::string name)
void EndQuery (std::string name)
Private Attributes
uint uiNum
GLuint * uiQueryIds
_OcclusionData * data
Map_si map
Map_is rmap
Static Private Attributes
static const int MAX_QUERIES = 32
Detailed Description
Definition at line 20 of file occlusion.h.
Constructor & Destructor Documentation
_Occlusion()
Core::_Occlusion::_Occlusion ()
Definition at line 74 of file occlusion.h.
References cout, MAX_QUERIES, uiNum, and uiQueryIds.
~_Occlusion()
Core::_Occlusion::~_Occlusion ()
Definition at line 87 of file occlusion.h.
References cout, data, MAX_QUERIES, and uiQueryIds.
Member Function Documentation
Add()
GLuint Core::_Occlusion::Add (std::string name, int type)
Definition at line 153 of file occlusion.h.
References map, MAX_QUERIES, uiNum, and uiQueryIds.
Referenced by Core::GameSys::_Satellite::add().
EndQuery()
void Core::_Occlusion::EndQuery (std::string name)
Definition at line 293 of file occlusion.h.
References id, and map.
Referenced by _TheVoid::Draw(), and Core::GameSys::_Satellite::draw().
GetAvailable()
bool Core::_Occlusion::GetAvailable (std::string name)
Definition at line 262 of file occlusion.h.
References id, and map.
GetRatio()
float Core::_Occlusion::GetRatio (std::string name)
Definition at line 217 of file occlusion.h.
References map.
Referenced by _Game::Update(), and Core::GameSys::_Satellite::update().
GetResultui()
GLuint Core::_Occlusion::GetResultui (std::string name)
Definition at line 287 of file occlusion.h.
References id, and map.
Referenced by runDebug().
GetSamples()
uint Core::_Occlusion::GetSamples (std::string name)
Definition at line 204 of file occlusion.h.
References id, and map.
Init()
void Core::_Occlusion::Init ()
Definition at line 106 of file occlusion.h.
References cout, MAX_QUERIES, and uiQueryIds.
Referenced by MY_NAMESPACE::Setup().
ReadAvailable()
bool Core::_Occlusion::ReadAvailable (std::string name)
Definition at line 252 of file occlusion.h.
References GL_FALSE, GL_QUERY_RESULT_AVAILABLE, GL_TRUE, id, and map.
Referenced by ReadResultb(), and ReadResultui().
ReadResultb()
bool Core::_Occlusion::ReadResultb (std::string name)
Definition at line 278 of file occlusion.h.
References GL_QUERY_RESULT, GL_TRUE, id, map, and ReadAvailable().
ReadResultui()
GLuint Core::_Occlusion::ReadResultui (std::string name)
Definition at line 267 of file occlusion.h.
References GL_QUERY_RESULT, id, map, and ReadAvailable().
SetSamples()
void Core::_Occlusion::SetSamples (std::string name, uint uiSamples)
Definition at line 189 of file occlusion.h.
References id, and map.
Referenced by Core::GameSys::_Satellite::calc().
StartQuery()
void Core::_Occlusion::StartQuery (std::string name, GLuint type = GL_SAMPLES_PASSED)
Definition at line 226 of file occlusion.h.
References id, and map.
Referenced by _TheVoid::Draw(), and Core::GameSys::_Satellite::draw().
Member Data Documentation
data
_OcclusionData* Core::_Occlusion::data private
Definition at line 44 of file occlusion.h.
Referenced by ~_Occlusion().
map
Map_si Core::_Occlusion::map private
Definition at line 47 of file occlusion.h.
Referenced by Add(), EndQuery(), GetAvailable(), GetRatio(), GetResultui(), GetSamples(), ReadAvailable(), ReadResultb(), ReadResultui(), SetSamples(), and StartQuery().
MAX_QUERIES
const int Core::_Occlusion::MAX_QUERIES = 32 static private
Definition at line 42 of file occlusion.h.
Referenced by _Occlusion(), Add(), Init(), and ~_Occlusion().
rmap
Map_is Core::_Occlusion::rmap private
Definition at line 48 of file occlusion.h.
uiNum
uint Core::_Occlusion::uiNum private
Definition at line 40 of file occlusion.h.
Referenced by _Occlusion(), and Add().
uiQueryIds
GLuint* Core::_Occlusion::uiQueryIds private
Definition at line 41 of file occlusion.h.
Referenced by _Occlusion(), Add(), Init(), and ~_Occlusion().
The documentation for this class was generated from the following file:
src/headers/core/occlusion.h