Project Parsec: Core::_SpriteSys Class Reference
Core::_SpriteSys Class Reference
#include <SpriteSys.h>
Public Member Functions
uint draw (uint x, uint y, float s, std::string sTex, bool textOffset)
uint draw (uint x, uint y, float s, std::string sTex, bool textOffset, Color fontColor)
uint draw (uint x, uint y, float w, float h, std::string sTex, bool textOffset)
uint draw (uint x, uint y, float w, float h, std::string sTex, bool textOffset, Color fontColor)
_SpriteSys ()
void draw (uint x, uint y, float w, float h, GLuint uiTex, SHADER_PROGRAMS uiShader)
void draw (uint x, uint y, float w, float h, Color fontColor, GLuint uiTex, SHADER_PROGRAMS uiShader)
void draw (Core::GUI::Props *con, std::string texture)
bool load ()
bool calc ()
Private Member Functions
void start (int x, int y, float w, float h, std::string sTex, bool textOffset, bool bNoTex, Core::_Colors::_ACTIVE_COLOR eColor=Core::_Colors::COLOR_FRONT, SHADER_PROGRAMS uiShader=GLS_FONT)
void update (SHADER_PROGRAMS uiShader)
void stop ()
void draw (std::string sTex, SHADER_PROGRAMS iShader)
Private Attributes
Texture texture
VAO vao
Vector4f gridCoord
uint uiNumTextures
uint uiRecordSize
std::string sFilename
std::string sDir
std::string sTexDir
Friends
class _GameSys
Detailed Description
Definition at line 19 of file SpriteSys.h.
Constructor & Destructor Documentation
_SpriteSys()
Core::_SpriteSys::_SpriteSys ()
Definition at line 63 of file SpriteSys.h.
References sDir, sFilename, sTexDir, uiNumTextures, and uiRecordSize.
Member Function Documentation
calc()
bool Core::_SpriteSys::calc ()
Definition at line 111 of file SpriteSys.h.
References Core::VAO::Begin(), Core::VAO::CopyData(), cout, Core::VAO::End(), GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, gridCoord, and vao.
draw() [1/8]
void Core::_SpriteSys::draw (Core::GUI::Props * con, std::string texture)
Definition at line 264 of file SpriteSys.h.
References Core::VAO::Draw(), GL_CULL_FACE, GL_DEPTH_TEST, GL_TEXTURE0, GL_TRUE, Core::GLS_FONT, Core::GUI::Props::pos, Core::GUI::Props::size, vao, Core::Vector2f::x, and Core::Vector2f::y.
draw() [2/8]
void Core::_SpriteSys::draw (std::string sTex, SHADER_PROGRAMS iShader) private
Definition at line 196 of file SpriteSys.h.
References Core::VAO::Draw(), GL_CULL_FACE, and vao.
Referenced by Core::GameSys::checkSprite(), draw(), Core::GameSys::drawSprite(), Core::GUI::Object::Sprite::exec(), and _Game::Update().
draw() [3/8]
uint Core::_SpriteSys::draw (uint x, uint y, float s, std::string sTex, bool textOffset)
Definition at line 204 of file SpriteSys.h.
References draw().
draw() [4/8]
uint Core::_SpriteSys::draw (uint x, uint y, float s, std::string sTex, bool textOffset, Color fontColor)
Definition at line 214 of file SpriteSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
draw() [5/8]
void Core::_SpriteSys::draw (uint x, uint y, float w, float h, Color fontColor, GLuint uiTex, SHADER_PROGRAMS uiShader = GLS_FONT)
Definition at line 237 of file SpriteSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
draw() [6/8]
void Core::_SpriteSys::draw (uint x, uint y, float w, float h, GLuint uiTex, SHADER_PROGRAMS uiShader = GLS_FONT)
Definition at line 243 of file SpriteSys.h.
References Core::_Colors::COLOR_FRONT, Core::VAO::Draw(), GL_CULL_FACE, GL_TEXTURE0, GL_TEXTURE_2D, start(), stop(), update(), and vao.
draw() [7/8]
uint Core::_SpriteSys::draw (uint x, uint y, float w, float h, std::string sTex, bool textOffset)
Definition at line 386 of file SpriteSys.h.
References Core::VAO::Draw(), Core::mouse, Core::_Mouse::MOUSE_NONE, start(), stop(), update(), and vao.
draw() [8/8]
uint Core::_SpriteSys::draw (uint x, uint y, float w, float h, std::string sTex, bool textOffset, Color fontColor)
Definition at line 379 of file SpriteSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
load()
bool Core::_SpriteSys::load ()
Definition at line 79 of file SpriteSys.h.
References Core::MemBlock::buffer, cout, Core::readFile(), sDir, sFilename, Core::MemBlock::size, sTexDir, uiNumTextures, and uiRecordSize.
start()
void Core::_SpriteSys::start (int x, int y, float w, float h, std::string sTex, bool textOffset, bool bNoTex = false, Core::_Colors::_ACTIVE_COLOR eColor = Core::_Colors::COLOR_FRONT, SHADER_PROGRAMS uiShader = GLS_FONT) private
Definition at line 158 of file SpriteSys.h.
References Core::colors, Core::GameVars::font, Core::gameVars, GL_DEPTH_TEST, GL_TRUE, Core::GameVars::Screen::origin, Core::GameVars::screen, Core::GameVars::Font::screenCoords, Core::_Colors::SetActive(), and Core::GameVars::Font::vSize.
Referenced by draw().
stop()
void Core::_SpriteSys::stop () private
Definition at line 186 of file SpriteSys.h.
References GL_DEPTH_TEST.
Referenced by draw().
update()
void Core::_SpriteSys::update (SHADER_PROGRAMS uiShader = GLS_FONT) private
Definition at line 181 of file SpriteSys.h.
Referenced by draw().
Friends And Related Function Documentation
_GameSys
friend class _GameSys friend
Definition at line 41 of file SpriteSys.h.
Member Data Documentation
gridCoord
Vector4f Core::_SpriteSys::gridCoord private
Definition at line 25 of file SpriteSys.h.
Referenced by calc().
sDir
std::string Core::_SpriteSys::sDir private
Definition at line 28 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
sFilename
std::string Core::_SpriteSys::sFilename private
Definition at line 28 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
sTexDir
std::string Core::_SpriteSys::sTexDir private
Definition at line 28 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
texture
Texture Core::_SpriteSys::texture private
Definition at line 23 of file SpriteSys.h.
uiNumTextures
uint Core::_SpriteSys::uiNumTextures private
Definition at line 26 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
uiRecordSize
uint Core::_SpriteSys::uiRecordSize private
Definition at line 26 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
vao
VAO Core::_SpriteSys::vao private
Definition at line 24 of file SpriteSys.h.
Referenced by calc(), and draw().
The documentation for this class was generated from the following file:
src/headers/gamesys/SpriteSys.h