Project Parsec: _Admin Class Reference
_Admin Class Reference
#include <runAdmin.h>
Classes
struct t_AutoPos
Public Member Functions
_Admin (_Game *gamePtr)
void init ()
void initSkillTree ()
void initColors ()
void run ()
Public Attributes
bool bInit
Private Types
enum eADMIN_MENU {
ADMIN_MAIN, ADMIN_GAMESTATE, ADMIN_TIMERS, ADMIN_SCREEN,
SCREEN_BLUR, SCREEN_STEREO, ADMIN_RENDER, ADMIN_FONT,
FONT_COLOR_1, FONT_COLOR_2, FONT_COLOR_3, FONT_COLOR_4,
ADMIN_TRANSFORM, ADMIN_GAMETIME, ADMIN_ATMOSPHERE, ATMOSPHERE_SUN,
ATMOSPHERE_MOON, ATMOSPHERE_RAIN, ATMOSPHERE_SNOW, ATMOSPHERE_HAIL,
ATMOSPHERE_FLORA, ATMOSPHERE_UWFLORA, ATMOSPHERE_GRASS, ATMOSPHERE_WATER,
ADMIN_CONTROLS, CONTROLS_MOUSE, CONTROLS_KEYBOARD, CONTROLS_WORLDMENU,
CONTROLS_JOURNAL, CONTROLS_BATTLESCROLL, CONTROLS_GRIMOIRE, CONTROLS_VORNICHT,
CONTROLS_SKILLWHEEL, CONTROLS_FKEYS, ADMIN_CHARSHEET, CHARSHEET_SHEET1,
CHARSHEET_SHEET2, CHARSHEET_DAMAGE, CHARSHEET_MAGIC, ADMIN_SHADER,
ADMIN_DIR, ADMIN_SIZE, ADMIN_DEBUG
}
Private Member Functions
void ProcessInput ()
void GetInput ()
void draw ()
Private Attributes
_Game * game
Core::_Keyboard keyboard
GLenum eMenu
std::string command
bool bOneShot [ONESHOTS]
bool bHasFocus
bool bFirstRun
int iBy
int iVx
int iTx
struct _Admin::t_AutoPos AutoPos
Static Private Attributes
static const int ONESHOTS = 64
Detailed Description
This class is a primary game class that runs when the admin menu is opened. It opens on top of all other systems but allows other systems to still run. This allows variables to be adjusted when the game world is still being drawn allowing real-time feedback of things such as the terrain generator.
Definition at line 26 of file runAdmin.h.
Member Enumeration Documentation
eADMIN_MENU
enum _Admin::eADMIN_MENU private
Enumerator
ADMIN_MAIN
ADMIN_GAMESTATE
ADMIN_TIMERS
ADMIN_SCREEN
SCREEN_BLUR
SCREEN_STEREO
ADMIN_RENDER
ADMIN_FONT
FONT_COLOR_1
FONT_COLOR_2
FONT_COLOR_3
FONT_COLOR_4
ADMIN_TRANSFORM
ADMIN_GAMETIME
ADMIN_ATMOSPHERE
ATMOSPHERE_SUN
ATMOSPHERE_MOON
ATMOSPHERE_RAIN
ATMOSPHERE_SNOW
ATMOSPHERE_HAIL
ATMOSPHERE_FLORA
ATMOSPHERE_UWFLORA
ATMOSPHERE_GRASS
ATMOSPHERE_WATER
ADMIN_CONTROLS
CONTROLS_MOUSE
CONTROLS_KEYBOARD
CONTROLS_WORLDMENU
CONTROLS_JOURNAL
CONTROLS_BATTLESCROLL
CONTROLS_GRIMOIRE
CONTROLS_VORNICHT
CONTROLS_SKILLWHEEL
CONTROLS_FKEYS
ADMIN_CHARSHEET
CHARSHEET_SHEET1
CHARSHEET_SHEET2
CHARSHEET_DAMAGE
CHARSHEET_MAGIC
ADMIN_SHADER
ADMIN_DIR
ADMIN_SIZE
ADMIN_DEBUG
Definition at line 30 of file runAdmin.h.
Constructor & Destructor Documentation
_Admin()
_Admin::_Admin (_Game * gamePtr)
Definition at line 190 of file runAdmin.h.
References bFirstRun, bHasFocus, bInit, bOneShot, Core::_Keyboard::calc(), game, keyboard, Core::_Keyboard::KEYTYPE_ONESHOT, and ONESHOTS.
Member Function Documentation
draw()
void _Admin::draw () private
Definition at line 2026 of file runAdmin.h.
GetInput()
void _Admin::GetInput () private
Definition at line 1913 of file runAdmin.h.
References bFirstRun, bHasFocus, Core::_Keyboard::event, Core::gameVars, Core::GameVars::Screen::half, keyboard, Core::mouse, ProcessInput(), Core::GameVars::screen, Core::_Mouse::update(), Core::_Keyboard::update(), and Core::Vector2f::y.
Referenced by run().
init()
void _Admin::init ()
Definition at line 215 of file runAdmin.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::Props::autoHeight(), Core::GUI::Props::autoWidth(), Core::GUI::Props_Window::Colors::back, Core::GUI::Props_Label::Colors::back(), Core::GUI::Props_Field::Colors::back(), Core::GUI::GUI_ColorB::base, Core::GUI::Props::bGlobalSettings, bInit, bOneShot, Core::GUI::Props_Field::Colors::border(), Core::GUI::Props_Window::borderNormal, Core::Vector4i::bottom, Core::GUI::Props::ToolTip::bShowGlobal, Core::GameVars::_Debug::_gui::buffer, Core::GUI::BUTTON_ONESHOT, Core::GUI::BUTTON_TOGGLE, Core::GUI::Props_Window::color, Core::GUI::Props_Label::color, Core::GUI::Props_Field::color, Core::colors, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_BOTTOM_LEFT, Core::GUI::CONSTRAIN_BOTTOM_RIGHT, Core::GUI::CONSTRAIN_CENTER, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, Core::GUI::CONSTRAIN_TOP, Core::GUI::CONSTRAIN_TOP_LEFT, Core::GUI::CONSTRAIN_TOP_RIGHT, Core::GUI::Props::_Size::constraint, Core::GUI::Props_Slider::control, cout, Core::GameVars::debug, Core::GUI::Props::disablePadding(), Core::GUI::Props_Window::disableScissor(), Core::GUI::Props_ProgressBar::empty, Core::GUI::Props::enablePadding(), Core::GUI::Props::enableToolTip(), Core::GUI::Props_Addon_Field::field, Core::GUI::Props_ProgressBar::field, Core::GUI::Props_ProgressBar::fill, game, Core::gameVars, Core::_Lights::GetDir(), Core::_Lights::GetPos(), Core::GameVars::_Debug::gui, MY_NAMESPACE::gui, Core::GUI::Props::ToolTip::hideDelay, Core::GUI::Props_Addon_Label::hideLabel(), Core::GUI::GUI_ColorH::highlight, Core::GameVars::_Debug::_Noise::iCurrentFractal, Core::GameVars::_Debug::_Noise::iCurrentSimplex, _Game::iDebugLight, Core::GUI::Props_Addon_Label::label, Core::Vector4i::left, Core::GameSys::_WorldMap::lights, Core::GUI::Props::modPos(), Core::GameVars::_Debug::noise, Core::GUI::PADDING_ALL, Core::GUI::PADDING_POSITION, Core::GUI::Props_Window::radius, Core::Vector4i::right, Core::GUI::Props_Window::roundBorder, Core::GUI::Props::setAnchor(), Core::GUI::Props_Window::setBorder(), Core::GUI::Props_TextArea::setBuffer(), Core::GUI::Props_Button::setButtonType(), Core::GUI::Props_Icon::setButtonType(), Core::GUI::Props_Addon_Group::setGroup(), Core::GUI::Props::setHeight(), Core::GUI::Props_Icon::setIconIDs(), Core::GUI::Props_Icon::setImage(), Core::GUI::Props_Sprite::setImage(), Core::GUI::Props_Slider::setMinMax(), Core::GUI::Props::setMinMaxWidth(), Core::GUI::Props::setMinWidth(), Core::GUI::Props_Addon_ReturnState::setOnState(), Core::GUI::Props::setOrigin(), Core::GUI::Props::setPadding(), Core::GUI::Props_TextArea::setPadding(), Core::GUI::Props::setPos(), Core::GUI::Props_Slider::setPrecision(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props_Slider::setStep(), Core::GUI::Props_Addon_Stipple::setStipple(), Core::GUI::Props_Addon_Stipple::setStipplePattern(), Core::GUI::Props::setToolTip(), Core::GUI::Props::setVisibility(), Core::GUI::Props::setWidth(), Core::GUI::Props::setX(), Core::GUI::Props::setY(), Core::GUI::Props_Addon_Background::showBackground(), Core::GUI::Props_Label::showBackground(), Core::GUI::Props::ToolTip::showDelay, Core::GUI::Props_Addon_Field::showField(), Core::GUI::Props_Addon_Label::showLabel(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::SIZE_CONSTRAINT_RELATIVE, Core::GUI::Props_Addon_Slider::slider, Core::stipple, Core::GUI::Props_Slider::swapOrientation(), Core::Vector4i::top, Core::GUI::Props::vPadding, _Game::world, Core::Vector2f::x, Core::Vector3f::x, Core::Vector2f::y, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by main().
initColors()
void _Admin::initColors ()
Definition at line 11 of file Colors.h.
References _Admin::t_AutoPos::AddX(), _Admin::t_AutoPos::AddY(), AutoPos, Core::colors, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_TOP, MY_NAMESPACE::gui, Core::GUI::Props_Addon_Label::hideLabel(), Core::GUI::Props_Addon_Slider::hideSlider(), _Admin::t_AutoPos::pos, Core::GUI::Props::setAnchor(), Core::GUI::Props_Window::setBorder(), Core::GUI::Props::setHeight(), Core::GUI::Props::setOrigin(), Core::GUI::Props::setPadding(), Core::GUI::Props::setPos(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props::setToolTip(), Core::GUI::Props::setWidth(), _Admin::t_AutoPos::SetX(), _Admin::t_AutoPos::SetY(), Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::Props_Addon_Slider::slider, _Admin::t_AutoPos::x, x, and y.
initSkillTree()
void _Admin::initSkillTree ()
Definition at line 11 of file SkillTree.h.
References Core::GUI::BUTTON_ONESHOT, Core::GUI::BUTTON_TOGGLE, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_BOTTOM_LEFT, Core::GUI::CONSTRAIN_BOTTOM_RIGHT, MY_NAMESPACE::gui, Core::GUI::Props::setAnchor(), Core::GUI::Props_Window::setBorder(), Core::GUI::Props_Button::setButtonType(), Core::GUI::Props::setHeight(), Core::GUI::Props::setOrigin(), Core::GUI::Props::setPos(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props::setWidth(), and Core::GUI::SIZE_CONSTRAINT_ABSOLUTE.
ProcessInput()
void _Admin::ProcessInput () private
Definition at line 1935 of file runAdmin.h.
References Core::GameVars::RunState::admin, Core::gameVars, keyboard, Core::_Keyboard::keys, Core::mouse, Core::GameVars::RunState::quit, Core::GameVars::runState, and Core::_Mouse::ToggleMouse().
Referenced by GetInput().
run()
void _Admin::run ()
Definition at line 1697 of file runAdmin.h.
References Core::GameVars::_Debug::_gui::b2, Core::GameVars::_Debug::_gui::b3, Core::GameVars::_Debug::_gui::b4, Core::GUI::Props::bGlobalSettings, bHasFocus, bInit, cout, Core::GameSys::_O3D::data, Core::GameVars::debug, Core::GameVars::font, game, Core::gameVars, Core::_Lights::GetDir(), GetInput(), Core::_Lights::GetPos(), GL_DEPTH_BUFFER_BIT, GL_TRUE, Core::GameVars::_Debug::gui, MY_NAMESPACE::gui, Core::GameVars::_Debug::_Noise::iCurrentSimplex, _Game::iDebugLight, _Game::iDebugObject, Core::GameSys::_O3D::_O3DCollection::items, Core::GameSys::_WorldMap::lights, Core::GameSys::_WorldMap::map, Core::GameVars::_Debug::noise, Core::GameSys::_WorldMap::o3d, Core::GameSys::_O3DData::posMod, Core::GameSys::_O3DData::rotMod, Core::stipple, to_string(), Core::GameSys::MapSys::update(), Core::GameVars::Font::update(), _Game::world, Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by main().
Member Data Documentation
AutoPos
struct _Admin::t_AutoPos _Admin::AutoPos private
Referenced by initColors().
bFirstRun
bool _Admin::bFirstRun private
Definition at line 82 of file runAdmin.h.
Referenced by _Admin(), and GetInput().
bHasFocus
bool _Admin::bHasFocus private
Definition at line 81 of file runAdmin.h.
Referenced by _Admin(), GetInput(), and run().
bInit
bool _Admin::bInit
Definition at line 187 of file runAdmin.h.
Referenced by _Admin(), init(), and run().
bOneShot
bool _Admin::bOneShot[ONESHOTS] private
Definition at line 80 of file runAdmin.h.
Referenced by _Admin(), and init().
command
std::string _Admin::command private
Definition at line 78 of file runAdmin.h.
eMenu
GLenum _Admin::eMenu private
Definition at line 77 of file runAdmin.h.
game
_Game* _Admin::game private
Definition at line 74 of file runAdmin.h.
Referenced by _Admin(), init(), and run().
iBy
int _Admin::iBy private
Definition at line 83 of file runAdmin.h.
iTx
int _Admin::iTx private
Definition at line 85 of file runAdmin.h.
iVx
int _Admin::iVx private
Definition at line 84 of file runAdmin.h.
keyboard
Core::_Keyboard _Admin::keyboard private
Definition at line 75 of file runAdmin.h.
Referenced by _Admin(), GetInput(), and ProcessInput().
ONESHOTS
const int _Admin::ONESHOTS = 64 static private
Definition at line 79 of file runAdmin.h.
Referenced by _Admin().
The documentation for this class was generated from the following files:
src/game/runAdmin.h
src/game/runAdmin/Colors.h
src/game/runAdmin/SkillTree.h