Project Parsec: Core::GameSys::_O3D Class Reference
Core::GameSys::_O3D Class Reference
#include <O3D.h>
Classes
struct _O3DCollection
Public Member Functions
bool init ()
bool load ()
bool calc ()
void draw (SHADER_PROGRAMS iShader, Core::_Lights &lights)
_O3D (Matrix_System &m, Shader_System &s, _Collision &c, _Helper &h)
~_O3D ()
Public Attributes
struct Core::GameSys::_O3D::_O3DCollection data
Private Attributes
Matrix_System * matrix
Shader_System * shader
_Collision * collision
_Helper * helper
uint uiRecordSize
std::string sFileDir
std::string sTexDir
Detailed Description
Definition at line 90 of file O3D.h.
Constructor & Destructor Documentation
_O3D()
Core::GameSys::_O3D::_O3D (Matrix_System & m, Shader_System & s, _Collision & c, _Helper & h) inline
Definition at line 125 of file O3D.h.
References collision, h, helper, sFileDir, sTexDir, and uiRecordSize.
~_O3D()
Core::GameSys::_O3D::~_O3D () inline
Definition at line 137 of file O3D.h.
References cout.
Member Function Documentation
calc()
bool _O3D::calc ()
Definition at line 248 of file O3D.h.
References cout, Core::GameVars::Screen::fScale, Core::gameVars, GL_TRIANGLES, Core::GLA_INDEX, Core::GLA_NORMAL, Core::GLA_TEXTURE, Core::GLA_VERTEX, Core::PLY_Loader::load(), Core::PLY_Loader::numDrawVerts, Core::PLY_Loader::numVerts, Core::GameVars::screen, sFileDir, Core::sOffset, Core::Degrees::toRadians(), Core::PLY_Loader::vCoords, Core::PLY_Loader::vIndex, Core::PLY_Loader::vNorms, Core::PLY_Loader::vVerts, Core::Vector4f::x, Core::Vector4f::y, and Core::Vector4f::z.
Referenced by Core::GameSys::_WorldMap::calc().
draw()
void _O3D::draw (SHADER_PROGRAMS iShader, Core::_Lights & lights)
Definition at line 374 of file O3D.h.
References Core::GameVars::Player::active, Core::_Collision::bUpdateRequest, collision, Core::colors, Core::_Helper::drawLine(), Core::_Helper::drawPosition(), Core::gameVars, GL_CULL_FACE, GL_FILL, GL_FRONT_AND_BACK, GL_LINES, GL_TEXTURE0, Core::GLM_DRAW_ELEMENTS, Core::GLS_LINES, helper, Core::mouse, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::_Collision::Ray(), Core::Degrees::toRadians(), and Core::GameSys::CharSheet::transform.
Referenced by Core::GameSys::_WorldMap::draw().
init()
bool _O3D::init ()
Definition at line 146 of file O3D.h.
References cout, and Core::sOffset.
load()
bool _O3D::load ()
Definition at line 152 of file O3D.h.
References Core::MemBlock::buffer, cout, Core::readFile(), Core::MemBlock::size, Core::sOffset, sTexDir, and uiRecordSize.
Referenced by Core::GameSys::_WorldMap::load().
Member Data Documentation
collision
_Collision* Core::GameSys::_O3D::collision private
Definition at line 94 of file O3D.h.
Referenced by _O3D(), and draw().
data
struct Core::GameSys::_O3D::_O3DCollection Core::GameSys::_O3D::data
Referenced by _Game::load(), _Game::ProcessInput(), and _Admin::run().
helper
_Helper* Core::GameSys::_O3D::helper private
Definition at line 95 of file O3D.h.
Referenced by _O3D(), and draw().
matrix
Matrix_System* Core::GameSys::_O3D::matrix private
Definition at line 92 of file O3D.h.
sFileDir
std::string Core::GameSys::_O3D::sFileDir private
Definition at line 98 of file O3D.h.
Referenced by _O3D(), and calc().
shader
Shader_System* Core::GameSys::_O3D::shader private
Definition at line 93 of file O3D.h.
sTexDir
std::string Core::GameSys::_O3D::sTexDir private
Definition at line 99 of file O3D.h.
Referenced by _O3D(), and load().
uiRecordSize
uint Core::GameSys::_O3D::uiRecordSize private
Definition at line 97 of file O3D.h.
Referenced by _O3D(), and load().
The documentation for this class was generated from the following file:
src/headers/gamesys/O3D.h