Project Parsec: RunJournal Class Reference
RunJournal Class Reference
#include <runJournal.h>
Public Member Functions
RunJournal ()
bool init ()
bool load ()
void run ()
Protected Member Functions
void toggle (bool &myBool)
void getInput ()
void processInput ()
void update ()
void draw ()
Private Types
enum MENUSTATES {
TAB1, TAB2, TAB3, TAB4,
TAB5, TAB6, TAB7, TAB8,
TAB9, TAB10, TAB11, TAB12
}
Private Member Functions
void changeTab (MENUSTATES m)
void close ()
Private Attributes
int menuState
int iInvStart
Keyboard keyboard
bool bShowMouse
bool bOpen
Detailed Description
Definition at line 11 of file runJournal.h.
Member Enumeration Documentation
MENUSTATES
enum RunJournal::MENUSTATES private
Enumerator
TAB1
TAB2
TAB3
TAB4
TAB5
TAB6
TAB7
TAB8
TAB9
TAB10
TAB11
TAB12
Definition at line 13 of file runJournal.h.
Constructor & Destructor Documentation
RunJournal()
RunJournal::RunJournal ()
Definition at line 58 of file runJournal.h.
References bOpen, bShowMouse, iInvStart, keyboard, menuState, and TAB2.
Member Function Documentation
changeTab()
void RunJournal::changeTab (MENUSTATES m) inline private
Definition at line 96 of file runJournal.h.
References Core::GameVars::Player::active, cout, Core::gameVars, iInvStart, menuState, and Core::GameVars::player.
Referenced by run().
close()
void RunJournal::close () private
Definition at line 88 of file runJournal.h.
References bOpen, Core::gameVars, and Core::GameVars::screen.
Referenced by processInput().
draw()
void RunJournal::draw () protected
Definition at line 2815 of file runJournal.h.
getInput()
void RunJournal::getInput () protected
Definition at line 2686 of file runJournal.h.
References Core::GameVars::Player::active, Core::GameVars::controls, Core::GameVars::debug, Core::gameVars, iInvStart, keyboard, Core::GameVars::player, processInput(), and Core::GameVars::screen.
Referenced by run().
init()
bool RunJournal::init ()
Definition at line 80 of file runJournal.h.
load()
bool RunJournal::load ()
Definition at line 84 of file runJournal.h.
processInput()
void RunJournal::processInput () protected
Definition at line 2752 of file runJournal.h.
References Core::GameVars::Player::active, close(), Core::GameVars::controls, Core::gameVars, iInvStart, keyboard, and Core::GameVars::player.
Referenced by getInput().
run()
void RunJournal::run ()
Definition at line 107 of file runJournal.h.
References Core::GameVars::Player::active, bOpen, changeTab(), Core::GameVars::Screen::clear, cout, Core::GameVars::font, Core::gameVars, getInput(), GL_TRUE, iInvStart, Core::itoa(), menuState, Core::GameVars::player, Core::GameVars::screen, Core::GameVars::Player::sheet, TAB1, TAB10, TAB11, TAB12, TAB2, TAB3, TAB4, TAB5, TAB6, TAB7, TAB8, TAB9, update(), _TheVoid::Update(), Core::GameVars::Font::vMax, Core::GameVars::Font::vSize, and world.
toggle()
void RunJournal::toggle (bool & myBool) protected
Definition at line 2819 of file runJournal.h.
update()
void RunJournal::update () protected
Definition at line 2676 of file runJournal.h.
References bShowMouse, Core::GameVars::controls, and Core::gameVars.
Referenced by run().
Member Data Documentation
bOpen
bool RunJournal::bOpen private
Definition at line 19 of file runJournal.h.
Referenced by close(), run(), and RunJournal().
bShowMouse
bool RunJournal::bShowMouse private
Definition at line 17 of file runJournal.h.
Referenced by RunJournal(), and update().
iInvStart
int RunJournal::iInvStart private
Definition at line 15 of file runJournal.h.
Referenced by changeTab(), getInput(), processInput(), run(), and RunJournal().
keyboard
Keyboard RunJournal::keyboard private
Definition at line 16 of file runJournal.h.
Referenced by getInput(), processInput(), and RunJournal().
menuState
int RunJournal::menuState private
Definition at line 14 of file runJournal.h.
Referenced by changeTab(), run(), and RunJournal().
The documentation for this class was generated from the following file:
src/game/ref/runJournal.h