Project Parsec: Core::GUI::GUI_Container::FieldInterface Class Reference
Core::GUI::GUI_Container::FieldInterface Class Reference
#include <GUI_Container.h>
Public Member Functions
template<typename T >
void add (std::string fieldName, T *ptr, Props_Field c, Props *p=nullptr)
template<typename T >
void add (std::string fieldName, T *ptr, Props_Field *c, Props *p=nullptr)
Props_Field * get (std::string fieldName)
Object::AnyField & operator[] (std::string fieldName)
FieldInterface (GUI_Container *parent)
~FieldInterface ()
Private Member Functions
void pushData (std::string name, Object::AnyField *data)
Private Attributes
std::vector< Object::AnyField * > fields
Map_si map
GUI_Container * gui
Friends
class GUI_Container
Detailed Description
Definition at line 143 of file GUI_Container.h.
Constructor & Destructor Documentation
FieldInterface()
Core::GUI::GUI_Container::FieldInterface::FieldInterface (GUI_Container * parent) inline
Definition at line 158 of file GUI_Container.h.
References gui, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
~FieldInterface()
Core::GUI::GUI_Container::FieldInterface::~FieldInterface () inline
Definition at line 159 of file GUI_Container.h.
References fields.
Member Function Documentation
add() [1/2]
template<typename T > void Core::GUI::GUI_Container::FieldInterface::add (std::string fieldName, T * ptr, Props_Field * c, Props * p = nullptr)
Definition at line 508 of file GUI_Container.h.
References MY_NAMESPACE::gui, Core::GUI::GUI_Container::pushData(), and Core::GUI::Object::AnyField::set().
add() [2/2]
template<typename T > void Core::GUI::GUI_Container::FieldInterface::add (std::string fieldName, T * ptr, Props_Field c, Props * p = nullptr)
Definition at line 501 of file GUI_Container.h.
References MY_NAMESPACE::gui, Core::GUI::GUI_Container::pushData(), and Core::GUI::Object::AnyField::set().
get()
Props_Field* Core::GUI::GUI_Container::FieldInterface::get (std::string fieldName)
operator[]()
Object::AnyField& Core::GUI::GUI_Container::FieldInterface::operator[] (std::string fieldName) inline
Definition at line 156 of file GUI_Container.h.
References fields, and map.
pushData()
void Core::GUI::GUI_Container::FieldInterface::pushData (std::string name, Object::AnyField * data) private
Definition at line 494 of file GUI_Container.h.
References Core::GUI::GUI_Container::map.
Friends And Related Function Documentation
GUI_Container
friend class GUI_Container friend
Definition at line 144 of file GUI_Container.h.
Member Data Documentation
fields
std::vector<Object::AnyField*> Core::GUI::GUI_Container::FieldInterface::fields private
Definition at line 146 of file GUI_Container.h.
Referenced by Core::GUI::GUI_Container::execObjects(), Core::GUI::GUI_Container::execToolTips(), operator[](), and ~FieldInterface().
gui
GUI_Container* Core::GUI::GUI_Container::FieldInterface::gui private
Definition at line 148 of file GUI_Container.h.
Referenced by FieldInterface().
map
Map_si Core::GUI::GUI_Container::FieldInterface::map private
Definition at line 147 of file GUI_Container.h.
Referenced by operator[]().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Container.h