Project Parsec: Core::GUI::GUI_Container::TextEditInterface Class Reference
Core::GUI::GUI_Container::TextEditInterface Class Reference
#include <GUI_Container.h>
Public Member Functions
void add (std::string textEditName, Props_TextArea c, Props *p=nullptr)
void add (std::string textEditName, Props_TextArea *c, Props *p=nullptr)
Object::TextEdit & operator[] (std::string textEditName)
Props_TextArea & operator() (std::string textEditName)
TextEditInterface (GUI_Container *parent)
~TextEditInterface ()
Private Member Functions
void pushData (std::string name, Object::TextEdit *data)
Private Attributes
std::vector< Object::TextEdit * > textEdits
Map_si map
GUI_Container * gui
Friends
class GUI_Container
Detailed Description
Definition at line 182 of file GUI_Container.h.
Constructor & Destructor Documentation
TextEditInterface()
Core::GUI::GUI_Container::TextEditInterface::TextEditInterface (GUI_Container * parent) inline
Definition at line 196 of file GUI_Container.h.
References gui, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
~TextEditInterface()
Core::GUI::GUI_Container::TextEditInterface::~TextEditInterface () inline
Definition at line 197 of file GUI_Container.h.
References textEdits.
Member Function Documentation
add() [1/2]
void Core::GUI::GUI_Container::TextEditInterface::add (std::string textEditName, Props_TextArea * c, Props * p = nullptr)
Definition at line 561 of file GUI_Container.h.
References MY_NAMESPACE::gui, Core::GUI::Object::TextEdit::init(), and Core::GUI::GUI_Container::pushData().
add() [2/2]
void Core::GUI::GUI_Container::TextEditInterface::add (std::string textEditName, Props_TextArea c, Props * p = nullptr)
Definition at line 553 of file GUI_Container.h.
References MY_NAMESPACE::gui, Core::GUI::Object::TextEdit::init(), and Core::GUI::GUI_Container::pushData().
operator()()
Props_TextArea& Core::GUI::GUI_Container::TextEditInterface::operator() (std::string textEditName) inline
Definition at line 195 of file GUI_Container.h.
References Core::GUI::Object::Base::Generic< Props_Window >::con, map, and textEdits.
operator[]()
Object::TextEdit& Core::GUI::GUI_Container::TextEditInterface::operator[] (std::string textEditName) inline
Definition at line 194 of file GUI_Container.h.
References map, and textEdits.
pushData()
void Core::GUI::GUI_Container::TextEditInterface::pushData (std::string name, Object::TextEdit * data) private
Definition at line 546 of file GUI_Container.h.
References Core::GUI::GUI_Container::map.
Friends And Related Function Documentation
GUI_Container
friend class GUI_Container friend
Definition at line 183 of file GUI_Container.h.
Member Data Documentation
gui
GUI_Container* Core::GUI::GUI_Container::TextEditInterface::gui private
Definition at line 187 of file GUI_Container.h.
Referenced by TextEditInterface().
map
Map_si Core::GUI::GUI_Container::TextEditInterface::map private
Definition at line 186 of file GUI_Container.h.
Referenced by operator()(), and operator[]().
textEdits
std::vector<Object::TextEdit*> Core::GUI::GUI_Container::TextEditInterface::textEdits private
Definition at line 185 of file GUI_Container.h.
Referenced by Core::GUI::GUI_Container::execObjects(), operator()(), operator[](), and ~TextEditInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Container.h