Project Parsec: Core::GameSys::MapSys Class Reference
Core::GameSys::MapSys Class Reference
#include <MapSys.h>
Classes
struct _MapSysData
Public Member Functions
MapSys ()
~MapSys ()
bool init ()
bool load ()
bool calc ()
void update ()
void draw (Core::SHADER_PROGRAMS iShader, Core::_Lights &lights)
double getPerlinElevation (float x, float z, float w, float h)
double getPerlinMoisture (float x, float z, float w, float h)
double getSimplexElevation (float x, float z)
double getSimplexElevation (float x, float z, float freq, float amp, float lac, float per, int oct)
double getFractalElevation (float x, float z)
Public Attributes
struct Core::GameSys::MapSys::_MapSysData data
std::string dir
VAO ** mapData
MapData terrainChunk [4]
Texture tex
Private Types
enum eTerrainType { TERRAIN_FLAT, TERRAIN_PERLIN, TERRAIN_SIMPLEX, TERRAIN_FRACTAL }
Private Member Functions
void generateTerrainChunk (MapData &map, float SIZE, int VERTEX_COUNT, eTerrainType eType=TERRAIN_PERLIN, int iTexScale=1, float fHeightOffset=0.0f)
double noise1 (double nx, double ny)
double noise2 (double nx, double ny)
double noise3 (double nx, double ny)
Private Attributes
unsigned seed1 = 42
unsigned seed2 = 1024
unsigned seed3 = 420
std::minstd_rand0 rng1
std::minstd_rand0 rng2
std::minstd_rand0 rng3
noise::module::Perlin gen1
noise::module::Perlin gen2
noise::module::Perlin gen3
const eTerrainType TERRAIN_TYPE = TERRAIN_SIMPLEX
Detailed Description
Definition at line 90 of file MapSys.h.
Member Enumeration Documentation
eTerrainType
enum Core::GameSys::MapSys::eTerrainType private
Enumerator
TERRAIN_FLAT
TERRAIN_PERLIN
TERRAIN_SIMPLEX
TERRAIN_FRACTAL
Definition at line 92 of file MapSys.h.
Constructor & Destructor Documentation
MapSys()
Core::GameSys::MapSys::MapSys () inline
Definition at line 148 of file MapSys.h.
References mapData.
~MapSys()
Core::GameSys::MapSys::~MapSys () inline
Definition at line 153 of file MapSys.h.
References cout, and mapData.
Member Function Documentation
calc()
bool Core::GameSys::MapSys::calc ()
Definition at line 605 of file MapSys.h.
References Core::VAO::Begin(), Core::VAO::CopyData(), cout, Core::VAO::End(), GL_TRIANGLES, Core::GLA_INDEX, Core::GLA_NORMAL, Core::GLA_TEXTURE, Core::GLA_VERTEX, mapData, Core::sOffset, and terrainChunk.
Referenced by Core::GameSys::_WorldMap::calc().
draw()
void Core::GameSys::MapSys::draw (Core::SHADER_PROGRAMS iShader, Core::_Lights & lights)
Definition at line 1088 of file MapSys.h.
References Core::GameVars::Player::active, Core::VAO::Draw(), Core::GameVars::Screen::fScale, Core::gameVars, GL_CULL_FACE, GL_FILL, GL_FRONT_AND_BACK, GL_TEXTURE0, Core::GLM_DRAW_ELEMENTS, Core::GLS_NORMAL_LINE2, mapData, Core::matrix, Core::GameVars::player, Core::Matrix_System::Pop(), Core::GameSys::CharSheet::Transform::pos, Core::Matrix_System::Push(), Core::Matrix_System::Scale(), Core::GameVars::screen, Core::_SystemTextures::set(), Core::sysTex, and Core::GameSys::CharSheet::transform.
Referenced by Core::GameSys::_WorldMap::draw().
generateTerrainChunk()
void Core::GameSys::MapSys::generateTerrainChunk (MapData & map, float SIZE, int VERTEX_COUNT, eTerrainType eType = TERRAIN_PERLIN, int iTexScale = 1, float fHeightOffset = 0.0f) private
Definition at line 451 of file MapSys.h.
References A, B, Core::_gmath::Cross(), Core::GameVars::debug, Core::GameVars::_Debug::_Noise::_Simplex::delta, Core::GameVars::_Debug::_Noise::_Fractal::delta, Core::GameVars::_Debug::_Noise::fractal, Core::gameVars, getFractalElevation(), getPerlinElevation(), getSimplexElevation(), Core::gmath, Core::Vector3f::length(), Core::GameVars::_Debug::noise, Core::GameSys::MapData::numDrawVerts, Core::GameSys::MapData::numVerts, Core::GameVars::_Debug::_Noise::simplex, TERRAIN_FRACTAL, TERRAIN_PERLIN, TERRAIN_SIMPLEX, Core::GameSys::MapData::vCoords, Core::GameSys::MapData::vIndex, Core::GameSys::MapData::vNorms, Core::GameSys::MapData::vVerts, Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by load(), and update().
getFractalElevation()
double Core::GameSys::MapSys::getFractalElevation (float x, float z)
Definition at line 1045 of file MapSys.h.
References Core::GameVars::debug, Core::GameVars::_Debug::_Noise::fractal, Core::GameVars::_Debug::_Noise::_Fractal::frequency, Core::gameVars, Core::GameVars::_Debug::_Noise::iCurrentFractal, Core::GameVars::_Debug::_Noise::_Fractal::lacunarity, Core::GameVars::_Debug::_Noise::_Fractal::layers, Core::GameVars::_Debug::_Noise::_Fractal::multiplier, Core::GameVars::_Debug::noise, noise1(), and Core::GameVars::_Debug::_Noise::_Fractal::scale.
Referenced by generateTerrainChunk().
getPerlinElevation()
double Core::GameSys::MapSys::getPerlinElevation (float x, float z, float w, float h)
Definition at line 969 of file MapSys.h.
References Core::GameVars::debug, Core::gameVars, Core::GameVars::_Debug::noise, noise1(), Core::GameVars::_Debug::_Noise::_Perlin::octave1, Core::GameVars::_Debug::_Noise::_Perlin::octave2, Core::GameVars::_Debug::_Noise::_Perlin::octave3, Core::GameVars::_Debug::_Noise::_Perlin::octave4, Core::GameVars::_Debug::_Noise::_Perlin::octave5, Core::GameVars::_Debug::_Noise::_Perlin::octave6, Core::GameVars::_Debug::_Noise::perlin, Core::GameVars::_Debug::_Noise::_Perlin::power, and Core::GameVars::_Debug::_Noise::_Perlin::scale.
Referenced by generateTerrainChunk().
getPerlinMoisture()
double Core::GameSys::MapSys::getPerlinMoisture (float x, float z, float w, float h)
Definition at line 996 of file MapSys.h.
getSimplexElevation() [1/2]
double Core::GameSys::MapSys::getSimplexElevation (float x, float z)
Definition at line 1014 of file MapSys.h.
References Core::GameVars::_Debug::_Noise::_Simplex::amplitude, Core::GameVars::debug, SimplexNoise::fractal(), Core::GameVars::_Debug::_Noise::_Simplex::frequency, Core::gameVars, Core::GameVars::_Debug::_Noise::_Simplex::lacunarity, Core::GameVars::_Debug::noise, Core::GameVars::_Debug::_Noise::_Simplex::octaves, Core::GameVars::_Debug::_Noise::_Simplex::offset, Core::GameVars::_Debug::_Noise::_Simplex::persistance, Core::GameVars::_Debug::_Noise::_Simplex::power, Core::GameVars::_Debug::_Noise::_Simplex::scale, Core::GameVars::_Debug::_Noise::simplex, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by generateTerrainChunk().
getSimplexElevation() [2/2]
double Core::GameSys::MapSys::getSimplexElevation (float x, float z, float freq, float amp, float lac, float per, int oct)
init()
bool Core::GameSys::MapSys::init ()
Definition at line 236 of file MapSys.h.
References cout, gen1, gen2, gen3, mapData, rng1, rng2, rng3, seed1, seed2, seed3, and Core::sOffset.
Referenced by Core::GameSys::_WorldMap::_WorldMap().
load()
bool Core::GameSys::MapSys::load ()
Definition at line 322 of file MapSys.h.
References cout, Core::GameVars::debug, Core::GameVars::_Debug::_Noise::fractal, Core::gameVars, generateTerrainChunk(), Core::_Profile::getTime(), Core::GameVars::_Debug::_Noise::iCurrentFractal, Core::GameVars::_Debug::_Noise::iCurrentSimplex, Core::GameVars::_Debug::noise, Core::profiles, Core::GameVars::_Debug::_Noise::_Simplex::res, Core::GameVars::_Debug::_Noise::_Fractal::res, Core::GameVars::_Debug::_Noise::simplex, Core::sOffset, Core::_Profile::startProfile(), Core::_Profile::stopProfile(), TERRAIN_FRACTAL, Core::GameVars::_Debug::_Noise::_Simplex::terrain_height_offset, Core::GameVars::_Debug::_Noise::_Fractal::terrain_height_offset, TERRAIN_PERLIN, TERRAIN_SIMPLEX, TERRAIN_TYPE, terrainChunk, Core::GameVars::_Debug::_Noise::_Simplex::tex_scale, and Core::GameVars::_Debug::_Noise::_Fractal::tex_scale.
Referenced by Core::GameSys::_WorldMap::load().
noise1()
double Core::GameSys::MapSys::noise1 (double nx, double ny) inline private
Definition at line 110 of file MapSys.h.
References gen1.
Referenced by getFractalElevation(), and getPerlinElevation().
noise2()
double Core::GameSys::MapSys::noise2 (double nx, double ny) inline private
Definition at line 111 of file MapSys.h.
References gen2.
noise3()
double Core::GameSys::MapSys::noise3 (double nx, double ny) inline private
Definition at line 112 of file MapSys.h.
References gen3.
update()
void Core::GameSys::MapSys::update ()
Definition at line 896 of file MapSys.h.
References Core::VAO::Begin(), Core::VAO::CopyData(), Core::GameVars::debug, Core::VAO::End(), Core::GameVars::_Debug::_Noise::fractal, Core::gameVars, generateTerrainChunk(), GL_TRIANGLES, Core::GLA_INDEX, Core::GLA_NORMAL, Core::GLA_TEXTURE, Core::GLA_VERTEX, Core::GameVars::_Debug::_Noise::iCurrentFractal, Core::GameVars::_Debug::_Noise::iCurrentSimplex, mapData, Core::GameVars::_Debug::noise, Core::GameVars::_Debug::_Noise::_Simplex::res, Core::GameVars::_Debug::_Noise::_Fractal::res, Core::GameVars::_Debug::_Noise::simplex, TERRAIN_FRACTAL, Core::GameVars::_Debug::_Noise::_Simplex::terrain_height_offset, Core::GameVars::_Debug::_Noise::_Fractal::terrain_height_offset, TERRAIN_PERLIN, TERRAIN_SIMPLEX, TERRAIN_TYPE, terrainChunk, Core::GameVars::_Debug::_Noise::_Simplex::tex_scale, and Core::GameVars::_Debug::_Noise::_Fractal::tex_scale.
Referenced by _Admin::run().
Member Data Documentation
data
struct Core::GameSys::MapSys::_MapSysData Core::GameSys::MapSys::data
dir
std::string Core::GameSys::MapSys::dir
Definition at line 187 of file MapSys.h.
gen1
noise::module::Perlin Core::GameSys::MapSys::gen1 private
Definition at line 107 of file MapSys.h.
Referenced by init(), and noise1().
gen2
noise::module::Perlin Core::GameSys::MapSys::gen2 private
Definition at line 108 of file MapSys.h.
Referenced by init(), and noise2().
gen3
noise::module::Perlin Core::GameSys::MapSys::gen3 private
Definition at line 109 of file MapSys.h.
Referenced by init(), and noise3().
mapData
VAO** Core::GameSys::MapSys::mapData
Definition at line 191 of file MapSys.h.
Referenced by calc(), draw(), init(), MapSys(), update(), and ~MapSys().
rng1
std::minstd_rand0 Core::GameSys::MapSys::rng1 private
Definition at line 104 of file MapSys.h.
Referenced by init().
rng2
std::minstd_rand0 Core::GameSys::MapSys::rng2 private
Definition at line 105 of file MapSys.h.
Referenced by init().
rng3
std::minstd_rand0 Core::GameSys::MapSys::rng3 private
Definition at line 106 of file MapSys.h.
Referenced by init().
seed1
unsigned Core::GameSys::MapSys::seed1 = 42 private
Definition at line 101 of file MapSys.h.
Referenced by init().
seed2
unsigned Core::GameSys::MapSys::seed2 = 1024 private
Definition at line 102 of file MapSys.h.
Referenced by init().
seed3
unsigned Core::GameSys::MapSys::seed3 = 420 private
Definition at line 103 of file MapSys.h.
Referenced by init().
TERRAIN_TYPE
const eTerrainType Core::GameSys::MapSys::TERRAIN_TYPE = TERRAIN_SIMPLEX private
Definition at line 119 of file MapSys.h.
Referenced by load(), and update().
terrainChunk
MapData Core::GameSys::MapSys::terrainChunk[4]
Definition at line 192 of file MapSys.h.
Referenced by calc(), load(), and update().
tex
Texture Core::GameSys::MapSys::tex
Definition at line 193 of file MapSys.h.
The documentation for this class was generated from the following file:
src/headers/gamesys/MapSys.h