Project Parsec: _TheVoid Class Reference
_TheVoid Class Reference
#include <runVoid.h>
Classes
struct _Cybotron
struct _DomeLake
struct _Doom
struct _Earth
struct _Eclipse
struct _HugoForest
struct _Ink
struct _Intermost
struct _Oudermost
struct _Prime
struct _QuickSilver
struct _Sun
struct _TheChamber
struct _Twilight
Public Types
enum _MODES {
EARTH, PRIME, DOMELAKE, INK,
SUN, HUGOFOREST, QUICKSILVER, THECHAMBER,
ECLIPSE, DOOM, INTERMOST, OUDERMOST,
CYBOTRON, TWILIGHT
}
Public Member Functions
void Run ()
void reload ()
float GetHeight ()
void Update (bool bThirdPerson)
void Draw (bool bWater[2])
void Draw (bool bWater[2], bool bThirdPerson, bool bExosphere, bool bThermosphere, bool bSun, bool bMoon, bool bStratosphere, bool bTroposphere, bool bWorld)
_TheVoid ()
Public Attributes
O3D o3d
Atmosphere atmosphere
WorldMap map
_Player player
_NPC npc
struct _TheVoid::_Prime Prime
struct _TheVoid::_DomeLake DomeLake
struct _TheVoid::_Ink Ink
struct _TheVoid::_Sun Sun
struct _TheVoid::_HugoForest HugoForest
struct _TheVoid::_QuickSilver QuickSilver
struct _TheVoid::_TheChamber TheChamber
struct _TheVoid::_Eclipse Eclipse
struct _TheVoid::_Doom Doom
struct _TheVoid::_Intermost Intermost
struct _TheVoid::_Oudermost Oudermost
struct _TheVoid::_Cybotron Cybotron
struct _TheVoid::_Twilight Twilight
struct _TheVoid::_Earth Earth
Private Member Functions
void GetInput ()
void ProcessInput ()
void CheckChunk ()
void GetJump ()
void SetVoid (int mode)
bool load (int mode, int iX, int iZ, bool bUpdate)
void bindFBO ()
void unbindFBO ()
Private Attributes
Matrix44f mShadow
Keyboard keyboard
Water water
O2D o2d
E2D e2d
GLuint fboRefract [2]
int DEBUG_index1
int DEBUG_max1
int DEBUG_min1
int DEBUG_delta1
int DEBUG_index2
int DEBUG_max2
int DEBUG_min2
int DEBUG_delta2
bool DEBUG_WATER1
bool DEBUG_WATER2
float DEBUG_3PDISTANCE
bool DEBUG_3PENABLE
bool bFirstLoad
int iCurrentVoid
Detailed Description
Definition at line 11 of file runVoid.h.
Member Enumeration Documentation
_MODES
enum _TheVoid::_MODES
Enumerator
EARTH
PRIME
DOMELAKE
INK
SUN
HUGOFOREST
QUICKSILVER
THECHAMBER
ECLIPSE
DOOM
INTERMOST
OUDERMOST
CYBOTRON
TWILIGHT
Definition at line 49 of file runVoid.h.
Constructor & Destructor Documentation
_TheVoid()
_TheVoid::_TheVoid () inline
Definition at line 216 of file runVoid.h.
References keyboard.
Member Function Documentation
bindFBO()
void _TheVoid::bindFBO () inline private
Definition at line 43 of file runVoid.h.
References fboRefract, Core::gameVars, GL_FRAMEBUFFER, GL_TEXTURE_2D, and Core::GameVars::screen.
CheckChunk()
void _TheVoid::CheckChunk () private
Definition at line 616 of file runVoid.h.
References Core::GameVars::Player::active, Core::GameVars::debug, Core::gameVars, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, reload(), Core::GameVars::screen, and Core::GameSys::CharSheet::transform.
Referenced by Run().
Draw() [1/2]
void _TheVoid::Draw (bool bWater[2])
Definition at line 949 of file runVoid.h.
Referenced by Update().
Draw() [2/2]
void _TheVoid::Draw (bool bWater[2], bool bThirdPerson = false, bool bExosphere = true, bool bThermosphere = true, bool bSun = true, bool bMoon = true, bool bStratosphere = true, bool bTroposphere = true, bool bWorld = true)
Definition at line 953 of file runVoid.h.
References Core::GameVars::Player::active, atmosphere, Core::GameVars::Screen::clear, Core::GameVars::debug, DEBUG_3PDISTANCE, O2D_BASE::draw(), E2D_BASE::draw(), WorldMap::draw(), _NPC::draw(), e2d, Core::_Occlusion::EndQuery(), Core::gameVars, GL_CLIP_DISTANCE0, GL_DEPTH_TEST, Core::GLS_EXOSPHERE, Core::GLS_FLORA, Core::GLS_STRATOSPHERE, Core::GLS_SUN, Core::GLS_THERMOSPHERE, Core::GLS_TROPOSPHERE, map, npc, o2d, o3d, Core::occlusion, player, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::Timers::pTimer, Core::GameSys::CharSheet::Transform::rot, Core::GameVars::screen, Core::GameVars::Player::sheet, Core::PTimer::start(), Core::_Occlusion::StartQuery(), Core::PTimer::stop(), Core::GameVars::timer, and Core::GameSys::CharSheet::transform.
GetHeight()
float _TheVoid::GetHeight ()
GetInput()
void _TheVoid::GetInput () private
Definition at line 1295 of file runVoid.h.
References Core::GameVars::controls, Core::GameVars::debug, DEBUG_3PDISTANCE, DEBUG_3PENABLE, Core::gameVars, keyboard, ProcessInput(), and Core::GameVars::screen.
Referenced by Run().
GetJump()
void _TheVoid::GetJump () private
Definition at line 610 of file runVoid.h.
load()
bool _TheVoid::load (int mode, int iX, int iZ, bool bUpdate = false) private
Definition at line 263 of file runVoid.h.
References atmosphere, O2D::calc(), WorldMap::calc(), E2D::calc(), cout, Core::GameVars::debug, WorldMap::dir, _TheVoid::_Prime::dir, _TheVoid::_Earth::dir, e2d, EARTH, Earth, Core::gameVars, iCurrentVoid, O2D_BASE::init(), WorldMap::init(), O2D::load(), WorldMap::load(), E2D::load(), map, WorldMap::mapData, npc, o2d, o3d, PRIME, Prime, _NPC::reload(), WorldMap::reset(), Core::GameVars::screen, WorldMap::vBase, WorldMap::vStart, and water.
Referenced by _TheVoid::_Prime::load(), _TheVoid::_Twilight::load(), _TheVoid::_Earth::load(), and reload().
ProcessInput()
void _TheVoid::ProcessInput () private
Definition at line 1374 of file runVoid.h.
References Core::GameVars::Controls::_KeyBinding::activate, Core::GameVars::Player::active, atmosphere, Core::GameVars::controls, cout, _NPC::data, Core::GameVars::debug, DEBUG_delta1, DEBUG_index1, DEBUG_index2, DEBUG_max1, DEBUG_min1, DEBUG_WATER1, DEBUG_WATER2, e2d, E2D::execute(), Core::GameVars::Controls::fly, Core::gameVars, GL_FILL, GL_FRONT_AND_BACK, GL_LINE, GL_POINT, Core::GameVars::Controls::key, keyboard, Core::GameSys::CharSheet::Transform::last, Core::GameVars::Controls::modSpeed, Core::GameVars::Controls::_KeyBinding::mouse_down, Core::GameVars::Controls::_KeyBinding::mouse_left, Core::GameVars::Controls::_KeyBinding::mouse_right, Core::GameVars::Controls::_KeyBinding::mouse_up, Core::GameVars::Controls::_KeyBinding::move_back, Core::GameVars::Controls::_KeyBinding::move_down, Core::GameVars::Controls::_KeyBinding::move_forward, Core::GameVars::Controls::_KeyBinding::move_up, Core::GameVars::Controls::moveSpeed, npc, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::Timers::pTimer, _NPC::reload(), Core::PTimer::ResetMax(), Core::GameSys::CharSheet::Transform::rot, Core::GameVars::Controls::_KeyBinding::run, Core::GameVars::screen, Core::GameVars::Controls::_KeyBinding::sneak, Core::GameVars::Controls::_KeyBinding::strafe_left, Core::GameVars::Controls::_KeyBinding::strafe_right, Core::GameVars::timer, and Core::GameSys::CharSheet::transform.
Referenced by GetInput().
reload()
void _TheVoid::reload ()
Definition at line 633 of file runVoid.h.
References Core::GameVars::Player::active, Core::GameVars::debug, e2d, Core::gameVars, iCurrentVoid, load(), map, o2d, o3d, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::screen, O2D::shift(), WorldMap::shift(), E2D::shift(), Core::GameSys::CharSheet::transform, and WorldMap::vStart.
Referenced by CheckChunk().
Run()
void _TheVoid::Run ()
Definition at line 542 of file runVoid.h.
References Core::GameVars::Player::active, CheckChunk(), Core::GameVars::Screen::clear, Core::GameVars::controls, Core::GameVars::debug, DEBUG_3PENABLE, Core::GameVars::Controls::fly, Core::gameVars, WorldMap::getHeight(), GetInput(), map, player, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::screen, Core::GameSys::CharSheet::transform, Update(), and Core::GameVars::Screen::vClearColorCurrent.
SetVoid()
void _TheVoid::SetVoid (int mode) inline private
Definition at line 41 of file runVoid.h.
References iCurrentVoid.
unbindFBO()
void _TheVoid::unbindFBO () inline private
Definition at line 44 of file runVoid.h.
References Core::gameVars, GL_FRAMEBUFFER, GL_TEXTURE_2D, and Core::GameVars::screen.
Update()
void _TheVoid::Update (bool bThirdPerson)
Definition at line 843 of file runVoid.h.
References Core::GameVars::Player::active, Core::PostProcess::ApplyBrightness(), Core::PostProcess::ApplyCombine(), Core::PostProcess::ApplyContrast(), Core::PostProcess::ApplyHBlur(), Core::PostProcess::ApplyLensFlare(), Core::PostProcess::ApplyUnderwater(), Core::PostProcess::ApplyVBlur(), atmosphere, Core::PostProcess::bEnable, Core::GameVars::Screen::clear, DEBUG_WATER1, DEBUG_WATER2, Draw(), Core::PostProcess::EndRenderLayer(), Core::gameVars, GL_FILL, GL_FRONT_AND_BACK, GL_LINE, GL_POINT, Core::GameVars::Screen::MultiSample, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::postProcess, Core::GameVars::Timers::pTimer, Core::PostProcess::RenderLayer(), Core::PostProcess::RenderToScreen(), Core::GameVars::screen, Core::PTimer::start(), Core::PTimer::stop(), Core::GameVars::timer, Core::GameSys::CharSheet::transform, and world.
Referenced by RunBattle::draw(), RunEndBattle::run(), RunGrimoire::run(), RunBattleScroll::run(), RunMenu::run(), RunJournal::run(), Run(), RunBattle::RunMagic(), and RunConsole::update().
Member Data Documentation
atmosphere
Atmosphere _TheVoid::atmosphere
Definition at line 50 of file runVoid.h.
Referenced by Draw(), RunBattle::draw(), load(), ProcessInput(), runDebug(), and Update().
bFirstLoad
bool _TheVoid::bFirstLoad private
Definition at line 35 of file runVoid.h.
Cybotron
struct _TheVoid::_Cybotron _TheVoid::Cybotron
DEBUG_3PDISTANCE
float _TheVoid::DEBUG_3PDISTANCE private
Definition at line 32 of file runVoid.h.
Referenced by Draw(), and GetInput().
DEBUG_3PENABLE
bool _TheVoid::DEBUG_3PENABLE private
Definition at line 33 of file runVoid.h.
Referenced by GetInput(), and Run().
DEBUG_delta1
int _TheVoid::DEBUG_delta1 private
Definition at line 25 of file runVoid.h.
Referenced by ProcessInput().
DEBUG_delta2
int _TheVoid::DEBUG_delta2 private
Definition at line 29 of file runVoid.h.
DEBUG_index1
int _TheVoid::DEBUG_index1 private
Definition at line 22 of file runVoid.h.
Referenced by ProcessInput().
DEBUG_index2
int _TheVoid::DEBUG_index2 private
Definition at line 26 of file runVoid.h.
Referenced by ProcessInput().
DEBUG_max1
int _TheVoid::DEBUG_max1 private
Definition at line 23 of file runVoid.h.
Referenced by ProcessInput().
DEBUG_max2
int _TheVoid::DEBUG_max2 private
Definition at line 27 of file runVoid.h.
DEBUG_min1
int _TheVoid::DEBUG_min1 private
Definition at line 24 of file runVoid.h.
Referenced by ProcessInput().
DEBUG_min2
int _TheVoid::DEBUG_min2 private
Definition at line 28 of file runVoid.h.
DEBUG_WATER1
bool _TheVoid::DEBUG_WATER1 private
Definition at line 30 of file runVoid.h.
Referenced by ProcessInput(), and Update().
DEBUG_WATER2
bool _TheVoid::DEBUG_WATER2 private
Definition at line 31 of file runVoid.h.
Referenced by ProcessInput(), and Update().
DomeLake
struct _TheVoid::_DomeLake _TheVoid::DomeLake
Doom
struct _TheVoid::_Doom _TheVoid::Doom
e2d
E2D _TheVoid::e2d private
Definition at line 19 of file runVoid.h.
Referenced by Draw(), load(), ProcessInput(), and reload().
Earth
struct _TheVoid::_Earth _TheVoid::Earth
Referenced by load().
Eclipse
struct _TheVoid::_Eclipse _TheVoid::Eclipse
fboRefract
GLuint _TheVoid::fboRefract[2] private
Definition at line 20 of file runVoid.h.
Referenced by bindFBO().
HugoForest
struct _TheVoid::_HugoForest _TheVoid::HugoForest
iCurrentVoid
int _TheVoid::iCurrentVoid private
Definition at line 36 of file runVoid.h.
Referenced by load(), reload(), and SetVoid().
Ink
struct _TheVoid::_Ink _TheVoid::Ink
Intermost
struct _TheVoid::_Intermost _TheVoid::Intermost
keyboard
Keyboard _TheVoid::keyboard private
Definition at line 15 of file runVoid.h.
Referenced by _TheVoid(), GetInput(), and ProcessInput().
map
WorldMap _TheVoid::map
Definition at line 51 of file runVoid.h.
Referenced by Draw(), NPC::height(), load(), RunBattle::processInput(), reload(), and Run().
mShadow
Matrix44f _TheVoid::mShadow private
Definition at line 13 of file runVoid.h.
npc
_NPC _TheVoid::npc
Definition at line 53 of file runVoid.h.
Referenced by Draw(), RunBattle::draw(), load(), and ProcessInput().
o2d
O2D _TheVoid::o2d private
Definition at line 17 of file runVoid.h.
Referenced by Draw(), load(), and reload().
o3d
O3D _TheVoid::o3d
Definition at line 44 of file runVoid.h.
Referenced by Draw(), load(), and reload().
Oudermost
struct _TheVoid::_Oudermost _TheVoid::Oudermost
player
_Player _TheVoid::player
Definition at line 52 of file runVoid.h.
Referenced by Draw(), and Run().
Prime
struct _TheVoid::_Prime _TheVoid::Prime
Referenced by load().
QuickSilver
struct _TheVoid::_QuickSilver _TheVoid::QuickSilver
Sun
struct _TheVoid::_Sun _TheVoid::Sun
TheChamber
struct _TheVoid::_TheChamber _TheVoid::TheChamber
Twilight
struct _TheVoid::_Twilight _TheVoid::Twilight
water
Water _TheVoid::water private
Definition at line 16 of file runVoid.h.
Referenced by load().
The documentation for this class was generated from the following file:
src/game/ref/runVoid.h