Project Parsec: Core::GUI::Object::Text Class Reference
Core::GUI::Object::Text Class Reference
#include <GUI_Text.h>
Public Member Functions
Text ()
Text (std::string n, Props_Text c)
Text (Window &p, std::string n, Props_Text c)
Text (std::string n, Props_Text *c)
Text (Window &p, std::string n, Props_Text *c)
virtual ~Text ()
void init ()
void exec (iState eExternState=STATE_NONE)
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Text >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Private Member Functions
void updateObjectState (iState eExternState)
Private Attributes
Window * parent
Additional Inherited Members
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Text >
int border
Props_Text * con
Props * parent
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Text >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 24 of file GUI_Text.h.
Constructor & Destructor Documentation
Text() [1/5]
Core::GUI::Object::Text::Text ()
Definition at line 40 of file GUI_Text.h.
References parent.
Text() [2/5]
Core::GUI::Object::Text::Text (std::string n, Props_Text c)
Definition at line 44 of file GUI_Text.h.
References Core::GUI::Object::Base::Generic< Props_Text >::bHasParent, Core::GUI::Object::Base::Generic< Props_Text >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Text >::con, and parent.
Text() [3/5]
Core::GUI::Object::Text::Text (Window & p, std::string n, Props_Text c)
Definition at line 55 of file GUI_Text.h.
References Core::GUI::Object::Base::Generic< Props_Text >::bHasParent, Core::GUI::Object::Base::Generic< Props_Text >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Text >::con, p, and parent.
Text() [4/5]
Core::GUI::Object::Text::Text (std::string n, Props_Text * c)
Definition at line 66 of file GUI_Text.h.
References Core::GUI::Object::Base::Generic< Props_Text >::bHasParent, Core::GUI::Object::Base::Generic< Props_Text >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Text >::con, and parent.
Text() [5/5]
Core::GUI::Object::Text::Text (Window & p, std::string n, Props_Text * c)
Definition at line 76 of file GUI_Text.h.
References Core::GUI::Object::Base::Generic< Props_Text >::bHasParent, Core::GUI::Object::Base::Generic< Props_Text >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Text >::con, p, and parent.
~Text()
Core::GUI::Object::Text::~Text () virtual
Definition at line 86 of file GUI_Text.h.
References Core::GUI::Object::Base::Generic< Props_Text >::bLocalCon, and Core::GUI::Object::Base::Generic< Props_Text >::con.
Member Function Documentation
exec()
void Core::GUI::Object::Text::exec (iState eExternState = STATE_NONE)
Definition at line 104 of file GUI_Text.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::GUI_ColorB::base, Core::GUI::Object::Base::Generic< Props_Text >::bHasParent, Core::GUI::Object::Base::Generic< Props_Text >::bInit, Core::GUI::Props_Text::color, Core::colors, Core::GUI::Object::Base::Generic< Props_Text >::con, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_TOP, Core::GameVars::_Pallette::disabled, Core::_TextSys::drawMulti(), Core::GUI::Props::exec(), Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::GUI_ColorH::highlight, Core::GUI::Props::_Size::isAutoSet(), Core::GameVars::pallette, parent, Core::_Colors::PopFront(), Core::_Colors::PushFront(), Core::GUI::Props::size, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::Props_Text::Colors::text, Core::textSys, updateObjectState(), and Core::GUI::Props::visibility.
Referenced by Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::TextArea::exec(), and Core::GUI::Object::TextEdit::exec().
init()
void Core::GUI::Object::Text::init ()
Definition at line 90 of file GUI_Text.h.
References Core::GUI::Object::Base::Generic< Props_Text >::bHasParent, Core::GUI::Object::Base::Generic< Props_Text >::bInit, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::Object::Base::Generic< Props_Text >::con, Core::GUI::Props::exec(), and parent.
Referenced by Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), and Core::GUI::Object::TextEdit::init().
updateObjectState()
void Core::GUI::Object::Text::updateObjectState (iState eExternState) private
Definition at line 96 of file GUI_Text.h.
References Core::GUI::Object::Base::Generic< Props_Text >::enabled(), Core::GUI::STATE_DISABLED, Core::GUI::STATE_NONE, and Core::GUI::STATE_UPDATE.
Referenced by exec().
Member Data Documentation
parent
Window* Core::GUI::Object::Text::parent private
Definition at line 36 of file GUI_Text.h.
Referenced by exec(), init(), and Text().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Text.h