Project Parsec: Core::_FrameRate Class Reference
Core::_FrameRate Class Reference
#include <FrameRate.h>
Public Member Functions
_FrameRate ()
virtual ~_FrameRate ()
void start ()
void update ()
void stop ()
uint getTicks ()
uint getSplitTicks ()
uint getSamples ()
float getStdDev ()
template<typename T >
T getFPS ()
Private Attributes
PTimer timer
float fps
Detailed Description
Definition at line 16 of file FrameRate.h.
Constructor & Destructor Documentation
_FrameRate()
Core::_FrameRate::_FrameRate ()
Definition at line 12 of file FrameRate.cpp.
References Core::PTimer::addTimer(), fps, and timer.
~_FrameRate()
Core::_FrameRate::~_FrameRate () virtual
Definition at line 17 of file FrameRate.cpp.
Member Function Documentation
getFPS()
template<typename T > template float Core::_FrameRate::getFPS< float > ()
Definition at line 63 of file FrameRate.cpp.
References fps.
Referenced by _Game::Update().
getSamples()
uint Core::_FrameRate::getSamples ()
Definition at line 52 of file FrameRate.cpp.
References Core::PTimer::GetSamples(), and timer.
getSplitTicks()
uint Core::_FrameRate::getSplitTicks ()
Definition at line 47 of file FrameRate.cpp.
References Core::PTimer::getSplitTicks(), and timer.
Referenced by _Game::Update().
getStdDev()
float Core::_FrameRate::getStdDev ()
Definition at line 57 of file FrameRate.cpp.
References Core::PTimer::GetStdDev(), and timer.
Referenced by _Game::Update().
getTicks()
uint Core::_FrameRate::getTicks ()
Definition at line 42 of file FrameRate.cpp.
References Core::PTimer::getTicks(), and timer.
Referenced by update().
start()
void Core::_FrameRate::start ()
Definition at line 20 of file FrameRate.cpp.
References Core::PTimer::start(), and timer.
Referenced by main().
stop()
void Core::_FrameRate::stop ()
Definition at line 38 of file FrameRate.cpp.
References Core::PTimer::stop(), and timer.
update()
void Core::_FrameRate::update ()
Definition at line 24 of file FrameRate.cpp.
References fps, getTicks(), Core::PTimer::stop(), timer, and Core::PTimer::update().
Referenced by main().
Member Data Documentation
fps
float Core::_FrameRate::fps private
Definition at line 20 of file FrameRate.h.
Referenced by _FrameRate(), getFPS(), and update().
timer
PTimer Core::_FrameRate::timer private
Definition at line 18 of file FrameRate.h.
Referenced by _FrameRate(), getSamples(), getSplitTicks(), getStdDev(), getTicks(), start(), stop(), and update().
The documentation for this class was generated from the following files:
src/headers/core/FrameRate.h
src/headers/core/FrameRate.cpp