Project Parsec: Core::Texture Class Reference
Core::Texture Class Reference
#include <texture.h>
Public Member Functions
bool Begin (GLuint uiRequestedLayers)
bool Load (std::string cDir, std::string cFile, GLuint uiLayer, bool bAnisotropy=false, GLenum eFilter=GL_LINEAR, GLenum eWrap=GL_REPEAT)
Texture ()
~Texture ()
int Get (std::string cName)
void Set (GLuint uiLayer)
void Set (std::string cName)
std::string Get (GLuint uiLayer)
Public Attributes
int iLoaded
Protected Member Functions
void LoadImageFromFile (std::string file, SDL_Surface *sdlImage)
void MakePair (std::string cName, GLuint uiNum)
Private Attributes
GLfloat fLargest
GLuint uiNumLayers
GLuint * glImage
Map_si mapImage
bool * bFinished
bool bBeginCalled
Detailed Description
Definition at line 36 of file texture.h.
Constructor & Destructor Documentation
Texture()
Core::Texture::Texture () inline
Definition at line 66 of file texture.h.
References bBeginCalled, bFinished, fLargest, glImage, iLoaded, and uiNumLayers.
~Texture()
Core::Texture::~Texture () inline
Definition at line 74 of file texture.h.
References bBeginCalled, bFinished, glImage, and uiNumLayers.
Member Function Documentation
Begin()
bool Core::Texture::Begin (GLuint uiRequestedLayers)
Definition at line 12 of file texture.cpp.
References bBeginCalled, bFinished, fLargest, GL_MAX_TEXTURE_MAX_ANISOTROPY_EXT, glImage, iLoaded, and uiNumLayers.
Referenced by Core::GameSys::_Flora::init(), Core::_Particles::init(), Core::GameSys::_Satellite::init(), Core::_ParticleEmitter::init(), and Core::GameSys::Atmosphere::load().
Get() [1/2]
std::string Core::Texture::Get (GLuint uiLayer) inline
Definition at line 92 of file texture.h.
References mapImage.
Get() [2/2]
int Core::Texture::Get (std::string cName) inline
Definition at line 89 of file texture.h.
References mapImage.
Load()
bool Core::Texture::Load (std::string cDir, std::string cFile, GLuint uiLayer, bool bAnisotropy = false, GLenum eFilter = GL_LINEAR, GLenum eWrap = GL_REPEAT)
Definition at line 32 of file texture.cpp.
References bFinished, fLargest, GL_LINEAR, GL_NEAREST, GL_RGB, GL_RGBA, GL_SRGB_ALPHA, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MAX_ANISOTROPY_EXT, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_R, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNSIGNED_BYTE, glImage, iLoaded, MakePair(), and uiNumLayers.
Referenced by Core::GameSys::_Flora::init(), Core::_Particles::init(), Core::GameSys::_Satellite::init(), Core::_ParticleEmitter::init(), and Core::GameSys::Atmosphere::load().
LoadImageFromFile()
void Core::Texture::LoadImageFromFile (std::string file, SDL_Surface * sdlImage) protected
MakePair()
void Core::Texture::MakePair (std::string cName, GLuint uiNum) inline protected
Definition at line 58 of file texture.h.
References mapImage.
Referenced by Load().
Set() [1/2]
void Core::Texture::Set (GLuint uiLayer) inline
Definition at line 90 of file texture.h.
References GL_TEXTURE_2D, and glImage.
Referenced by Core::GameSys::_Flora::draw(), Core::_Particles::draw(), Core::GameSys::Atmosphere::draw(), Core::GameSys::_Satellite::draw(), Core::_ParticleEmitter::draw(), and Core::GameSys::_Satellite::drawFlare().
Set() [2/2]
void Core::Texture::Set (std::string cName) inline
Definition at line 91 of file texture.h.
References GL_TEXTURE_2D, glImage, and mapImage.
Member Data Documentation
bBeginCalled
bool Core::Texture::bBeginCalled private
Definition at line 43 of file texture.h.
Referenced by Begin(), Texture(), and ~Texture().
bFinished
bool* Core::Texture::bFinished private
Definition at line 42 of file texture.h.
Referenced by Begin(), Load(), Texture(), and ~Texture().
fLargest
GLfloat Core::Texture::fLargest private
Definition at line 38 of file texture.h.
Referenced by Begin(), Load(), and Texture().
glImage
GLuint* Core::Texture::glImage private
Definition at line 40 of file texture.h.
Referenced by Begin(), Load(), Set(), Texture(), and ~Texture().
iLoaded
int Core::Texture::iLoaded
Definition at line 61 of file texture.h.
Referenced by Begin(), Core::GameSys::_Flora::calc(), Core::_Particles::calc(), Core::GameSys::_Flora::draw(), Core::_Particles::draw(), Core::_Particles::init(), Load(), Texture(), Core::GameSys::_Flora::update(), and Core::_Particles::updateQuad().
mapImage
Map_si Core::Texture::mapImage private
Definition at line 41 of file texture.h.
Referenced by Get(), MakePair(), and Set().
uiNumLayers
GLuint Core::Texture::uiNumLayers private
Definition at line 39 of file texture.h.
Referenced by Begin(), Load(), Texture(), and ~Texture().
The documentation for this class was generated from the following files:
src/headers/core/texture.h
src/headers/core/texture.cpp