Project Parsec: Core::GUI::Object::Window Class Reference
Core::GUI::Object::Window Class Reference
#include <GUI_Window.h>
Public Member Functions
Window ()
Window (std::string n, Props_Window c)
Window (Props &p, std::string n, Props_Window c)
Window (std::string n, Props_Window *c)
Window (Props &p, std::string n, Props_Window *c)
~Window ()
void init ()
void update ()
void exec (iState eExternState=STATE_NONE)
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Window >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Protected Member Functions
void updateObjectState (iState eExternState)
Protected Attributes
VAO vao
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Window >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Additional Inherited Members
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Window >
int border
Props_Window * con
Props * parent
Detailed Description
Definition at line 48 of file GUI_Window.h.
Constructor & Destructor Documentation
Window() [1/5]
Core::GUI::Object::Window::Window ()
Definition at line 72 of file GUI_Window.h.
Referenced by Core::GUI::GUI_Container::execObjects().
Window() [2/5]
Core::GUI::Object::Window::Window (std::string n, Props_Window c)
Definition at line 74 of file GUI_Window.h.
References Core::GUI::Object::Base::Generic< Props_Window >::bHasParent, Core::GUI::Object::Base::Generic< Props_Window >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Window >::con, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
Window() [3/5]
Core::GUI::Object::Window::Window (Props & p, std::string n, Props_Window c)
Definition at line 85 of file GUI_Window.h.
References Core::GUI::Object::Base::Generic< Props_Window >::bHasParent, Core::GUI::Object::Base::Generic< Props_Window >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Window >::con, p, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
Window() [4/5]
Core::GUI::Object::Window::Window (std::string n, Props_Window * c)
Definition at line 96 of file GUI_Window.h.
References Core::GUI::Object::Base::Generic< Props_Window >::bHasParent, Core::GUI::Object::Base::Generic< Props_Window >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Window >::con, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
Window() [5/5]
Core::GUI::Object::Window::Window (Props & p, std::string n, Props_Window * c)
Definition at line 106 of file GUI_Window.h.
References Core::GUI::Object::Base::Generic< Props_Window >::bHasParent, Core::GUI::Object::Base::Generic< Props_Window >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Window >::con, p, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
~Window()
Core::GUI::Object::Window::~Window ()
Definition at line 116 of file GUI_Window.h.
References Core::GUI::Object::Base::Generic< Props_Window >::bLocalCon, and Core::GUI::Object::Base::Generic< Props_Window >::con.
Member Function Documentation
exec()
void Core::GUI::Object::Window::exec (iState eExternState = STATE_NONE)
Definition at line 169 of file GUI_Window.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::Props_Window::Colors::back, Core::GUI::GUI_ColorB::base, Core::GUI::Props_Addon_Stipple::bEnableStipple, Core::GUI::Object::Base::Generic< Props_Window >::bHasParent, Core::GUI::Object::Base::Generic< Props_Window >::bInit, Core::GUI::Object::Base::Generic< Props_Window >::border, Core::GUI::Props_Window::Colors::border, Core::GUI::Props_Window::borderHover, Core::GUI::Props_Window::borderNormal, Core::GUI::Props_Window::color, Core::colors, Core::GUI::Object::Base::Generic< Props_Window >::con, Core::Vector2f::data, Core::Color::data, Core::GameVars::_Pallette::disabled, Core::VAO::Draw(), Core::GUI::Props::exec(), Core::gameVars, Core::GUI::Props::getPos(), Core::GUI::Props_Window::getRadius(), Core::GUI::Props_Window::getRoundBorder(), Core::GUI::Props::getSize(), GL_CULL_FACE, GL_DEPTH_TEST, GL_TRUE, Core::GLS_MENU, Core::GameVars::_Pallette::gui, Core::GUI::GUI_ColorH::highlight, Core::GameVars::pallette, Core::GUI::Object::Base::Generic< Props_Window >::parent, Core::_Colors::PopBack(), Core::_Colors::PopFront(), Core::_Colors::PushBack(), Core::_Colors::PushFront(), Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::Props_Addon_Stipple::stipple, Core::GUI::Props_Addon_Stipple::stippleColor, update(), updateObjectState(), vao, Core::GUI::Props::visibility, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::ProgressBar::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::CheckBox::exec(), Core::GUI::Object::ColorSwatch::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::ComboBox::exec(), Core::GUI::Object::Icon::exec(), Core::GUI::Object::TextEdit::exec(), and Core::GUI::GUI_Container::execObjects().
init()
void Core::GUI::Object::Window::init ()
Definition at line 120 of file GUI_Window.h.
References Core::VAO::Begin(), Core::GUI::Object::Base::Generic< Props_Window >::bHasParent, Core::GUI::Object::Base::Generic< Props_Window >::bInit, Core::GUI::Object::Base::Generic< Props_Window >::con, Core::VAO::CopyData(), Core::VAO::End(), Core::GUI::Props::exec(), GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, Core::GUI::Object::Base::Generic< Props_Window >::parent, and vao.
Referenced by Core::GUI::GUI_Container::add(), Core::GUI::GUI_Container::GUI_Container(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ProgressBar::init(), Core::GUI::Object::Label::init(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Sprite::init(), Core::GUI::Object::Button::init(), Core::GUI::Object::ComboBox::init(), Core::GUI::Object::Icon::init(), and Core::GUI::Object::TextEdit::init().
update()
void Core::GUI::Object::Window::update ()
Definition at line 154 of file GUI_Window.h.
References Core::GUI::Props_Window::bResizeRadius, Core::GUI::Object::Base::Generic< Props_Window >::con, Core::GUI::Props_Window::radius, Core::GUI::Props_Window::setRadius(), Core::GUI::Props::size, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
updateObjectState()
void Core::GUI::Object::Window::updateObjectState (iState eExternState) protected
Definition at line 161 of file GUI_Window.h.
References Core::GUI::Object::Base::Generic< Props_Window >::enabled(), Core::GUI::STATE_DISABLED, Core::GUI::STATE_NONE, and Core::GUI::STATE_UPDATE.
Referenced by exec().
Member Data Documentation
vao
VAO Core::GUI::Object::Window::vao protected
Definition at line 67 of file GUI_Window.h.
Referenced by exec(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Window.h