Project Parsec: Core::GUI::Object::Button Class Reference
Core::GUI::Object::Button Class Reference
#include <GUI_Button.h>
Public Member Functions
Button ()
Button (std::string n, bool b, Props_Button c)
Button (std::string n, bool b, Props_Button *c)
Button (Props &p, std::string n, bool b, Props_Button c)
Button (Props &p, std::string n, bool b, Props_Button *c)
Button (std::string n, bool *b, Props_Button c)
Button (std::string n, bool *b, Props_Button *c)
Button (Props &p, std::string n, bool *b, Props_Button c)
Button (Props &p, std::string n, bool *b, Props_Button *c)
virtual ~Button ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
void updateNoFocus ()
void updateObjectState (iState eExternState)
Public Member Functions inherited from Core::GUI::Object::Base::Interactive< Props_Button, bool >
Interactive ()
Interactive & operator= (const Interactive &src)
bool getPtrValue ()
void setPointer (bool *ptr)
bool * getPointer ()
void init (Props_Addon_ReturnState *ptr)
int getState (int n=0)
bool valueChanged ()
void updateValuePtr ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Button >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Member Functions inherited from Core::GUI::Object::Base::Interactive_Base
Interactive_Base ()
~Interactive_Base ()
Public Member Functions inherited from Core::GUI::Object::Base::AudioFeedback
void initSound (int iChannel, int iSampleOn, int iSampleOff, int iLoopOn, int iLoopOff, bool bOverlapOn, bool bOverlapOff)
void Sound_PlayOn ()
void Sound_AbortState ()
void Sound_PlayOff ()
void Sound_PlayAuto (iState eState, bool bRepeat=false)
AudioFeedback ()
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Button >
int border
Props_Button * con
Props * parent
Public Attributes inherited from Core::GUI::Object::Base::AudioFeedback
bool bRising
bool bOneShotOn
bool bOneShotOff
int iSampleOn
int iSampleOff
int iLoopOn
int iLoopOff
bool bOverlapOn
bool bOverlapOff
int iChannel
Private Attributes
Window win
Additional Inherited Members
Static Public Attributes inherited from Core::GUI::Object::Base::Interactive_Base
static bool bFocusPresent = false
static std::string sActiveObject = ""
static std::string sGroupObject [32] = { "" }
Protected Attributes inherited from Core::GUI::Object::Base::Interactive< Props_Button, bool >
bool * valuePtr
bool bLocalValue
bool bReturnInit
bool bValueChanged
Timer debounceTimer
Props_Addon_ReturnState * returnState
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Button >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 36 of file GUI_Button.h.
Constructor & Destructor Documentation
Button() [1/9]
Core::GUI::Object::Button::Button ()
Definition at line 63 of file GUI_Button.h.
Button() [2/9]
Core::GUI::Object::Button::Button (std::string n, bool b, Props_Button c)
Definition at line 65 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Button, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::Object::Base::Generic< Props_Button >::con, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr.
Button() [3/9]
Core::GUI::Object::Button::Button (std::string n, bool b, Props_Button * c)
Definition at line 101 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Button, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::Object::Base::Generic< Props_Button >::con, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr.
Button() [4/9]
Core::GUI::Object::Button::Button (Props & p, std::string n, bool b, Props_Button c)
Definition at line 83 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Button, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::Object::Base::Generic< Props_Button >::con, p, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr.
Button() [5/9]
Core::GUI::Object::Button::Button (Props & p, std::string n, bool b, Props_Button * c)
Definition at line 118 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Button, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::Object::Base::Generic< Props_Button >::con, p, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr.
Button() [6/9]
Core::GUI::Object::Button::Button (std::string n, bool * b, Props_Button c)
Definition at line 135 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Button, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::Object::Base::Generic< Props_Button >::con, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr.
Button() [7/9]
Core::GUI::Object::Button::Button (std::string n, bool * b, Props_Button * c)
Definition at line 172 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Button, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::Object::Base::Generic< Props_Button >::con, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr.
Button() [8/9]
Core::GUI::Object::Button::Button (Props & p, std::string n, bool * b, Props_Button c)
Definition at line 153 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Button, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::Object::Base::Generic< Props_Button >::con, p, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr.
Button() [9/9]
Core::GUI::Object::Button::Button (Props & p, std::string n, bool * b, Props_Button * c)
Definition at line 189 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Button, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::Object::Base::Generic< Props_Button >::con, p, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr.
~Button()
Core::GUI::Object::Button::~Button () virtual
Definition at line 206 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bLocalCon, and Core::GUI::Object::Base::Generic< Props_Button >::con.
Member Function Documentation
exec()
void Core::GUI::Object::Button::exec (iState eExternState = STATE_NONE)
Definition at line 341 of file GUI_Button.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::GUI_ColorB::base, Core::GUI::Object::Base::Interactive_Base::bFocusPresent, Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bInit, Core::GUI::Props::ToolTip::bShow, Core::GUI::Props_Button::color, Core::colors, Core::GUI::Object::Base::Generic< Props_Button >::con, Core::GameVars::_Pallette::disabled, Core::_TextSys::draw(), Core::GUI::Props_Button::eLabelAnchor, Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::GUI_ColorH::highlight, Core::GameVars::pallette, Core::GUI::Object::Base::Generic< Props_Button >::parent, Core::_Colors::PopFront(), Core::_Colors::PushFront(), Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::Props_Button::Colors::text, Core::textSys, toolTip, Core::GUI::Props::toolTip, Core::GUI::Object::ToolTip::updateObjectState(), updateObjectState(), Core::GUI::Props::visibility, and win.
Referenced by Core::GUI::Object::TextArea::exec(), and Core::GUI::Object::TextEdit::exec().
execToolTip()
void Core::GUI::Object::Button::execToolTip ()
Definition at line 372 of file GUI_Button.h.
References Core::GUI::Object::ToolTip::exec(), and toolTip.
init()
void Core::GUI::Object::Button::init ()
Definition at line 210 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bHasParent, Core::GUI::Object::Base::Generic< Props_Button >::bInit, Core::GUI::Object::Base::Generic< Props_Button >::con, Core::GUI::Props::exec(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::Window::init(), Core::GUI::Object::Base::AudioFeedback::initSound(), Core::GUI::Object::Base::Generic< Props_Button >::parent, toolTip, and win.
Referenced by Core::GUI::Object::TextArea::init(), and Core::GUI::Object::TextEdit::init().
updateNoFocus()
void Core::GUI::Object::Button::updateNoFocus ()
Definition at line 381 of file GUI_Button.h.
References Core::GUI::STATE_UPDATE, updateObjectState(), and Core::GUI::Object::Base::Interactive< Props_Button, bool >::updateValuePtr().
updateObjectState()
void Core::GUI::Object::Button::updateObjectState (iState eExternState)
Definition at line 230 of file GUI_Button.h.
References Core::GUI::Object::Base::Generic< Props_Button >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Button >::bRepeatStatus, Core::GUI::BUTTON_DEBOUNCE, Core::GUI::BUTTON_ONESHOT, Core::GUI::BUTTON_TOGGLE, Core::GUI::Props_Button::buttonType, Core::_Mouse::checkInput(), Core::GUI::Object::Base::Generic< Props_Button >::con, Core::GUI::Props_Button::debounceTime, Core::GUI::Object::Base::Interactive< Props_Button, bool >::debounceTimer, Core::GUI::Object::Base::Generic< Props_Button >::enabled(), Core::gameVars, Core::GameVars::Screen::half, Core::GUI::Props_Addon_Group::iGroup, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_LEFT, Core::_Mouse::MOUSE_LEFT_DOWN, Core::_Mouse::MOUSE_NONE, Core::GUI::Object::Base::Generic< Props_Button >::mState, Core::GUI::Object::Base::Generic< Props_Button >::name, Core::GUI::Props::pos, Core::GUI::Object::Base::Interactive< Props_Button, bool >::returnState, Core::GameVars::screen, Core::GUI::Object::Base::Interactive_Base::sGroupObject, Core::GUI::Props::size, Core::GUI::Object::Base::AudioFeedback::Sound_AbortState(), Core::GUI::Object::Base::AudioFeedback::Sound_PlayOff(), Core::GUI::Object::Base::AudioFeedback::Sound_PlayOn(), Core::Timer::split(), Core::Timer::start(), Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::GUI::Object::Base::Interactive< Props_Button, bool >::updateValuePtr(), Core::GUI::Object::Base::Interactive< Props_Button, bool >::valuePtr, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec(), and updateNoFocus().
Member Data Documentation
toolTip
ToolTip Core::GUI::Object::Button::toolTip
Definition at line 51 of file GUI_Button.h.
Referenced by exec(), execToolTip(), and init().
win
Window Core::GUI::Object::Button::win private
Definition at line 58 of file GUI_Button.h.
Referenced by exec(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Button.h