Project Parsec: Core::GUI::GUI::ColorSwatchInterface Class Reference
Core::GUI::GUI::ColorSwatchInterface Class Reference
#include <GUI.h>
Public Member Functions
void add (std::string guiName, std::string colorSwatchName, Color *ptr, Constraints_ColorSwatch c)
void add (std::string guiName, std::string windowName, std::string colorSwatchName, Color *ptr, Constraints_ColorSwatch c)
void add (std::string guiName, std::string colorSwatchName, Color *ptr, Constraints_ColorSwatch *c)
void add (std::string guiName, std::string windowName, std::string colorSwatchName, Color *ptr, Constraints_ColorSwatch *c)
Constraints_ColorSwatch * get (std::string guiName, std::string colorSwatchName)
ColorSwatchInterface (GUI *parent)
Public Attributes
GUI * gui
Detailed Description
Definition at line 198 of file GUI.h.
Constructor & Destructor Documentation
ColorSwatchInterface()
Core::GUI::GUI::ColorSwatchInterface::ColorSwatchInterface (GUI * parent) inline
Definition at line 206 of file GUI.h.
References gui.
Member Function Documentation
add() [1/4]
void Core::GUI::GUI::ColorSwatchInterface::add (std::string guiName, std::string colorSwatchName, Color * ptr, Constraints_ColorSwatch * c)
Definition at line 837 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::ColorSwatch::init().
add() [2/4]
void Core::GUI::GUI::ColorSwatchInterface::add (std::string guiName, std::string colorSwatchName, Color * ptr, Constraints_ColorSwatch c)
Definition at line 818 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::ColorSwatch::init().
add() [3/4]
void Core::GUI::GUI::ColorSwatchInterface::add (std::string guiName, std::string windowName, std::string colorSwatchName, Color * ptr, Constraints_ColorSwatch * c)
Definition at line 846 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::ColorSwatch::init().
add() [4/4]
void Core::GUI::GUI::ColorSwatchInterface::add (std::string guiName, std::string windowName, std::string colorSwatchName, Color * ptr, Constraints_ColorSwatch c)
Definition at line 827 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::ColorSwatch::init().
get()
Constraints_ColorSwatch * Core::GUI::GUI::ColorSwatchInterface::get (std::string guiName, std::string colorSwatchName)
Definition at line 856 of file GUI.h.
References MY_NAMESPACE::gui.
Member Data Documentation
gui
GUI* Core::GUI::GUI::ColorSwatchInterface::gui
Definition at line 205 of file GUI.h.
Referenced by ColorSwatchInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI.h