Project Parsec: Core::GUI::Object::TextEditBase Class Reference
Core::GUI::Object::TextEditBase Class Reference
Keyboard control and TextEdit object focus tracking.
#include <GUI_TextEdit.h>
Public Member Functions
TextEditBase ()
Static Public Attributes
static Core::_Keyboard keyboard = Core::_Keyboard()
static bool bKeyboardInit = false
Detailed Description
Keyboard control and TextEdit object focus tracking.
Creates a keyboard object to allow input while editing that is used across all instances of TextEdit objects. Also keeps track of if any TextEdit objects are currently active preventing others from also being edited at the same time.
Definition at line 33 of file GUI_TextEdit.h.
Constructor & Destructor Documentation
TextEditBase()
Core::GUI::Object::TextEditBase::TextEditBase () inline
Definition at line 38 of file GUI_TextEdit.h.
References bKeyboardInit, Core::_Keyboard::calc(), keyboard, and Core::_Keyboard::KEYTYPE_DEBOUNCE.
Member Data Documentation
bKeyboardInit
bool Core::GUI::Object::TextEditBase::bKeyboardInit = false static
Definition at line 36 of file GUI_TextEdit.h.
Referenced by TextEditBase().
keyboard
Core::_Keyboard Core::GUI::Object::TextEditBase::keyboard = Core::_Keyboard() static
Definition at line 35 of file GUI_TextEdit.h.
Referenced by Core::GUI::Object::TextEdit::execEdit(), and TextEditBase().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_TextEdit.h