Project Parsec: Core::GUI::Object::Sprite Class Reference
Core::GUI::Object::Sprite Class Reference
#include <GUI_Sprite.h>
Public Member Functions
Sprite ()
Sprite (std::string n, Props_Sprite c)
Sprite (Props &p, std::string n, Props_Sprite c)
Sprite (std::string n, Props_Sprite *c)
Sprite (Props &p, std::string n, Props_Sprite *c)
virtual ~Sprite ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Sprite >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Sprite >
int border
Props_Sprite * con
Props * parent
Private Member Functions
void updateObjectState (iState eExternState)
Private Attributes
Window win
Additional Inherited Members
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Sprite >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 41 of file GUI_Sprite.h.
Constructor & Destructor Documentation
Sprite() [1/5]
Sprite::Sprite ()
Definition at line 61 of file GUI_Sprite.h.
Sprite() [2/5]
Sprite::Sprite (std::string n, Props_Sprite c)
Definition at line 63 of file GUI_Sprite.h.
References Core::GUI::Object::Base::Generic< Props_Sprite >::bHasParent, Core::GUI::Object::Base::Generic< Props_Sprite >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Sprite >::con, and Core::GUI::Object::Base::Generic< Props_Sprite >::parent.
Sprite() [3/5]
Sprite::Sprite (Props & p, std::string n, Props_Sprite c)
Definition at line 74 of file GUI_Sprite.h.
References Core::GUI::Object::Base::Generic< Props_Sprite >::bHasParent, Core::GUI::Object::Base::Generic< Props_Sprite >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Sprite >::con, p, and Core::GUI::Object::Base::Generic< Props_Sprite >::parent.
Sprite() [4/5]
Sprite::Sprite (std::string n, Props_Sprite * c)
Definition at line 85 of file GUI_Sprite.h.
References Core::GUI::Object::Base::Generic< Props_Sprite >::bHasParent, Core::GUI::Object::Base::Generic< Props_Sprite >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Sprite >::con, and Core::GUI::Object::Base::Generic< Props_Sprite >::parent.
Sprite() [5/5]
Sprite::Sprite (Props & p, std::string n, Props_Sprite * c)
Definition at line 95 of file GUI_Sprite.h.
References Core::GUI::Object::Base::Generic< Props_Sprite >::bHasParent, Core::GUI::Object::Base::Generic< Props_Sprite >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Sprite >::con, p, and Core::GUI::Object::Base::Generic< Props_Sprite >::parent.
~Sprite()
Sprite::~Sprite () virtual
Definition at line 105 of file GUI_Sprite.h.
References Core::GUI::Object::Base::Generic< Props_Sprite >::bLocalCon, and Core::GUI::Object::Base::Generic< Props_Sprite >::con.
Member Function Documentation
exec()
void Sprite::exec (iState eExternState = STATE_NONE)
Definition at line 144 of file GUI_Sprite.h.
References Core::GUI::GUI_ColorB::base, Core::GUI::Object::Base::Generic< Props_Sprite >::bHasParent, Core::GUI::Object::Base::Generic< Props_Sprite >::bInit, Core::GUI::Props::ToolTip::bShow, Core::GUI::Props_Sprite::color, Core::colors, Core::GUI::Object::Base::Generic< Props_Sprite >::con, Core::GameVars::_Pallette::disabled, Core::_SpriteSys::draw(), Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Core::gameVars, Core::GameVars::_Pallette::gui, Core::GameVars::pallette, Core::GUI::Object::Base::Generic< Props_Sprite >::parent, Core::_Colors::PopFront(), Core::_Colors::PushFront(), Core::GUI::Props_Sprite::Colors::sprite, Core::GUI::Props_Sprite::spriteImage, Core::spriteSys, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, toolTip, Core::GUI::Props::toolTip, Core::GUI::Object::ToolTip::updateObjectState(), updateObjectState(), Core::GUI::Props::visibility, and win.
execToolTip()
void Sprite::execToolTip ()
Definition at line 169 of file GUI_Sprite.h.
References Core::GUI::Object::ToolTip::exec(), and toolTip.
init()
void Sprite::init ()
Definition at line 112 of file GUI_Sprite.h.
References Core::GUI::Object::Base::Generic< Props_Sprite >::bHasParent, Core::GUI::Object::Base::Generic< Props_Sprite >::bInit, Core::GUI::Object::Base::Generic< Props_Sprite >::con, Core::GUI::Props::exec(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::Window::init(), Core::GUI::Object::Base::Generic< Props_Sprite >::parent, toolTip, and win.
updateObjectState()
void Sprite::updateObjectState (iState eExternState) private
Definition at line 127 of file GUI_Sprite.h.
References Core::_Mouse::checkInput(), Core::GUI::Object::Base::Generic< Props_Sprite >::con, Core::GUI::Object::Base::Generic< Props_Sprite >::enabled(), Core::gameVars, Core::GameVars::Screen::half, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_NONE, Core::GUI::Object::Base::Generic< Props_Sprite >::mState, Core::GUI::Props::pos, Core::GameVars::screen, Core::GUI::Props::size, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
Member Data Documentation
toolTip
ToolTip Core::GUI::Object::Sprite::toolTip
Definition at line 51 of file GUI_Sprite.h.
Referenced by exec(), execToolTip(), and init().
win
Window Core::GUI::Object::Sprite::win private
Definition at line 57 of file GUI_Sprite.h.
Referenced by exec(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Sprite.h