Project Parsec: Core::_FBO Class Reference
Core::_FBO Class Reference
#include <fbo.h>
Classes
struct _FBO_Struct
Public Member Functions
_FBO ()
~_FBO ()
void CreateFbo (std::string name, uint w, uint h, uint uiMultisample=0)
void AddColorAttachment (std::string name, uint n, GLuint filter, GLuint clamp)
void AddDepthBuffer (std::string name)
void AddDepthTexture (std::string name, GLuint filter, GLuint clamp)
void SetDrawBuffer (std::string name, uint ui, bool bDepth)
void SetReadBuffer (std::string name, uint ui, bool bDepth)
void ResolveFBO (std::string s, std::string t, GLuint filter)
void ResolveFBOtoScreen (std::string source, GLuint filter)
void FinishFbo (std::string name)
void BindFbo (std::string name)
void UnbindFbo ()
uint GetTexture (std::string name, uint n)
uint GetDepthTexture (std::string name)
int GetViewPortWidth (std::string name)
int GetViewPortHeight (std::string name)
bool HasMultisample (std::string name)
uint GetMultisamples (std::string name)
void CheckStatus ()
Private Attributes
_FBO_Struct * fbo
GLint iViewport [4]
uint uiNumBuffers
uint uiMaxFbos
Map_si siMap
bool bDebug
Detailed Description
Definition at line 14 of file fbo.h.
Constructor & Destructor Documentation
_FBO()
Core::_FBO::_FBO ()
Definition at line 68 of file fbo.h.
References Core::_FBO::_FBO_Struct::bColorBuffer, bDebug, Core::_FBO::_FBO_Struct::bDepthBuffer, Core::_FBO::_FBO_Struct::bFinished, Core::_FBO::_FBO_Struct::bFrameBuffer, Core::_FBO::_FBO_Struct::bTexColor, Core::_FBO::_FBO_Struct::bTexDepth, fbo, Core::_FBO::_FBO_Struct::h, Core::_FBO::_FBO_Struct::uiColorBuffer, Core::_FBO::_FBO_Struct::uiDepthBuffer, Core::_FBO::_FBO_Struct::uiFramebuffer, uiMaxFbos, Core::_FBO::_FBO_Struct::uiMultisample, uiNumBuffers, Core::_FBO::_FBO_Struct::uiTexColor, Core::_FBO::_FBO_Struct::uiTexDepth, and Core::_FBO::_FBO_Struct::w.
~_FBO()
Core::_FBO::~_FBO ()
Definition at line 100 of file fbo.h.
References cout, fbo, and uiNumBuffers.
Member Function Documentation
AddColorAttachment()
void Core::_FBO::AddColorAttachment (std::string name, uint n = 0, GLuint filter = GL_LINEAR, GLuint clamp = GL_CLAMP_TO_EDGE)
Definition at line 140 of file fbo.h.
References Core::_FBO::_FBO_Struct::bColorBuffer, bDebug, Core::_FBO::_FBO_Struct::bTexColor, CheckStatus(), cout, fbo, GL_COLOR_ATTACHMENT0, GL_COLOR_ATTACHMENT1, GL_COLOR_ATTACHMENT2, GL_COLOR_ATTACHMENT3, GL_FRAMEBUFFER, GL_RENDERBUFFER, GL_RGBA, GL_RGBA8, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_R, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, GL_UNSIGNED_BYTE, id, and siMap.
Referenced by Core::PostProcess::init().
AddDepthBuffer()
void Core::_FBO::AddDepthBuffer (std::string name)
Definition at line 175 of file fbo.h.
References bDebug, Core::_FBO::_FBO_Struct::bDepthBuffer, CheckStatus(), cout, fbo, GL_DEPTH_ATTACHMENT, GL_DEPTH_COMPONENT, GL_FRAMEBUFFER, GL_RENDERBUFFER, id, and siMap.
Referenced by AddDepthTexture(), and Core::PostProcess::init().
AddDepthTexture()
void Core::_FBO::AddDepthTexture (std::string name, GLuint filter = GL_LINEAR, GLuint clamp = GL_CLAMP_TO_EDGE)
Definition at line 191 of file fbo.h.
References AddDepthBuffer(), bDebug, Core::_FBO::_FBO_Struct::bTexDepth, CheckStatus(), cout, fbo, GL_DEPTH_ATTACHMENT, GL_DEPTH_COMPONENT, GL_DEPTH_COMPONENT32, GL_FLOAT, GL_FRAMEBUFFER, GL_TEXTURE_2D, GL_TEXTURE_MAG_FILTER, GL_TEXTURE_MIN_FILTER, GL_TEXTURE_WRAP_R, GL_TEXTURE_WRAP_S, GL_TEXTURE_WRAP_T, id, and siMap.
Referenced by Core::PostProcess::init().
BindFbo()
void Core::_FBO::BindFbo (std::string name)
Definition at line 298 of file fbo.h.
References fbo, GL_FRAMEBUFFER, GL_TEXTURE_2D, GL_VIEWPORT, iViewport, and siMap.
Referenced by Core::PostProcess::ApplyBrightness(), Core::PostProcess::ApplyBrightnessFilter(), Core::PostProcess::ApplyCombine(), Core::PostProcess::ApplyContrast(), Core::PostProcess::ApplyHBlur(), Core::PostProcess::ApplyLensFlare(), Core::PostProcess::ApplyRadialBlur(), Core::PostProcess::ApplyVBlur(), and Core::PostProcess::RenderLayer().
CheckStatus()
void Core::_FBO::CheckStatus ()
Definition at line 311 of file fbo.h.
References bDebug, cout, GL_FRAMEBUFFER, GL_FRAMEBUFFER_COMPLETE, GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT, GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER, GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS, GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT, GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE, GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER, GL_FRAMEBUFFER_UNDEFINED, and GL_FRAMEBUFFER_UNSUPPORTED.
Referenced by AddColorAttachment(), AddDepthBuffer(), and AddDepthTexture().
CreateFbo()
void Core::_FBO::CreateFbo (std::string name, uint w, uint h, uint uiMultisample = 0)
Definition at line 117 of file fbo.h.
References bDebug, Core::_FBO::_FBO_Struct::bFrameBuffer, cout, fbo, GL_DEPTH_TEST, GL_FRAMEBUFFER, GL_LEQUAL, GL_TRUE, Core::_FBO::_FBO_Struct::h, h, id, siMap, uiMaxFbos, Core::_FBO::_FBO_Struct::uiMultisample, uiNumBuffers, Core::_FBO::_FBO_Struct::w, and w.
Referenced by Core::PostProcess::init().
FinishFbo()
void Core::_FBO::FinishFbo (std::string name)
Definition at line 274 of file fbo.h.
References bDebug, Core::_FBO::_FBO_Struct::bFinished, cout, fbo, GL_FRAMEBUFFER, GL_FRAMEBUFFER_COMPLETE, GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT, GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER, GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS, GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT, GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE, GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER, GL_FRAMEBUFFER_UNDEFINED, GL_FRAMEBUFFER_UNSUPPORTED, GL_TEXTURE_2D, and siMap.
Referenced by Core::PostProcess::init().
GetDepthTexture()
uint Core::_FBO::GetDepthTexture (std::string name) inline
Definition at line 60 of file fbo.h.
References fbo, siMap, and Core::_FBO::_FBO_Struct::uiTexDepth.
GetMultisamples()
uint Core::_FBO::GetMultisamples (std::string name)
Definition at line 270 of file fbo.h.
References fbo, siMap, and Core::_FBO::_FBO_Struct::uiMultisample.
GetTexture()
uint Core::_FBO::GetTexture (std::string name, uint n) inline
Definition at line 59 of file fbo.h.
References fbo, siMap, and Core::_FBO::_FBO_Struct::uiTexColor.
Referenced by Core::PostProcess::ApplyBrightness(), Core::PostProcess::ApplyBrightnessFilter(), Core::PostProcess::ApplyCombine(), Core::PostProcess::ApplyContrast(), Core::PostProcess::ApplyHBlur(), Core::PostProcess::ApplyLensFlare(), Core::PostProcess::ApplyRadialBlur(), Core::PostProcess::ApplyVBlur(), and Core::PostProcess::EndRenderLayer().
GetViewPortHeight()
int Core::_FBO::GetViewPortHeight (std::string name) inline
Definition at line 62 of file fbo.h.
References fbo, Core::_FBO::_FBO_Struct::h, and siMap.
GetViewPortWidth()
int Core::_FBO::GetViewPortWidth (std::string name) inline
Definition at line 61 of file fbo.h.
References fbo, siMap, and Core::_FBO::_FBO_Struct::w.
HasMultisample()
bool Core::_FBO::HasMultisample (std::string name)
Definition at line 265 of file fbo.h.
References fbo, and siMap.
ResolveFBO()
void Core::_FBO::ResolveFBO (std::string s, std::string t, GLuint filter = GL_NEAREST)
Definition at line 234 of file fbo.h.
References fbo, GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT, GL_DRAW_FRAMEBUFFER, GL_READ_FRAMEBUFFER, siMap, and UnbindFbo().
Referenced by Core::PostProcess::EndRenderLayer().
ResolveFBOtoScreen()
void Core::_FBO::ResolveFBOtoScreen (std::string source, GLuint filter = GL_NEAREST)
Definition at line 246 of file fbo.h.
References bDebug, cout, fbo, GL_BACK, GL_COLOR_BUFFER_BIT, GL_DRAW_FRAMEBUFFER, GL_READ_FRAMEBUFFER, siMap, and UnbindFbo().
SetDrawBuffer()
void Core::_FBO::SetDrawBuffer (std::string name, uint ui, bool bDepth = false)
Definition at line 214 of file fbo.h.
References fbo, GL_FRAMEBUFFER, GL_RENDERBUFFER, and siMap.
SetReadBuffer()
void Core::_FBO::SetReadBuffer (std::string name, uint ui, bool bDepth = false)
Definition at line 224 of file fbo.h.
References fbo, GL_FRAMEBUFFER, GL_RENDERBUFFER, and siMap.
UnbindFbo()
void Core::_FBO::UnbindFbo ()
Definition at line 305 of file fbo.h.
References GL_FRAMEBUFFER, GL_TEXTURE_2D, and iViewport.
Referenced by Core::PostProcess::ApplyBrightness(), Core::PostProcess::ApplyBrightnessFilter(), Core::PostProcess::ApplyCombine(), Core::PostProcess::ApplyContrast(), Core::PostProcess::ApplyHBlur(), Core::PostProcess::ApplyLensFlare(), Core::PostProcess::ApplyRadialBlur(), Core::PostProcess::ApplyVBlur(), Core::PostProcess::EndRenderLayer(), ResolveFBO(), and ResolveFBOtoScreen().
Member Data Documentation
bDebug
bool Core::_FBO::bDebug private
Definition at line 43 of file fbo.h.
Referenced by _FBO(), AddColorAttachment(), AddDepthBuffer(), AddDepthTexture(), CheckStatus(), CreateFbo(), FinishFbo(), and ResolveFBOtoScreen().
fbo
_FBO_Struct* Core::_FBO::fbo private
Definition at line 38 of file fbo.h.
Referenced by _FBO(), AddColorAttachment(), AddDepthBuffer(), AddDepthTexture(), BindFbo(), CreateFbo(), FinishFbo(), GetDepthTexture(), GetMultisamples(), GetTexture(), GetViewPortHeight(), GetViewPortWidth(), HasMultisample(), ResolveFBO(), ResolveFBOtoScreen(), SetDrawBuffer(), SetReadBuffer(), and ~_FBO().
iViewport
GLint Core::_FBO::iViewport[4] private
Definition at line 39 of file fbo.h.
Referenced by BindFbo(), and UnbindFbo().
siMap
Map_si Core::_FBO::siMap private
Definition at line 42 of file fbo.h.
Referenced by AddColorAttachment(), AddDepthBuffer(), AddDepthTexture(), BindFbo(), CreateFbo(), FinishFbo(), GetDepthTexture(), GetMultisamples(), GetTexture(), GetViewPortHeight(), GetViewPortWidth(), HasMultisample(), ResolveFBO(), ResolveFBOtoScreen(), SetDrawBuffer(), and SetReadBuffer().
uiMaxFbos
uint Core::_FBO::uiMaxFbos private
Definition at line 41 of file fbo.h.
Referenced by _FBO(), and CreateFbo().
uiNumBuffers
uint Core::_FBO::uiNumBuffers private
Definition at line 40 of file fbo.h.
Referenced by _FBO(), CreateFbo(), and ~_FBO().
The documentation for this class was generated from the following file:
src/headers/core/fbo.h