Project Parsec: Core::GUI::Props Class Reference
Core::GUI::Props Class Reference
General Props used for all objects.
#include <GUI_Constraint.h>
Classes
struct _Position
struct _Size
struct ToolTip
Public Member Functions
void setPos (Vector2f v)
void setPos (int n1, int n2)
void modPos (int n1, int n2)
void setX (int n)
void setY (int n)
void modX (int n)
void modY (int n)
void setWidth (int n, eSizeConstraint e=SIZE_CONSTRAINT_ABSOLUTE)
void setHeight (int n, eSizeConstraint e=SIZE_CONSTRAINT_ABSOLUTE)
void modSize (int n1, int n2)
void setAnchor (iConstrain e=CONSTRAIN_CENTER)
void setOrigin (iConstrain e=CONSTRAIN_CENTER)
void exec ()
void exec (Props c)
Vector2f getPos ()
Vector2f getSize ()
void setPadding (int i)
void setPadding (int t, int b, int l, int r)
void setPadding (Vector4i v)
void enablePadding (ePadding e=PADDING_POSITION)
void disablePadding ()
void setVisibility (bool b)
void enableToolTip ()
void disableToolTip ()
void setToolTip (std::string s)
void autoWidth (bool b=true)
void autoHeight (bool b=true)
void setMinMaxWidth (int min, int max)
void setMinWidth (int i)
void setMaxWidth (int i)
void setMinMaxHeight (int min, int max)
void setMinHeight (int i)
void setMaxHeight (int i)
Props ()
Props (Props &src)
~Props ()
Public Attributes
Core::GUI::Props::_Position pos
Actual calculated position from origin and anchor constraints, automatically updated.
Core::GUI::Props::_Size size
Actual calculated width(x) and height(y) from origin and anchor constraints, automatically updated.
int origin
The starting drawing point with respect to the parent, if present, otherwise full screen.
int anchor
The point at which this object is offset from the origin.
Vector4i vPadding
Extra reserved space taken into account for origin.
ePadding eEnablePadding
bool visibility
Controls if this object is drawn and any of its direct children.
struct Core::GUI::Props::ToolTip toolTip
Static Public Attributes
static bool bGlobalSettings = true
Used externally to allow multiple windows to use identical settings.
Private Member Functions
void execPos (Vector2f cHalf, Vector2f oPos=Vector2f(0.0f), Vector4i vPad=Vector4i(0))
void execSize (Vector2f cSize, Vector4i vPad=Vector4i(0))
Detailed Description
General Props used for all objects.
Generic constraints that all other contraints rely on. This is also the class that is used for parents to constrain objects to each other.
Definition at line 162 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Props() [1/2]
Core::GUI::Props::Props () inline
Definition at line 255 of file GUI_Constraint.h.
References anchor, autoHeight(), autoWidth(), Core::GUI::Props::ToolTip::border, Core::GUI::Props::ToolTip::bShow, Core::GUI::CONSTRAIN_CENTER, enablePadding(), origin, Core::GUI::Props::ToolTip::padding, Core::GUI::PADDING_POSITION, Core::GUI::Props::ToolTip::radius, Core::GUI::Props::ToolTip::round, setHeight(), setMinMaxHeight(), setMinMaxWidth(), setPos(), setWidth(), Core::GUI::Props::ToolTip::showLabel, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::Props::ToolTip::Text, toolTip, and visibility.
Props() [2/2]
Core::GUI::Props::Props (Props & src) inline
Definition at line 296 of file GUI_Constraint.h.
References anchor, Core::GUI::Props::ToolTip::bShow, Core::GUI::Props::_Position::constraint, eEnablePadding, origin, pos, Core::GUI::Props::ToolTip::Text, toolTip, visibility, vPadding, Core::Vector2f::x, and Core::Vector2f::y.
~Props()
Core::GUI::Props::~Props () inline
Definition at line 325 of file GUI_Constraint.h.
Member Function Documentation
autoHeight()
void Core::GUI::Props::autoHeight (bool b = true) inline
Definition at line 247 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::ToolTip::init(), _Admin::init(), Props(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), and Core::GUI::Props_Text::Props_Text().
autoWidth()
void Core::GUI::Props::autoWidth (bool b = true) inline
Definition at line 246 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::ToolTip::init(), _Admin::init(), Props(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), and Core::GUI::Props_Text::Props_Text().
disablePadding()
void Core::GUI::Props::disablePadding () inline
Definition at line 241 of file GUI_Constraint.h.
References eEnablePadding, and Core::GUI::PADDING_NONE.
Referenced by Core::GUI::Object::TextArea::init(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::TextEdit::init(), and _Admin::init().
disableToolTip()
void Core::GUI::Props::disableToolTip () inline
Definition at line 244 of file GUI_Constraint.h.
References Core::GUI::Props::ToolTip::bShow, and toolTip.
enablePadding()
void Core::GUI::Props::enablePadding (ePadding e = PADDING_POSITION) inline
Definition at line 240 of file GUI_Constraint.h.
References eEnablePadding.
Referenced by _Admin::init(), Props(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), Core::GUI::Props_Sprite::Props_Sprite(), and Core::GUI::Props_Window::Props_Window().
enableToolTip()
void Core::GUI::Props::enableToolTip () inline
Definition at line 243 of file GUI_Constraint.h.
References Core::GUI::Props::ToolTip::bShow, and toolTip.
Referenced by _Admin::init().
exec() [1/2]
void Core::GUI::Props::exec () inline
Definition at line 233 of file GUI_Constraint.h.
References execPos(), execSize(), Core::gameVars, Core::GameVars::Screen::half, Core::GameVars::Screen::res, and Core::GameVars::screen.
Referenced by Core::_TextSys::drawMulti(), Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::Text::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::ProgressBar::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::ColorSwatch::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::Icon::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::Window::exec(), Core::GUI::GUI_Container::execObjects(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::Text::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ProgressBar::init(), Core::GUI::Object::Label::init(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Sprite::init(), Core::GUI::Object::Button::init(), Core::GUI::Object::ComboBox::init(), Core::GUI::Object::Icon::init(), Core::GUI::Object::Window::init(), and Core::GUI::Object::TextEdit::init().
exec() [2/2]
void Core::GUI::Props::exec (Props c) inline
Definition at line 234 of file GUI_Constraint.h.
References execPos(), and execSize().
execPos()
void Core::GUI::Props::execPos (Vector2f cHalf, Vector2f oPos = Vector2f(0.0f), Vector4i vPad = Vector4i(0)) private
Definition at line 1631 of file GUI_Constraint.h.
References Core::Vector4i::bottom, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, Core::GUI::CONSTRAIN_TOP, Core::GUI::Props::_Position::constraint, eEnablePadding, Core::Vector4i::left, origin, Core::GUI::PADDING_POSITION, pos, Core::Vector4i::right, Core::GUI::SIZE_CONSTRAINT_RELATIVE, Core::Vector4i::top, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
execSize()
void Core::GUI::Props::execSize (Vector2f cSize, Vector4i vPad = Vector4i(0)) private
Definition at line 1655 of file GUI_Constraint.h.
References anchor, Core::Vector4i::bottom, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, Core::GUI::CONSTRAIN_TOP, eEnablePadding, Core::Vector4i::left, Core::GUI::PADDING_SIZE, pos, Core::Vector4i::right, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::SIZE_CONSTRAINT_RELATIVE, Core::Vector4i::top, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
getPos()
Vector2f Core::GUI::Props::getPos () inline
Definition at line 235 of file GUI_Constraint.h.
References pos, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by Core::GUI::Object::Window::exec().
getSize()
Vector2f Core::GUI::Props::getSize () inline
Definition at line 236 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::Window::exec().
modPos()
void Core::GUI::Props::modPos (int n1, int n2) inline
Definition at line 223 of file GUI_Constraint.h.
References Core::GUI::Props::_Position::constraint, pos, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by _Admin::init().
modSize()
void Core::GUI::Props::modSize (int n1, int n2) inline
Definition at line 230 of file GUI_Constraint.h.
modX()
void Core::GUI::Props::modX (int n) inline
Definition at line 226 of file GUI_Constraint.h.
References Core::GUI::Props::_Position::constraint, pos, and Core::Vector2f::x.
modY()
void Core::GUI::Props::modY (int n) inline
Definition at line 227 of file GUI_Constraint.h.
References Core::GUI::Props::_Position::constraint, pos, and Core::Vector2f::y.
setAnchor()
void Core::GUI::Props::setAnchor (iConstrain e = CONSTRAIN_CENTER) inline
Definition at line 231 of file GUI_Constraint.h.
References anchor.
Referenced by Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), _Admin::initColors(), _Admin::initSkillTree(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), Core::GUI::Props_ComboBox::Props_ComboBox(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), and Core::GUI::Props_Slider::Props_Slider().
setHeight()
void Core::GUI::Props::setHeight (int n, eSizeConstraint e = SIZE_CONSTRAINT_ABSOLUTE) inline
Definition at line 229 of file GUI_Constraint.h.
Referenced by Core::_TextSys::drawMulti(), Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Icon::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), _Admin::initColors(), _Admin::initSkillTree(), Props(), Core::GUI::Props_CheckBox::Props_CheckBox(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), Core::GUI::Props_ComboBox::Props_ComboBox(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), Core::GUI::Props_Slider::Props_Slider(), and Core::GUI::Props_Slider::swapOrientation().
setMaxHeight()
void Core::GUI::Props::setMaxHeight (int i) inline
Definition at line 253 of file GUI_Constraint.h.
setMaxWidth()
void Core::GUI::Props::setMaxWidth (int i) inline
Definition at line 250 of file GUI_Constraint.h.
setMinHeight()
void Core::GUI::Props::setMinHeight (int i) inline
Definition at line 252 of file GUI_Constraint.h.
setMinMaxHeight()
void Core::GUI::Props::setMinMaxHeight (int min, int max) inline
Definition at line 251 of file GUI_Constraint.h.
Referenced by Props().
setMinMaxWidth()
void Core::GUI::Props::setMinMaxWidth (int min, int max) inline
Definition at line 248 of file GUI_Constraint.h.
Referenced by _Admin::init(), Props(), Core::GUI::Props_Addon_Field::Props_Addon_Field(), Core::GUI::Props_Field::Props_Field(), and Core::GUI::Props_Label::Props_Label().
setMinWidth()
void Core::GUI::Props::setMinWidth (int i) inline
Definition at line 249 of file GUI_Constraint.h.
Referenced by _Admin::init(), and Core::GUI::Props_ProgressBar::Props_ProgressBar().
setOrigin()
void Core::GUI::Props::setOrigin (iConstrain e = CONSTRAIN_CENTER) inline
Definition at line 232 of file GUI_Constraint.h.
References origin.
Referenced by Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), _Admin::initColors(), _Admin::initSkillTree(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), Core::GUI::Props_ComboBox::Props_ComboBox(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), and Core::GUI::Props_Slider::Props_Slider().
setPadding() [1/3]
void Core::GUI::Props::setPadding (int i) inline
Definition at line 237 of file GUI_Constraint.h.
References Core::Vector4i::bottom, Core::Vector4i::left, Core::Vector4i::right, Core::Vector4i::top, and vPadding.
Referenced by Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::Icon::init(), _Admin::init(), _Admin::initColors(), Core::GUI::Props_CheckBox::Props_CheckBox(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), Core::GUI::Props_ComboBox::Props_ComboBox(), Core::GUI::Props_Field::Props_Field(), Core::GUI::Props_Icon::Props_Icon(), Core::GUI::Props_Label::Props_Label(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), Core::GUI::Props_Slider::Props_Slider(), Core::GUI::Props_TextArea::Props_TextArea(), Core::GUI::Props_TextArea::setPadding(), and Core::GUI::Props_Slider::swapOrientation().
setPadding() [2/3]
void Core::GUI::Props::setPadding (int t, int b, int l, int r) inline
Definition at line 238 of file GUI_Constraint.h.
References Core::Vector4i::bottom, Core::Vector4i::left, Core::Vector4i::right, t, Core::Vector4i::top, and vPadding.
setPadding() [3/3]
void Core::GUI::Props::setPadding (Vector4i v) inline
Definition at line 239 of file GUI_Constraint.h.
References vPadding.
setPos() [1/2]
void Core::GUI::Props::setPos (int n1, int n2) inline
Definition at line 222 of file GUI_Constraint.h.
References Core::GUI::Props::_Position::constraint, pos, Core::Vector2f::x, and Core::Vector2f::y.
setPos() [2/2]
void Core::GUI::Props::setPos (Vector2f v) inline
Definition at line 221 of file GUI_Constraint.h.
References Core::GUI::Props::_Position::constraint, pos, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), _Admin::initColors(), _Admin::initSkillTree(), Props(), Core::GUI::Props_Addon_Field::Props_Addon_Field(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), and Core::GUI::Props_Slider::Props_Slider().
setToolTip()
void Core::GUI::Props::setToolTip (std::string s) inline
Definition at line 245 of file GUI_Constraint.h.
References Core::GUI::Props::ToolTip::bShow, Core::GUI::Props::ToolTip::Text, and toolTip.
Referenced by _Admin::init(), and _Admin::initColors().
setVisibility()
void Core::GUI::Props::setVisibility (bool b) inline
Definition at line 242 of file GUI_Constraint.h.
References visibility.
Referenced by _Admin::init().
setWidth()
void Core::GUI::Props::setWidth (int n, eSizeConstraint e = SIZE_CONSTRAINT_ABSOLUTE) inline
Definition at line 228 of file GUI_Constraint.h.
Referenced by Core::_TextSys::drawMulti(), Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::ProgressBar::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ProgressBar::init(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Icon::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), _Admin::initColors(), _Admin::initSkillTree(), Props(), Core::GUI::Props_CheckBox::Props_CheckBox(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), Core::GUI::Props_ComboBox::Props_ComboBox(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), Core::GUI::Props_Slider::Props_Slider(), and Core::GUI::Props_Slider::swapOrientation().
setX()
void Core::GUI::Props::setX (int n) inline
Definition at line 224 of file GUI_Constraint.h.
References Core::GUI::Props::_Position::constraint, pos, and Core::Vector2f::x.
Referenced by _Admin::init().
setY()
void Core::GUI::Props::setY (int n) inline
Definition at line 225 of file GUI_Constraint.h.
References Core::GUI::Props::_Position::constraint, pos, and Core::Vector2f::y.
Referenced by Core::GUI::Object::ColorSwatch::init(), and _Admin::init().
Member Data Documentation
anchor
int Core::GUI::Props::anchor
The point at which this object is offset from the origin.
Definition at line 196 of file GUI_Constraint.h.
Referenced by Core::_TextSys::draw(), execSize(), Props(), and setAnchor().
bGlobalSettings
bool Core::GUI::Props::bGlobalSettings = true inline static
Used externally to allow multiple windows to use identical settings.
Definition at line 200 of file GUI_Constraint.h.
Referenced by _Admin::init(), and _Admin::run().
eEnablePadding
ePadding Core::GUI::Props::eEnablePadding
Definition at line 198 of file GUI_Constraint.h.
Referenced by disablePadding(), enablePadding(), execPos(), execSize(), and Props().
origin
int Core::GUI::Props::origin
The starting drawing point with respect to the parent, if present, otherwise full screen.
Definition at line 195 of file GUI_Constraint.h.
Referenced by execPos(), Props(), and setOrigin().
pos
Core::GUI::Props::_Position Core::GUI::Props::pos
Actual calculated position from origin and anchor constraints, automatically updated.
Referenced by Core::_IconSys::draw(), Core::_SpriteSys::draw(), Core::_TextSys::draw(), Core::GUI::GUI_Container::execObjects(), execPos(), execSize(), getPos(), modPos(), modX(), modY(), Props(), setPos(), setX(), setY(), Core::GUI::Object::TextArea::updateObjectState(), Core::GUI::Object::CheckBox::updateObjectState(), Core::GUI::Object::ProgressBar::updateObjectState(), Core::GUI::Object::Sprite::updateObjectState(), Core::GUI::Object::Button::updateObjectState(), Core::GUI::Object::ColorSwatch::updateObjectState(), Core::GUI::Object::Icon::updateObjectState(), and Core::GUI::Object::TextEdit::updateObjectState().
size
Core::GUI::Props::_Size Core::GUI::Props::size
Actual calculated width(x) and height(y) from origin and anchor constraints, automatically updated.
Referenced by Core::_IconSys::draw(), Core::_SpriteSys::draw(), Core::_TextSys::draw(), Core::_TextSys::drawMulti(), Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::Text::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::GUI_Container::execObjects(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Icon::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), Core::GUI::Props_Slider::swapOrientation(), Core::GUI::Object::CheckBox::update(), Core::GUI::Object::Window::update(), Core::GUI::Object::TextArea::updateObjectState(), Core::GUI::Object::CheckBox::updateObjectState(), Core::GUI::Object::ProgressBar::updateObjectState(), Core::GUI::Object::Sprite::updateObjectState(), Core::GUI::Object::Button::updateObjectState(), Core::GUI::Object::ColorSwatch::updateObjectState(), Core::GUI::Object::Icon::updateObjectState(), and Core::GUI::Object::TextEdit::updateObjectState().
toolTip
struct Core::GUI::Props::ToolTip Core::GUI::Props::toolTip
Referenced by disableToolTip(), enableToolTip(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::ProgressBar::exec(), Core::GUI::Object::CheckBox::exec(), Core::GUI::Object::ColorSwatch::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::Icon::exec(), Core::GUI::Object::ToolTip::init(), Props(), setToolTip(), and Core::GUI::Object::ToolTip::updateObjectState().
visibility
bool Core::GUI::Props::visibility
Controls if this object is drawn and any of its direct children.
Definition at line 199 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::Text::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::ProgressBar::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::CheckBox::exec(), Core::GUI::Object::ColorSwatch::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::ComboBox::exec(), Core::GUI::Object::Icon::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::Window::exec(), Core::GUI::GUI_Container::execObjects(), Props(), and setVisibility().
vPadding
Vector4i Core::GUI::Props::vPadding
Extra reserved space taken into account for origin.
Definition at line 197 of file GUI_Constraint.h.
Referenced by Core::_IconSys::draw(), Core::_TextSys::draw(), Core::_TextSys::drawMulti(), Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::Label::exec(), Core::GUI::GUI_Container::execObjects(), Core::GUI::Object::TextArea::init(), _Admin::init(), Props(), Core::GUI::Props_Window::Props_Window(), setPadding(), and Core::GUI::Props_Slider::swapOrientation().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Constraint.h