Project Parsec: Core::GUI::GUI::SliderInterface Class Reference
Core::GUI::GUI::SliderInterface Class Reference
#include <GUI.h>
Public Member Functions
template<typename T >
void add (std::string guiName, std::string sliderName, T *ptr, Constraints_Slider c=Constraints_Slider())
template<typename T >
void add (std::string guiName, std::string windowName, std::string sliderName, T *ptr, Constraints_Slider c=Constraints_Slider())
template<typename T >
void add (std::string guiName, std::string sliderName, T *ptr, Constraints_Slider *c)
template<typename T >
void add (std::string guiName, std::string windowName, std::string sliderName, T *ptr, Constraints_Slider *c)
template<typename T >
void setPointer (std::string guiName, std::string sliderName, T *tPtr)
Core::_Mouse::MOUSE_STATE getState (std::string guiName, std::string sliderName)
bool valueChanged (std::string guiName, std::string sliderName)
Constraints_Slider * get (std::string guiName, std::string sliderName)
SliderInterface (GUI *parent)
Public Attributes
GUI * gui
Detailed Description
Definition at line 135 of file GUI.h.
Constructor & Destructor Documentation
SliderInterface()
Core::GUI::GUI::SliderInterface::SliderInterface (GUI * parent) inline
Definition at line 146 of file GUI.h.
References gui.
Member Function Documentation
add() [1/4]
template<typename T > void Core::GUI::GUI::SliderInterface::add (std::string guiName, std::string sliderName, T * ptr, Constraints_Slider * c)
Definition at line 563 of file GUI.h.
References MY_NAMESPACE::gui, Core::GUI::Object::AnySlider::init(), and Core::GUI::Object::AnySlider::set().
add() [2/4]
template<typename T > void Core::GUI::GUI::SliderInterface::add (std::string guiName, std::string sliderName, T * ptr, Constraints_Slider c = Constraints_Slider())
Definition at line 541 of file GUI.h.
References MY_NAMESPACE::gui, Core::GUI::Object::AnySlider::init(), and Core::GUI::Object::AnySlider::set().
add() [3/4]
template<typename T > void Core::GUI::GUI::SliderInterface::add (std::string guiName, std::string windowName, std::string sliderName, T * ptr, Constraints_Slider * c)
Definition at line 574 of file GUI.h.
References MY_NAMESPACE::gui, Core::GUI::Object::AnySlider::init(), and Core::GUI::Object::AnySlider::set().
add() [4/4]
template<typename T > void Core::GUI::GUI::SliderInterface::add (std::string guiName, std::string windowName, std::string sliderName, T * ptr, Constraints_Slider c = Constraints_Slider())
Definition at line 552 of file GUI.h.
References MY_NAMESPACE::gui, Core::GUI::Object::AnySlider::init(), and Core::GUI::Object::AnySlider::set().
get()
Constraints_Slider * Core::GUI::GUI::SliderInterface::get (std::string guiName, std::string sliderName)
Definition at line 607 of file GUI.h.
References MY_NAMESPACE::gui.
getState()
Core::_Mouse::MOUSE_STATE Core::GUI::GUI::SliderInterface::getState (std::string guiName, std::string sliderName)
Definition at line 591 of file GUI.h.
References MY_NAMESPACE::gui.
setPointer()
template<typename T > void Core::GUI::GUI::SliderInterface::setPointer (std::string guiName, std::string sliderName, T * tPtr)
Definition at line 585 of file GUI.h.
References MY_NAMESPACE::gui.
valueChanged()
bool Core::GUI::GUI::SliderInterface::valueChanged (std::string guiName, std::string sliderName)
Definition at line 601 of file GUI.h.
References MY_NAMESPACE::gui.
Member Data Documentation
gui
GUI* Core::GUI::GUI::SliderInterface::gui
Definition at line 145 of file GUI.h.
Referenced by SliderInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI.h