Project Parsec: Core::Shader_System Class Reference
Core::Shader_System Class Reference
#include <shader.h>
Classes
struct _FogParams
struct ShaderData
Public Member Functions
Shader_System (Matrix_System &m)
~Shader_System ()
void SetMatrixSystem (Matrix_System &m)
void init (Vector2f *vRes, Vector3f *vPos)
void load ()
void load (SHADER_PROGRAMS newShader)
void use (SHADER_PROGRAMS eShader)
void getUniformVar (SHADER_PROGRAMS eShader,...)
void getUniform (SHADER_PROGRAMS eShader)
void getUniform (SHADER_PROGRAMS eShader, int iStyle, Color vColor, float fRotation, int iSpikes, float fThickness, float fBlend=0.0f, int iSize=1, Vector2f vTexCoord0=Vector2f(), Vector2f vTexCoord1=Vector2f())
void getUniform (SHADER_PROGRAMS eShader, _Lights *lightData, int n=0,...)
GLuint loadShader2 (const char *vertSrc, const char *fragSrc,...)
GLuint loadShader (const char *vertSrc, const char *geoSrc, const char *fragSrc,...)
std::string readShaderFile (std::string filePath, std::string filename, uint type)
Public Attributes
struct Core::Shader_System::ShaderData data
bool debug
bool debug2
struct {
enum { VERTEX_SHADER, GEOMETRY_SHADER, FRAGMENT_SHADER }
enum Core::Shader_System:: { ... }
} TYPE
struct Core::Shader_System::_FogParams worldFog
struct Core::Shader_System::_FogParams waterFog
struct Core::Shader_System::_FogParams activeFog
Protected Member Functions
void readSrc (const char *shaderSrc, GLuint shaderNum)
Private Attributes
Matrix_System * matrix
GLuint uiShaders [GLS_LAST]
Detailed Description
Definition at line 79 of file shader.h.
Constructor & Destructor Documentation
Shader_System()
Core::Shader_System::Shader_System (Matrix_System & m) inline
Definition at line 214 of file shader.h.
References debug, and debug2.
~Shader_System()
Core::Shader_System::~Shader_System () inline
Definition at line 221 of file shader.h.
References cout.
Member Function Documentation
getUniform() [1/3]
void Core::Shader_System::getUniform (SHADER_PROGRAMS eShader)
Definition at line 728 of file shader.cpp.
References Core::colors, cout, Core::Color::data, Core::_Colors::GetActive(), Core::_Colors::GetBack(), Core::_Colors::GetFront(), GL_FALSE, Core::GLS_BOUNDINGVOLUME_AABB, Core::GLS_BOUNDINGVOLUME_CYLINDER, Core::GLS_BOUNDINGVOLUME_OBB, Core::GLS_BOUNDINGVOLUME_SPHERE, Core::GLS_EXOSPHERE, Core::GLS_FLORA, Core::GLS_FONT, Core::GLS_ICON, Core::GLS_LINES, Core::GLS_MENU, Core::GLS_MOUSERAY, Core::GLS_NORMAL_LINE2, Core::GLS_STRATOSPHERE, Core::GLS_SUN, Core::GLS_THERMOSPHERE, Core::GLS_TROPOSPHERE, and uiShaders.
getUniform() [2/3]
void Core::Shader_System::getUniform (SHADER_PROGRAMS eShader, _Lights * lightData, int n = 0, ...)
Definition at line 954 of file shader.cpp.
References Core::Vector3f::data, Core::_Lights::GetAmbient(), Core::_Lights::GetAttenuation(), Core::_Lights::GetDiffuse(), Core::_Lights::GetDir(), Core::_Lights::GetNumLights(), Core::_Lights::GetPos(), Core::_Lights::GetSpecular(), Core::_Lights::GetType(), GL_FALSE, Core::GLS_FLAT, Core::GLS_PHONG, Core::GLS_PHONG_O2D, to_string(), and uiShaders.
getUniform() [3/3]
void Core::Shader_System::getUniform (SHADER_PROGRAMS eShader, int iStyle, Color vColor, float fRotation, int iSpikes, float fThickness, float fBlend = 0.0f, int iSize = 1, Vector2f vTexCoord0 = Vector2f(), Vector2f vTexCoord1 = Vector2f())
Definition at line 891 of file shader.cpp.
References cout, Core::Vector2f::data, Core::Color::data, GL_FALSE, Core::GLS_PARTICLE_SPRITE, Core::GLS_POINT_SPRITE, and uiShaders.
getUniformVar()
void Core::Shader_System::getUniformVar (SHADER_PROGRAMS eShader, ...)
Definition at line 519 of file shader.cpp.
References cout, Core::Vector3f::data, Core::Vector4f::data, GL_FALSE, Core::GLS_POINTS, Core::GLS_PP_BRIGHTNESS, Core::GLS_PP_BRIGHTNESS_FILTER, Core::GLS_PP_COMBINE, Core::GLS_PP_CONTRAST, Core::GLS_PP_HBLUR, Core::GLS_PP_RADIALBLUR, Core::GLS_PP_VBLUR, and uiShaders.
init()
void Core::Shader_System::init (Vector2f * vRes, Vector3f * vPos)
Definition at line 55 of file shader.cpp.
Referenced by MY_NAMESPACE::Setup().
load() [1/2]
void Core::Shader_System::load ()
Definition at line 61 of file shader.cpp.
References cout, Core::GLS_LAST, load(), Core::shader, and Core::sOffset.
Referenced by load(), and MY_NAMESPACE::Setup().
load() [2/2]
void Core::Shader_System::load (SHADER_PROGRAMS newShader)
Definition at line 71 of file shader.cpp.
References cout, Core::GLA_COLOR, Core::GLA_EXTRA, Core::GLA_NORMAL, Core::GLA_POSITION, Core::GLA_TEXTURE0, Core::GLA_VERTEX, Core::GLS_BOUNDINGVOLUME_AABB, Core::GLS_BOUNDINGVOLUME_CYLINDER, Core::GLS_BOUNDINGVOLUME_OBB, Core::GLS_BOUNDINGVOLUME_SPHERE, Core::GLS_EXOSPHERE, Core::GLS_FLAT, Core::GLS_FLORA, Core::GLS_FONT, Core::GLS_ICON, Core::GLS_LINES, Core::GLS_MENU, Core::GLS_MOUSERAY, Core::GLS_NORMAL_LINE2, Core::GLS_PARTICLE_SPRITE, Core::GLS_PHONG, Core::GLS_PHONG_O2D, Core::GLS_POINT_SPRITE, Core::GLS_POINTS, Core::GLS_PP_BRIGHTNESS, Core::GLS_PP_BRIGHTNESS_FILTER, Core::GLS_PP_COMBINE, Core::GLS_PP_CONTRAST, Core::GLS_PP_HBLUR, Core::GLS_PP_RADIALBLUR, Core::GLS_PP_VBLUR, Core::GLS_SNOW, Core::GLS_SNOW_3D, Core::GLS_SUN, loadShader(), readShaderFile(), Core::sOffset, TYPE, and uiShaders.
loadShader()
GLuint Core::Shader_System::loadShader (const char * vertSrc, const char * geoSrc, const char * fragSrc, ...)
Definition at line 1851 of file shader.cpp.
References debug, debug2, GL_COMPILE_STATUS, GL_FRAGMENT_SHADER, GL_GEOMETRY_SHADER, GL_LINK_STATUS, GL_VERTEX_SHADER, and readSrc().
Referenced by load().
loadShader2()
GLuint Core::Shader_System::loadShader2 (const char * vertSrc, const char * fragSrc, ...)
Definition at line 1755 of file shader.cpp.
References debug, debug2, GL_COMPILE_STATUS, GL_FRAGMENT_SHADER, GL_LINK_STATUS, GL_VERTEX_SHADER, and readSrc().
readShaderFile()
std::string Core::Shader_System::readShaderFile (std::string filePath, std::string filename, uint type)
Definition at line 21 of file shader.cpp.
References TYPE.
Referenced by load().
readSrc()
void Core::Shader_System::readSrc (const char * shaderSrc, GLuint shaderNum) protected
Definition at line 1748 of file shader.cpp.
Referenced by loadShader(), and loadShader2().
SetMatrixSystem()
void Core::Shader_System::SetMatrixSystem (Matrix_System & m) inline
Definition at line 228 of file shader.h.
use()
void Core::Shader_System::use (SHADER_PROGRAMS eShader) inline
Definition at line 251 of file shader.h.
References uiShaders.
Member Data Documentation
activeFog
struct Core::Shader_System::_FogParams Core::Shader_System::activeFog
data
struct Core::Shader_System::ShaderData Core::Shader_System::data
debug
bool Core::Shader_System::debug
Definition at line 229 of file shader.h.
Referenced by loadShader(), loadShader2(), and Shader_System().
debug2
bool Core::Shader_System::debug2
Definition at line 230 of file shader.h.
Referenced by loadShader(), loadShader2(), and Shader_System().
matrix
Matrix_System* Core::Shader_System::matrix private
Definition at line 81 of file shader.h.
TYPE
struct { ... } Core::Shader_System::TYPE
Referenced by load(), and readShaderFile().
uiShaders
GLuint Core::Shader_System::uiShaders[GLS_LAST] private
Definition at line 82 of file shader.h.
Referenced by getUniform(), getUniformVar(), load(), and use().
waterFog
struct Core::Shader_System::_FogParams Core::Shader_System::waterFog
worldFog
struct Core::Shader_System::_FogParams Core::Shader_System::worldFog
The documentation for this class was generated from the following files:
src/headers/core/shader.h
src/headers/core/shader.cpp