Project Parsec: Core::GUI::Object::ToolTip Class Reference
Core::GUI::Object::ToolTip Class Reference
#include <GUI_ToolTip.h>
Public Member Functions
ToolTip ()
virtual ~ToolTip ()
void init (Props &parent, std::string n)
void exec ()
void updateObjectState (iState eExternState)
Public Attributes
iState eObjectState
Protected Attributes
Window win
Text text
Label * label
Timer timer
Props_TextArea * con
Props * parent
std::string name
bool bInit
Detailed Description
Definition at line 26 of file GUI_ToolTip.h.
Constructor & Destructor Documentation
ToolTip()
Core::GUI::Object::ToolTip::ToolTip ()
Definition at line 49 of file GUI_ToolTip.h.
References bInit, con, parent, and Core::GUI::STATE_NONE.
~ToolTip()
Core::GUI::Object::ToolTip::~ToolTip () virtual
Definition at line 60 of file GUI_ToolTip.h.
References con, and label.
Member Function Documentation
exec()
void Core::GUI::Object::ToolTip::exec ()
Definition at line 138 of file GUI_ToolTip.h.
References bInit, Core::GUI::Props_Addon_Label::bShowLabel, con, Core::GUI::Props::_Size::constraint, Core::GUI::Object::Text::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Core::GameVars::font, Core::gameVars, Core::GameVars::Screen::half, Core::GUI::Props::_Size::isAutoSet(), Core::GUI::Props_Addon_Label::label, Core::Vector4i::left, Core::mouse, Core::Vector4i::right, Core::GameVars::screen, Core::GUI::Props::setHeight(), Core::GUI::Props::setPos(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::STATE_ACTIVE, text, Core::GUI::Props_TextArea::text, Core::GUI::Props::visibility, Core::GUI::Props::vPadding, Core::GameVars::Font::vSize, win, Core::Vector2f::x, Core::GUI::Props::_Size::_SizeConstraint::xAuto, Core::_Mouse::y, Core::Vector2f::y, and Core::GUI::Props::_Size::_SizeConstraint::yAuto.
Referenced by Core::GUI::Object::ProgressBar::execToolTip(), Core::GUI::Object::CheckBox::execToolTip(), Core::GUI::Object::ColorSwatch::execToolTip(), Core::GUI::Object::Button::execToolTip(), Core::GUI::Object::Sprite::execToolTip(), Core::GUI::Object::ComboBox::execToolTip(), and Core::GUI::Object::Icon::execToolTip().
init()
void Core::GUI::Object::ToolTip::init (Props & parent, std::string n)
Definition at line 65 of file GUI_ToolTip.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::Props::autoHeight(), Core::GUI::Props::autoWidth(), Core::GUI::Props_Window::Colors::back, bInit, Core::GUI::Props::ToolTip::border, Core::GUI::Props_Window::Colors::border, Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Props_Text::bWordWrap, Core::GUI::Props_Window::color, Core::GUI::Props_Text::color, Core::colors, con, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::CONSTRAIN_BOTTOM_RIGHT, Core::GUI::CONSTRAIN_CENTER, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_TOP, Core::GUI::Props::exec(), Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::Object::Text::init(), Core::GUI::Object::Window::init(), Core::GUI::Props_Addon_Label::label, p, Core::GUI::Props::ToolTip::padding, Core::GameVars::pallette, parent, Core::GUI::Props::ToolTip::radius, Core::GUI::Props::ToolTip::round, Core::GUI::Props::setAnchor(), Core::GUI::Props_Window::setBorder(), Core::GUI::Props_Text::setBuffer(), Core::GUI::Props::setHeight(), Core::GUI::Props::setOrigin(), Core::GUI::Props::setPadding(), Core::GUI::Props_TextArea::setPadding(), Core::GUI::Props::setPos(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props_Window::setRoundBorder(), Core::GUI::Props::setWidth(), Core::GUI::Props_Addon_Label::showLabel(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::stipple, Core::Stipple::STIPPLE_SHADE_50, text, Core::GUI::Props_Text::Colors::text, Core::GUI::Props_TextArea::text, Core::GUI::Props::toolTip, Core::GameVars::_Pallette::toolTip, win, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by Core::GUI::Object::TextArea::init(), Core::GUI::Object::ProgressBar::init(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Sprite::init(), Core::GUI::Object::Button::init(), and Core::GUI::Object::Icon::init().
updateObjectState()
void Core::GUI::Object::ToolTip::updateObjectState (iState eExternState)
Definition at line 124 of file GUI_ToolTip.h.
References Core::GUI::Props::ToolTip::hideDelay, Core::Timer::is_started(), parent, Core::GUI::Props::ToolTip::showDelay, Core::Timer::split(), Core::Timer::start(), Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::Timer::stop(), timer, and Core::GUI::Props::toolTip.
Referenced by Core::GUI::Object::TextArea::exec(), Core::GUI::Object::ProgressBar::exec(), Core::GUI::Object::CheckBox::exec(), Core::GUI::Object::ColorSwatch::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::Button::exec(), and Core::GUI::Object::Icon::exec().
Member Data Documentation
bInit
bool Core::GUI::Object::ToolTip::bInit protected
Definition at line 46 of file GUI_ToolTip.h.
Referenced by exec(), init(), and ToolTip().
con
Props_TextArea* Core::GUI::Object::ToolTip::con protected
Definition at line 42 of file GUI_ToolTip.h.
Referenced by exec(), init(), ToolTip(), and ~ToolTip().
eObjectState
iState Core::GUI::Object::ToolTip::eObjectState
Definition at line 35 of file GUI_ToolTip.h.
label
Label* Core::GUI::Object::ToolTip::label protected
Definition at line 40 of file GUI_ToolTip.h.
Referenced by ~ToolTip().
name
std::string Core::GUI::Object::ToolTip::name protected
Definition at line 45 of file GUI_ToolTip.h.
parent
Props* Core::GUI::Object::ToolTip::parent protected
Definition at line 43 of file GUI_ToolTip.h.
Referenced by init(), ToolTip(), and updateObjectState().
text
Text Core::GUI::Object::ToolTip::text protected
Definition at line 39 of file GUI_ToolTip.h.
Referenced by exec(), and init().
timer
Timer Core::GUI::Object::ToolTip::timer protected
Definition at line 41 of file GUI_ToolTip.h.
Referenced by updateObjectState().
win
Window Core::GUI::Object::ToolTip::win protected
Definition at line 38 of file GUI_ToolTip.h.
Referenced by exec(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_ToolTip.h