Project Parsec: Core::GUI::Object::Field< T > Class Template Reference
Core::GUI::Object::Field< T > Class Template Reference
#include <GUI_Constraint.h>
Public Member Functions
Field ()
Field (std::string n, T *tPtr, Props_Field c)
Field (std::string n, T *tPtr, Props_Field *c)
Field (Props &p, std::string n, T *tPtr, Props_Field c)
Field (Props &p, std::string n, T *tPtr, Props_Field *c)
Field (std::string n, T t, Props_Field c)
Field (std::string n, T t, Props_Field *c)
Field (Props &p, std::string n, T t, Props_Field c)
Field (Props &p, std::string n, T t, Props_Field *c)
virtual ~Field ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
void updateNoFocus ()
Public Member Functions inherited from Core::GUI::Object::FieldBase
FieldBase ()
Public Member Functions inherited from Core::GUI::Object::Base::Interactive< Props_Field, T >
Interactive ()
Interactive & operator= (const Interactive &src)
T getPtrValue ()
void setPointer (T *ptr)
T * getPointer ()
void init (Props_Addon_ReturnState *ptr)
int getState (int n=0)
bool valueChanged ()
void updateValuePtr ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Field >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Member Functions inherited from Core::GUI::Object::Base::Interactive_Base
Interactive_Base ()
~Interactive_Base ()
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Field >
int border
Props_Field * con
Props * parent
Private Member Functions
bool getFocus ()
void execEditStart ()
void execEditInput ()
void execEditInputGlobal ()
void updateObjectState (iState eExternState)
std::string execEdit ()
void execEditSet ()
template<>
void execEditStart ()
template<>
void execEditInput ()
template<>
std::string execEdit ()
Private Attributes
Window win
std::string sEditVar
bool bHasFocus
std::string lastValue
Value at the last cycle, used to determine bValueChanged.
Friends
class AnyField
Additional Inherited Members
Static Public Attributes inherited from Core::GUI::Object::FieldBase
static Core::_Keyboard keyboard = Core::_Keyboard()
static bool bKeyboardInit = false
Static Public Attributes inherited from Core::GUI::Object::Base::Interactive_Base
static bool bFocusPresent = false
static std::string sActiveObject = ""
static std::string sGroupObject [32] = { "" }
Protected Attributes inherited from Core::GUI::Object::Base::Interactive< Props_Field, T >
T * valuePtr
bool bLocalValue
bool bReturnInit
bool bValueChanged
Timer debounceTimer
Props_Addon_ReturnState * returnState
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Field >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
template<class T>
class Core::GUI::Object::Field< T >
Definition at line 45 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Field() [1/9]
template<class T > Core::GUI::Object::Field< T >::Field ()
Definition at line 80 of file GUI_Field.h.
Field() [2/9]
template<class T> Core::GUI::Object::Field< T >::Field (std::string n, T * tPtr, Props_Field< T > c)
Definition at line 84 of file GUI_Field.h.
Field() [3/9]
template<class T> Core::GUI::Object::Field< T >::Field (std::string n, T * tPtr, Props_Field< T > * c)
Definition at line 99 of file GUI_Field.h.
Field() [4/9]
template<class T> Core::GUI::Object::Field< T >::Field (Props & p, std::string n, T * tPtr, Props_Field< T > c)
Definition at line 113 of file GUI_Field.h.
Field() [5/9]
template<class T> Core::GUI::Object::Field< T >::Field (Props & p, std::string n, T * tPtr, Props_Field< T > * c)
Definition at line 128 of file GUI_Field.h.
Field() [6/9]
template<class T> Core::GUI::Object::Field< T >::Field (std::string n, T t, Props_Field< T > c)
Definition at line 142 of file GUI_Field.h.
Field() [7/9]
template<class T> Core::GUI::Object::Field< T >::Field (std::string n, T t, Props_Field< T > * c)
Definition at line 157 of file GUI_Field.h.
Field() [8/9]
template<class T> Core::GUI::Object::Field< T >::Field (Props & p, std::string n, T t, Props_Field< T > c)
Definition at line 171 of file GUI_Field.h.
Field() [9/9]
template<class T> Core::GUI::Object::Field< T >::Field (Props & p, std::string n, T t, Props_Field< T > * c)
Definition at line 186 of file GUI_Field.h.
~Field()
template<class T > Core::GUI::Object::Field< T >::~Field () virtual
Definition at line 200 of file GUI_Field.h.
Member Function Documentation
exec()
template<class T > void Core::GUI::Object::Field< T >::exec (iState eExternState = STATE_NONE)
Definition at line 361 of file GUI_Field.h.
Referenced by Core::GUI::Object::ComboBox::exec(), and Core::GUI::Object::Field< int >::execToolTip().
execEdit() [1/2]
template<class T > std::string Core::GUI::Object::Field< T >::execEdit () private
Definition at line 301 of file GUI_Field.h.
execEdit() [2/2]
template<> std::string Core::GUI::Object::Field< std::string >::execEdit () private
Definition at line 314 of file GUI_Field.h.
execEditInput() [1/2]
template<class T > void Core::GUI::Object::Field< T >::execEditInput () private
Definition at line 254 of file GUI_Field.h.
execEditInput() [2/2]
template<> void Core::GUI::Object::Field< std::string >::execEditInput () private
Definition at line 279 of file GUI_Field.h.
execEditInputGlobal()
template<class T > void Core::GUI::Object::Field< T >::execEditInputGlobal () private
Definition at line 240 of file GUI_Field.h.
execEditSet()
template<class T> void Core::GUI::Object::Field< T >::execEditSet () private
execEditStart() [1/2]
template<class T > void Core::GUI::Object::Field< T >::execEditStart () private
Definition at line 227 of file GUI_Field.h.
execEditStart() [2/2]
template<> void Core::GUI::Object::Field< std::string >::execEditStart () private
Definition at line 236 of file GUI_Field.h.
execToolTip()
template<class T > void Core::GUI::Object::Field< T >::execToolTip ()
Definition at line 410 of file GUI_Field.h.
getFocus()
template<class T> bool Core::GUI::Object::Field< T >::getFocus () inline private
Definition at line 71 of file GUI_Field.h.
init()
template<class T > void Core::GUI::Object::Field< T >::init ()
Definition at line 207 of file GUI_Field.h.
Referenced by Core::GUI::Object::ComboBox::init().
updateNoFocus()
template<class T > void Core::GUI::Object::Field< T >::updateNoFocus ()
Definition at line 418 of file GUI_Field.h.
updateObjectState()
template<class T > void Core::GUI::Object::Field< T >::updateObjectState (iState eExternState) private
Definition at line 322 of file GUI_Field.h.
Friends And Related Function Documentation
AnyField
template<class T> friend class AnyField friend
Definition at line 45 of file GUI_Field.h.
Member Data Documentation
bHasFocus
template<class T> bool Core::GUI::Object::Field< T >::bHasFocus private
Definition at line 69 of file GUI_Field.h.
Referenced by Core::GUI::Object::Field< int >::getFocus().
lastValue
template<class T> std::string Core::GUI::Object::Field< T >::lastValue private
Value at the last cycle, used to determine bValueChanged.
Definition at line 70 of file GUI_Field.h.
sEditVar
template<class T> std::string Core::GUI::Object::Field< T >::sEditVar private
Definition at line 68 of file GUI_Field.h.
toolTip
template<class T> ToolTip Core::GUI::Object::Field< T >::toolTip
Definition at line 60 of file GUI_Field.h.
win
template<class T> Window Core::GUI::Object::Field< T >::win private
Definition at line 67 of file GUI_Field.h.
The documentation for this class was generated from the following files:
src/headers/gamesys/GUI/GUI_Constraint.h
src/headers/gamesys/GUI/GUI_Field.h