Project Parsec: O2D Class Reference
O2D Class Reference
#include <water.h>
Public Member Functions
bool load (int iShift)
void shift (int iShift)
bool calc (bool bUpdate)
O2D (WorldMap &m, Atmosphere &a)
~O2D ()
Public Member Functions inherited from O2D_BASE
bool init ()
void clear ()
bool calc (bool bUpdate)
void draw (int iShader, bool bSort)
O2D_BASE (Atmosphere &a)
Private Attributes
WorldMap & map
Additional Inherited Members
Public Attributes inherited from O2D_BASE
O2dData data [9][9]
O2DGroups group [9][9]
Atmosphere & atmosphere
Detailed Description
Definition at line 31 of file water.h.
Constructor & Destructor Documentation
O2D()
O2D::O2D (WorldMap & m, Atmosphere & a) inline
Definition at line 39 of file water.h.
~O2D()
O2D::~O2D () inline
Definition at line 40 of file water.h.
References cout.
Member Function Documentation
calc()
bool O2D::calc (bool bUpdate = false)
Definition at line 456 of file water.h.
References cout, Core::GameVars::debug, Core::gameVars, WorldMap::getHeight(), GL_LINES, GL_TRIANGLE_STRIP, Core::GLA_EXTRA, Core::GLA_POSITION, Core::GLA_TEXTURE, Core::GLA_VERTEX, map, Core::GameVars::screen, t, x, Core::Vector4f::y, and z.
Referenced by _TheVoid::load(), and shift().
load()
bool O2D::load (int iShift = SHIFT_LAST)
Definition at line 128 of file water.h.
References cout, Core::GameVars::debug, WorldMap::dir, Core::gameVars, map, Core::readFile(), Core::GameVars::screen, WorldMap::vBase, x, and z.
Referenced by _TheVoid::load(), and shift().
shift()
void O2D::shift (int iShift)
Definition at line 70 of file water.h.
References calc(), cout, Core::gameVars, load(), and Core::GameVars::screen.
Referenced by _TheVoid::reload().
Member Data Documentation
map
WorldMap& O2D::map private
Definition at line 33 of file water.h.
Referenced by calc(), and load().
The documentation for this class was generated from the following file:
src/game/ref/runBattle/water.h