Project Parsec: Core::GUI::Object::ProgressBar Class Reference
Core::GUI::Object::ProgressBar Class Reference
#include <GUI_ProgressBar.h>
Public Member Functions
ProgressBar ()
ProgressBar (std::string n, int progress, Props_ProgressBar c)
ProgressBar (Props &p, std::string n, int progress, Props_ProgressBar c)
ProgressBar (std::string n, int progress, Props_ProgressBar *c)
ProgressBar (Props &p, std::string n, int progress, Props_ProgressBar *c)
ProgressBar (std::string n, int *progress, Props_ProgressBar c)
ProgressBar (Props &p, std::string n, int *progress, Props_ProgressBar c)
ProgressBar (std::string n, int *progress, Props_ProgressBar *c)
ProgressBar (Props &p, std::string n, int *progress, Props_ProgressBar *c)
virtual ~ProgressBar ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
void setPointer (int *ptr)
int * getPointer ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_ProgressBar >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_ProgressBar >
int border
Props_ProgressBar * con
Props * parent
Private Member Functions
void updateObjectState (iState eExternState)
Private Attributes
Window winBack
Window winProgress
Window winNoProgress
AnyField field
int * valuePtr
bool bLocalValue
Additional Inherited Members
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_ProgressBar >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 21 of file GUI_ProgressBar.h.
Constructor & Destructor Documentation
ProgressBar() [1/9]
Core::GUI::Object::ProgressBar::ProgressBar ()
Definition at line 57 of file GUI_ProgressBar.h.
References bLocalValue, and valuePtr.
ProgressBar() [2/9]
Core::GUI::Object::ProgressBar::ProgressBar (std::string n, int progress, Props_ProgressBar c)
Definition at line 62 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, and valuePtr.
ProgressBar() [3/9]
Core::GUI::Object::ProgressBar::ProgressBar (Props & p, std::string n, int progress, Props_ProgressBar c)
Definition at line 77 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, p, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, and valuePtr.
ProgressBar() [4/9]
Core::GUI::Object::ProgressBar::ProgressBar (std::string n, int progress, Props_ProgressBar * c)
Definition at line 92 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, and valuePtr.
ProgressBar() [5/9]
Core::GUI::Object::ProgressBar::ProgressBar (Props & p, std::string n, int progress, Props_ProgressBar * c)
Definition at line 106 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, p, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, and valuePtr.
ProgressBar() [6/9]
Core::GUI::Object::ProgressBar::ProgressBar (std::string n, int * progress, Props_ProgressBar c)
Definition at line 120 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, and valuePtr.
ProgressBar() [7/9]
Core::GUI::Object::ProgressBar::ProgressBar (Props & p, std::string n, int * progress, Props_ProgressBar c)
Definition at line 135 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, p, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, and valuePtr.
ProgressBar() [8/9]
Core::GUI::Object::ProgressBar::ProgressBar (std::string n, int * progress, Props_ProgressBar * c)
Definition at line 150 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, and valuePtr.
ProgressBar() [9/9]
Core::GUI::Object::ProgressBar::ProgressBar (Props & p, std::string n, int * progress, Props_ProgressBar * c)
Definition at line 164 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, p, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, and valuePtr.
~ProgressBar()
Core::GUI::Object::ProgressBar::~ProgressBar () virtual
Definition at line 178 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bLocalCon, bLocalValue, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, and valuePtr.
Member Function Documentation
exec()
void Core::GUI::Object::ProgressBar::exec (iState eExternState = STATE_NONE)
Definition at line 268 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Props::ToolTip::bShow, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Core::GUI::Object::AnyField::exec(), field, Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, Core::GUI::Props::setWidth(), Core::GUI::SIZE_CONSTRAINT_RELATIVE, Core::GUI::STATE_NONE, toolTip, Core::GUI::Props::toolTip, Core::GUI::Object::ToolTip::updateObjectState(), updateObjectState(), valuePtr, Core::GUI::Props::visibility, winBack, winNoProgress, and winProgress.
execToolTip()
void Core::GUI::Object::ProgressBar::execToolTip ()
Definition at line 287 of file GUI_ProgressBar.h.
References Core::GUI::Object::ToolTip::exec(), and toolTip.
getPointer()
int* Core::GUI::Object::ProgressBar::getPointer () inline
Definition at line 45 of file GUI_ProgressBar.h.
References valuePtr.
init()
void Core::GUI::Object::ProgressBar::init ()
Definition at line 183 of file GUI_ProgressBar.h.
References Core::GUI::Object::Base::Generic< Props_ProgressBar >::bHasParent, Core::GUI::Object::Base::Generic< Props_ProgressBar >::bInit, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, Core::GUI::Props_ProgressBar::empty, Core::GUI::Props::exec(), field, Core::GUI::Props_ProgressBar::field, Core::GUI::Props_ProgressBar::fill, Core::GUI::Object::ToolTip::init(), Core::GUI::Object::Window::init(), Core::GUI::Object::AnyField::init(), Core::GUI::Object::Base::Generic< Props_ProgressBar >::parent, Core::GUI::Object::AnyField::set(), Core::GUI::Props::setWidth(), Core::GUI::SIZE_CONSTRAINT_RELATIVE, toolTip, valuePtr, winBack, winNoProgress, and winProgress.
setPointer()
void Core::GUI::Object::ProgressBar::setPointer (int * ptr) inline
Definition at line 39 of file GUI_ProgressBar.h.
References bLocalValue, field, Core::GUI::Object::AnyField::setPointer(), and valuePtr.
updateObjectState()
void Core::GUI::Object::ProgressBar::updateObjectState (iState eExternState) private
Definition at line 255 of file GUI_ProgressBar.h.
References Core::_Mouse::checkInput(), Core::GUI::Object::Base::Generic< Props_ProgressBar >::con, Core::GUI::Object::Base::Generic< Props_ProgressBar >::enabled(), Core::gameVars, Core::GameVars::Screen::half, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_NONE, Core::GUI::Object::Base::Generic< Props_ProgressBar >::mState, Core::GUI::Props::pos, Core::GameVars::screen, Core::GUI::Props::size, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
Member Data Documentation
bLocalValue
bool Core::GUI::Object::ProgressBar::bLocalValue private
Definition at line 53 of file GUI_ProgressBar.h.
Referenced by ProgressBar(), setPointer(), and ~ProgressBar().
field
AnyField Core::GUI::Object::ProgressBar::field private
Definition at line 51 of file GUI_ProgressBar.h.
Referenced by exec(), init(), and setPointer().
toolTip
ToolTip Core::GUI::Object::ProgressBar::toolTip
Definition at line 35 of file GUI_ProgressBar.h.
Referenced by exec(), execToolTip(), and init().
valuePtr
int* Core::GUI::Object::ProgressBar::valuePtr private
Definition at line 52 of file GUI_ProgressBar.h.
Referenced by exec(), getPointer(), init(), ProgressBar(), setPointer(), and ~ProgressBar().
winBack
Window Core::GUI::Object::ProgressBar::winBack private
Definition at line 48 of file GUI_ProgressBar.h.
Referenced by exec(), and init().
winNoProgress
Window Core::GUI::Object::ProgressBar::winNoProgress private
Definition at line 48 of file GUI_ProgressBar.h.
Referenced by exec(), and init().
winProgress
Window Core::GUI::Object::ProgressBar::winProgress private
Definition at line 48 of file GUI_ProgressBar.h.
Referenced by exec(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_ProgressBar.h