Project Parsec: Core::Matrix_System Class Reference
Core::Matrix_System Class Reference
#include <matrix.h>
Public Types
enum MATRIX_MODES { MM_PERSPECTIVE, MM_ORTHO, MM_LIGHT }
Public Member Functions
Matrix_System ()
~Matrix_System ()
void LoadIdentity (Matrix44f m)
void SetIdentity ()
void Scale (float f)
void Scale (float x, float y, float z)
void Translate (Vector3f &v)
void Translate (float x, float y, float z)
void Translate (Matrix44f &m, float x, float y, float z)
void RotateAxis (Vector3f vAxis, Radians theta)
Matrix44f GetRotateAxis (Vector3f vAxis, Radians theta)
void Rotate (Vector3f vRotation)
void Rotate (Radians angle, float x, float y, float z)
void Rotate (Matrix44f &out, Radians angle, float x, float y, float z)
void Skew (Radians angle, float x, float y, float z)
void SetPerspective (Degrees degFov, float fAspect, float fNear, float fFar)
void SetOrtho (float fHalfWidth, float fHalfHeight, float fNear, float fFar)
void SetLight (float fHalfWidth, float fHalfHeight, float fNear, float fFar)
void SetProjection (GLenum eProj)
void LookAt (Vector3f vEye, Vector3f vCenter, Vector3f vUp)
const Matrix44f & GetLookAt (Vector3f vEye, Vector3f vCenter, Vector3f vUp)
void SetModelView (Matrix44f &mMatrix)
Matrix44f & GetTransView (void)
Matrix44f & GetRotView (void)
Matrix44f & GetModelView (void)
Matrix44f & GetModelViewProjection (void)
Matrix44f & GetProjectionMatrix (void)
void Apply (Matrix44f &mMatrix)
void CopyMatrix (Matrix44f &dst, Matrix44f &src)
void SetTransform ()
void Push ()
void Pop ()
Public Attributes
int iCurrentStack
Matrix44f * mvStack
Matrix44f * mMatrix
Matrix44f * mtvStack
Matrix44f * mrvStack
Protected Attributes
int iStackDepth
Matrix44f * mvpStack
Matrix44f projMatrix
Matrix44f perspectiveMatrix
Matrix44f orthographicMatrix
Matrix33f mNormalMatrix
Matrix44f mLookAt
Matrix44f lightMatrix
Detailed Description
Definition at line 16 of file matrix.h.
Member Enumeration Documentation
MATRIX_MODES
enum Core::Matrix_System::MATRIX_MODES
Enumerator
MM_PERSPECTIVE
MM_ORTHO
MM_LIGHT
Definition at line 28 of file matrix.h.
Constructor & Destructor Documentation
Matrix_System()
Core::Matrix_System::Matrix_System ()
Definition at line 11 of file matrix.cpp.
References cout, iCurrentStack, iStackDepth, LoadIdentity(), mrvStack, mtvStack, mvpStack, and mvStack.
~Matrix_System()
Core::Matrix_System::~Matrix_System ()
Definition at line 29 of file matrix.cpp.
References cout, mrvStack, mtvStack, mvpStack, and mvStack.
Member Function Documentation
Apply()
void Core::Matrix_System::Apply (Matrix44f & mMatrix) inline
Definition at line 74 of file matrix.h.
References iCurrentStack, mMatrix, and mvStack.
CopyMatrix()
void Core::Matrix_System::CopyMatrix (Matrix44f & dst, Matrix44f & src) inline
Definition at line 82 of file matrix.h.
GetLookAt()
const Matrix44f & Core::Matrix_System::GetLookAt (Vector3f vEye, Vector3f vCenter, Vector3f vUp)
Definition at line 511 of file matrix.cpp.
References Core::_gmath::Cross(), Core::gmath, LoadIdentity(), M, mLookAt, Core::_gmath::Normalize(), and Translate().
GetModelView()
Matrix44f& Core::Matrix_System::GetModelView (void) inline
Definition at line 70 of file matrix.h.
References iCurrentStack, and mvStack.
GetModelViewProjection()
Matrix44f& Core::Matrix_System::GetModelViewProjection (void) inline
Definition at line 71 of file matrix.h.
References iCurrentStack, and mvpStack.
GetProjectionMatrix()
Matrix44f& Core::Matrix_System::GetProjectionMatrix (void) inline
Definition at line 72 of file matrix.h.
References projMatrix.
GetRotateAxis()
Matrix44f Core::Matrix_System::GetRotateAxis (Vector3f vAxis, Radians theta)
Definition at line 152 of file matrix.cpp.
References Core::Matrix44f::a0, Core::Matrix44f::a1, Core::Matrix44f::a2, Core::Matrix44f::a3, Core::Matrix44f::b0, Core::Matrix44f::b1, Core::Matrix44f::b2, Core::Matrix44f::b3, Core::Matrix44f::c0, Core::Matrix44f::c1, Core::Matrix44f::c2, Core::Matrix44f::c3, Core::Matrix44f::d0, Core::Matrix44f::d1, Core::Matrix44f::d2, Core::Matrix44f::d3, LoadIdentity(), Core::Radians::radians, Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
GetRotView()
Matrix44f& Core::Matrix_System::GetRotView (void) inline
Definition at line 69 of file matrix.h.
References iCurrentStack, and mrvStack.
GetTransView()
Matrix44f& Core::Matrix_System::GetTransView (void) inline
Definition at line 68 of file matrix.h.
References iCurrentStack, and mtvStack.
LoadIdentity()
void Core::Matrix_System::LoadIdentity (Matrix44f m)
Definition at line 39 of file matrix.cpp.
Referenced by GetLookAt(), GetRotateAxis(), LookAt(), Matrix_System(), Rotate(), RotateAxis(), Scale(), SetIdentity(), SetLight(), SetOrtho(), Skew(), and Translate().
LookAt()
void Core::Matrix_System::LookAt (Vector3f vEye, Vector3f vCenter, Vector3f vUp)
Definition at line 477 of file matrix.cpp.
References Core::_gmath::Cross(), Core::gmath, iCurrentStack, LoadIdentity(), M, mvStack, Core::_gmath::Normalize(), SetTransform(), and Translate().
Pop()
void Core::Matrix_System::Pop ()
Definition at line 568 of file matrix.cpp.
References iCurrentStack.
Referenced by Core::GameSys::MapSys::draw(), _Game::Update(), and Core::GameSys::_Satellite::update().
Push()
void Core::Matrix_System::Push ()
Definition at line 544 of file matrix.cpp.
References iCurrentStack, iStackDepth, mrvStack, mtvStack, mvpStack, and mvStack.
Referenced by Core::GameSys::MapSys::draw(), _Game::Update(), and Core::GameSys::_Satellite::update().
Rotate() [1/3]
void Core::Matrix_System::Rotate (Matrix44f & out, Radians angle, float x, float y, float z)
Definition at line 235 of file matrix.cpp.
References LoadIdentity(), M, x, y, and z.
Rotate() [2/3]
void Core::Matrix_System::Rotate (Radians angle, float x, float y, float z)
Definition at line 171 of file matrix.cpp.
References iCurrentStack, LoadIdentity(), M, mrvStack, mvStack, x, y, and z.
Rotate() [3/3]
void Core::Matrix_System::Rotate (Vector3f vRotation)
Definition at line 164 of file matrix.cpp.
References Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by _Game::Update().
RotateAxis()
void Core::Matrix_System::RotateAxis (Vector3f vAxis, Radians theta)
Definition at line 137 of file matrix.cpp.
References Core::Matrix44f::a0, Core::Matrix44f::a1, Core::Matrix44f::a2, Core::Matrix44f::a3, Core::Matrix44f::b0, Core::Matrix44f::b1, Core::Matrix44f::b2, Core::Matrix44f::b3, Core::Matrix44f::c0, Core::Matrix44f::c1, Core::Matrix44f::c2, Core::Matrix44f::c3, Core::Matrix44f::d0, Core::Matrix44f::d1, Core::Matrix44f::d2, Core::Matrix44f::d3, iCurrentStack, LoadIdentity(), mrvStack, mvStack, Core::Radians::radians, Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
Scale() [1/2]
void Core::Matrix_System::Scale (float f)
Definition at line 71 of file matrix.cpp.
Referenced by Core::GameSys::MapSys::draw().
Scale() [2/2]
void Core::Matrix_System::Scale (float x, float y, float z)
Definition at line 86 of file matrix.cpp.
References iCurrentStack, LoadIdentity(), mvStack, x, y, and z.
SetIdentity()
void Core::Matrix_System::SetIdentity ()
Definition at line 67 of file matrix.cpp.
References iCurrentStack, LoadIdentity(), and mvStack.
Referenced by Core::GameSys::_Satellite::drawFlare(), and _Game::Update().
SetLight()
void Core::Matrix_System::SetLight (float fHalfWidth, float fHalfHeight, float fNear, float fFar)
Definition at line 441 of file matrix.cpp.
References lightMatrix, and LoadIdentity().
SetModelView()
void Core::Matrix_System::SetModelView (Matrix44f & mMatrix) inline
Definition at line 67 of file matrix.h.
References iCurrentStack, mMatrix, mvStack, and SetTransform().
SetOrtho()
void Core::Matrix_System::SetOrtho (float fHalfWidth, float fHalfHeight, float fNear, float fFar)
Definition at line 423 of file matrix.cpp.
References LoadIdentity(), and orthographicMatrix.
SetPerspective()
void Core::Matrix_System::SetPerspective (Degrees degFov, float fAspect, float fNear, float fFar)
Definition at line 378 of file matrix.cpp.
References perspectiveMatrix, and Core::Degrees::toRadians().
SetProjection()
void Core::Matrix_System::SetProjection (GLenum eProj)
Definition at line 459 of file matrix.cpp.
References MM_ORTHO, MM_PERSPECTIVE, orthographicMatrix, perspectiveMatrix, and projMatrix.
Referenced by Core::GameSys::_Satellite::drawFlare(), _Game::Update(), and Core::GameSys::_Satellite::update().
SetTransform()
void Core::Matrix_System::SetTransform () inline
Definition at line 88 of file matrix.h.
References iCurrentStack, mvpStack, mvStack, and projMatrix.
Referenced by LookAt(), SetModelView(), and _Game::Update().
Skew()
void Core::Matrix_System::Skew (Radians angle, float x = 0, float y = 0, float z = 0)
Definition at line 298 of file matrix.cpp.
References Core::gmath, iCurrentStack, LoadIdentity(), M, Core::_gmath::Max(), and mvStack.
Translate() [1/3]
void Core::Matrix_System::Translate (float x, float y, float z)
Definition at line 104 of file matrix.cpp.
References iCurrentStack, LoadIdentity(), mtvStack, mvStack, x, y, and z.
Translate() [2/3]
void Core::Matrix_System::Translate (Matrix44f & m, float x, float y, float z)
Definition at line 122 of file matrix.cpp.
References iCurrentStack, LoadIdentity(), mvStack, x, y, and z.
Translate() [3/3]
void Core::Matrix_System::Translate (Vector3f & v)
Definition at line 100 of file matrix.cpp.
Referenced by GetLookAt(), LookAt(), and _Game::Update().
Member Data Documentation
iCurrentStack
int Core::Matrix_System::iCurrentStack
Definition at line 29 of file matrix.h.
Referenced by Apply(), GetModelView(), GetModelViewProjection(), GetRotView(), GetTransView(), LookAt(), Matrix_System(), Pop(), Push(), Rotate(), RotateAxis(), Scale(), SetIdentity(), SetModelView(), SetTransform(), Skew(), and Translate().
iStackDepth
int Core::Matrix_System::iStackDepth protected
Definition at line 19 of file matrix.h.
Referenced by Matrix_System(), and Push().
lightMatrix
Matrix44f Core::Matrix_System::lightMatrix protected
Definition at line 26 of file matrix.h.
Referenced by SetLight().
mLookAt
Matrix44f Core::Matrix_System::mLookAt protected
Definition at line 25 of file matrix.h.
Referenced by GetLookAt().
mMatrix
Matrix44f* Core::Matrix_System::mMatrix
Definition at line 31 of file matrix.h.
Referenced by Apply(), and SetModelView().
mNormalMatrix
Matrix33f Core::Matrix_System::mNormalMatrix protected
Definition at line 24 of file matrix.h.
mrvStack
Matrix44f* Core::Matrix_System::mrvStack
Definition at line 33 of file matrix.h.
Referenced by GetRotView(), Matrix_System(), Push(), Rotate(), RotateAxis(), and ~Matrix_System().
mtvStack
Matrix44f* Core::Matrix_System::mtvStack
Definition at line 32 of file matrix.h.
Referenced by GetTransView(), Matrix_System(), Push(), Translate(), and ~Matrix_System().
mvpStack
Matrix44f* Core::Matrix_System::mvpStack protected
Definition at line 20 of file matrix.h.
Referenced by GetModelViewProjection(), Matrix_System(), Push(), SetTransform(), and ~Matrix_System().
mvStack
Matrix44f* Core::Matrix_System::mvStack
Definition at line 30 of file matrix.h.
Referenced by Apply(), GetModelView(), LookAt(), Matrix_System(), Push(), Rotate(), RotateAxis(), Scale(), SetIdentity(), SetModelView(), SetTransform(), Skew(), Translate(), and ~Matrix_System().
orthographicMatrix
Matrix44f Core::Matrix_System::orthographicMatrix protected
Definition at line 23 of file matrix.h.
Referenced by SetOrtho(), and SetProjection().
perspectiveMatrix
Matrix44f Core::Matrix_System::perspectiveMatrix protected
Definition at line 22 of file matrix.h.
Referenced by SetPerspective(), and SetProjection().
projMatrix
Matrix44f Core::Matrix_System::projMatrix protected
Definition at line 21 of file matrix.h.
Referenced by GetProjectionMatrix(), SetProjection(), and SetTransform().
The documentation for this class was generated from the following files:
src/headers/core/matrix.h
src/headers/core/matrix.cpp