Project Parsec: Core::GUI::GUI_Container::CheckBoxInterface Class Reference
Core::GUI::GUI_Container::CheckBoxInterface Class Reference
#include <GUI_Container.h>
Public Member Functions
void add (std::string checkBoxName, bool b, Props_CheckBox c, Props *p=nullptr)
void add (std::string checkBoxName, bool b, Props_CheckBox *c, Props *p=nullptr)
void add (std::string checkBoxName, bool *b, Props_CheckBox c, Props *p=nullptr)
void add (std::string checkBoxName, bool *b, Props_CheckBox *c, Props *p=nullptr)
int groupState (int iGroup, int n=0)
Object::CheckBox & operator[] (std::string checkBoxName)
Props_CheckBox & operator() (std::string checkBoxName)
CheckBoxInterface (GUI_Container *parent)
~CheckBoxInterface ()
Private Member Functions
void pushData (std::string name, Object::CheckBox *data)
Private Attributes
std::vector< Object::CheckBox * > checkBoxes
Map_si map
GUI_Container * gui
Friends
class GUI_Container
Detailed Description
Definition at line 220 of file GUI_Container.h.
Constructor & Destructor Documentation
CheckBoxInterface()
Core::GUI::GUI_Container::CheckBoxInterface::CheckBoxInterface (GUI_Container * parent) inline
Definition at line 238 of file GUI_Container.h.
References gui, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
~CheckBoxInterface()
Core::GUI::GUI_Container::CheckBoxInterface::~CheckBoxInterface () inline
Definition at line 239 of file GUI_Container.h.
References checkBoxes.
Member Function Documentation
add() [1/4]
void Core::GUI::GUI_Container::CheckBoxInterface::add (std::string checkBoxName, bool * b, Props_CheckBox * c, Props * p = nullptr)
Definition at line 628 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [2/4]
void Core::GUI::GUI_Container::CheckBoxInterface::add (std::string checkBoxName, bool * b, Props_CheckBox c, Props * p = nullptr)
Definition at line 621 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [3/4]
void Core::GUI::GUI_Container::CheckBoxInterface::add (std::string checkBoxName, bool b, Props_CheckBox * c, Props * p = nullptr)
Definition at line 614 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [4/4]
void Core::GUI::GUI_Container::CheckBoxInterface::add (std::string checkBoxName, bool b, Props_CheckBox c, Props * p = nullptr)
Definition at line 607 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
groupState()
int Core::GUI::GUI_Container::CheckBoxInterface::groupState (int iGroup, int n = 0)
Definition at line 635 of file GUI_Container.h.
operator()()
Props_CheckBox& Core::GUI::GUI_Container::CheckBoxInterface::operator() (std::string checkBoxName) inline
Definition at line 237 of file GUI_Container.h.
References checkBoxes, Core::GUI::Object::Base::Generic< Props_Window >::con, and map.
operator[]()
Object::CheckBox& Core::GUI::GUI_Container::CheckBoxInterface::operator[] (std::string checkBoxName) inline
Definition at line 236 of file GUI_Container.h.
References checkBoxes, and map.
pushData()
void Core::GUI::GUI_Container::CheckBoxInterface::pushData (std::string name, Object::CheckBox * data) private
Definition at line 600 of file GUI_Container.h.
References Core::GUI::GUI_Container::map.
Friends And Related Function Documentation
GUI_Container
friend class GUI_Container friend
Definition at line 221 of file GUI_Container.h.
Member Data Documentation
checkBoxes
std::vector<Object::CheckBox*> Core::GUI::GUI_Container::CheckBoxInterface::checkBoxes private
Definition at line 224 of file GUI_Container.h.
Referenced by Core::GUI::GUI_Container::execObjects(), Core::GUI::GUI_Container::execToolTips(), operator()(), operator[](), and ~CheckBoxInterface().
gui
GUI_Container* Core::GUI::GUI_Container::CheckBoxInterface::gui private
Definition at line 226 of file GUI_Container.h.
Referenced by CheckBoxInterface().
map
Map_si Core::GUI::GUI_Container::CheckBoxInterface::map private
Definition at line 225 of file GUI_Container.h.
Referenced by operator()(), and operator[]().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Container.h