Project Parsec: Core::GUI::GUI::TextAreaInterface Class Reference
Core::GUI::GUI::TextAreaInterface Class Reference
#include <GUI.h>
Public Member Functions
void add (std::string guiName, std::string textAreaName, Constraints_TextArea c)
void add (std::string guiName, std::string windowName, std::string textArealName, Constraints_TextArea c)
void add (std::string guiName, std::string textAreaName, Constraints_TextArea *c)
void add (std::string guiName, std::string windowName, std::string textArealName, Constraints_TextArea *c)
Constraints_TextArea * get (std::string guiName, std::string textAreaName)
TextAreaInterface (GUI *parent)
Public Attributes
GUI * gui
Detailed Description
Definition at line 174 of file GUI.h.
Constructor & Destructor Documentation
TextAreaInterface()
Core::GUI::GUI::TextAreaInterface::TextAreaInterface (GUI * parent) inline
Definition at line 182 of file GUI.h.
References gui.
Member Function Documentation
add() [1/4]
void Core::GUI::GUI::TextAreaInterface::add (std::string guiName, std::string textAreaName, Constraints_TextArea * c)
Definition at line 739 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::TextArea::init().
add() [2/4]
void Core::GUI::GUI::TextAreaInterface::add (std::string guiName, std::string textAreaName, Constraints_TextArea c)
Definition at line 720 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::TextArea::init().
add() [3/4]
void Core::GUI::GUI::TextAreaInterface::add (std::string guiName, std::string windowName, std::string textArealName, Constraints_TextArea * c)
Definition at line 748 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::TextArea::init().
add() [4/4]
void Core::GUI::GUI::TextAreaInterface::add (std::string guiName, std::string windowName, std::string textArealName, Constraints_TextArea c)
Definition at line 729 of file GUI.h.
References MY_NAMESPACE::gui, and Core::GUI::Object::TextArea::init().
get()
Constraints_TextArea * Core::GUI::GUI::TextAreaInterface::get (std::string guiName, std::string textAreaName)
Definition at line 758 of file GUI.h.
References MY_NAMESPACE::gui.
Member Data Documentation
gui
GUI* Core::GUI::GUI::TextAreaInterface::gui
Definition at line 181 of file GUI.h.
Referenced by TextAreaInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI.h