Project Parsec: Core::GUI::Props_Icon Class Reference
Core::GUI::Props_Icon Class Reference
#include <GUI_Constraint.h>
Classes
struct Colors
Public Member Functions
void setIconIDs (int b, int h, int a)
void setButtonType (eButtonType e)
void setDebounceTime (int i)
void setImage (std::string s)
Props_Icon ()
~Props_Icon ()
Public Member Functions inherited from Core::GUI::Props
void setPos (Vector2f v)
void setPos (int n1, int n2)
void modPos (int n1, int n2)
void setX (int n)
void setY (int n)
void modX (int n)
void modY (int n)
void setWidth (int n, eSizeConstraint e=SIZE_CONSTRAINT_ABSOLUTE)
void setHeight (int n, eSizeConstraint e=SIZE_CONSTRAINT_ABSOLUTE)
void modSize (int n1, int n2)
void setAnchor (iConstrain e=CONSTRAIN_CENTER)
void setOrigin (iConstrain e=CONSTRAIN_CENTER)
void exec ()
void exec (Props c)
Vector2f getPos ()
Vector2f getSize ()
void setPadding (int i)
void setPadding (int t, int b, int l, int r)
void setPadding (Vector4i v)
void enablePadding (ePadding e=PADDING_POSITION)
void disablePadding ()
void setVisibility (bool b)
void enableToolTip ()
void disableToolTip ()
void setToolTip (std::string s)
void autoWidth (bool b=true)
void autoHeight (bool b=true)
void setMinMaxWidth (int min, int max)
void setMinWidth (int i)
void setMaxWidth (int i)
void setMinMaxHeight (int min, int max)
void setMinHeight (int i)
void setMaxHeight (int i)
Props ()
Props (Props &src)
~Props ()
Public Member Functions inherited from Core::GUI::Props_Addon_Background
void showBackground ()
void hideBackground ()
Props_Addon_Background ()
Public Member Functions inherited from Core::GUI::Props_Addon_Label
void showLabel ()
void hideLabel ()
Props_Addon_Label ()
Public Member Functions inherited from Core::GUI::Props_Addon_Group
void setGroup (int i)
Props_Addon_Group ()
Public Member Functions inherited from Core::GUI::Props_Addon_Toggle
void setToggle (bool b)
Props_Addon_Toggle ()
Public Member Functions inherited from Core::GUI::Props_Addon_ReturnState
void setOnState (int i, int n=0)
void setOffState (int i, int n=0)
Props_Addon_ReturnState ()
Props_Addon_ReturnState (Props_Addon_ReturnState &src)
Props_Addon_ReturnState & operator= (const Props_Addon_ReturnState &src)
Public Attributes
struct Core::GUI::Props_Icon::Colors color
struct {
int base
int active
int highlight
} iconID
eButtonType buttonType
int debounceTime
std::string iconAtlas
Public Attributes inherited from Core::GUI::Props
Core::GUI::Props::_Position pos
Actual calculated position from origin and anchor constraints, automatically updated.
Core::GUI::Props::_Size size
Actual calculated width(x) and height(y) from origin and anchor constraints, automatically updated.
int origin
The starting drawing point with respect to the parent, if present, otherwise full screen.
int anchor
The point at which this object is offset from the origin.
Vector4i vPadding
Extra reserved space taken into account for origin.
ePadding eEnablePadding
bool visibility
Controls if this object is drawn and any of its direct children.
struct Core::GUI::Props::ToolTip toolTip
Public Attributes inherited from Core::GUI::Props_Addon_Background
bool bShowBackground
Props_Window background
Public Attributes inherited from Core::GUI::Props_Addon_Label
bool bShowLabel
Props_Label label
Public Attributes inherited from Core::GUI::Props_Addon_Group
int iGroup
Public Attributes inherited from Core::GUI::Props_Addon_Toggle
bool bToggle
Public Attributes inherited from Core::GUI::Props_Addon_ReturnState
int on [8]
int off [8]
Friends
class Object::Icon
Additional Inherited Members
Static Public Attributes inherited from Core::GUI::Props
static bool bGlobalSettings = true
Used externally to allow multiple windows to use identical settings.
Detailed Description
Definition at line 1270 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Props_Icon()
Core::GUI::Props_Icon::Props_Icon () inline
Definition at line 1302 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::Props_Window::Colors::back, Core::GUI::Props_Addon_Background::background, Core::GUI::GUI_ColorB::base, Core::GUI::Props_Window::Colors::border, Core::GUI::BUTTON_ONESHOT, buttonType, Core::GUI::Props_Window::color, Core::GUI::CONSTRAIN_TOP_LEFT, Core::GUI::CONSTRAIN_TOP_RIGHT, debounceTime, Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::GUI_ColorH::highlight, Core::GameVars::_Pallette::icon, iconAtlas, iconID, Core::GameVars::pallette, Core::GUI::Props_Window::setBorder(), Core::GUI::Props::setPadding(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props_Addon_Background::showBackground(), and Core::GUI::Props_Addon_Label::showLabel().
~Props_Icon()
Core::GUI::Props_Icon::~Props_Icon () inline
Definition at line 1332 of file GUI_Constraint.h.
Member Function Documentation
setButtonType()
void Core::GUI::Props_Icon::setButtonType (eButtonType e) inline
Definition at line 1298 of file GUI_Constraint.h.
References buttonType.
Referenced by _Admin::init(), and Core::GUI::Props_ComboBox::Props_ComboBox().
setDebounceTime()
void Core::GUI::Props_Icon::setDebounceTime (int i) inline
Definition at line 1299 of file GUI_Constraint.h.
References debounceTime.
setIconIDs()
void Core::GUI::Props_Icon::setIconIDs (int b, int h, int a) inline
Definition at line 1297 of file GUI_Constraint.h.
References h, and iconID.
Referenced by _Admin::init().
setImage()
void Core::GUI::Props_Icon::setImage (std::string s) inline
Definition at line 1300 of file GUI_Constraint.h.
References iconAtlas.
Referenced by _Admin::init().
Friends And Related Function Documentation
Object::Icon
friend class Object::Icon friend
Definition at line 1277 of file GUI_Constraint.h.
Member Data Documentation
active
int Core::GUI::Props_Icon::active
Definition at line 1292 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::Icon::exec().
base
int Core::GUI::Props_Icon::base
Definition at line 1292 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::Icon::exec().
buttonType
eButtonType Core::GUI::Props_Icon::buttonType
Definition at line 1293 of file GUI_Constraint.h.
Referenced by Props_Icon(), setButtonType(), and Core::GUI::Object::Icon::updateObjectState().
color
struct Core::GUI::Props_Icon::Colors Core::GUI::Props_Icon::color
Referenced by Core::GUI::Object::Icon::exec().
debounceTime
int Core::GUI::Props_Icon::debounceTime
Definition at line 1294 of file GUI_Constraint.h.
Referenced by Props_Icon(), setDebounceTime(), and Core::GUI::Object::Icon::updateObjectState().
highlight
int Core::GUI::Props_Icon::highlight
Definition at line 1292 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::Icon::exec().
iconAtlas
std::string Core::GUI::Props_Icon::iconAtlas
Definition at line 1295 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::Icon::exec(), Props_Icon(), and setImage().
iconID
struct { ... } Core::GUI::Props_Icon::iconID
Referenced by Core::GUI::Object::Icon::exec(), Props_Icon(), and setIconIDs().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Constraint.h