Project Parsec: Core::_TextSys Class Reference
Core::_TextSys Class Reference
#include <TextSys.h>
Public Member Functions
_TextSys ()
int getIndex (char myChar)
int getIndex (std::string sChar)
bool load ()
bool init ()
void draw (float x, float y, std::string buffer, GUI::iConstrain anchor=Core::GUI::CONSTRAIN_CENTER, GUI::iConstrain origin=GUI::CONSTRAIN_TOP|GUI::CONSTRAIN_LEFT)
void draw (GUI::Props *con, std::string buffer)
void draw (GUI::Props *con, std::string buffer, GUI::iConstrain anchor)
void draw2 (float x, float y, std::string buffer, GUI::iConstrain anchor=Core::GUI::CONSTRAIN_CENTER, GUI::iConstrain origin=GUI::CONSTRAIN_TOP|GUI::CONSTRAIN_LEFT)
void drawMulti (GUI::Props_Text *con, GUI::iConstrain anchor=Core::GUI::CONSTRAIN_LEFT)
template<typename T >
void drawVar (GUI::Props c, std::string buffer, T t, int precision, GUI::iConstrain anchor)
template<typename T >
void drawVar (int x, int y, std::string buffer, T t, int precision, GUI::iConstrain anchor=Core::GUI::CONSTRAIN_CENTER, GUI::iConstrain origin=GUI::CONSTRAIN_TOP|GUI::CONSTRAIN_LEFT)
template<typename T >
void drawVar2 (int x, int y, std::string buffer, T t, int precision, GUI::iConstrain anchor=Core::GUI::CONSTRAIN_CENTER, GUI::iConstrain origin=GUI::CONSTRAIN_TOP|GUI::CONSTRAIN_LEFT)
Private Member Functions
Vector24f setTexCoords (int n)
void start (int x, int y, int fontNum, Core::_Colors::_ACTIVE_COLOR eColor)
void update ()
void stop ()
void drawText (std::string buffer)
Base drawing command. This is private and should not be called directly.
Private Attributes
Timer cursorBlink
bool bBlinkState
Map_si mapChar
Vector24f pArray
Texture texture
VAO vao [CHARS]
uint uiNumTextures
uint uiRecordSize
std::string sFilename
std::string sDir
std::string sTexDir
Static Private Attributes
static const int CHARS = 256
static const int SPACECHAR = 94
Detailed Description
Definition at line 25 of file TextSys.h.
Constructor & Destructor Documentation
_TextSys()
Core::_TextSys::_TextSys ()
Definition at line 116 of file TextSys.h.
References bBlinkState, cursorBlink, sDir, sFilename, Core::Timer::start(), sTexDir, uiNumTextures, and uiRecordSize.
Member Function Documentation
draw() [1/3]
void Core::_TextSys::draw (float x, float y, std::string buffer, GUI::iConstrain anchor = Core::GUI::CONSTRAIN_CENTER, GUI::iConstrain origin = GUI::CONSTRAIN_TOP|GUI::CONSTRAIN_LEFT)
Draw text at exact position given by x and y.
Parameters
x Exact horizontal screen coordinate
y Exact vertical screen coordinate
buffer Text to draw
anchor Text anchor
origin Text origin
Definition at line 1781 of file TextSys.h.
References Core::GameVars::font, Core::gameVars, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GameVars::Font::vSize, and Core::Vector2f::x.
Referenced by Core::GameSys::_MenuSys::draw(), draw(), draw2(), drawMulti(), Core::GameSys::drawText(), drawVar(), Core::GUI::Object::Label::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Field< int >::exec(), and _Game::Update().
draw() [2/3]
void Core::_TextSys::draw (GUI::Props * con, std::string buffer)
Definition at line 1794 of file TextSys.h.
References Core::GUI::Props::anchor, and draw().
draw() [3/3]
void Core::_TextSys::draw (GUI::Props * con, std::string buffer, GUI::iConstrain anchor)
Position based on Props, override anchor point. This is primarily used by other functions such as GUI slider that uses constraints for position information but label and values use their own anchor points. This function expects the position to be based on text center point
Parameters
c Text constraints from the calling object
buffer Text to be drawn
anchor Anchor point for the text relative to position of c. This anchor may not match the anchor in c.
Definition at line 1810 of file TextSys.h.
References Core::Vector4i::bottom, Core::_Colors::COLOR_FRONT, Core::colors, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, Core::GUI::CONSTRAIN_TOP, drawText(), Core::GameVars::font, Core::gameVars, GL_DEPTH_TEST, GL_TRUE, Core::GLS_FONT, Core::GUI::Props::_Size::isAutoSet(), Core::Vector4i::left, Core::GUI::Props::pos, Core::Vector4i::right, Core::_Colors::SetActive(), Core::GUI::Props::size, Core::Vector4i::top, Core::GUI::Props::vPadding, Core::GameVars::Font::vSize, Core::Vector2f::x, and Core::Vector2f::y.
draw2()
void Core::_TextSys::draw2 (float x, float y, std::string buffer, GUI::iConstrain anchor = Core::GUI::CONSTRAIN_CENTER, GUI::iConstrain origin = GUI::CONSTRAIN_TOP|GUI::CONSTRAIN_LEFT)
Draw text at character position given by x and y.
Parameters
x Character horizontal screen coordinate
y Character vertical screen coordinate
buffer Text to draw
anchor Text anchor
origin Text origin
Definition at line 1759 of file TextSys.h.
References draw(), Core::GameVars::font, Core::gameVars, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GameVars::Font::vSize, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by _Game::Update().
drawMulti()
void Core::_TextSys::drawMulti (GUI::Props_Text * con, GUI::iConstrain anchor = Core::GUI::CONSTRAIN_LEFT)
Draw text on multiple lines constrained by the size defined in con. Word wrapping occurs at spaces and newline characters.
Parameters
con Text constraints from the calling object
buffer Text to be drawn
anchor Anchor point for the text relative to position of con. This anchor may not match the anchor in con.
Definition at line 1863 of file TextSys.h.
References Core::GUI::Props_Text::bEnableCursor, Core::Vector4i::bottom, Core::GUI::Props_Text::bOverwrite, Core::GUI::Props_Text::bufferPtr, Core::GUI::Props_Text::bWordWrap, Core::GameVars::Font::cCursorI, Core::GameVars::Font::cCursorO, Core::GUI::Props::_Size::constraint, draw(), Core::GUI::Props::exec(), Core::GameVars::font, Core::gameVars, Core::GUI::Props_Text::iCursorChars, Core::GUI::Props_Text::iCursorPosition, Core::GUI::Props_Text::iDownChars, Core::GUI::Props_Text::iMaxLines, Core::GUI::Props::_Size::isAutoSet(), Core::GUI::Props_Text::iUpChars, Core::Vector4i::left, Core::GUI::Props_Text::limit, Core::GameVars::Screen::res, Core::Vector4i::right, Core::GameVars::screen, Core::GUI::Props_Text::scrollPosition, Core::GUI::Props::setHeight(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, Core::Vector4i::top, Core::GameVars::Font::vMax, Core::GUI::Props::vPadding, Core::GameVars::Font::vSize, Core::Vector2i::x, Core::Vector2f::x, Core::GUI::Props::_Size::_SizeConstraint::xAuto, Core::Vector2i::y, Core::Vector2f::y, and Core::GUI::Props::_Size::_SizeConstraint::yAuto.
Referenced by Core::GUI::Object::Text::exec().
drawText()
void Core::_TextSys::drawText (std::string buffer) private
Base drawing command. This is private and should not be called directly.
Parameters
buffer
Definition at line 2145 of file TextSys.h.
References bBlinkState, Core::GameVars::Font::cCursorO, Core::colors, cursorBlink, Core::VAO::Draw(), Core::GameVars::font, Core::gameVars, getIndex(), Core::_Colors::PopFront(), Core::_Colors::PushFront(), SPACECHAR, Core::Timer::split(), Core::Timer::start(), update(), and vao.
Referenced by draw().
drawVar() [1/2]
template<typename T > void Core::_TextSys::drawVar (GUI::Props c, std::string buffer, T t, int precision, GUI::iConstrain anchor)
Template Parameters
T
T
Parameters
c
buffer
t
precision
anchor
Definition at line 2057 of file TextSys.h.
References draw(), and t.
Referenced by drawVar2(), and _Game::Update().
drawVar() [2/2]
template<typename T > void Core::_TextSys::drawVar (int x, int y, std::string buffer, T t, int precision, GUI::iConstrain anchor = Core::GUI::CONSTRAIN_CENTER, GUI::iConstrain origin = GUI::CONSTRAIN_TOP|GUI::CONSTRAIN_LEFT)
Template Parameters
T
T
Parameters
x
y
buffer
t
precision
anchor
origin
Definition at line 2086 of file TextSys.h.
References draw(), and t.
drawVar2()
template<typename T > void Core::_TextSys::drawVar2 (int x, int y, std::string buffer, T t, int precision, GUI::iConstrain anchor = Core::GUI::CONSTRAIN_CENTER, GUI::iConstrain origin = GUI::CONSTRAIN_TOP|GUI::CONSTRAIN_LEFT)
Template Parameters
T
T
Parameters
x
y
buffer
t
precision
anchor
origin
Definition at line 2116 of file TextSys.h.
References drawVar(), Core::GameVars::font, Core::gameVars, Core::GameVars::Font::vSize, and Core::Vector2f::y.
Referenced by _Game::Update().
getIndex() [1/2]
int Core::_TextSys::getIndex (char myChar)
Parameters
myChar
Returns
Definition at line 1720 of file TextSys.h.
References mapChar, and SPACECHAR.
Referenced by drawText().
getIndex() [2/2]
int Core::_TextSys::getIndex (std::string sChar)
Parameters
sChar
Returns
Definition at line 1733 of file TextSys.h.
References mapChar.
init()
bool Core::_TextSys::init ()
Returns
Definition at line 190 of file TextSys.h.
References Core::Vector24f::a, A, Core::Vector24f::b, B, Core::VAO::Begin(), Core::Vector24f::c, CHARS, Core::VAO::CopyData(), cout, Core::Vector24f::d, Core::VAO::End(), Core::GameVars::font, Core::gameVars, GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, h, M, mapChar, p, P, pArray, setTexCoords(), t, vao, Core::GameVars::Font::vSize, w, x, y, and z.
load()
bool Core::_TextSys::load ()
Returns
Definition at line 131 of file TextSys.h.
References Core::MemBlock::buffer, cout, GL_CLAMP_TO_EDGE, GL_LINEAR_MIPMAP_LINEAR, Core::readFile(), sDir, sFilename, Core::MemBlock::size, sTexDir, uiNumTextures, and uiRecordSize.
setTexCoords()
Vector24f Core::_TextSys::setTexCoords (int n) private
Parameters
n
Returns
Definition at line 170 of file TextSys.h.
Referenced by init().
start()
void Core::_TextSys::start (int x, int y, int fontNum, Core::_Colors::_ACTIVE_COLOR eColor) private
Parameters
x
y
fontNum
eColor
Definition at line 1686 of file TextSys.h.
References Core::colors, Core::GameVars::font, Core::gameVars, GL_DEPTH_TEST, GL_TRUE, Core::GLS_FONT, Core::GameVars::Font::screenCoords, Core::_Colors::SetActive(), and Core::GameVars::Font::vSize.
stop()
void Core::_TextSys::stop () private
Definition at line 1709 of file TextSys.h.
References GL_DEPTH_TEST.
update()
void Core::_TextSys::update () private
Definition at line 1701 of file TextSys.h.
References Core::GLS_FONT.
Referenced by drawText().
Member Data Documentation
bBlinkState
bool Core::_TextSys::bBlinkState private
Definition at line 31 of file TextSys.h.
Referenced by _TextSys(), and drawText().
CHARS
const int Core::_TextSys::CHARS = 256 static private
Definition at line 27 of file TextSys.h.
Referenced by init().
cursorBlink
Timer Core::_TextSys::cursorBlink private
Definition at line 30 of file TextSys.h.
Referenced by _TextSys(), and drawText().
mapChar
Map_si Core::_TextSys::mapChar private
Definition at line 33 of file TextSys.h.
Referenced by getIndex(), and init().
pArray
Vector24f Core::_TextSys::pArray private
Definition at line 37 of file TextSys.h.
Referenced by init().
sDir
std::string Core::_TextSys::sDir private
Definition at line 43 of file TextSys.h.
Referenced by _TextSys(), and load().
sFilename
std::string Core::_TextSys::sFilename private
Definition at line 43 of file TextSys.h.
Referenced by _TextSys(), and load().
SPACECHAR
const int Core::_TextSys::SPACECHAR = 94 static private
Definition at line 28 of file TextSys.h.
Referenced by drawText(), and getIndex().
sTexDir
std::string Core::_TextSys::sTexDir private
Definition at line 43 of file TextSys.h.
Referenced by _TextSys(), and load().
texture
Texture Core::_TextSys::texture private
Definition at line 38 of file TextSys.h.
uiNumTextures
uint Core::_TextSys::uiNumTextures private
Definition at line 41 of file TextSys.h.
Referenced by _TextSys(), and load().
uiRecordSize
uint Core::_TextSys::uiRecordSize private
Definition at line 41 of file TextSys.h.
Referenced by _TextSys(), and load().
vao
VAO Core::_TextSys::vao[CHARS] private
Definition at line 39 of file TextSys.h.
Referenced by drawText(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/TextSys.h