Project Parsec: Core::GUI::GUI_Container::SliderInterface Class Reference
Core::GUI::GUI_Container::SliderInterface Class Reference
#include <GUI_Container.h>
Public Member Functions
template<typename T >
void add (std::string sliderName, T *ptr, Props_Slider c, Props *p=nullptr)
template<typename T >
void add (std::string sliderName, T *ptr, Props_Slider *c, Props *p=nullptr)
template<typename T >
void add (std::string sliderName, T t, Props_Slider c, Props *p=nullptr)
template<typename T >
void add (std::string sliderName, T t, Props_Slider *c, Props *p=nullptr)
Object::AnySlider & operator[] (std::string sliderName)
SliderInterface (GUI_Container *parent)
~SliderInterface ()
Private Member Functions
void pushData (std::string name, Object::AnySlider *data)
Private Attributes
std::vector< Object::AnySlider * > sliders
Map_si map
GUI_Container * gui
Friends
class GUI_Container
Detailed Description
Definition at line 121 of file GUI_Container.h.
Constructor & Destructor Documentation
SliderInterface()
Core::GUI::GUI_Container::SliderInterface::SliderInterface (GUI_Container * parent) inline
Definition at line 138 of file GUI_Container.h.
References gui, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
~SliderInterface()
Core::GUI::GUI_Container::SliderInterface::~SliderInterface () inline
Definition at line 139 of file GUI_Container.h.
References sliders.
Member Function Documentation
add() [1/4]
template<typename T > void Core::GUI::GUI_Container::SliderInterface::add (std::string sliderName, T * ptr, Props_Slider * c, Props * p = nullptr)
Definition at line 467 of file GUI_Container.h.
References MY_NAMESPACE::gui, Core::GUI::GUI_Container::pushData(), and Core::GUI::Object::AnySlider::set().
add() [2/4]
template<typename T > void Core::GUI::GUI_Container::SliderInterface::add (std::string sliderName, T * ptr, Props_Slider c, Props * p = nullptr)
Definition at line 459 of file GUI_Container.h.
References MY_NAMESPACE::gui, Core::GUI::GUI_Container::pushData(), and Core::GUI::Object::AnySlider::set().
add() [3/4]
template<typename T > void Core::GUI::GUI_Container::SliderInterface::add (std::string sliderName, T t, Props_Slider * c, Props * p = nullptr)
Definition at line 482 of file GUI_Container.h.
References MY_NAMESPACE::gui, Core::GUI::GUI_Container::pushData(), and Core::GUI::Object::AnySlider::set().
add() [4/4]
template<typename T > void Core::GUI::GUI_Container::SliderInterface::add (std::string sliderName, T t, Props_Slider c, Props * p = nullptr)
Definition at line 474 of file GUI_Container.h.
References MY_NAMESPACE::gui, Core::GUI::GUI_Container::pushData(), and Core::GUI::Object::AnySlider::set().
operator[]()
Object::AnySlider& Core::GUI::GUI_Container::SliderInterface::operator[] (std::string sliderName) inline
Definition at line 136 of file GUI_Container.h.
References map, and sliders.
pushData()
void Core::GUI::GUI_Container::SliderInterface::pushData (std::string name, Object::AnySlider * data) private
Definition at line 452 of file GUI_Container.h.
References Core::GUI::GUI_Container::map.
Friends And Related Function Documentation
GUI_Container
friend class GUI_Container friend
Definition at line 122 of file GUI_Container.h.
Member Data Documentation
gui
GUI_Container* Core::GUI::GUI_Container::SliderInterface::gui private
Definition at line 126 of file GUI_Container.h.
Referenced by SliderInterface().
map
Map_si Core::GUI::GUI_Container::SliderInterface::map private
Definition at line 125 of file GUI_Container.h.
Referenced by operator[]().
sliders
std::vector<Object::AnySlider*> Core::GUI::GUI_Container::SliderInterface::sliders private
Definition at line 124 of file GUI_Container.h.
Referenced by operator[](), and ~SliderInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Container.h