Project Parsec: Core::GUI::GUI_Container::ProgressBarInterface Class Reference
Core::GUI::GUI_Container::ProgressBarInterface Class Reference
#include <GUI_Container.h>
Public Member Functions
void add (std::string progressBarName, int progress, Props_ProgressBar c, Props *p=nullptr)
void add (std::string progressBarName, int progress, Props_ProgressBar *c, Props *p=nullptr)
void add (std::string progressBarName, int *progress, Props_ProgressBar c, Props *p=nullptr)
void add (std::string progressBarName, int *progress, Props_ProgressBar *c, Props *p=nullptr)
Object::ProgressBar & operator[] (std::string progressBarName)
Props_ProgressBar & operator() (std::string progressBarName)
ProgressBarInterface (GUI_Container *parent)
~ProgressBarInterface ()
Private Member Functions
void pushData (std::string name, Object::ProgressBar *data)
Private Attributes
std::vector< Object::ProgressBar * > progressBars
Map_si map
GUI_Container * gui
Friends
class GUI_Container
Detailed Description
Definition at line 285 of file GUI_Container.h.
Constructor & Destructor Documentation
ProgressBarInterface()
Core::GUI::GUI_Container::ProgressBarInterface::ProgressBarInterface (GUI_Container * parent) inline
Definition at line 302 of file GUI_Container.h.
References gui, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
~ProgressBarInterface()
Core::GUI::GUI_Container::ProgressBarInterface::~ProgressBarInterface () inline
Definition at line 303 of file GUI_Container.h.
References progressBars.
Member Function Documentation
add() [1/4]
void Core::GUI::GUI_Container::ProgressBarInterface::add (std::string progressBarName, int * progress, Props_ProgressBar * c, Props * p = nullptr)
Definition at line 747 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [2/4]
void Core::GUI::GUI_Container::ProgressBarInterface::add (std::string progressBarName, int * progress, Props_ProgressBar c, Props * p = nullptr)
Definition at line 740 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [3/4]
void Core::GUI::GUI_Container::ProgressBarInterface::add (std::string progressBarName, int progress, Props_ProgressBar * c, Props * p = nullptr)
Definition at line 733 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [4/4]
void Core::GUI::GUI_Container::ProgressBarInterface::add (std::string progressBarName, int progress, Props_ProgressBar c, Props * p = nullptr)
Definition at line 726 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
operator()()
Props_ProgressBar& Core::GUI::GUI_Container::ProgressBarInterface::operator() (std::string progressBarName) inline
Definition at line 301 of file GUI_Container.h.
References Core::GUI::Object::Base::Generic< Props_Window >::con, map, and progressBars.
operator[]()
Object::ProgressBar& Core::GUI::GUI_Container::ProgressBarInterface::operator[] (std::string progressBarName) inline
Definition at line 300 of file GUI_Container.h.
References map, and progressBars.
pushData()
void Core::GUI::GUI_Container::ProgressBarInterface::pushData (std::string name, Object::ProgressBar * data) private
Definition at line 719 of file GUI_Container.h.
References Core::GUI::GUI_Container::map.
Friends And Related Function Documentation
GUI_Container
friend class GUI_Container friend
Definition at line 286 of file GUI_Container.h.
Member Data Documentation
gui
GUI_Container* Core::GUI::GUI_Container::ProgressBarInterface::gui private
Definition at line 291 of file GUI_Container.h.
Referenced by ProgressBarInterface().
map
Map_si Core::GUI::GUI_Container::ProgressBarInterface::map private
Definition at line 290 of file GUI_Container.h.
Referenced by operator()(), and operator[]().
progressBars
std::vector<Object::ProgressBar*> Core::GUI::GUI_Container::ProgressBarInterface::progressBars private
Definition at line 289 of file GUI_Container.h.
Referenced by Core::GUI::GUI_Container::execObjects(), Core::GUI::GUI_Container::execToolTips(), operator()(), operator[](), and ~ProgressBarInterface().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Container.h