Project Parsec: Core::GUI::Props_Addon_Field Class Reference
Core::GUI::Props_Addon_Field Class Reference
#include <GUI_Constraint.h>
Public Member Functions
void showField ()
void hideField ()
Props_Addon_Field ()
Public Attributes
bool bShowField
Props_Field field
Detailed Description
Definition at line 736 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Props_Addon_Field()
Core::GUI::Props_Addon_Field::Props_Addon_Field () inline
Definition at line 745 of file GUI_Constraint.h.
References bShowField, field, Core::GUI::Props::setMinMaxWidth(), and Core::GUI::Props::setPos().
Member Function Documentation
hideField()
void Core::GUI::Props_Addon_Field::hideField () inline
Definition at line 743 of file GUI_Constraint.h.
References bShowField.
Referenced by Core::GUI::Object::TextArea::init(), and Core::GUI::Object::TextEdit::init().
showField()
void Core::GUI::Props_Addon_Field::showField () inline
Definition at line 742 of file GUI_Constraint.h.
References bShowField.
Referenced by _Admin::init(), and Core::GUI::Props_ColorSwatch::Props_ColorSwatch().
Member Data Documentation
bShowField
bool Core::GUI::Props_Addon_Field::bShowField
Definition at line 738 of file GUI_Constraint.h.
Referenced by hideField(), Props_Addon_Field(), Core::GUI::Props_Slider::Props_Slider(), and showField().
field
Props_Field Core::GUI::Props_Addon_Field::field
Definition at line 740 of file GUI_Constraint.h.
Referenced by _Admin::init(), Props_Addon_Field(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), and Core::GUI::Props_Slider::Props_Slider().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Constraint.h