Project Parsec: RunBattle Class Reference
RunBattle Class Reference
#include <runBattle.h>
Public Member Functions
void setTarget ()
void setTarget (CharSheet &sheet, CharSheet &target)
void ResetRound ()
void ResetRound (CharSheet &sheet, bool firstLoad)
RunBattle ()
~RunBattle ()
void run ()
void run (CharSheet &CSattacker)
void init (int iNum)
void init (CharSheet &sheet, int iNum)
void setActive ()
void setActive (CharSheet &active)
void setActive (CharSheet &active, CharSheet &target)
void initSheet (int mode, CharSheet &sheet)
void initSheet (CharSheet &sheet, CharSheet &target)
void initSheet (CharSheet &sheet)
void initSheet (CharSheet &sheet, CharSheet &target, int iNum)
void draw ()
void draw (CharSheet &CSattacker, CharSheet &CStarget)
Public Attributes
bool bInit
CharSheet ** enemies
int iPlayer
int numEnemy
Protected Member Functions
void getInput ()
void processInput (uint key)
void processInput ()
void update ()
void getHeight ()
void getJump ()
bool CheckDeath (CharSheet &sheet)
Private Types
enum _CRITICALS {
CRITICAL_ZERO, CRITICAL_ONE, CRITICAL_TWO, CRITICAL_THREE,
CRITICAL_FOUR
}
Private Member Functions
void Initial (int mode, CharSheet &sheet)
void ExecInitial (int mode, CharSheet &sheet)
void Move (int mode, CharSheet &sheet)
void ExecMove ()
void ChangeStance (int mode, CharSheet &sheet)
void ExecChangeStance (int mode)
void Engage (int mode, CharSheet &sheet)
void ExecEngage (int mode, CharSheet &sheet)
void Attack (int mode, CharSheet &sheet)
void ExecAttack (int mode)
void ExecAttack (int mode, CharSheet &player, unsigned int eNum)
void UpdateCards (CharSheet &sheet)
void RunMagic ()
void ExecMagic ()
void Defend (int mode, CharSheet &sheet)
void ExecDefend (int mode, CharSheet &sheet)
void Enemy (int mode, CharSheet &sheet)
void ExecEnemy (int mode)
bool Between (int i, int a, int b)
void UpdateRound (bool bSkip)
void NextTarget ()
void Message (std::string s)
void DebugMenu (CharSheet &sheet, int iPrev, int iNext)
void EndBattle ()
void UpdateMovement (CharSheet &sheet)
void ChangeWeapon (CharSheet &sheet)
void ExecChangeWeapon (int mode, CharSheet &sheet)
void ShowAttackStats (CharSheet &sheet)
void ShowEnemyStats (CharSheet &sheet)
void ShowPlayerStats (CharSheet &sheet)
void ShowStats ()
std::string GetAttackStat (unsigned int iC, unsigned int iT)
void Shift_Spells (int x, int y)
Private Attributes
bool bUpdateRound
CharSheet::_Magic TempMagic [2]
Keyboard keyboard
Vector4f vTint
Vector4f vTintBase
Vector4f vSelected
Vector4f vHighlight
Vector4f vDisabled
bool bNext
Detailed Description
Definition at line 13 of file runBattle.h.
Member Enumeration Documentation
_CRITICALS
enum RunBattle::_CRITICALS private
Enumerator
CRITICAL_ZERO
CRITICAL_ONE
CRITICAL_TWO
CRITICAL_THREE
CRITICAL_FOUR
Definition at line 53 of file runBattle.h.
Constructor & Destructor Documentation
RunBattle()
RunBattle::RunBattle ()
Definition at line 110 of file runBattle.h.
References bInit, bNext, bUpdateRound, enemies, iPlayer, keyboard, numEnemy, vDisabled, vHighlight, vSelected, vTint, and vTintBase.
~RunBattle()
RunBattle::~RunBattle () inline
Definition at line 83 of file runBattle.h.
Member Function Documentation
Attack()
void RunBattle::Attack (int mode, CharSheet & sheet) private
Between()
bool RunBattle::Between (int i, int a, int b) private
Definition at line 906 of file runBattle.h.
ChangeStance()
void RunBattle::ChangeStance (int mode, CharSheet & sheet) private
ChangeWeapon()
void RunBattle::ChangeWeapon (CharSheet & sheet) private
CheckDeath()
bool RunBattle::CheckDeath (CharSheet & sheet) protected
Definition at line 667 of file runBattle.h.
References cout.
Referenced by run().
DebugMenu()
void RunBattle::DebugMenu (CharSheet & sheet, int iPrev, int iNext) private
Defend()
void RunBattle::Defend (int mode, CharSheet & sheet) private
draw() [1/2]
void RunBattle::draw ()
Definition at line 3237 of file runBattle.h.
References Core::GameVars::Player::active, _TheVoid::atmosphere, Core::GameVars::controls, _NPC::draw(), Core::gameVars, GL_TEXTURE0, iPlayer, _TheVoid::npc, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameSys::CharSheet::Transform::rot, Core::GameVars::screen, Core::GameSys::CharSheet::transform, _TheVoid::Update(), and world.
Referenced by RunEndBattle::run(), RunGrimoire::run(), RunBattleScroll::run(), RunMenu::run(), run(), and RunMagic().
draw() [2/2]
void RunBattle::draw (CharSheet & CSattacker, CharSheet & CStarget)
EndBattle()
void RunBattle::EndBattle () private
Definition at line 645 of file runBattle.h.
References Core::GameVars::Player::active, Core::gameVars, Core::GameVars::player, Core::GameVars::screen, Core::GameVars::Player::sheet, and Core::GameSys::CharSheet::transform.
Referenced by NextTarget(), processInput(), and run().
Enemy()
void RunBattle::Enemy (int mode, CharSheet & sheet) private
Engage()
void RunBattle::Engage (int mode, CharSheet & sheet) private
ExecAttack() [1/2]
void RunBattle::ExecAttack (int mode) private
Definition at line 1042 of file runBattle.h.
References Core::GameVars::Player::active, cout, CRITICAL_FOUR, CRITICAL_ONE, CRITICAL_THREE, CRITICAL_TWO, CRITICAL_ZERO, ExecChangeStance(), Core::gameVars, Core::GameVars::player, and UpdateCards().
Referenced by update().
ExecAttack() [2/2]
void RunBattle::ExecAttack (int mode, CharSheet & player, unsigned int eNum) private
ExecChangeStance()
void RunBattle::ExecChangeStance (int mode) private
Definition at line 998 of file runBattle.h.
References Core::GameVars::Player::active, cout, Core::gameVars, Core::GameVars::player, and Core::GameSys::CharSheet::transform.
Referenced by ExecAttack(), and update().
ExecChangeWeapon()
void RunBattle::ExecChangeWeapon (int mode, CharSheet & sheet) private
Definition at line 1036 of file runBattle.h.
ExecDefend()
void RunBattle::ExecDefend (int mode, CharSheet & sheet) private
Definition at line 3220 of file runBattle.h.
ExecEnemy()
void RunBattle::ExecEnemy (int mode) private
ExecEngage()
void RunBattle::ExecEngage (int mode, CharSheet & sheet) private
ExecInitial()
void RunBattle::ExecInitial (int mode, CharSheet & sheet) private
ExecMagic()
void RunBattle::ExecMagic () private
Definition at line 3216 of file runBattle.h.
Referenced by update().
ExecMove()
void RunBattle::ExecMove () private
Definition at line 918 of file runBattle.h.
References Core::GameVars::Player::active, cout, Core::gameVars, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameVars::screen, and Core::GameSys::CharSheet::transform.
Referenced by update().
GetAttackStat()
std::string RunBattle::GetAttackStat (unsigned int iC, unsigned int iT) private
Definition at line 15 of file debug.h.
getHeight()
void RunBattle::getHeight () protected
getInput()
void RunBattle::getInput () protected
Definition at line 3500 of file runBattle.h.
References Core::GameVars::controls, Core::gameVars, keyboard, processInput(), and Core::GameVars::screen.
Referenced by run().
getJump()
void RunBattle::getJump () protected
init() [1/2]
void RunBattle::init (CharSheet & sheet, int iNum)
init() [2/2]
void RunBattle::init (int iNum)
Definition at line 151 of file runBattle.h.
References enemies, and numEnemy.
Referenced by NextTarget().
Initial()
void RunBattle::Initial (int mode, CharSheet & sheet) private
initSheet() [1/4]
void RunBattle::initSheet (CharSheet & sheet)
Definition at line 218 of file runBattle.h.
References enemies, and TempMagic.
initSheet() [2/4]
void RunBattle::initSheet (CharSheet & sheet, CharSheet & target)
initSheet() [3/4]
void RunBattle::initSheet (CharSheet & sheet, CharSheet & target, int iNum)
Definition at line 161 of file runBattle.h.
References enemies, and TempMagic.
initSheet() [4/4]
void RunBattle::initSheet (int mode, CharSheet & sheet)
Message()
void RunBattle::Message (std::string s) private
Move()
void RunBattle::Move (int mode, CharSheet & sheet) private
NextTarget()
void RunBattle::NextTarget () private
Definition at line 691 of file runBattle.h.
References Core::GameVars::Player::active, cout, EndBattle(), enemies, Core::gameVars, init(), numEnemy, Core::GameVars::player, and Core::GameVars::Player::sheet.
Referenced by processInput(), and setActive().
processInput() [1/2]
void RunBattle::processInput () protected
Definition at line 3577 of file runBattle.h.
References Core::GameVars::Player::active, Core::GameVars::Screen::clear, Core::GameVars::controls, EndBattle(), Core::GameVars::Controls::fly, Core::gameVars, WorldMap::getHeight(), GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT, GL_FILL, GL_FRONT_AND_BACK, GL_LINE, GL_POINT, Core::GameVars::Controls::key, keyboard, _TheVoid::map, Core::GameVars::Controls::_KeyBinding::mouse_down, Core::GameVars::Controls::_KeyBinding::mouse_left, Core::GameVars::Controls::_KeyBinding::mouse_right, Core::GameVars::Controls::_KeyBinding::mouse_up, Core::GameVars::Controls::_KeyBinding::move_back, Core::GameVars::Controls::_KeyBinding::move_down, Core::GameVars::Controls::_KeyBinding::move_forward, Core::GameVars::Controls::_KeyBinding::move_up, Core::GameVars::Controls::moveSpeed, NextTarget(), Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameSys::CharSheet::Transform::rot, Core::GameVars::screen, Core::GameVars::Controls::_KeyBinding::strafe_left, Core::GameVars::Controls::_KeyBinding::strafe_right, Core::GameSys::CharSheet::transform, and world.
Referenced by getInput(), and processInput().
processInput() [2/2]
void RunBattle::processInput (uint key) protected
Definition at line 3572 of file runBattle.h.
References keyboard, and processInput().
ResetRound() [1/2]
void RunBattle::ResetRound ()
Definition at line 485 of file runBattle.h.
References Core::GameVars::Player::active, bNext, cout, Core::gameVars, iPlayer, numEnemy, Core::GameVars::player, setActive(), Core::GameVars::Player::sheet, and TempMagic.
Referenced by UpdateRound().
ResetRound() [2/2]
void RunBattle::ResetRound (CharSheet & sheet, bool firstLoad = false)
Definition at line 567 of file runBattle.h.
References bNext, cout, Core::gameVars, iPlayer, numEnemy, Core::GameVars::player, setActive(), Core::GameVars::Player::sheet, and TempMagic.
run() [1/2]
void RunBattle::run ()
Definition at line 731 of file runBattle.h.
References Core::GameVars::Player::active, bUpdateRound, CheckDeath(), draw(), EndBattle(), enemies, Core::gameVars, getInput(), numEnemy, Core::GameVars::player, ShowStats(), update(), and UpdateRound().
run() [2/2]
void RunBattle::run (CharSheet & CSattacker)
RunMagic()
void RunBattle::RunMagic () private
Definition at line 2830 of file runBattle.h.
References Core::GameVars::Player::active, Battle, Core::GameVars::Screen::clear, draw(), Core::GameVars::font, Core::gameVars, GL_TRUE, h, Core::GameVars::player, Core::GameVars::screen, Core::GameVars::Font::screenCoords, Shift_Spells(), TempMagic, _TheVoid::Update(), vHighlight, vSelected, Core::GameVars::Font::vSize, vTint, vTintBase, w, world, x, and y.
Referenced by update().
setActive() [1/3]
void RunBattle::setActive ()
Definition at line 395 of file runBattle.h.
References Core::GameVars::Player::active, bNext, cout, enemies, Core::gameVars, iPlayer, NextTarget(), Core::GameVars::player, and TempMagic.
Referenced by ResetRound().
setActive() [2/3]
void RunBattle::setActive (CharSheet & active)
Definition at line 368 of file runBattle.h.
References Core::GameVars::Player::active, bNext, cout, Core::gameVars, NextTarget(), Core::GameVars::player, and TempMagic.
setActive() [3/3]
void RunBattle::setActive (CharSheet & active, CharSheet & target)
Definition at line 342 of file runBattle.h.
References Core::GameVars::Player::active, bNext, Core::gameVars, Core::GameVars::player, and TempMagic.
setTarget() [1/2]
void RunBattle::setTarget ()
Definition at line 468 of file runBattle.h.
References enemies, Core::gameVars, numEnemy, Core::GameVars::player, and Core::GameVars::Player::sheet.
setTarget() [2/2]
void RunBattle::setTarget (CharSheet & sheet, CharSheet & target)
Definition at line 474 of file runBattle.h.
Shift_Spells()
void RunBattle::Shift_Spells (int x, int y) private
Definition at line 2820 of file runBattle.h.
References TempMagic, x, and z.
Referenced by RunMagic().
ShowAttackStats()
void RunBattle::ShowAttackStats (CharSheet & sheet) private
ShowEnemyStats()
void RunBattle::ShowEnemyStats (CharSheet & sheet) private
ShowPlayerStats()
void RunBattle::ShowPlayerStats (CharSheet & sheet) private
ShowStats()
void RunBattle::ShowStats () private
Definition at line 157 of file debug.h.
References A, Core::GameVars::Player::active, B, Core::GameVars::font, Core::gameVars, h, Core::itoa(), Core::GameVars::player, Core::GameVars::screen, Core::GameVars::Font::vSize, vTint, w, x, and y.
Referenced by run().
update()
void RunBattle::update () protected
Definition at line 805 of file runBattle.h.
References Core::GameVars::Player::active, bUpdateRound, cout, ExecAttack(), ExecChangeStance(), ExecMagic(), ExecMove(), Core::gameVars, Core::GameVars::player, RunMagic(), UpdateRound(), and vTint.
Referenced by run().
UpdateCards()
void RunBattle::UpdateCards (CharSheet & sheet) private
Definition at line 2687 of file runBattle.h.
Referenced by ExecAttack().
UpdateMovement()
void RunBattle::UpdateMovement (CharSheet & sheet) private
Definition at line 3549 of file runBattle.h.
UpdateRound()
void RunBattle::UpdateRound (bool bSkip = false) private
Definition at line 452 of file runBattle.h.
References Core::GameVars::Player::active, bUpdateRound, Core::gameVars, Core::GameVars::player, and ResetRound().
Referenced by run(), and update().
Member Data Documentation
bInit
bool RunBattle::bInit
Definition at line 86 of file runBattle.h.
Referenced by RunBattle().
bNext
bool RunBattle::bNext private
Definition at line 66 of file runBattle.h.
Referenced by ResetRound(), RunBattle(), and setActive().
bUpdateRound
bool RunBattle::bUpdateRound private
Definition at line 15 of file runBattle.h.
Referenced by run(), RunBattle(), update(), and UpdateRound().
enemies
CharSheet** RunBattle::enemies
Definition at line 87 of file runBattle.h.
Referenced by init(), initSheet(), NextTarget(), RunEndBattle::run(), RunBattleScroll::run(), run(), RunBattle(), setActive(), and setTarget().
iPlayer
int RunBattle::iPlayer
Definition at line 90 of file runBattle.h.
Referenced by draw(), ResetRound(), RunBattle(), and setActive().
keyboard
Keyboard RunBattle::keyboard private
Definition at line 51 of file runBattle.h.
Referenced by getInput(), processInput(), and RunBattle().
numEnemy
int RunBattle::numEnemy
Definition at line 91 of file runBattle.h.
Referenced by init(), NextTarget(), ResetRound(), RunEndBattle::run(), RunBattleScroll::run(), run(), RunBattle(), and setTarget().
TempMagic
CharSheet::_Magic RunBattle::TempMagic[2] private
Definition at line 50 of file runBattle.h.
Referenced by initSheet(), ResetRound(), RunMagic(), setActive(), and Shift_Spells().
vDisabled
Vector4f RunBattle::vDisabled private
Definition at line 61 of file runBattle.h.
Referenced by RunBattle().
vHighlight
Vector4f RunBattle::vHighlight private
Definition at line 61 of file runBattle.h.
Referenced by RunBattle(), and RunMagic().
vSelected
Vector4f RunBattle::vSelected private
Definition at line 61 of file runBattle.h.
Referenced by RunBattle(), and RunMagic().
vTint
Vector4f RunBattle::vTint private
Definition at line 61 of file runBattle.h.
Referenced by RunBattle(), RunMagic(), ShowStats(), and update().
vTintBase
Vector4f RunBattle::vTintBase private
Definition at line 61 of file runBattle.h.
Referenced by RunBattle(), and RunMagic().
The documentation for this class was generated from the following files:
src/game/ref/runBattle.h
src/game/ref/runBattle/debug.h