Project Parsec: Core::GameSys::_IconSys Class Reference
Core::GameSys::_IconSys Class Reference
#include <IconSys.h>
Public Member Functions
_IconSys ()
bool load ()
bool calc ()
void draw (uint x, uint y, float w, float h, uint id, std::string sTex, bool textOffset)
void draw (uint x, uint y, float w, float h, uint id, std::string sTex, bool textOffset, Color fontColor)
void draw (int id, std::string sTex, SHADER_PROGRAMS iShader)
void draw (int id0, int id1, int id2, int id3, std::string sTex, SHADER_PROGRAMS iShader)
Private Member Functions
void start (int x, int y, float w, float h, std::string sTex, bool textOffset, Core::_Colors::_ACTIVE_COLOR eColor=Core::_Colors::COLOR_FRONT)
void update ()
void stop ()
Private Attributes
Texture texture
VAO vao [64]
Vector4f tempColor
Vector4f currentColor
Vector4f gridCoord [64]
uint uiNumTextures
uint uiRecordSize
std::string sFilename
std::string sDir
std::string sTexDir
float fMouseDelay
float fMouseDelayConst
Detailed Description
Definition at line 19 of file IconSys.h.
Constructor & Destructor Documentation
_IconSys()
Core::GameSys::_IconSys::_IconSys ()
Definition at line 68 of file IconSys.h.
References fMouseDelay, fMouseDelayConst, sDir, sFilename, sTexDir, tempColor, uiNumTextures, and uiRecordSize.
Member Function Documentation
calc()
bool Core::GameSys::_IconSys::calc ()
Definition at line 120 of file IconSys.h.
References Core::VAO::Begin(), Core::VAO::CopyData(), cout, Core::VAO::End(), GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, gridCoord, and vao.
draw() [1/4]
void Core::GameSys::_IconSys::draw (int id, std::string sTex, SHADER_PROGRAMS iShader)
Definition at line 337 of file IconSys.h.
References Core::colors, Core::VAO::Draw(), id, Core::_Colors::PopFront(), Core::_Colors::PushFront(), and vao.
draw() [2/4]
void Core::GameSys::_IconSys::draw (int id0, int id1, int id2, int id3, std::string sTex, SHADER_PROGRAMS iShader)
Definition at line 294 of file IconSys.h.
References Core::colors, Core::VAO::Draw(), GL_POLYGON_OFFSET_FILL, Core::_Colors::PopFront(), Core::_Colors::PushFront(), and vao.
draw() [3/4]
void Core::GameSys::_IconSys::draw (uint x, uint y, float w, float h, uint id, std::string sTex, bool textOffset)
Definition at line 370 of file IconSys.h.
References Core::VAO::Draw(), id, start(), stop(), update(), and vao.
Referenced by draw().
draw() [4/4]
void Core::GameSys::_IconSys::draw (uint x, uint y, float w, float h, uint id, std::string sTex, bool textOffset, Color fontColor)
Definition at line 364 of file IconSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
load()
bool Core::GameSys::_IconSys::load ()
Definition at line 87 of file IconSys.h.
References Core::MemBlock::buffer, cout, GL_NEAREST, Core::readFile(), sDir, sFilename, Core::MemBlock::size, sTexDir, uiNumTextures, and uiRecordSize.
start()
void Core::GameSys::_IconSys::start (int x, int y, float w, float h, std::string sTex, bool textOffset, Core::_Colors::_ACTIVE_COLOR eColor = Core::_Colors::COLOR_FRONT) private
Definition at line 249 of file IconSys.h.
References Core::colors, Core::GameVars::font, Core::gameVars, GL_DEPTH_TEST, GL_TRUE, Core::GLS_ICON, Core::GameVars::Screen::half, Core::GameVars::Screen::origin, Core::GameVars::screen, Core::_Colors::SetActive(), Core::GameVars::Font::vSize, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by draw().
stop()
void Core::GameSys::_IconSys::stop () private
Definition at line 284 of file IconSys.h.
References GL_DEPTH_TEST.
Referenced by draw().
update()
void Core::GameSys::_IconSys::update () private
Definition at line 278 of file IconSys.h.
References Core::GLS_ICON.
Referenced by draw().
Member Data Documentation
currentColor
Vector4f Core::GameSys::_IconSys::currentColor private
Definition at line 25 of file IconSys.h.
fMouseDelay
float Core::GameSys::_IconSys::fMouseDelay private
Definition at line 33 of file IconSys.h.
Referenced by _IconSys().
fMouseDelayConst
float Core::GameSys::_IconSys::fMouseDelayConst private
Definition at line 33 of file IconSys.h.
Referenced by _IconSys().
gridCoord
Vector4f Core::GameSys::_IconSys::gridCoord[64] private
Definition at line 25 of file IconSys.h.
Referenced by calc().
sDir
std::string Core::GameSys::_IconSys::sDir private
Definition at line 30 of file IconSys.h.
Referenced by _IconSys(), and load().
sFilename
std::string Core::GameSys::_IconSys::sFilename private
Definition at line 30 of file IconSys.h.
Referenced by _IconSys(), and load().
sTexDir
std::string Core::GameSys::_IconSys::sTexDir private
Definition at line 30 of file IconSys.h.
Referenced by _IconSys(), and load().
tempColor
Vector4f Core::GameSys::_IconSys::tempColor private
Definition at line 25 of file IconSys.h.
Referenced by _IconSys().
texture
Texture Core::GameSys::_IconSys::texture private
Definition at line 23 of file IconSys.h.
uiNumTextures
uint Core::GameSys::_IconSys::uiNumTextures private
Definition at line 28 of file IconSys.h.
Referenced by _IconSys(), and load().
uiRecordSize
uint Core::GameSys::_IconSys::uiRecordSize private
Definition at line 28 of file IconSys.h.
Referenced by _IconSys(), and load().
vao
VAO Core::GameSys::_IconSys::vao[64] private
Definition at line 24 of file IconSys.h.
Referenced by calc(), and draw().
The documentation for this class was generated from the following file:
src/headers/gamesys/IconSys.h