Project Parsec: Core::GameSys::_WorldMap Class Reference
Core::GameSys::_WorldMap Class Reference
#include <WorldMap.h>
Public Member Functions
_WorldMap (_Collision &inCollision, _Helper &inHelper)
virtual ~_WorldMap ()
bool load ()
bool calc ()
void draw ()
Public Attributes
_O2D * o2d
_O3D * o3d
_Lights * lights
Atmosphere * atmosphere
MapSys * map
Private Attributes
_Collision * collision
_Helper * helper
Detailed Description
Definition at line 49 of file WorldMap.h.
Constructor & Destructor Documentation
_WorldMap()
Core::GameSys::_WorldMap::_WorldMap (_Collision & inCollision, _Helper & inHelper)
Definition at line 75 of file WorldMap.h.
References atmosphere, collision, cout, helper, Core::_Lights::init(), Core::GameSys::Atmosphere::init(), Core::GameSys::MapSys::init(), lights, map, o2d, o3d, and Core::sOffset.
~_WorldMap()
Core::GameSys::_WorldMap::~_WorldMap () virtual
Definition at line 106 of file WorldMap.h.
References atmosphere, cout, lights, map, o2d, o3d, and Core::sOffset.
Member Function Documentation
calc()
bool Core::GameSys::_WorldMap::calc ()
Definition at line 133 of file WorldMap.h.
References atmosphere, Core::_Lights::calc(), Core::GameSys::_O2D::calc(), Core::GameSys::_O3D::calc(), Core::GameSys::Atmosphere::calc(), Core::GameSys::MapSys::calc(), cout, Core::gameVars, lights, map, o2d, o3d, and Core::sOffset.
Referenced by _Game::load().
draw()
void Core::GameSys::_WorldMap::draw ()
Definition at line 149 of file WorldMap.h.
References atmosphere, Core::GameSys::_O2D::draw(), Core::GameSys::_O3D::draw(), Core::GameSys::MapSys::draw(), Core::GLS_PHONG, Core::GLS_PHONG_O2D, lights, map, Core::GameSys::Atmosphere::MODE_FLORA, Core::GameSys::Atmosphere::MODE_SATELLITE, o2d, o3d, and Core::GameSys::Atmosphere::update().
Referenced by _Game::Update().
load()
bool Core::GameSys::_WorldMap::load ()
Definition at line 120 of file WorldMap.h.
References atmosphere, cout, lights, Core::_Lights::load(), Core::GameSys::_O2D::load(), Core::GameSys::_O3D::load(), Core::GameSys::Atmosphere::load(), Core::GameSys::MapSys::load(), map, o2d, o3d, and Core::sOffset.
Referenced by _Game::load().
Member Data Documentation
atmosphere
Atmosphere* Core::GameSys::_WorldMap::atmosphere
Definition at line 62 of file WorldMap.h.
Referenced by _WorldMap(), calc(), draw(), load(), _Game::Update(), and ~_WorldMap().
collision
_Collision* Core::GameSys::_WorldMap::collision private
Definition at line 71 of file WorldMap.h.
Referenced by _WorldMap().
helper
_Helper* Core::GameSys::_WorldMap::helper private
Definition at line 72 of file WorldMap.h.
Referenced by _WorldMap().
lights
_Lights* Core::GameSys::_WorldMap::lights
Definition at line 61 of file WorldMap.h.
Referenced by _WorldMap(), calc(), draw(), _Admin::init(), _Game::load(), load(), _Game::ProcessInput(), _Admin::run(), and ~_WorldMap().
map
MapSys* Core::GameSys::_WorldMap::map
Definition at line 63 of file WorldMap.h.
Referenced by _WorldMap(), calc(), draw(), load(), _Admin::run(), and ~_WorldMap().
o2d
_O2D* Core::GameSys::_WorldMap::o2d
Definition at line 51 of file WorldMap.h.
Referenced by _WorldMap(), calc(), draw(), load(), and ~_WorldMap().
o3d
_O3D* Core::GameSys::_WorldMap::o3d
Definition at line 52 of file WorldMap.h.
Referenced by _WorldMap(), calc(), draw(), _Game::load(), load(), _Game::ProcessInput(), _Admin::run(), and ~_WorldMap().
The documentation for this class was generated from the following file:
src/headers/gamesys/WorldMap.h