Project Parsec: Core::GUI::Object::ComboBox Class Reference
Core::GUI::Object::ComboBox Class Reference
#include <GUI_ComboBox.h>
Public Member Functions
ComboBox ()
ComboBox (std::string n, Props_ComboBox c)
ComboBox (std::string n, Props_ComboBox *c)
ComboBox (Props &p, std::string n, Props_ComboBox c)
ComboBox (Props &p, std::string n, Props_ComboBox *c)
virtual ~ComboBox ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_ComboBox >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Attributes
Object::Field< int > * selectedItem
Window * itemList
std::vector< Props_Addon_ReturnState > items
Map_si itemMap
std::variant< int, float, std::string > intFloatString
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_ComboBox >
int border
Props_ComboBox * con
Props * parent
Private Member Functions
void updateObjectState (iState eExternState)
Private Attributes
Window win
Additional Inherited Members
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_ComboBox >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 28 of file GUI_ComboBox.h.
Constructor & Destructor Documentation
ComboBox() [1/5]
Core::GUI::Object::ComboBox::ComboBox ()
Definition at line 63 of file GUI_ComboBox.h.
References itemList, and selectedItem.
ComboBox() [2/5]
Core::GUI::Object::ComboBox::ComboBox (std::string n, Props_ComboBox c)
Definition at line 68 of file GUI_ComboBox.h.
References Core::GUI::Object::Base::Generic< Props_ComboBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_ComboBox >::bInit, Core::GUI::Object::Base::Generic< Props_ComboBox >::bLocalCon, Core::GUI::Object::Base::Generic< Props_ComboBox >::con, itemList, Core::GUI::Object::Base::Generic< Props_ComboBox >::parent, and selectedItem.
ComboBox() [3/5]
Core::GUI::Object::ComboBox::ComboBox (std::string n, Props_ComboBox * c)
Definition at line 98 of file GUI_ComboBox.h.
References Core::GUI::Object::Base::Generic< Props_ComboBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_ComboBox >::bInit, Core::GUI::Object::Base::Generic< Props_ComboBox >::bLocalCon, Core::GUI::Object::Base::Generic< Props_ComboBox >::con, itemList, Core::GUI::Object::Base::Generic< Props_ComboBox >::parent, and selectedItem.
ComboBox() [4/5]
Core::GUI::Object::ComboBox::ComboBox (Props & p, std::string n, Props_ComboBox c)
Definition at line 83 of file GUI_ComboBox.h.
References Core::GUI::Object::Base::Generic< Props_ComboBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_ComboBox >::bInit, Core::GUI::Object::Base::Generic< Props_ComboBox >::bLocalCon, Core::GUI::Object::Base::Generic< Props_ComboBox >::con, itemList, p, Core::GUI::Object::Base::Generic< Props_ComboBox >::parent, and selectedItem.
ComboBox() [5/5]
Core::GUI::Object::ComboBox::ComboBox (Props & p, std::string n, Props_ComboBox * c)
Definition at line 112 of file GUI_ComboBox.h.
References Core::GUI::Object::Base::Generic< Props_ComboBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_ComboBox >::bInit, Core::GUI::Object::Base::Generic< Props_ComboBox >::bLocalCon, Core::GUI::Object::Base::Generic< Props_ComboBox >::con, itemList, p, Core::GUI::Object::Base::Generic< Props_ComboBox >::parent, and selectedItem.
~ComboBox()
Core::GUI::Object::ComboBox::~ComboBox () virtual
Definition at line 126 of file GUI_ComboBox.h.
References Core::GUI::Object::Base::Generic< Props_ComboBox >::bLocalCon, Core::GUI::Object::Base::Generic< Props_ComboBox >::con, itemList, and selectedItem.
Member Function Documentation
exec()
void Core::GUI::Object::ComboBox::exec (iState eExternState = STATE_NONE)
Definition at line 166 of file GUI_ComboBox.h.
References Core::GUI::Object::Base::Generic< Props_ComboBox >::bInit, Core::GUI::Object::Base::Generic< Props_ComboBox >::con, Core::GUI::Object::Field< T >::exec(), Core::GUI::Object::Window::exec(), itemList, Core::GUI::Object::Base::Generic< Props_ComboBox >::parent, selectedItem, updateObjectState(), and Core::GUI::Props::visibility.
execToolTip()
void Core::GUI::Object::ComboBox::execToolTip ()
Definition at line 205 of file GUI_ComboBox.h.
References Core::GUI::Object::ToolTip::exec(), and toolTip.
init()
void Core::GUI::Object::ComboBox::init ()
Definition at line 132 of file GUI_ComboBox.h.
References Core::GUI::Object::Base::Generic< Props_ComboBox >::bHasParent, Core::GUI::Object::Base::Generic< Props_ComboBox >::bInit, Core::GUI::Object::Base::Generic< Props_ComboBox >::con, Core::GUI::Props::exec(), Core::GUI::Object::Window::init(), Core::GUI::Object::Field< T >::init(), itemList, Core::GUI::Props_ComboBox::itemList, Core::GUI::Object::Base::Generic< Props_ComboBox >::parent, selectedItem, and Core::GUI::Props_ComboBox::selectedItem.
updateObjectState()
void Core::GUI::Object::ComboBox::updateObjectState (iState eExternState) private
Definition at line 146 of file GUI_ComboBox.h.
References Core::GUI::STATE_NOACTION.
Referenced by exec().
Member Data Documentation
intFloatString
std::variant<int, float, std::string> Core::GUI::Object::ComboBox::intFloatString
Definition at line 51 of file GUI_ComboBox.h.
itemList
Window* Core::GUI::Object::ComboBox::itemList
Definition at line 46 of file GUI_ComboBox.h.
Referenced by ComboBox(), exec(), init(), and ~ComboBox().
itemMap
Map_si Core::GUI::Object::ComboBox::itemMap
Definition at line 49 of file GUI_ComboBox.h.
items
std::vector<Props_Addon_ReturnState> Core::GUI::Object::ComboBox::items
Definition at line 48 of file GUI_ComboBox.h.
selectedItem
Object::Field<int>* Core::GUI::Object::ComboBox::selectedItem
Definition at line 44 of file GUI_ComboBox.h.
Referenced by ComboBox(), exec(), init(), and ~ComboBox().
toolTip
ToolTip Core::GUI::Object::ComboBox::toolTip
Definition at line 53 of file GUI_ComboBox.h.
Referenced by execToolTip().
win
Window Core::GUI::Object::ComboBox::win private
Definition at line 59 of file GUI_ComboBox.h.
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_ComboBox.h