Project Parsec: Core::GlInit_System Class Reference
Core::GlInit_System Class Reference
#include <glinit.h>
Public Member Functions
void init (std::string cCaption, GLuint uiWidth, GLuint uiHeight, GLuint uiBpp, bool bMS, Vector4f vClearColor)
void EnableAdditiveBlending ()
void DisableAdditiveBlending ()
void RestoreClearColor ()
~GlInit_System ()
Public Attributes
SDL_Window * window
SDL_GLContext context
Private Attributes
Vector4f vClearColor
Detailed Description
Definition at line 22 of file glinit.h.
Constructor & Destructor Documentation
~GlInit_System()
Core::GlInit_System::~GlInit_System ()
Definition at line 31 of file glinit.cpp.
References cout.
Member Function Documentation
DisableAdditiveBlending()
void Core::GlInit_System::DisableAdditiveBlending ()
Definition at line 62 of file glinit.cpp.
References GL_ONE_MINUS_SRC_ALPHA, and GL_SRC_ALPHA.
Referenced by Core::_ParticleEmitter::draw(), Core::GameSys::_Satellite::drawFlare(), and init().
EnableAdditiveBlending()
void Core::GlInit_System::EnableAdditiveBlending ()
Definition at line 52 of file glinit.cpp.
References GL_ONE, and GL_SRC_ALPHA.
Referenced by Core::_ParticleEmitter::draw(), and Core::GameSys::_Satellite::drawFlare().
init()
void Core::GlInit_System::init (std::string cCaption, GLuint uiWidth, GLuint uiHeight, GLuint uiBpp, bool bMS, Vector4f vClearColor)
Definition at line 66 of file glinit.cpp.
References context, cout, DisableAdditiveBlending(), GL_BACK, GL_BLEND, GL_CCW, GL_CULL_FACE, GL_DEPTH_CLAMP, GL_DEPTH_TEST, GL_FILL, GL_FRONT_AND_BACK, GL_FUNC_ADD, GL_GEQUAL, GL_LINE_SMOOTH_HINT, GL_LOWER_LEFT, GL_MULTISAMPLE, GL_NICEST, GL_NO_ERROR, GL_POINT_FADE_THRESHOLD_SIZE, GL_POINT_SPRITE, GL_POINT_SPRITE_COORD_ORIGIN, GL_POLYGON_SMOOTH_HINT, GL_PROGRAM_POINT_SIZE, GL_TRUE, GL_UPPER_LEFT, GL_ZERO_TO_ONE, vClearColor, and window.
Referenced by MY_NAMESPACE::Setup().
RestoreClearColor()
void Core::GlInit_System::RestoreClearColor ()
Definition at line 45 of file glinit.cpp.
References vClearColor.
Referenced by _Game::Update().
Member Data Documentation
context
SDL_GLContext Core::GlInit_System::context
Definition at line 28 of file glinit.h.
Referenced by init().
vClearColor
Vector4f Core::GlInit_System::vClearColor private
Definition at line 24 of file glinit.h.
Referenced by init(), and RestoreClearColor().
window
SDL_Window* Core::GlInit_System::window
Definition at line 27 of file glinit.h.
Referenced by init().
The documentation for this class was generated from the following files:
src/headers/core/glinit.h
src/headers/core/glinit.cpp