Project Parsec: Core::GUI::Constraints Class Reference
Core::GUI::Constraints Class Reference
General Constraints used for all objects.
#include <GUI_Constraint.h>
Classes
struct _Position
struct _Size
Public Member Functions
void setPos (int n1, int n2)
void setX (int n)
void setY (int n)
void setWidth (int n, eSizeConstraint e=SIZE_CONSTRAINT_RELATIVE)
void setHeight (int n, eSizeConstraint e=SIZE_CONSTRAINT_RELATIVE)
void setAnchor (iConstrain e=CONSTRAIN_CENTER)
void setOrigin (iConstrain e=CONSTRAIN_CENTER)
void exec ()
void exec (Constraints c)
Vector2f getPos ()
Vector2f getSize ()
void setPadding (int i)
void enablePadding ()
void disablePadding ()
void setVisibility (bool b)
Constraints ()
~Constraints ()
Public Attributes
Core::GUI::Constraints::_Position pos
Actual calculated position from origin and anchor constraints, automatically updated.
Core::GUI::Constraints::_Size size
Actual calculated width(x) and height(y) from origin and anchor constraints, automatically updated.
int origin
The starting drawing point with respect to the parent, if present, otherwise full screen.
int anchor
The point at which this object is offset from the origin.
int padding
Extra reserved space taken into account for origin. This is similar to margins in HTML except is global for all sides.
bool bEnablePadding
Allow individual objects to ignore padding (ex: allows anchoring to outside of a window)
bool visibility
Controls if this object is drawn. Only used in Containers and Windows. All other objects rely on their parents status.
Private Member Functions
void execPos (Vector2f cHalf, Vector2f oPos=Vector2f(0.0f), int iPad=0)
void execSize (Vector2f cSize)
Detailed Description
General Constraints used for all objects.
Generic constraints that all other contraints rely on. This is also the class that is used for parents to constrain objects to each other.
Definition at line 121 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Constraints()
Core::GUI::Constraints::Constraints () inline
Definition at line 161 of file GUI_Constraint.h.
References anchor, bEnablePadding, Core::GUI::CONSTRAIN_CENTER, origin, padding, setHeight(), setPos(), setWidth(), Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, and visibility.
~Constraints()
Core::GUI::Constraints::~Constraints () inline
Definition at line 181 of file GUI_Constraint.h.
Member Function Documentation
disablePadding()
void Core::GUI::Constraints::disablePadding () inline
Definition at line 158 of file GUI_Constraint.h.
References bEnablePadding.
Referenced by Core::GUI::Object::TextArea::init(), and Core::GUI::Object::ColorSwatch::init().
enablePadding()
void Core::GUI::Constraints::enablePadding () inline
Definition at line 157 of file GUI_Constraint.h.
References bEnablePadding.
exec() [1/2]
void Core::GUI::Constraints::exec () inline
Definition at line 152 of file GUI_Constraint.h.
References execPos(), execSize(), Core::gameVars, Core::GameVars::Screen::half, Core::GameVars::Screen::res, and Core::GameVars::screen.
Referenced by Core::GUI::Object::Label::exec(), Core::GUI::Object::Text::exec(), Core::GUI::Object::Container::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::ColorSwatch::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::Label::init(), Core::GUI::Object::Container::init(), Core::GUI::Object::Text::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::Window::init(), Core::GUI::Object::Button::init(), and Core::GUI::Object::ColorSwatch::init().
exec() [2/2]
void Core::GUI::Constraints::exec (Constraints c) inline
Definition at line 153 of file GUI_Constraint.h.
References execPos(), and execSize().
execPos()
void Core::GUI::Constraints::execPos (Vector2f cHalf, Vector2f oPos = Vector2f(0.0f), int iPad = 0) private
Definition at line 847 of file GUI_Constraint.h.
References bEnablePadding, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, Core::GUI::CONSTRAIN_TOP, Core::GUI::Constraints::_Position::constraint, origin, pos, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
execSize()
void Core::GUI::Constraints::execSize (Vector2f cSize) private
Definition at line 872 of file GUI_Constraint.h.
References anchor, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, Core::GUI::CONSTRAIN_TOP, pos, Core::GUI::SIZE_CONSTRAINT_RELATIVE, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
getPos()
Vector2f Core::GUI::Constraints::getPos () inline
Definition at line 154 of file GUI_Constraint.h.
References pos, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by Core::GUI::Object::Window::exec(), and Core::GUI::Object::ColorSwatch::exec().
getSize()
Vector2f Core::GUI::Constraints::getSize () inline
Definition at line 155 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::Window::exec(), and Core::GUI::Object::ColorSwatch::exec().
setAnchor()
void Core::GUI::Constraints::setAnchor (iConstrain e = CONSTRAIN_CENTER) inline
Definition at line 150 of file GUI_Constraint.h.
References anchor.
Referenced by Core::GUI::Object::CheckBox::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Slider< int >::init(), and _Admin::run().
setHeight()
void Core::GUI::Constraints::setHeight (int n, eSizeConstraint e = SIZE_CONSTRAINT_RELATIVE) inline
Definition at line 149 of file GUI_Constraint.h.
Referenced by Constraints(), Core::GUI::Constraints_CheckBox::Constraints_CheckBox(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Slider< int >::init(), and _Admin::run().
setOrigin()
void Core::GUI::Constraints::setOrigin (iConstrain e = CONSTRAIN_CENTER) inline
Definition at line 151 of file GUI_Constraint.h.
References origin.
Referenced by Core::GUI::Object::CheckBox::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Slider< int >::init(), and _Admin::run().
setPadding()
void Core::GUI::Constraints::setPadding (int i) inline
Definition at line 156 of file GUI_Constraint.h.
References padding.
Referenced by Core::GUI::Constraints_CheckBox::Constraints_CheckBox(), Core::GUI::Object::TextArea::init(), and _Admin::run().
setPos()
void Core::GUI::Constraints::setPos (int n1, int n2) inline
Definition at line 145 of file GUI_Constraint.h.
References Core::GUI::Constraints::_Position::constraint, pos, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by Constraints(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Slider< int >::init(), and _Admin::run().
setVisibility()
void Core::GUI::Constraints::setVisibility (bool b) inline
Definition at line 159 of file GUI_Constraint.h.
References visibility.
Referenced by _Admin::run().
setWidth()
void Core::GUI::Constraints::setWidth (int n, eSizeConstraint e = SIZE_CONSTRAINT_RELATIVE) inline
Definition at line 148 of file GUI_Constraint.h.
Referenced by Constraints(), Core::GUI::Constraints_CheckBox::Constraints_CheckBox(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::Label::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Slider< int >::init(), and _Admin::run().
setX()
void Core::GUI::Constraints::setX (int n) inline
Definition at line 146 of file GUI_Constraint.h.
References Core::GUI::Constraints::_Position::constraint, pos, and Core::Vector2f::x.
setY()
void Core::GUI::Constraints::setY (int n) inline
Definition at line 147 of file GUI_Constraint.h.
References Core::GUI::Constraints::_Position::constraint, pos, and Core::Vector2f::y.
Referenced by Core::GUI::Object::ColorSwatch::init(), and _Admin::run().
Member Data Documentation
anchor
int Core::GUI::Constraints::anchor
The point at which this object is offset from the origin.
Definition at line 135 of file GUI_Constraint.h.
Referenced by Constraints(), execSize(), and setAnchor().
bEnablePadding
bool Core::GUI::Constraints::bEnablePadding
Allow individual objects to ignore padding (ex: allows anchoring to outside of a window)
Definition at line 137 of file GUI_Constraint.h.
Referenced by Constraints(), disablePadding(), enablePadding(), and execPos().
origin
int Core::GUI::Constraints::origin
The starting drawing point with respect to the parent, if present, otherwise full screen.
Definition at line 134 of file GUI_Constraint.h.
Referenced by Constraints(), execPos(), and setOrigin().
padding
int Core::GUI::Constraints::padding
Extra reserved space taken into account for origin. This is similar to margins in HTML except is global for all sides.
Definition at line 136 of file GUI_Constraint.h.
Referenced by Constraints(), Core::GUI::Constraints_ColorSwatch::Constraints_ColorSwatch(), Core::GUI::Constraints_Label::Constraints_Label(), Core::GUI::Constraints_Slider::Constraints_Slider(), Core::GUI::Constraints_Window::Constraints_Window(), Core::_TextSys::drawMulti(), Core::GUI::Object::Label::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), and setPadding().
pos
Core::GUI::Constraints::_Position Core::GUI::Constraints::pos
Actual calculated position from origin and anchor constraints, automatically updated.
Referenced by Core::GUI::Object::CheckBox::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::TextEdit::exec(), execPos(), execSize(), getPos(), setPos(), setX(), and setY().
size
Core::GUI::Constraints::_Size Core::GUI::Constraints::size
Actual calculated width(x) and height(y) from origin and anchor constraints, automatically updated.
Referenced by Core::_TextSys::drawMulti(), Core::GUI::Object::CheckBox::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::Label::init(), Core::GUI::Object::TextArea::init(), and Core::GUI::Object::ColorSwatch::init().
visibility
bool Core::GUI::Constraints::visibility
Controls if this object is drawn. Only used in Containers and Windows. All other objects rely on their parents status.
Definition at line 138 of file GUI_Constraint.h.
Referenced by Constraints(), Core::GUI::Object::CheckBox::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::Text::exec(), Core::GUI::Object::Container::exec(), Core::GUI::Object::TextArea::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::ColorSwatch::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::Container::hide(), Core::GUI::Object::Window::hide(), setVisibility(), Core::GUI::Object::Container::show(), Core::GUI::Object::Window::show(), Core::GUI::Object::Container::toggle(), and Core::GUI::Object::Window::toggle().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI_Constraint.h