Project Parsec: RunDungeon Class Reference
RunDungeon Class Reference
#include <runDungeon.h>
Public Member Functions
RunDungeon ()
void run ()
bool load ()
Public Attributes
DungeonMap map
Atmosphere atmosphere
O2DD o2d
O3D_Dungeon o3d
Water water
Protected Member Functions
void getInput ()
void processInput ()
void update (bool shadowPass)
void draw ()
void getHeight ()
void getJump ()
Private Attributes
Keyboard keyboard
Detailed Description
Definition at line 17 of file runDungeon.h.
Constructor & Destructor Documentation
RunDungeon()
RunDungeon::RunDungeon ()
Definition at line 52 of file runDungeon.h.
References keyboard.
Member Function Documentation
draw()
void RunDungeon::draw () protected
Definition at line 155 of file runDungeon.h.
Referenced by run().
getHeight()
void RunDungeon::getHeight () protected
getInput()
void RunDungeon::getInput () protected
Definition at line 161 of file runDungeon.h.
References Core::GameVars::controls, Core::GameVars::debug, Core::gameVars, keyboard, processInput(), and Core::GameVars::screen.
Referenced by run().
getJump()
void RunDungeon::getJump () protected
load()
bool RunDungeon::load ()
Definition at line 57 of file runDungeon.h.
References atmosphere, O3D_Dungeon::calc(), DungeonMap::calc(), Water::calc(), Core::GameVars::debug, Core::gameVars, Water::init(), DungeonMap::init(), O3D_Dungeon::load(), Water::load(), map, o3d, and water.
processInput()
void RunDungeon::processInput () protected
Definition at line 212 of file runDungeon.h.
References Core::GameVars::Screen::clear, Core::GameVars::controls, Core::GameVars::debug, Core::GameVars::Controls::fly, Core::gameVars, GL_COLOR_BUFFER_BIT, GL_DEPTH_BUFFER_BIT, GL_FILL, GL_FRONT_AND_BACK, GL_LINE, GL_POINT, Core::GameVars::Controls::key, keyboard, Core::GameVars::Controls::_KeyBinding::mouse_down, Core::GameVars::Controls::_KeyBinding::mouse_left, Core::GameVars::Controls::_KeyBinding::mouse_right, Core::GameVars::Controls::_KeyBinding::mouse_up, Core::GameVars::Controls::_KeyBinding::move_back, Core::GameVars::Controls::_KeyBinding::move_down, Core::GameVars::Controls::_KeyBinding::move_forward, Core::GameVars::Controls::_KeyBinding::move_up, Core::GameVars::Controls::moveSpeed, Core::GameVars::Controls::_KeyBinding::run, Core::GameVars::screen, Core::GameVars::Controls::_KeyBinding::sneak, Core::GameVars::Controls::_KeyBinding::strafe_left, Core::GameVars::Controls::_KeyBinding::strafe_right, Core::GameVars::Controls::_KeyBinding::turn_left, and Core::GameVars::Controls::_KeyBinding::turn_right.
Referenced by getInput().
run()
void RunDungeon::run ()
Definition at line 94 of file runDungeon.h.
References Core::GameVars::Screen::clear, draw(), Core::gameVars, getInput(), Core::GameVars::screen, and update().
update()
void RunDungeon::update (bool shadowPass) protected
Definition at line 111 of file runDungeon.h.
References atmosphere, O3D_Dungeon::draw(), DungeonMap::draw(), Water::draw(), Core::gameVars, GL_TEXTURE0, Core::GLS_FONT, map, o3d, Core::GameVars::player, Core::GameVars::Player::sheet, Core::GameSys::CharSheet::transform, and water.
Referenced by run().
Member Data Documentation
atmosphere
Atmosphere RunDungeon::atmosphere
Definition at line 37 of file runDungeon.h.
Referenced by load(), and update().
keyboard
Keyboard RunDungeon::keyboard private
Definition at line 19 of file runDungeon.h.
Referenced by getInput(), processInput(), and RunDungeon().
map
DungeonMap RunDungeon::map
Definition at line 30 of file runDungeon.h.
Referenced by load(), and update().
o2d
O2DD RunDungeon::o2d
Definition at line 39 of file runDungeon.h.
o3d
O3D_Dungeon RunDungeon::o3d
Definition at line 42 of file runDungeon.h.
Referenced by load(), and update().
water
Water RunDungeon::water
Definition at line 43 of file runDungeon.h.
Referenced by load(), and update().
The documentation for this class was generated from the following file:
src/game/ref/runDungeon.h