Project Parsec: Core::_TimeSys Class Reference
Core::_TimeSys Class Reference
#include <TimeSys.h>
Public Types
enum _SEASONS {
SPRING, SUMMER, FALL, WINTER,
SEASON_LAST
}
Public Member Functions
_TimeSys ()
virtual ~_TimeSys ()
float Update ()
void SetSeasonFactors ()
std::string GetSeasonStr ()
void UpdateDay ()
void UpdateTime ()
void UpdateTime (float fTime)
void UpdateSeason ()
int GetHour ()
int GetMinute ()
int GetSecond ()
int GetHour (float fTime)
int GetMinute (float fTime)
int GetSecond (float fTime)
int GetMinutes ()
int GetSeconds ()
Public Member Functions inherited from Core::Timer
Timer ()
void set (float fTime)
void start ()
void stop ()
void pause ()
void unpause ()
float split ()
float get_split ()
float get_splitdiff ()
void reset ()
float get_ticks ()
bool is_started ()
bool is_paused ()
Public Attributes
float fFactor
int iDay
int iYear
int iSeason
int iHour
int iMinute
int iSecond
float fSWinter
float fSSpring
float fSSummer
float fSFall
float fTimeRaw
float fDay
float fHour
Public Attributes inherited from Core::Timer
float startTicks
float rate
float rateMod
Detailed Description
Definition at line 34 of file TimeSys.h.
Member Enumeration Documentation
_SEASONS
enum Core::_TimeSys::_SEASONS
Enumerator
SPRING
SUMMER
FALL
WINTER
SEASON_LAST
Definition at line 39 of file TimeSys.h.
Constructor & Destructor Documentation
_TimeSys()
Core::_TimeSys::_TimeSys ()
Definition at line 11 of file TimeSys.cpp.
~_TimeSys()
Core::_TimeSys::~_TimeSys () virtual
Definition at line 27 of file TimeSys.cpp.
Member Function Documentation
GetHour() [1/2]
int Core::_TimeSys::GetHour ()
Definition at line 181 of file TimeSys.cpp.
References iHour.
Referenced by GetMinute(), GetSecond(), and _Game::Update().
GetHour() [2/2]
int Core::_TimeSys::GetHour (float fTime)
Definition at line 193 of file TimeSys.cpp.
References iHour.
GetMinute() [1/2]
int Core::_TimeSys::GetMinute ()
Definition at line 184 of file TimeSys.cpp.
References iMinute.
Referenced by GetSecond(), and _Game::Update().
GetMinute() [2/2]
int Core::_TimeSys::GetMinute (float fTime)
Definition at line 197 of file TimeSys.cpp.
References GetHour(), and iMinute.
GetMinutes()
int Core::_TimeSys::GetMinutes ()
Definition at line 205 of file TimeSys.cpp.
References fFactor, and Core::Timer::get_ticks().
GetSeasonStr()
std::string Core::_TimeSys::GetSeasonStr ()
Definition at line 108 of file TimeSys.cpp.
References FALL, iSeason, SPRING, SUMMER, and WINTER.
GetSecond() [1/2]
int Core::_TimeSys::GetSecond ()
Definition at line 187 of file TimeSys.cpp.
References iSecond.
Referenced by _Game::Update().
GetSecond() [2/2]
int Core::_TimeSys::GetSecond (float fTime)
Definition at line 201 of file TimeSys.cpp.
References GetHour(), GetMinute(), and iSecond.
GetSeconds()
int Core::_TimeSys::GetSeconds ()
Definition at line 208 of file TimeSys.cpp.
References fFactor, and Core::Timer::get_ticks().
SetSeasonFactors()
void Core::_TimeSys::SetSeasonFactors ()
Definition at line 49 of file TimeSys.cpp.
References fDay, fSFall, fSSpring, fSSummer, fSWinter, and iDay.
Referenced by Update().
Update()
float Core::_TimeSys::Update ()
Definition at line 126 of file TimeSys.cpp.
References fTimeRaw, SetSeasonFactors(), UpdateDay(), UpdateSeason(), and UpdateTime().
Referenced by main().
UpdateDay()
void Core::_TimeSys::UpdateDay ()
Definition at line 138 of file TimeSys.cpp.
References fDay, fHour, fTimeRaw, iDay, iYear, and Core::Timer::reset().
Referenced by Update().
UpdateSeason()
void Core::_TimeSys::UpdateSeason ()
Definition at line 170 of file TimeSys.cpp.
References FALL, iDay, iSeason, SPRING, SUMMER, and WINTER.
Referenced by Update().
UpdateTime() [1/2]
void Core::_TimeSys::UpdateTime ()
Definition at line 157 of file TimeSys.cpp.
References fFactor, fTimeRaw, Core::Timer::get_ticks(), iHour, iMinute, and iSecond.
Referenced by Update().
UpdateTime() [2/2]
void Core::_TimeSys::UpdateTime (float fTime)
Definition at line 164 of file TimeSys.cpp.
References fFactor, Core::Timer::get_ticks(), iHour, iMinute, and iSecond.
Member Data Documentation
fDay
float Core::_TimeSys::fDay
Definition at line 51 of file TimeSys.h.
Referenced by SetSeasonFactors(), and UpdateDay().
fFactor
float Core::_TimeSys::fFactor
Definition at line 40 of file TimeSys.h.
Referenced by GetMinutes(), GetSeconds(), and UpdateTime().
fHour
float Core::_TimeSys::fHour
Definition at line 51 of file TimeSys.h.
Referenced by UpdateDay().
fSFall
float Core::_TimeSys::fSFall
Definition at line 47 of file TimeSys.h.
Referenced by SetSeasonFactors().
fSSpring
float Core::_TimeSys::fSSpring
Definition at line 47 of file TimeSys.h.
Referenced by SetSeasonFactors().
fSSummer
float Core::_TimeSys::fSSummer
Definition at line 47 of file TimeSys.h.
Referenced by SetSeasonFactors().
fSWinter
float Core::_TimeSys::fSWinter
Definition at line 47 of file TimeSys.h.
Referenced by SetSeasonFactors().
fTimeRaw
float Core::_TimeSys::fTimeRaw
Definition at line 51 of file TimeSys.h.
Referenced by Update(), Core::GameSys::_Satellite::update(), UpdateDay(), and UpdateTime().
iDay
int Core::_TimeSys::iDay
Definition at line 41 of file TimeSys.h.
Referenced by SetSeasonFactors(), _Game::Update(), UpdateDay(), and UpdateSeason().
iHour
int Core::_TimeSys::iHour
Definition at line 44 of file TimeSys.h.
Referenced by GetHour(), and UpdateTime().
iMinute
int Core::_TimeSys::iMinute
Definition at line 45 of file TimeSys.h.
Referenced by GetMinute(), and UpdateTime().
iSeason
int Core::_TimeSys::iSeason
Definition at line 43 of file TimeSys.h.
Referenced by GetSeasonStr(), and UpdateSeason().
iSecond
int Core::_TimeSys::iSecond
Definition at line 46 of file TimeSys.h.
Referenced by GetSecond(), and UpdateTime().
iYear
int Core::_TimeSys::iYear
Definition at line 42 of file TimeSys.h.
Referenced by _Game::Update(), and UpdateDay().
The documentation for this class was generated from the following files:
src/headers/core/TimeSys.h
src/headers/core/TimeSys.cpp