Project Parsec: Core::GUI::Object::ColorSwatch Class Reference
Core::GUI::Object::ColorSwatch Class Reference
#include <GUI_ColorSwatch.h>
Public Member Functions
ColorSwatch ()
ColorSwatch (std::string n, Color *ptr, Props_ColorSwatch c)
ColorSwatch (Props &p, std::string n, Color *ptr, Props_ColorSwatch c)
ColorSwatch (std::string n, Color *ptr, Props_ColorSwatch *c)
ColorSwatch (Props &p, std::string n, Color *ptr, Props_ColorSwatch *c)
virtual ~ColorSwatch ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_ColorSwatch >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_ColorSwatch >
int border
Props_ColorSwatch * con
Props * parent
Protected Member Functions
void updateObjectState (iState eExternState)
Protected Attributes
Color * colorPtr
Slider< float > * sliderR
Slider< float > * sliderG
Slider< float > * sliderB
Slider< float > * sliderA
Label * label
Window * background
Window swatch
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_ColorSwatch >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 38 of file GUI_ColorSwatch.h.
Constructor & Destructor Documentation
ColorSwatch() [1/5]
Core::GUI::Object::ColorSwatch::ColorSwatch ()
Definition at line 64 of file GUI_ColorSwatch.h.
References background, colorPtr, sliderA, sliderB, sliderG, and sliderR.
ColorSwatch() [2/5]
Core::GUI::Object::ColorSwatch::ColorSwatch (std::string n, Color * ptr, Props_ColorSwatch c)
Definition at line 74 of file GUI_ColorSwatch.h.
References background, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bHasParent, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bLocalCon, colorPtr, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::parent, sliderA, sliderB, sliderG, and sliderR.
ColorSwatch() [3/5]
Core::GUI::Object::ColorSwatch::ColorSwatch (Props & p, std::string n, Color * ptr, Props_ColorSwatch c)
Definition at line 93 of file GUI_ColorSwatch.h.
References background, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bHasParent, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bLocalCon, colorPtr, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, p, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::parent, sliderA, sliderB, sliderG, and sliderR.
ColorSwatch() [4/5]
Core::GUI::Object::ColorSwatch::ColorSwatch (std::string n, Color * ptr, Props_ColorSwatch * c)
Definition at line 112 of file GUI_ColorSwatch.h.
References background, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bHasParent, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bLocalCon, colorPtr, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::parent, sliderA, sliderB, sliderG, and sliderR.
ColorSwatch() [5/5]
Core::GUI::Object::ColorSwatch::ColorSwatch (Props & p, std::string n, Color * ptr, Props_ColorSwatch * c)
Definition at line 130 of file GUI_ColorSwatch.h.
References background, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bHasParent, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bLocalCon, colorPtr, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, p, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::parent, sliderA, sliderB, sliderG, and sliderR.
~ColorSwatch()
Core::GUI::Object::ColorSwatch::~ColorSwatch () virtual
Definition at line 149 of file GUI_ColorSwatch.h.
References background, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bInit, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bLocalCon, Core::GUI::Props_Addon_Slider::bShowSlider, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, label, sliderA, sliderB, sliderG, and sliderR.
Member Function Documentation
exec()
void Core::GUI::Object::ColorSwatch::exec (iState eExternState = STATE_NONE)
Definition at line 236 of file GUI_ColorSwatch.h.
References background, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bHasParent, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bInit, Core::GUI::Props::ToolTip::bShow, Core::GUI::Props_Addon_Background::bShowBackground, Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Props_Addon_Slider::bShowSlider, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, Core::GUI::Object::Slider< T >::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Core::GUI::Object::Base::Generic< Props_ColorSwatch >::parent, sliderA, sliderB, sliderG, sliderR, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, swatch, toolTip, Core::GUI::Props::toolTip, Core::GUI::Object::ToolTip::updateObjectState(), updateObjectState(), and Core::GUI::Props::visibility.
execToolTip()
void Core::GUI::Object::ColorSwatch::execToolTip ()
Definition at line 284 of file GUI_ColorSwatch.h.
References Core::GUI::Props_Addon_Slider::bShowSlider, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::Slider< T >::execToolTip(), sliderA, sliderB, sliderG, sliderR, and toolTip.
init()
void Core::GUI::Object::ColorSwatch::init ()
Definition at line 161 of file GUI_ColorSwatch.h.
References Core::Color::a, Core::Color::b, Core::GUI::Props_Window::Colors::back, background, Core::GUI::Props_Addon_Background::background, Core::GUI::GUI_ColorB::base, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bHasParent, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::bInit, Core::GUI::Props_Window::borderHover, Core::GUI::Props_Window::borderNormal, Core::GUI::Props_Addon_Background::bShowBackground, Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Props_Addon_Slider::bShowSlider, Core::GUI::Props_Window::color, colorPtr, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::Props_Slider::control, Core::GUI::Props::disablePadding(), Core::GUI::Props_Addon_Stipple::enableStipple(), Core::GUI::Props::exec(), Core::Color::g, Core::GUI::GUI_ColorH::highlight, Core::GUI::Object::ToolTip::init(), Core::GUI::Object::Slider< T >::init(), Core::GUI::Object::Window::init(), Core::GUI::Object::Base::Generic< Props_ColorSwatch >::Label, Core::GUI::Props_Addon_Label::label, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::parent, Core::Color::r, Core::GUI::Props_Window::radius, Core::GUI::Props_Window::setBorder(), Core::GUI::Props::setHeight(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props_Addon_Stipple::setStipplePattern(), Core::GUI::Props::setWidth(), Core::GUI::Props::setY(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::SIZE_CONSTRAINT_RELATIVE, Core::GUI::Props_Addon_Slider::slider, sliderA, sliderB, sliderG, sliderR, Core::stipple, swatch, toolTip, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::Window, and Core::Vector2f::y.
updateObjectState()
void Core::GUI::Object::ColorSwatch::updateObjectState (iState eExternState) protected
Definition at line 217 of file GUI_ColorSwatch.h.
References Core::_Mouse::checkInput(), Core::GUI::Object::Base::Generic< Props_ColorSwatch >::con, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::enabled(), Core::gameVars, Core::GameVars::Screen::half, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_NONE, Core::GUI::Object::Base::Generic< Props_ColorSwatch >::mState, Core::GUI::Props::pos, Core::GameVars::screen, Core::GUI::Props::size, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
Member Data Documentation
background
Window* Core::GUI::Object::ColorSwatch::background protected
Definition at line 59 of file GUI_ColorSwatch.h.
Referenced by ColorSwatch(), exec(), init(), and ~ColorSwatch().
colorPtr
Color* Core::GUI::Object::ColorSwatch::colorPtr protected
Definition at line 53 of file GUI_ColorSwatch.h.
Referenced by ColorSwatch(), and init().
label
Label* Core::GUI::Object::ColorSwatch::label protected
Definition at line 58 of file GUI_ColorSwatch.h.
Referenced by ~ColorSwatch().
sliderA
Slider<float>* Core::GUI::Object::ColorSwatch::sliderA protected
Definition at line 57 of file GUI_ColorSwatch.h.
Referenced by ColorSwatch(), exec(), execToolTip(), init(), and ~ColorSwatch().
sliderB
Slider<float>* Core::GUI::Object::ColorSwatch::sliderB protected
Definition at line 56 of file GUI_ColorSwatch.h.
Referenced by ColorSwatch(), exec(), execToolTip(), init(), and ~ColorSwatch().
sliderG
Slider<float>* Core::GUI::Object::ColorSwatch::sliderG protected
Definition at line 55 of file GUI_ColorSwatch.h.
Referenced by ColorSwatch(), exec(), execToolTip(), init(), and ~ColorSwatch().
sliderR
Slider<float>* Core::GUI::Object::ColorSwatch::sliderR protected
Definition at line 54 of file GUI_ColorSwatch.h.
Referenced by ColorSwatch(), exec(), execToolTip(), init(), and ~ColorSwatch().
swatch
Window Core::GUI::Object::ColorSwatch::swatch protected
Definition at line 60 of file GUI_ColorSwatch.h.
Referenced by exec(), and init().
toolTip
ToolTip Core::GUI::Object::ColorSwatch::toolTip
Definition at line 47 of file GUI_ColorSwatch.h.
Referenced by exec(), execToolTip(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_ColorSwatch.h