Project Parsec: Core::GUI::Props_Slider Class Reference
Core::GUI::Props_Slider Class Reference
#include <GUI_Constraint.h>
Public Member Functions
void setOrientation (eSlider e)
void setMinMax (Vector2f v)
void setMinMax (float min, float max)
void setPrecision (int i)
void setFieldSizeAbsolute (int i)
void setFieldSizeRelative (int i)
void setScrollSpeed (float f)
void setStep (float f)
void setStep (float min, float std, float max)
void swapOrientation ()
Props_Slider (eSlider orientation=SLIDER_HORIZONTAL)
~Props_Slider ()
Public Member Functions inherited from Core::GUI::Props_Window
void setBorder (int iNormal, int iHover)
void setRadius (int i)
void setRoundBorder (bool b=true)
int getRadius ()
bool getRoundBorder ()
void setScissor (bool b)
void enableScissor ()
void disableScissor ()
void setResizeRadius (bool b=true)
Props_Window ()
~Props_Window ()
Public Member Functions inherited from Core::GUI::Props
void setPos (Vector2f v)
void setPos (int n1, int n2)
void modPos (int n1, int n2)
void setX (int n)
void setY (int n)
void modX (int n)
void modY (int n)
void setWidth (int n, eSizeConstraint e=SIZE_CONSTRAINT_ABSOLUTE)
void setHeight (int n, eSizeConstraint e=SIZE_CONSTRAINT_ABSOLUTE)
void modSize (int n1, int n2)
void setAnchor (iConstrain e=CONSTRAIN_CENTER)
void setOrigin (iConstrain e=CONSTRAIN_CENTER)
void exec ()
void exec (Props c)
Vector2f getPos ()
Vector2f getSize ()
void setPadding (int i)
void setPadding (int t, int b, int l, int r)
void setPadding (Vector4i v)
void enablePadding (ePadding e=PADDING_POSITION)
void disablePadding ()
void setVisibility (bool b)
void enableToolTip ()
void disableToolTip ()
void setToolTip (std::string s)
void autoWidth (bool b=true)
void autoHeight (bool b=true)
void setMinMaxWidth (int min, int max)
void setMinWidth (int i)
void setMaxWidth (int i)
void setMinMaxHeight (int min, int max)
void setMinHeight (int i)
void setMaxHeight (int i)
Props ()
Props (Props &src)
~Props ()
Public Member Functions inherited from Core::GUI::Props_Addon_Stipple
void setStipple (bool b)
void enableStipple ()
void disableStipple ()
void setStipplePattern (Stipple_Pattern *s)
void setStippleColorB (Color *c)
void setStippleColorH (Color *c)
void setStippleColorA (Color *c)
Props_Addon_Stipple ()
Public Member Functions inherited from Core::GUI::Props_Addon_Label
void showLabel ()
void hideLabel ()
Props_Addon_Label ()
Public Member Functions inherited from Core::GUI::Props_Addon_Field
void showField ()
void hideField ()
Props_Addon_Field ()
Public Attributes
eSlider orientation
float minValue
float maxValue
float scrollSpeed
int precision
int iFieldSize
bool bExactSize
Vector3f vStep
Props_Window control
Public Attributes inherited from Core::GUI::Props_Window
struct Core::GUI::Props_Window::Colors color
bool roundBorder
int borderNormal
int borderHover
int radius
bool bResizeRadius
bool bScissor
Public Attributes inherited from Core::GUI::Props
Core::GUI::Props::_Position pos
Actual calculated position from origin and anchor constraints, automatically updated.
Core::GUI::Props::_Size size
Actual calculated width(x) and height(y) from origin and anchor constraints, automatically updated.
int origin
The starting drawing point with respect to the parent, if present, otherwise full screen.
int anchor
The point at which this object is offset from the origin.
Vector4i vPadding
Extra reserved space taken into account for origin.
ePadding eEnablePadding
bool visibility
Controls if this object is drawn and any of its direct children.
struct Core::GUI::Props::ToolTip toolTip
Public Attributes inherited from Core::GUI::Props_Addon_Stipple
Stipple_Pattern * stipple
GUI_ColorBHA stippleColor
bool bEnableStipple
Public Attributes inherited from Core::GUI::Props_Addon_Label
bool bShowLabel
Props_Label label
Public Attributes inherited from Core::GUI::Props_Addon_Field
bool bShowField
Props_Field field
Friends
template<class T >
class Object::Slider
Additional Inherited Members
Static Public Attributes inherited from Core::GUI::Props
static bool bGlobalSettings = true
Used externally to allow multiple windows to use identical settings.
Detailed Description
Definition at line 760 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Props_Slider()
Core::GUI::Props_Slider::Props_Slider (eSlider orientation = SLIDER_HORIZONTAL) inline
Definition at line 824 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::Props_Window::Colors::back, Core::GUI::GUI_ColorB::base, bExactSize, Core::GUI::Props_Window::Colors::border, Core::GUI::Props_Addon_Field::bShowField, Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Props_Window::color, Core::GUI::Props_Field::color, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, control, Core::GUI::Props_Addon_Field::field, Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::GUI_ColorH::highlight, iFieldSize, maxValue, minValue, orientation, Core::GameVars::pallette, scrollSpeed, Core::GUI::Props::setAnchor(), Core::GUI::Props_Window::setBorder(), Core::GUI::Props::setHeight(), Core::GUI::Props::setOrigin(), Core::GUI::Props::setPadding(), Core::GUI::Props::setPos(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props::setWidth(), Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GameVars::_Pallette::slider, Core::GUI::SLIDER_HORIZONTAL, Core::GUI::Props_Field::Colors::text, and vStep.
~Props_Slider()
Core::GUI::Props_Slider::~Props_Slider () inline
Definition at line 891 of file GUI_Constraint.h.
Member Function Documentation
setFieldSizeAbsolute()
void Core::GUI::Props_Slider::setFieldSizeAbsolute (int i) inline
Definition at line 784 of file GUI_Constraint.h.
References bExactSize, and iFieldSize.
Referenced by Core::GUI::Props_ColorSwatch::Props_ColorSwatch().
setFieldSizeRelative()
void Core::GUI::Props_Slider::setFieldSizeRelative (int i) inline
Definition at line 785 of file GUI_Constraint.h.
References bExactSize, and iFieldSize.
setMinMax() [1/2]
void Core::GUI::Props_Slider::setMinMax (float min, float max) inline
Definition at line 782 of file GUI_Constraint.h.
References maxValue, and minValue.
setMinMax() [2/2]
void Core::GUI::Props_Slider::setMinMax (Vector2f v) inline
Definition at line 781 of file GUI_Constraint.h.
References maxValue, and minValue.
Referenced by Core::GUI::Object::TextArea::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), and Core::GUI::Props_ColorSwatch::Props_ColorSwatch().
setOrientation()
void Core::GUI::Props_Slider::setOrientation (eSlider e) inline
Definition at line 780 of file GUI_Constraint.h.
References orientation.
setPrecision()
void Core::GUI::Props_Slider::setPrecision (int i) inline
Definition at line 783 of file GUI_Constraint.h.
Referenced by _Admin::init(), and Core::GUI::Props_ColorSwatch::Props_ColorSwatch().
setScrollSpeed()
void Core::GUI::Props_Slider::setScrollSpeed (float f) inline
Definition at line 786 of file GUI_Constraint.h.
References scrollSpeed.
Referenced by Core::GUI::Object::TextArea::init(), and Core::GUI::Object::TextEdit::init().
setStep() [1/2]
void Core::GUI::Props_Slider::setStep (float f) inline
Definition at line 788 of file GUI_Constraint.h.
References vStep.
Referenced by _Admin::init(), and Core::GUI::Props_ColorSwatch::Props_ColorSwatch().
setStep() [2/2]
void Core::GUI::Props_Slider::setStep (float min, float std, float max) inline
Definition at line 789 of file GUI_Constraint.h.
References vStep.
swapOrientation()
void Core::GUI::Props_Slider::swapOrientation () inline
Definition at line 790 of file GUI_Constraint.h.
References Core::Vector4i::bottom, Core::GUI::Props::_Size::constraint, control, Core::Vector4i::left, orientation, Core::Vector4i::right, Core::GUI::Props::setHeight(), Core::GUI::Props::setPadding(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, Core::GUI::SLIDER_HORIZONTAL, Core::GUI::SLIDER_VERTICAL, Core::Vector4i::top, Core::GUI::Props::vPadding, Core::Vector2f::x, Core::GUI::Props::_Size::_SizeConstraint::xType, Core::Vector2f::y, and Core::GUI::Props::_Size::_SizeConstraint::yType.
Referenced by _Admin::init().
Friends And Related Function Documentation
Object::Slider
template<class T > friend class Object::Slider friend
Definition at line 765 of file GUI_Constraint.h.
Member Data Documentation
bExactSize
bool Core::GUI::Props_Slider::bExactSize
Definition at line 774 of file GUI_Constraint.h.
Referenced by Props_Slider(), setFieldSizeAbsolute(), and setFieldSizeRelative().
control
Props_Window Core::GUI::Props_Slider::control
Definition at line 778 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), Props_Slider(), and swapOrientation().
iFieldSize
int Core::GUI::Props_Slider::iFieldSize
Definition at line 772 of file GUI_Constraint.h.
Referenced by Props_Slider(), setFieldSizeAbsolute(), and setFieldSizeRelative().
maxValue
float Core::GUI::Props_Slider::maxValue
Definition at line 769 of file GUI_Constraint.h.
Referenced by Props_Slider(), and setMinMax().
minValue
float Core::GUI::Props_Slider::minValue
Definition at line 769 of file GUI_Constraint.h.
Referenced by Props_Slider(), and setMinMax().
orientation
eSlider Core::GUI::Props_Slider::orientation
Definition at line 768 of file GUI_Constraint.h.
Referenced by Props_Slider(), setOrientation(), and swapOrientation().
precision
int Core::GUI::Props_Slider::precision
Definition at line 772 of file GUI_Constraint.h.
scrollSpeed
float Core::GUI::Props_Slider::scrollSpeed
Definition at line 769 of file GUI_Constraint.h.
Referenced by Props_Slider(), and setScrollSpeed().
vStep
Vector3f Core::GUI::Props_Slider::vStep
Definition at line 776 of file GUI_Constraint.h.
Referenced by Props_Slider(), and setStep().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Constraint.h