Project Parsec: RunMainMenu Class Reference
RunMainMenu Class Reference
#include <runMainMenu.h>
Public Member Functions
bool init ()
bool load ()
void reset ()
void set ()
void run ()
RunMainMenu ()
Public Attributes
int eS
Protected Member Functions
void toggle (bool &myBool)
void getInput ()
void processInput ()
void update ()
void draw ()
void choice (int iChoice)
Private Types
enum _CHOICES {
CHOICE_NONE, CHOICE_NEW, CHOICE_LOAD, CHOICE_OPTION,
CHOICE_QUIT
}
Private Attributes
Keyboard keyboard
Detailed Description
Definition at line 11 of file runMainMenu.h.
Member Enumeration Documentation
_CHOICES
enum RunMainMenu::_CHOICES private
Enumerator
CHOICE_NONE
CHOICE_NEW
CHOICE_LOAD
CHOICE_OPTION
CHOICE_QUIT
Definition at line 18 of file runMainMenu.h.
Constructor & Destructor Documentation
RunMainMenu()
RunMainMenu::RunMainMenu ()
Definition at line 40 of file runMainMenu.h.
References keyboard.
Member Function Documentation
choice()
void RunMainMenu::choice (int iChoice) protected
Definition at line 66 of file runMainMenu.h.
References CHOICE_LOAD, CHOICE_NEW, CHOICE_OPTION, CHOICE_QUIT, cout, and Core::gameVars.
Referenced by run().
draw()
void RunMainMenu::draw () protected
Definition at line 254 of file runMainMenu.h.
getInput()
void RunMainMenu::getInput () protected
Definition at line 170 of file runMainMenu.h.
References Core::GameVars::controls, Core::GameVars::debug, Core::gameVars, keyboard, processInput(), and Core::GameVars::screen.
Referenced by run().
init()
bool RunMainMenu::init ()
Definition at line 54 of file runMainMenu.h.
load()
bool RunMainMenu::load ()
Definition at line 58 of file runMainMenu.h.
processInput()
void RunMainMenu::processInput () protected
Definition at line 200 of file runMainMenu.h.
References CHOICE_QUIT, Core::GameVars::controls, Core::gameVars, and keyboard.
Referenced by getInput().
reset()
void RunMainMenu::reset ()
Definition at line 62 of file runMainMenu.h.
run()
void RunMainMenu::run ()
Definition at line 98 of file runMainMenu.h.
References choice(), CHOICE_LOAD, CHOICE_NEW, CHOICE_OPTION, CHOICE_QUIT, Core::GameVars::Screen::clear, Core::gameVars, getInput(), Core::GameVars::screen, update(), and Core::GameVars::Screen::vClearColorCurrent.
set()
void RunMainMenu::set ()
Definition at line 86 of file runMainMenu.h.
toggle()
void RunMainMenu::toggle (bool & myBool) protected
Definition at line 258 of file runMainMenu.h.
update()
void RunMainMenu::update () protected
Definition at line 167 of file runMainMenu.h.
Referenced by run().
Member Data Documentation
eS
int RunMainMenu::eS
Definition at line 29 of file runMainMenu.h.
keyboard
Keyboard RunMainMenu::keyboard private
Definition at line 13 of file runMainMenu.h.
Referenced by getInput(), processInput(), and RunMainMenu().
The documentation for this class was generated from the following file:
src/game/ref/runMainMenu.h