Project Parsec: Core::GUI::Object::Icon Class Reference
Core::GUI::Object::Icon Class Reference
#include <GUI_Icon.h>
Public Member Functions
Icon ()
Icon (std::string n, bool b, Props_Icon c)
Icon (std::string n, bool b, Props_Icon *c)
Icon (Props &p, std::string n, bool b, Props_Icon c)
Icon (Props &p, std::string n, bool b, Props_Icon *c)
Icon (std::string n, bool *b, Props_Icon c)
Icon (std::string n, bool *b, Props_Icon *c)
Icon (Props &p, std::string n, bool *b, Props_Icon c)
Icon (Props &p, std::string n, bool *b, Props_Icon *c)
virtual ~Icon ()
void init ()
void exec (iState eExternState=STATE_NONE)
void execToolTip ()
void updateNoFocus ()
Public Member Functions inherited from Core::GUI::Object::Base::Interactive< Props_Icon, bool >
Interactive ()
Interactive & operator= (const Interactive &src)
bool getPtrValue ()
void setPointer (bool *ptr)
bool * getPointer ()
void init (Props_Addon_ReturnState *ptr)
int getState (int n=0)
bool valueChanged ()
void updateValuePtr ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Icon >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Member Functions inherited from Core::GUI::Object::Base::Interactive_Base
Interactive_Base ()
~Interactive_Base ()
Public Member Functions inherited from Core::GUI::Object::Base::AudioFeedback
void initSound (int iChannel, int iSampleOn, int iSampleOff, int iLoopOn, int iLoopOff, bool bOverlapOn, bool bOverlapOff)
void Sound_PlayOn ()
void Sound_AbortState ()
void Sound_PlayOff ()
void Sound_PlayAuto (iState eState, bool bRepeat=false)
AudioFeedback ()
Public Attributes
ToolTip toolTip
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Icon >
int border
Props_Icon * con
Props * parent
Public Attributes inherited from Core::GUI::Object::Base::AudioFeedback
bool bRising
bool bOneShotOn
bool bOneShotOff
int iSampleOn
int iSampleOff
int iLoopOn
int iLoopOff
bool bOverlapOn
bool bOverlapOff
int iChannel
Private Member Functions
void updateObjectState (iState eExternState)
Private Attributes
Window background
Label * label
Additional Inherited Members
Static Public Attributes inherited from Core::GUI::Object::Base::Interactive_Base
static bool bFocusPresent = false
static std::string sActiveObject = ""
static std::string sGroupObject [32] = { "" }
Protected Attributes inherited from Core::GUI::Object::Base::Interactive< Props_Icon, bool >
bool * valuePtr
bool bLocalValue
bool bReturnInit
bool bValueChanged
Timer debounceTimer
Props_Addon_ReturnState * returnState
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Icon >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 43 of file GUI_Icon.h.
Constructor & Destructor Documentation
Icon() [1/9]
Core::GUI::Object::Icon::Icon ()
Definition at line 69 of file GUI_Icon.h.
Icon() [2/9]
Core::GUI::Object::Icon::Icon (std::string n, bool b, Props_Icon c)
Definition at line 73 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
Icon() [3/9]
Core::GUI::Object::Icon::Icon (std::string n, bool b, Props_Icon * c)
Definition at line 109 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
Icon() [4/9]
Core::GUI::Object::Icon::Icon (Props & p, std::string n, bool b, Props_Icon c)
Definition at line 91 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, p, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
Icon() [5/9]
Core::GUI::Object::Icon::Icon (Props & p, std::string n, bool b, Props_Icon * c)
Definition at line 126 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, p, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
Icon() [6/9]
Core::GUI::Object::Icon::Icon (std::string n, bool * b, Props_Icon c)
Definition at line 143 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
Icon() [7/9]
Core::GUI::Object::Icon::Icon (std::string n, bool * b, Props_Icon * c)
Definition at line 179 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
Icon() [8/9]
Core::GUI::Object::Icon::Icon (Props & p, std::string n, bool * b, Props_Icon c)
Definition at line 161 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, p, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
Icon() [9/9]
Core::GUI::Object::Icon::Icon (Props & p, std::string n, bool * b, Props_Icon * c)
Definition at line 196 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, p, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_NONE, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
~Icon()
Core::GUI::Object::Icon::~Icon () virtual
Definition at line 213 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bLocalCon, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::bLocalValue, Core::GUI::Object::Base::Generic< Props_Icon >::con, label, and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr.
Member Function Documentation
exec()
void Core::GUI::Object::Icon::exec (iState eExternState = STATE_NONE)
Definition at line 371 of file GUI_Icon.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::Props_Icon::active, background, Core::GUI::GUI_ColorB::base, Core::GUI::Props_Icon::base, Core::GUI::Object::Base::Interactive_Base::bFocusPresent, Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bInit, Core::GUI::Props::ToolTip::bShow, Core::GUI::Props_Addon_Background::bShowBackground, Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Props_Icon::color, Core::colors, Core::GUI::Object::Base::Generic< Props_Icon >::con, Core::GameVars::_Pallette::disabled, Core::_IconSys::draw(), Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::GUI_ColorH::highlight, Core::GUI::Props_Icon::highlight, Core::GUI::Props_Icon::Colors::icon, Core::GUI::Props_Icon::iconAtlas, Core::GUI::Props_Icon::iconID, Core::iconSys, Core::GameVars::pallette, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::_Colors::PopFront(), Core::_Colors::PushFront(), Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, toolTip, Core::GUI::Props::toolTip, Core::GUI::Object::ToolTip::updateObjectState(), updateObjectState(), and Core::GUI::Props::visibility.
execToolTip()
void Core::GUI::Object::Icon::execToolTip ()
Definition at line 406 of file GUI_Icon.h.
References Core::GUI::Object::ToolTip::exec(), and toolTip.
init()
void Core::GUI::Object::Icon::init ()
Definition at line 222 of file GUI_Icon.h.
References background, Core::GUI::Props_Addon_Background::background, Core::GUI::Object::Base::Generic< Props_Icon >::bHasParent, Core::GUI::Object::Base::Generic< Props_Icon >::bInit, Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Object::Base::Generic< Props_Icon >::con, Core::GUI::Props::_Size::constraint, Core::GUI::Props::exec(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::Window::init(), Core::GUI::Object::Base::AudioFeedback::initSound(), Core::GUI::Object::Base::Interactive< Props_Icon, bool >::Label, Core::GUI::Props_Addon_Label::label, Core::GUI::Object::Base::Generic< Props_Icon >::parent, Core::GUI::Props::setHeight(), Core::GUI::Props::setPadding(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, toolTip, Core::Vector2f::x, Core::GUI::Props::_Size::_SizeConstraint::xType, Core::Vector2f::y, and Core::GUI::Props::_Size::_SizeConstraint::yType.
updateNoFocus()
void Core::GUI::Object::Icon::updateNoFocus ()
Definition at line 415 of file GUI_Icon.h.
References Core::GUI::STATE_UPDATE, updateObjectState(), and Core::GUI::Object::Base::Interactive< Props_Icon, bool >::updateValuePtr().
updateObjectState()
void Core::GUI::Object::Icon::updateObjectState (iState eExternState) private
Definition at line 253 of file GUI_Icon.h.
References Core::GUI::Object::Base::Generic< Props_Icon >::bIsGrouped, Core::GUI::Object::Base::Generic< Props_Icon >::bRepeatStatus, Core::GUI::BUTTON_DEBOUNCE, Core::GUI::BUTTON_ONESHOT, Core::GUI::BUTTON_TOGGLE, Core::GUI::Props_Icon::buttonType, Core::_Mouse::checkInput(), Core::GUI::Object::Base::Generic< Props_Icon >::con, Core::GUI::Props_Icon::debounceTime, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::debounceTimer, Core::GUI::Object::Base::Generic< Props_Icon >::enabled(), Core::gameVars, Core::GameVars::Screen::half, Core::GUI::Props_Addon_Group::iGroup, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_LEFT, Core::_Mouse::MOUSE_LEFT_DOWN, Core::_Mouse::MOUSE_NONE, Core::GUI::Object::Base::Generic< Props_Icon >::mState, Core::GUI::Object::Base::Generic< Props_Icon >::name, Core::GUI::Props::pos, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::returnState, Core::GameVars::screen, Core::GUI::Object::Base::Interactive_Base::sGroupObject, Core::GUI::Props::size, Core::GUI::Object::Base::AudioFeedback::Sound_AbortState(), Core::GUI::Object::Base::AudioFeedback::Sound_PlayOff(), Core::GUI::Object::Base::AudioFeedback::Sound_PlayOn(), Core::Timer::split(), Core::Timer::start(), Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::GUI::Object::Base::Interactive< Props_Icon, bool >::updateValuePtr(), Core::GUI::Object::Base::Interactive< Props_Icon, bool >::valuePtr, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec(), and updateNoFocus().
Member Data Documentation
background
Window Core::GUI::Object::Icon::background private
Definition at line 64 of file GUI_Icon.h.
Referenced by exec(), and init().
label
Label* Core::GUI::Object::Icon::label private
Definition at line 65 of file GUI_Icon.h.
Referenced by ~Icon().
toolTip
ToolTip Core::GUI::Object::Icon::toolTip
Definition at line 57 of file GUI_Icon.h.
Referenced by exec(), execToolTip(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Icon.h