Project Parsec: Core::GUI::Object::Label Class Reference
Core::GUI::Object::Label Class Reference
#include <GUI_Label.h>
Public Member Functions
Label ()
Label (std::string n, Props_Label c)
Label (Props &p, std::string n, Props_Label c)
Label (std::string n, Props_Label *c)
Label (Props &p, std::string n, Props_Label *c)
virtual ~Label ()
void init ()
void exec (iState eExternState=STATE_NONE)
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Label >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Private Member Functions
void updateObjectState (iState eExternState)
Private Attributes
Window win
Additional Inherited Members
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Label >
int border
Props_Label * con
Props * parent
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Label >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 27 of file GUI_Label.h.
Constructor & Destructor Documentation
Label() [1/5]
Core::GUI::Object::Label::Label ()
Definition at line 45 of file GUI_Label.h.
Label() [2/5]
Core::GUI::Object::Label::Label (std::string n, Props_Label c)
Definition at line 47 of file GUI_Label.h.
References Core::GUI::Object::Base::Generic< Props_Label >::bHasParent, Core::GUI::Object::Base::Generic< Props_Label >::bInit, Core::GUI::Object::Base::Generic< Props_Label >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Label >::con, and Core::GUI::Object::Base::Generic< Props_Label >::parent.
Label() [3/5]
Core::GUI::Object::Label::Label (Props & p, std::string n, Props_Label c)
Definition at line 59 of file GUI_Label.h.
References Core::GUI::Object::Base::Generic< Props_Label >::bHasParent, Core::GUI::Object::Base::Generic< Props_Label >::bInit, Core::GUI::Object::Base::Generic< Props_Label >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Label >::con, p, and Core::GUI::Object::Base::Generic< Props_Label >::parent.
Label() [4/5]
Core::GUI::Object::Label::Label (std::string n, Props_Label * c)
Definition at line 71 of file GUI_Label.h.
References Core::GUI::Object::Base::Generic< Props_Label >::bHasParent, Core::GUI::Object::Base::Generic< Props_Label >::bInit, Core::GUI::Object::Base::Generic< Props_Label >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Label >::con, and Core::GUI::Object::Base::Generic< Props_Label >::parent.
Label() [5/5]
Core::GUI::Object::Label::Label (Props & p, std::string n, Props_Label * c)
Definition at line 82 of file GUI_Label.h.
References Core::GUI::Object::Base::Generic< Props_Label >::bHasParent, Core::GUI::Object::Base::Generic< Props_Label >::bInit, Core::GUI::Object::Base::Generic< Props_Label >::bLocalCon, Core::GUI::Object::Base::Generic< Props_Label >::con, p, and Core::GUI::Object::Base::Generic< Props_Label >::parent.
~Label()
Core::GUI::Object::Label::~Label () virtual
Definition at line 93 of file GUI_Label.h.
References Core::GUI::Object::Base::Generic< Props_Label >::bLocalCon, and Core::GUI::Object::Base::Generic< Props_Label >::con.
Member Function Documentation
exec()
void Core::GUI::Object::Label::exec (iState eExternState = STATE_NONE)
Definition at line 116 of file GUI_Label.h.
References Core::GUI::GUI_ColorB::base, Core::GUI::Object::Base::Generic< Props_Label >::bHasParent, Core::GUI::Object::Base::Generic< Props_Label >::bInit, Core::Vector4i::bottom, Core::GUI::Props_Label::bShowBackground, Core::GUI::Props_Label::color, Core::colors, Core::GUI::Object::Base::Generic< Props_Label >::con, Core::GUI::CONSTRAIN_CENTER, Core::GUI::Props::_Size::constraint, Core::GameVars::_Pallette::disabled, Core::_TextSys::draw(), Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Core::GameVars::font, Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::GUI_ColorH::highlight, Core::GUI::Props::_Size::isAutoSet(), Core::Vector4i::left, Core::GameVars::pallette, Core::GUI::Object::Base::Generic< Props_Label >::parent, Core::_Colors::PopFront(), Core::_Colors::PushFront(), Core::Vector4i::right, Core::GUI::Props::setHeight(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::Props_Label::Colors::text, Core::textSys, Core::Vector4i::top, updateObjectState(), Core::GUI::Props::visibility, Core::GUI::Props::vPadding, Core::GameVars::Font::vSize, win, Core::Vector2f::x, Core::GUI::Props::_Size::_SizeConstraint::xAuto, Core::GUI::Props::_Size::_SizeConstraint::xMax, Core::GUI::Props::_Size::_SizeConstraint::xMin, and Core::GUI::Props::_Size::_SizeConstraint::yAuto.
init()
void Core::GUI::Object::Label::init ()
Definition at line 97 of file GUI_Label.h.
References Core::GUI::Object::Base::Generic< Props_Label >::bHasParent, Core::GUI::Object::Base::Generic< Props_Label >::bInit, Core::GUI::Object::Base::Generic< Props_Label >::con, Core::GUI::Props::exec(), Core::GUI::Object::Window::init(), Core::GUI::Object::Base::Generic< Props_Label >::parent, and win.
updateObjectState()
void Core::GUI::Object::Label::updateObjectState (iState eExternState) private
Definition at line 108 of file GUI_Label.h.
References Core::GUI::Object::Base::Generic< Props_Label >::enabled(), Core::GUI::STATE_DISABLED, Core::GUI::STATE_NONE, and Core::GUI::STATE_UPDATE.
Referenced by exec().
Member Data Documentation
win
Window Core::GUI::Object::Label::win private
Definition at line 41 of file GUI_Label.h.
Referenced by exec(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Label.h