Project Parsec: Core::_Collision Class Reference
Core::_Collision Class Reference
#include <collision.h>
Public Member Functions
_Collision ()
~_Collision ()
bool Ray (Vector3f p, Vector3f d, _BOUNDING_VOLUME &s, bool bUpdateCData=false)
Public Attributes
bool bUpdateRequest [32]
Private Member Functions
Vector3f CalcIntersection (Vector3f p, Vector3f q, float t)
void SetCData (_BOUNDING_VOLUME &bv, Vector3f d, float t, bool result)
bool Ray_OBB (Vector3f p, Vector3f d, _BOUNDING_VOLUME &s, bool bUpdateCData)
bool Ray_AABB (Vector3f p, Vector3f d, _BOUNDING_VOLUME &a, bool bUpdateCData)
bool Ray_AABB (Vector3f p, Vector3f d, _BOUNDING_VOLUME &a, _BOUNDING_VOLUME::_BB &b, bool bUpdateCData)
bool Ray_Sphere (Vector3f p, Vector3f d, _BOUNDING_VOLUME &s)
bool Ray_SphereFast (Vector3f p, Vector3f d, _BOUNDING_VOLUME &s)
bool Ray_Cylinder (Vector3f vP, Vector3f vD, _BOUNDING_VOLUME &bv, bool bUpdateCData)
Detailed Description
Definition at line 14 of file collision.h.
Constructor & Destructor Documentation
_Collision()
Core::_Collision::_Collision ()
Definition at line 72 of file collision.h.
References bUpdateRequest.
~_Collision()
Core::_Collision::~_Collision ()
Definition at line 80 of file collision.h.
Member Function Documentation
CalcIntersection()
Vector3f Core::_Collision::CalcIntersection (Vector3f p, Vector3f q, float t) inline private
Definition at line 17 of file collision.h.
References t.
Referenced by Ray_AABB(), Ray_Cylinder(), Ray_OBB(), and Ray_Sphere().
Ray()
bool Core::_Collision::Ray (Vector3f p, Vector3f d, _BOUNDING_VOLUME & s, bool bUpdateCData = false)
Definition at line 83 of file collision.h.
References Core::_BOUNDING_VOLUME::BOUNDING_VOLUME_AABB, Core::_BOUNDING_VOLUME::BOUNDING_VOLUME_CYLINDER, Core::_BOUNDING_VOLUME::BOUNDING_VOLUME_OBB, Core::_BOUNDING_VOLUME::BOUNDING_VOLUME_SPHERE, Ray_AABB(), Ray_Cylinder(), Ray_OBB(), Ray_Sphere(), and Ray_SphereFast().
Referenced by Core::GameSys::_O3D::draw().
Ray_AABB() [1/2]
bool Core::_Collision::Ray_AABB (Vector3f p, Vector3f d, _BOUNDING_VOLUME & a, _BOUNDING_VOLUME::_BB & b, bool bUpdateCData) private
Definition at line 132 of file collision.h.
References CalcIntersection(), and SetCData().
Ray_AABB() [2/2]
bool Core::_Collision::Ray_AABB (Vector3f p, Vector3f d, _BOUNDING_VOLUME & a, bool bUpdateCData) private
Definition at line 126 of file collision.h.
References CalcIntersection(), and SetCData().
Referenced by Ray(), and Ray_OBB().
Ray_Cylinder()
bool Core::_Collision::Ray_Cylinder (Vector3f vP, Vector3f vD, _BOUNDING_VOLUME & bv, bool bUpdateCData) private
Definition at line 224 of file collision.h.
References CalcIntersection(), Core::_BOUNDING_VOLUME::Cylinder, Core::_gmath::Dot(), Core::gmath, p, Core::_BOUNDING_VOLUME::_BBC::p, Core::_BOUNDING_VOLUME::_BBC::q, Core::_BOUNDING_VOLUME::_BBS::radius, SetCData(), and Core::_BOUNDING_VOLUME::vTranslate.
Referenced by Ray().
Ray_OBB()
bool Core::_Collision::Ray_OBB (Vector3f p, Vector3f d, _BOUNDING_VOLUME & s, bool bUpdateCData) private
Definition at line 94 of file collision.h.
References CalcIntersection(), Ray_AABB(), SetCData(), Core::Degrees::toRadians(), Core::Vector3f::x, Core::Vector4f::x, Core::Vector3f::y, Core::Vector4f::y, Core::Vector3f::z, and Core::Vector4f::z.
Referenced by Ray().
Ray_Sphere()
bool Core::_Collision::Ray_Sphere (Vector3f p, Vector3f d, _BOUNDING_VOLUME & s) private
Definition at line 163 of file collision.h.
References CalcIntersection(), Core::_gmath::Dot(), Core::gmath, and SetCData().
Referenced by Ray().
Ray_SphereFast()
bool Core::_Collision::Ray_SphereFast (Vector3f p, Vector3f d, _BOUNDING_VOLUME & s) private
Definition at line 196 of file collision.h.
References Core::_gmath::Dot(), and Core::gmath.
Referenced by Ray().
SetCData()
void Core::_Collision::SetCData (_BOUNDING_VOLUME & bv, Vector3f d, float t, bool result) private
Definition at line 316 of file collision.h.
References Core::_BOUNDING_VOLUME::cdata, Core::_BOUNDING_VOLUME::_CollisionData::d, Core::_BOUNDING_VOLUME::_CollisionData::result, t, and Core::_BOUNDING_VOLUME::_CollisionData::t.
Referenced by Ray_AABB(), Ray_Cylinder(), Ray_OBB(), and Ray_Sphere().
Member Data Documentation
bUpdateRequest
bool Core::_Collision::bUpdateRequest[32]
Definition at line 54 of file collision.h.
Referenced by _Collision(), Core::GameSys::_O3D::draw(), and _Game::ProcessInput().
The documentation for this class was generated from the following file:
src/headers/core/collision.h