Project Parsec: Core::GUI::GUI_Container Class Reference
Core::GUI::GUI_Container Class Reference
#include <GUI_Container.h>
Classes
class ButtonInterface
class CheckBoxInterface
class ColorSwatchInterface
class ComboBoxInterface
class FieldInterface
class IconInterface
class LabelInterface
class ProgressBarInterface
class SliderInterface
class SpriteInterface
class TextAreaInterface
class TextEditInterface
class WindowInterface
Public Member Functions
GUI_Container (std::string name, Props_Window c)
GUI_Container (std::string name, Props_Window *c)
GUI_Container (Props &p, std::string name, Props_Window c)
GUI_Container (Props &p, std::string name, Props_Window *c)
~GUI_Container ()
void exec ()
bool isActive ()
void add (std::string containerName, Props_Window c, Props *p=nullptr)
void add (std::string containerName, Props_Window *c, Props *p=nullptr)
GUI_Container & operator[] (std::string containerName)
Props_Window & operator() (std::string containerName)
Public Member Functions inherited from Core::GUI::Object::Window
Window ()
Window (std::string n, Props_Window c)
Window (Props &p, std::string n, Props_Window c)
Window (std::string n, Props_Window *c)
Window (Props &p, std::string n, Props_Window *c)
~Window ()
void init ()
void update ()
void exec (iState eExternState=STATE_NONE)
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_Window >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Attributes
WindowInterface Window = WindowInterface(this)
LabelInterface Label = LabelInterface(this)
ButtonInterface Button = ButtonInterface(this)
SliderInterface Slider = SliderInterface(this)
FieldInterface Field = FieldInterface(this)
TextAreaInterface TextArea = TextAreaInterface(this)
TextEditInterface TextEdit = TextEditInterface(this)
ColorSwatchInterface ColorSwatch = ColorSwatchInterface(this)
CheckBoxInterface CheckBox = CheckBoxInterface(this)
IconInterface Icon = IconInterface(this)
SpriteInterface Sprite = SpriteInterface(this)
ProgressBarInterface ProgressBar = ProgressBarInterface(this)
ComboBoxInterface ComboBox = ComboBoxInterface(this)
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_Window >
int border
Props_Window * con
Props * parent
Private Member Functions
void execObjects ()
void execToolTips ()
void pushData (std::string name, GUI_Container *data)
Private Attributes
std::vector< GUI_Container * > containers
Map_si map
Additional Inherited Members
Protected Member Functions inherited from Core::GUI::Object::Window
void updateObjectState (iState eExternState)
Protected Attributes inherited from Core::GUI::Object::Window
VAO vao
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_Window >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
Definition at line 37 of file GUI_Container.h.
Constructor & Destructor Documentation
GUI_Container() [1/4]
Core::GUI::GUI_Container::GUI_Container (std::string name, Props_Window c) inline
Definition at line 39 of file GUI_Container.h.
References Core::GUI::Object::Window::init().
Referenced by add().
GUI_Container() [2/4]
Core::GUI::GUI_Container::GUI_Container (std::string name, Props_Window * c) inline
Definition at line 40 of file GUI_Container.h.
References Core::GUI::Object::Window::init().
GUI_Container() [3/4]
Core::GUI::GUI_Container::GUI_Container (Props & p, std::string name, Props_Window c) inline
Definition at line 41 of file GUI_Container.h.
References Core::GUI::Object::Window::init().
GUI_Container() [4/4]
Core::GUI::GUI_Container::GUI_Container (Props & p, std::string name, Props_Window * c) inline
Definition at line 42 of file GUI_Container.h.
References Core::GUI::Object::Window::init().
~GUI_Container()
Core::GUI::GUI_Container::~GUI_Container () inline
Definition at line 43 of file GUI_Container.h.
Member Function Documentation
add() [1/2]
void Core::GUI::GUI_Container::add (std::string containerName, Props_Window * c, Props * p = nullptr)
Definition at line 347 of file GUI_Container.h.
References Core::GUI::Object::Base::Generic< Props_Window >::con, GUI_Container(), Core::GUI::Object::Window::init(), and pushData().
add() [2/2]
void Core::GUI::GUI_Container::add (std::string containerName, Props_Window c, Props * p = nullptr)
Definition at line 339 of file GUI_Container.h.
References Core::GUI::Object::Base::Generic< Props_Window >::con, GUI_Container(), Core::GUI::Object::Window::init(), and pushData().
exec()
void Core::GUI::GUI_Container::exec ()
Definition at line 785 of file GUI_Container.h.
References Core::GUI::Props::ToolTip::bShowGlobal, execObjects(), and execToolTips().
execObjects()
void Core::GUI::GUI_Container::execObjects () private
Definition at line 790 of file GUI_Container.h.
References Core::GUI::Object::Base::Generic< Props_Window >::bInit, Core::Vector4i::bottom, Core::GUI::Props_Window::bScissor, Button, Core::GUI::GUI_Container::ButtonInterface::buttons, CheckBox, Core::GUI::GUI_Container::CheckBoxInterface::checkBoxes, ColorSwatch, Core::GUI::GUI_Container::ColorSwatchInterface::colorSwatches, ComboBox, Core::GUI::GUI_Container::ComboBoxInterface::comboBoxes, Core::GUI::Object::Base::Generic< Props_Window >::con, containers, Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), Field, Core::GUI::GUI_Container::FieldInterface::fields, Core::gameVars, GL_SCISSOR_TEST, Core::GameVars::Screen::half, Icon, Core::GUI::GUI_Container::IconInterface::icons, Label, Core::GUI::GUI_Container::LabelInterface::labels, Core::Vector4i::left, Core::GUI::Props::pos, ProgressBar, Core::GUI::GUI_Container::ProgressBarInterface::progressBars, Core::Vector4i::right, Core::GameVars::screen, Core::GUI::Props::size, TextArea, Core::GUI::GUI_Container::TextAreaInterface::textAreas, TextEdit, Core::GUI::GUI_Container::TextEditInterface::textEdits, Core::Vector4i::top, Core::GUI::Props::visibility, Core::GUI::Props::vPadding, Core::GUI::Object::Window::Window(), Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec().
execToolTips()
void Core::GUI::GUI_Container::execToolTips () private
Definition at line 848 of file GUI_Container.h.
References Button, Core::GUI::GUI_Container::ButtonInterface::buttons, CheckBox, Core::GUI::GUI_Container::CheckBoxInterface::checkBoxes, ColorSwatch, Core::GUI::GUI_Container::ColorSwatchInterface::colorSwatches, ComboBox, Core::GUI::GUI_Container::ComboBoxInterface::comboBoxes, containers, Field, Core::GUI::GUI_Container::FieldInterface::fields, GL_SCISSOR_TEST, Icon, Core::GUI::GUI_Container::IconInterface::icons, ProgressBar, Core::GUI::GUI_Container::ProgressBarInterface::progressBars, TextArea, and Core::GUI::GUI_Container::TextAreaInterface::textAreas.
Referenced by exec().
isActive()
bool Core::GUI::GUI_Container::isActive () inline
Definition at line 45 of file GUI_Container.h.
References Core::GUI::Object::Base::Interactive_Base::bFocusPresent.
operator()()
Props_Window& Core::GUI::GUI_Container::operator() (std::string containerName) inline
Definition at line 60 of file GUI_Container.h.
References Core::GUI::Object::Base::Generic< Props_Window >::con, containers, and map.
operator[]()
GUI_Container& Core::GUI::GUI_Container::operator[] (std::string containerName) inline
Definition at line 59 of file GUI_Container.h.
References containers, and map.
pushData()
void Core::GUI::GUI_Container::pushData (std::string name, GUI_Container * data) private
Definition at line 332 of file GUI_Container.h.
References containers, and map.
Referenced by add(), Core::GUI::GUI_Container::WindowInterface::add(), Core::GUI::GUI_Container::LabelInterface::add(), Core::GUI::GUI_Container::ButtonInterface::add(), Core::GUI::GUI_Container::SliderInterface::add(), Core::GUI::GUI_Container::FieldInterface::add(), Core::GUI::GUI_Container::TextAreaInterface::add(), Core::GUI::GUI_Container::TextEditInterface::add(), Core::GUI::GUI_Container::ColorSwatchInterface::add(), Core::GUI::GUI_Container::CheckBoxInterface::add(), Core::GUI::GUI_Container::IconInterface::add(), Core::GUI::GUI_Container::SpriteInterface::add(), Core::GUI::GUI_Container::ProgressBarInterface::add(), and Core::GUI::GUI_Container::ComboBoxInterface::add().
Member Data Documentation
Button
ButtonInterface Core::GUI::GUI_Container::Button = ButtonInterface(this)
Definition at line 119 of file GUI_Container.h.
Referenced by execObjects(), and execToolTips().
CheckBox
CheckBoxInterface Core::GUI::GUI_Container::CheckBox = CheckBoxInterface(this)
Definition at line 241 of file GUI_Container.h.
Referenced by execObjects(), and execToolTips().
ColorSwatch
ColorSwatchInterface Core::GUI::GUI_Container::ColorSwatch = ColorSwatchInterface(this)
Definition at line 218 of file GUI_Container.h.
Referenced by execObjects(), and execToolTips().
ComboBox
ComboBoxInterface Core::GUI::GUI_Container::ComboBox = ComboBoxInterface(this)
Definition at line 324 of file GUI_Container.h.
Referenced by execObjects(), and execToolTips().
containers
std::vector<GUI_Container*> Core::GUI::GUI_Container::containers private
Definition at line 51 of file GUI_Container.h.
Referenced by execObjects(), execToolTips(), operator()(), operator[](), and pushData().
Field
FieldInterface Core::GUI::GUI_Container::Field = FieldInterface(this)
Definition at line 161 of file GUI_Container.h.
Referenced by execObjects(), and execToolTips().
Icon
IconInterface Core::GUI::GUI_Container::Icon = IconInterface(this)
Definition at line 263 of file GUI_Container.h.
Referenced by execObjects(), and execToolTips().
Label
LabelInterface Core::GUI::GUI_Container::Label = LabelInterface(this)
Definition at line 98 of file GUI_Container.h.
Referenced by execObjects().
map
Map_si Core::GUI::GUI_Container::map private
Definition at line 52 of file GUI_Container.h.
Referenced by operator()(), operator[](), pushData(), Core::GUI::GUI_Container::LabelInterface::pushData(), Core::GUI::GUI_Container::ButtonInterface::pushData(), Core::GUI::GUI_Container::SliderInterface::pushData(), Core::GUI::GUI_Container::FieldInterface::pushData(), Core::GUI::GUI_Container::TextAreaInterface::pushData(), Core::GUI::GUI_Container::TextEditInterface::pushData(), Core::GUI::GUI_Container::ColorSwatchInterface::pushData(), Core::GUI::GUI_Container::CheckBoxInterface::pushData(), Core::GUI::GUI_Container::IconInterface::pushData(), Core::GUI::GUI_Container::SpriteInterface::pushData(), Core::GUI::GUI_Container::ProgressBarInterface::pushData(), and Core::GUI::GUI_Container::ComboBoxInterface::pushData().
ProgressBar
ProgressBarInterface Core::GUI::GUI_Container::ProgressBar = ProgressBarInterface(this)
Definition at line 305 of file GUI_Container.h.
Referenced by execObjects(), and execToolTips().
Slider
SliderInterface Core::GUI::GUI_Container::Slider = SliderInterface(this)
Definition at line 141 of file GUI_Container.h.
Sprite
SpriteInterface Core::GUI::GUI_Container::Sprite = SpriteInterface(this)
Definition at line 283 of file GUI_Container.h.
TextArea
TextAreaInterface Core::GUI::GUI_Container::TextArea = TextAreaInterface(this)
Definition at line 180 of file GUI_Container.h.
Referenced by execObjects(), and execToolTips().
TextEdit
TextEditInterface Core::GUI::GUI_Container::TextEdit = TextEditInterface(this)
Definition at line 199 of file GUI_Container.h.
Referenced by execObjects().
Window
WindowInterface Core::GUI::GUI_Container::Window = WindowInterface(this)
Definition at line 79 of file GUI_Container.h.
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Container.h