Project Parsec: Core::_Colors Class Reference
Core::_Colors Class Reference
#include <Colors.h>
Classes
struct Colors_Extended
Public Types
enum _ACTIVE_COLOR {
COLOR_FRONT, COLOR_FRONT_HIGHLIGHT, COLOR_BACK, COLOR_BACK_HIGHLIGHT,
COLOR_DETAIL1
}
enum _PALLETTE_COLOR {
PAL_TEXT, PAL_TEXT_HIGHLIGHT, PAL_ICON, PAL_ICON_HIGHLIGHT,
PAL_LAST
}
Public Member Functions
_Colors ()
virtual ~_Colors ()
int AddColor (std::string name, Color color)
int AddColor (std::string name, float r, float g, float b, float a)
int AddColor255 (std::string name, int r, int g, int b, int a)
Color & GetColor (std::string name)
Color & GetColor (int id)
Colors_Extended & operator() ()
Color & operator[] (std::string name)
Color GetPallette (_PALLETTE_COLOR e)
void SetFront (Color color)
void PushFront (Color color)
void PushFront (std::string name)
void PushFront ()
void PopFront ()
Color GetFront ()
void SetBack (Color color)
void PushBack (Color color)
void PushBack ()
void PopBack ()
Color GetBack ()
void SetFrontHighlight (Color color)
void PushFrontHighlight (Color color)
void PushFrontHighlight ()
void PopFrontHighlight ()
Color GetFrontHighlight ()
void SetBackHighlight (Color color)
void PushBackHighlight (Color color)
void PushBackHighlight ()
void PopBackHighlight ()
Color GetBackHighlight ()
void SetDetail1 (Color color)
void PushDetail1 (Color color)
void PushDetail1 ()
void PopDetail1 ()
Color GetDetail1 ()
void SetActive (_ACTIVE_COLOR e)
Color GetActive ()
Public Attributes
std::vector< Color * > colors
Map_si map
struct Core::_Colors::Colors_Extended Extended
Private Attributes
_ACTIVE_COLOR eActiveColor
Color * vActiveColor
Color * vFrontColor
Color * vBackColor
Color * vFrontHighlight
Color * vBackHighlight
Color * vDetail1Color
int uiFrontStack
int uiBackStack
int uiFrontHighlightStack
int uiBackHighlightStack
int uiDetail1Stack
Color * pallette
Static Private Attributes
static const int PALETTE_SIZE = 32
static const int STACK_SIZE = 16
Detailed Description
Definition at line 15 of file Colors.h.
Member Enumeration Documentation
_ACTIVE_COLOR
enum Core::_Colors::_ACTIVE_COLOR
Enumerator
COLOR_FRONT
COLOR_FRONT_HIGHLIGHT
COLOR_BACK
COLOR_BACK_HIGHLIGHT
COLOR_DETAIL1
Definition at line 17 of file Colors.h.
_PALLETTE_COLOR
enum Core::_Colors::_PALLETTE_COLOR
Enumerator
PAL_TEXT
PAL_TEXT_HIGHLIGHT
PAL_ICON
PAL_ICON_HIGHLIGHT
PAL_LAST
Definition at line 25 of file Colors.h.
Constructor & Destructor Documentation
_Colors()
Core::_Colors::_Colors ()
Definition at line 18 of file Colors.cpp.
References Core::_Colors::Colors_Extended::Absolute_Zero, Core::_Colors::Colors_Extended::Acid_green, AddColor(), AddColor255(), Core::_Colors::Colors_Extended::Aero, Core::_Colors::Colors_Extended::Aero_blue, Core::_Colors::Colors_Extended::African_violet, Core::_Colors::Colors_Extended::Air_superiority_blue, Core::_Colors::Colors_Extended::Alabaster, Core::_Colors::Colors_Extended::Alice_blue, Core::_Colors::Colors_Extended::Alloy_orange, Core::_Colors::Colors_Extended::Almond, Core::_Colors::Colors_Extended::Amaranth, Core::_Colors::Colors_Extended::Amaranth_MP, Core::_Colors::Colors_Extended::Amaranth_pink, Core::_Colors::Colors_Extended::Amaranth_purple, Core::_Colors::Colors_Extended::Amaranth_red, Core::_Colors::Colors_Extended::Amazon, Core::_Colors::Colors_Extended::Amber, Core::_Colors::Colors_Extended::Amber_SAE, Core::_Colors::Colors_Extended::Amethyst, Core::_Colors::Colors_Extended::Android_green, Core::_Colors::Colors_Extended::Antique_brass, Core::_Colors::Colors_Extended::Antique_bronze, Core::_Colors::Colors_Extended::Antique_fuchsia, Core::_Colors::Colors_Extended::Antique_ruby, Core::_Colors::Colors_Extended::Antique_white, Core::_Colors::Colors_Extended::Ao, Core::_Colors::Colors_Extended::Apple_green, Core::_Colors::Colors_Extended::Apricot, Core::_Colors::Colors_Extended::Aqua, Core::_Colors::Colors_Extended::Aquamarine, Core::_Colors::Colors_Extended::Arctic_lime, Core::_Colors::Colors_Extended::Army_green, Core::_Colors::Colors_Extended::Artichoke, Core::_Colors::Colors_Extended::Arylide_yellow, Core::_Colors::Colors_Extended::Ash_gray, Core::_Colors::Colors_Extended::Asparagus, Core::_Colors::Colors_Extended::Atomic_tangerine, Core::_Colors::Colors_Extended::Auburn, Core::_Colors::Colors_Extended::Aureolin, Core::_Colors::Colors_Extended::Avocado, Core::_Colors::Colors_Extended::Azure, Core::_Colors::Colors_Extended::Azure_X11, Core::_Colors::Colors_Extended::Baby_blue, Core::_Colors::Colors_Extended::Baby_blue_eyes, Core::_Colors::Colors_Extended::Baby_pink, Core::_Colors::Colors_Extended::Baby_powder, Core::_Colors::Colors_Extended::Baker_Miller_pink, Core::_Colors::Colors_Extended::Banana_Mania, Core::_Colors::Colors_Extended::Barbie_Pink, Core::_Colors::Colors_Extended::Barn_red, Core::_Colors::Colors_Extended::Battleship_grey, Core::_Colors::Colors_Extended::Bdazzled_blue, Core::_Colors::Colors_Extended::Beau_blue, Core::_Colors::Colors_Extended::Beaver, Core::_Colors::Colors_Extended::Beige, Core::_Colors::Colors_Extended::Big_dip_o_ruby, Core::_Colors::Colors_Extended::Bisque, Core::_Colors::Colors_Extended::Bistre, Core::_Colors::Colors_Extended::Bistre_brown, Core::_Colors::Colors_Extended::Bitter_lemon, Core::_Colors::Colors_Extended::Bitter_lime, Core::_Colors::Colors_Extended::Bittersweet, Core::_Colors::Colors_Extended::Bittersweet_shimmer, Core::_Colors::Colors_Extended::Black, Core::_Colors::Colors_Extended::Black_bean, Core::_Colors::Colors_Extended::Black_chocolate, Core::_Colors::Colors_Extended::Black_coffee, Core::_Colors::Colors_Extended::Black_coral, Core::_Colors::Colors_Extended::Black_olive, Core::_Colors::Colors_Extended::Black_Shadows, Core::_Colors::Colors_Extended::Blanched_almond, Core::_Colors::Colors_Extended::Blast_off_bronze, Core::_Colors::Colors_Extended::Blaze_orange, Core::_Colors::Colors_Extended::Bleu_de_France, Core::_Colors::Colors_Extended::Blizzard_blue, Core::_Colors::Colors_Extended::Blond, Core::_Colors::Colors_Extended::Blood_red, Core::_Colors::Colors_Extended::Blue, Core::_Colors::Colors_Extended::Blue_bell, Core::_Colors::Colors_Extended::Blue_Crayola, Core::_Colors::Colors_Extended::Blue_gray, Core::_Colors::Colors_Extended::Blue_green, Core::_Colors::Colors_Extended::Blue_green_CW, Core::_Colors::Colors_Extended::Blue_jeans, Core::_Colors::Colors_Extended::Blue_Munsell, Core::_Colors::Colors_Extended::Blue_NCS, Core::_Colors::Colors_Extended::Blue_Pantone, Core::_Colors::Colors_Extended::Blue_pigment, Core::_Colors::Colors_Extended::Blue_RYB, Core::_Colors::Colors_Extended::Blue_sapphire, Core::_Colors::Colors_Extended::Blue_violet, Core::_Colors::Colors_Extended::Blue_violet_Crayola, Core::_Colors::Colors_Extended::Blue_violet_CW, Core::_Colors::Colors_Extended::Blue_yonder, Core::_Colors::Colors_Extended::Bluetiful, Core::_Colors::Colors_Extended::Blush, Core::_Colors::Colors_Extended::Bole, Core::_Colors::Colors_Extended::Bone, Core::_Colors::Colors_Extended::Bottle_green, Core::_Colors::Colors_Extended::Brandy, Core::_Colors::Colors_Extended::Brick_red, Core::_Colors::Colors_Extended::Bright_green, Core::_Colors::Colors_Extended::Bright_lilac, Core::_Colors::Colors_Extended::Bright_maroon, Core::_Colors::Colors_Extended::Bright_navy_blue, Core::_Colors::Colors_Extended::Bright_yellow_Crayola, Core::_Colors::Colors_Extended::Brilliant_rose, Core::_Colors::Colors_Extended::Brink_pink, Core::_Colors::Colors_Extended::British_racing_green, Core::_Colors::Colors_Extended::Bronze, Core::_Colors::Colors_Extended::Brown, Core::_Colors::Colors_Extended::Brown_sugar, Core::_Colors::Colors_Extended::Brunswick_green, Core::_Colors::Colors_Extended::Bud_green, Core::_Colors::Colors_Extended::Buff, Core::_Colors::Colors_Extended::Burgundy, Core::_Colors::Colors_Extended::Burlywood, Core::_Colors::Colors_Extended::Burnished_brown, Core::_Colors::Colors_Extended::Burnt_orange, Core::_Colors::Colors_Extended::Burnt_sienna, Core::_Colors::Colors_Extended::Burnt_umber, Core::_Colors::Colors_Extended::Byzantine, Core::_Colors::Colors_Extended::Byzantium, Core::_Colors::Colors_Extended::Cadet, Core::_Colors::Colors_Extended::Cadet_blue, Core::_Colors::Colors_Extended::Cadet_blue_Crayola, Core::_Colors::Colors_Extended::Cadet_grey, Core::_Colors::Colors_Extended::Cadmium_green, Core::_Colors::Colors_Extended::Cadmium_orange, Core::_Colors::Colors_Extended::Cadmium_red, Core::_Colors::Colors_Extended::Cadmium_yellow, Core::_Colors::Colors_Extended::Cafe_au_lait, Core::_Colors::Colors_Extended::Cafe_noir, Core::_Colors::Colors_Extended::Cambridge_blue, Core::_Colors::Colors_Extended::Camel, Core::_Colors::Colors_Extended::Cameo_pink, Core::_Colors::Colors_Extended::Canary, Core::_Colors::Colors_Extended::Canary_yellow, Core::_Colors::Colors_Extended::Candy_apple_red, Core::_Colors::Colors_Extended::Candy_pink, Core::_Colors::Colors_Extended::Capri, Core::_Colors::Colors_Extended::Caput_mortuum, Core::_Colors::Colors_Extended::Cardinal, Core::_Colors::Colors_Extended::Caribbean_green, Core::_Colors::Colors_Extended::Carmine, Core::_Colors::Colors_Extended::Carmine_MP, Core::_Colors::Colors_Extended::Carnation_pink, Core::_Colors::Colors_Extended::Carnelian, Core::_Colors::Colors_Extended::Carolina_blue, Core::_Colors::Colors_Extended::Carrot_orange, Core::_Colors::Colors_Extended::Castleton_green, Core::_Colors::Colors_Extended::Catawba, Core::_Colors::Colors_Extended::Cedar_Chest, Core::_Colors::Colors_Extended::Celadon, Core::_Colors::Colors_Extended::Celadon_blue, Core::_Colors::Colors_Extended::Celadon_green, Core::_Colors::Colors_Extended::Celeste, Core::_Colors::Colors_Extended::Celtic_blue, Core::_Colors::Colors_Extended::Cerise, Core::_Colors::Colors_Extended::Cerulean, Core::_Colors::Colors_Extended::Cerulean_blue, Core::_Colors::Colors_Extended::Cerulean_Crayola, Core::_Colors::Colors_Extended::Cerulean_frost, Core::_Colors::Colors_Extended::CG_blue, Core::_Colors::Colors_Extended::CG_red, Core::_Colors::Colors_Extended::Champagne, Core::_Colors::Colors_Extended::Champagne_pink, Core::_Colors::Colors_Extended::Charcoal, Core::_Colors::Colors_Extended::Charleston_green, Core::_Colors::Colors_Extended::Charm_pink, Core::_Colors::Colors_Extended::Chartreuse_traditional, Core::_Colors::Colors_Extended::Chartreuse_web, Core::_Colors::Colors_Extended::Cherry_blossom_pink, Core::_Colors::Colors_Extended::Chestnut, Core::_Colors::Colors_Extended::China_pink, Core::_Colors::Colors_Extended::China_rose, Core::_Colors::Colors_Extended::Chinese_red, Core::_Colors::Colors_Extended::Chinese_violet, Core::_Colors::Colors_Extended::Chinese_yellow, Core::_Colors::Colors_Extended::Chocolate_traditional, Core::_Colors::Colors_Extended::Chocolate_web, Core::_Colors::Colors_Extended::Chrome_yellow, Core::_Colors::Colors_Extended::Cinereous, Core::_Colors::Colors_Extended::Cinnabar, Core::_Colors::Colors_Extended::Cinnamon_Satin, Core::_Colors::Colors_Extended::Citrine, Core::_Colors::Colors_Extended::Citron, Core::_Colors::Colors_Extended::Claret, Core::_Colors::Colors_Extended::Cobalt_blue, Core::_Colors::Colors_Extended::Cocoa_brown, Core::_Colors::Colors_Extended::Coffee, COLOR_FRONT, Core::_Colors::Colors_Extended::Columbia_Blue, Core::_Colors::Colors_Extended::Congo_pink, Core::_Colors::Colors_Extended::Cool_grey, Core::_Colors::Colors_Extended::Copper, Core::_Colors::Colors_Extended::Copper_Crayola, Core::_Colors::Colors_Extended::Copper_penny, Core::_Colors::Colors_Extended::Copper_red, Core::_Colors::Colors_Extended::Copper_rose, Core::_Colors::Colors_Extended::Coquelicot, Core::_Colors::Colors_Extended::Coral, Core::_Colors::Colors_Extended::Coral_pink, Core::_Colors::Colors_Extended::Cordovan, Core::_Colors::Colors_Extended::Corn, Core::_Colors::Colors_Extended::Cornflower_blue, Core::_Colors::Colors_Extended::Cornsilk, Core::_Colors::Colors_Extended::Cosmic_cobalt, Core::_Colors::Colors_Extended::Cosmic_latte, Core::_Colors::Colors_Extended::Cotton_candy, Core::_Colors::Colors_Extended::Coyote_brown, Core::_Colors::Colors_Extended::Cream, Core::_Colors::Colors_Extended::Crimson, Core::_Colors::Colors_Extended::Crimson_UA, Core::_Colors::Colors_Extended::Cultured, Core::_Colors::Colors_Extended::Cyan, Core::_Colors::Colors_Extended::Cyan_process, Core::_Colors::Colors_Extended::Cyber_grape, Core::_Colors::Colors_Extended::Cyber_yellow, Core::_Colors::Colors_Extended::Cyclamen, Core::_Colors::Colors_Extended::Dark_blue_gray, Core::_Colors::Colors_Extended::Dark_brown, Core::_Colors::Colors_Extended::Dark_byzantium, Core::_Colors::Colors_Extended::Dark_cornflower_blue, Core::_Colors::Colors_Extended::Dark_cyan, Core::_Colors::Colors_Extended::Dark_electric_blue, Core::_Colors::Colors_Extended::Dark_goldenrod, Core::_Colors::Colors_Extended::Dark_green, Core::_Colors::Colors_Extended::Dark_green_X11, Core::_Colors::Colors_Extended::Dark_jungle_green, Core::_Colors::Colors_Extended::Dark_khaki, Core::_Colors::Colors_Extended::Dark_lava, Core::_Colors::Colors_Extended::Dark_liver, Core::_Colors::Colors_Extended::Dark_liver_horses, Core::_Colors::Colors_Extended::Dark_magenta, Core::_Colors::Colors_Extended::Dark_moss_green, Core::_Colors::Colors_Extended::Dark_olive_green, Core::_Colors::Colors_Extended::Dark_orange, Core::_Colors::Colors_Extended::Dark_orchid, Core::_Colors::Colors_Extended::Dark_pastel_green, Core::_Colors::Colors_Extended::Dark_purple, Core::_Colors::Colors_Extended::Dark_red, Core::_Colors::Colors_Extended::Dark_salmon, Core::_Colors::Colors_Extended::Dark_sea_green, Core::_Colors::Colors_Extended::Dark_sienna, Core::_Colors::Colors_Extended::Dark_sky_blue, Core::_Colors::Colors_Extended::Dark_slate_blue, Core::_Colors::Colors_Extended::Dark_slate_gray, Core::_Colors::Colors_Extended::Dark_spring_green, Core::_Colors::Colors_Extended::Dark_turquoise, Core::_Colors::Colors_Extended::Dark_violet, Core::_Colors::Colors_Extended::Dartmouth_green, Core::_Colors::Colors_Extended::Davys_grey, Core::_Colors::Colors_Extended::Deep_cerise, Core::_Colors::Colors_Extended::Deep_champagne, Core::_Colors::Colors_Extended::Deep_chestnut, Core::_Colors::Colors_Extended::Deep_jungle_green, Core::_Colors::Colors_Extended::Deep_pink, Core::_Colors::Colors_Extended::Deep_saffron, Core::_Colors::Colors_Extended::Deep_sky_blue, Core::_Colors::Colors_Extended::Deep_Space_Sparkle, Core::_Colors::Colors_Extended::Deep_taupe, Core::_Colors::Colors_Extended::Denim, Core::_Colors::Colors_Extended::Denim_blue, Core::_Colors::Colors_Extended::Desert, Core::_Colors::Colors_Extended::Desert_sand, Core::_Colors::Colors_Extended::Dim_gray, Core::_Colors::Colors_Extended::Dodger_blue, Core::_Colors::Colors_Extended::Dogwood_rose, Core::_Colors::Colors_Extended::Drab, Core::_Colors::Colors_Extended::Duke_blue, Core::_Colors::Colors_Extended::Dutch_white, eActiveColor, Core::_Colors::Colors_Extended::Earth_yellow, Core::_Colors::Colors_Extended::Ebony, Core::_Colors::Colors_Extended::Ecru, Core::_Colors::Colors_Extended::Eerie_black, Core::_Colors::Colors_Extended::Eggplant, Core::_Colors::Colors_Extended::Eggshell, Core::_Colors::Colors_Extended::Egyptian_blue, Core::_Colors::Colors_Extended::Electric_blue, Core::_Colors::Colors_Extended::Electric_green, Core::_Colors::Colors_Extended::Electric_indigo, Core::_Colors::Colors_Extended::Electric_lime, Core::_Colors::Colors_Extended::Electric_purple, Core::_Colors::Colors_Extended::Electric_violet, Core::_Colors::Colors_Extended::Emerald, Core::_Colors::Colors_Extended::Eminence, Core::_Colors::Colors_Extended::English_green, Core::_Colors::Colors_Extended::English_lavender, Core::_Colors::Colors_Extended::English_red, Core::_Colors::Colors_Extended::English_vermillion, Core::_Colors::Colors_Extended::English_violet, Core::_Colors::Colors_Extended::Erin, Core::_Colors::Colors_Extended::Eton_blue, Extended, Core::_Colors::Colors_Extended::Fallow, Core::_Colors::Colors_Extended::Falu_red, Core::_Colors::Colors_Extended::Fandango, Core::_Colors::Colors_Extended::Fandango_pink, Core::_Colors::Colors_Extended::Fashion_fuchsia, Core::_Colors::Colors_Extended::Fawn, Core::_Colors::Colors_Extended::Feldgrau, Core::_Colors::Colors_Extended::Fern_green, Core::_Colors::Colors_Extended::Field_drab, Core::_Colors::Colors_Extended::Fiery_rose, Core::_Colors::Colors_Extended::Fire_engine_red, Core::_Colors::Colors_Extended::Fire_opal, Core::_Colors::Colors_Extended::Firebrick, Core::_Colors::Colors_Extended::Flame, Core::_Colors::Colors_Extended::Flax, Core::_Colors::Colors_Extended::Flirt, Core::_Colors::Colors_Extended::Floral_white, Core::_Colors::Colors_Extended::Fluorescent_blue, Core::_Colors::Colors_Extended::Forest_green_Crayola, Core::_Colors::Colors_Extended::Forest_green_traditional, Core::_Colors::Colors_Extended::Forest_green_web, Core::_Colors::Colors_Extended::French_beige, Core::_Colors::Colors_Extended::French_bistre, Core::_Colors::Colors_Extended::French_blue, Core::_Colors::Colors_Extended::French_fuchsia, Core::_Colors::Colors_Extended::French_lilac, Core::_Colors::Colors_Extended::French_lime, Core::_Colors::Colors_Extended::French_mauve, Core::_Colors::Colors_Extended::French_pink, Core::_Colors::Colors_Extended::French_raspberry, Core::_Colors::Colors_Extended::French_rose, Core::_Colors::Colors_Extended::French_sky_blue, Core::_Colors::Colors_Extended::French_violet, Core::_Colors::Colors_Extended::Frostbite, Core::_Colors::Colors_Extended::Fuchsia, Core::_Colors::Colors_Extended::Fuchsia_Crayola, Core::_Colors::Colors_Extended::Fuchsia_purple, Core::_Colors::Colors_Extended::Fuchsia_rose, Core::_Colors::Colors_Extended::Fulvous, Core::_Colors::Colors_Extended::Fuzzy_Wuzzy, Core::_Colors::Colors_Extended::Gainsboro, Core::_Colors::Colors_Extended::Gamboge, Core::_Colors::Colors_Extended::Generic_viridian, GetColor(), Core::_Colors::Colors_Extended::Ghost_white, Core::_Colors::Colors_Extended::Glaucous, Core::_Colors::Colors_Extended::Glossy_grape, Core::_Colors::Colors_Extended::GO_green, Core::_Colors::Colors_Extended::Gold, Core::_Colors::Colors_Extended::Gold_Crayola, Core::_Colors::Colors_Extended::Gold_Fusion, Core::_Colors::Colors_Extended::Gold_metallic, Core::_Colors::Colors_Extended::Gold_web, Core::_Colors::Colors_Extended::Golden_brown, Core::_Colors::Colors_Extended::Golden_poppy, Core::_Colors::Colors_Extended::Golden_yellow, Core::_Colors::Colors_Extended::Goldenrod, Core::_Colors::Colors_Extended::Granite_gray, Core::_Colors::Colors_Extended::Granny_Smith_apple, Core::_Colors::Colors_Extended::Gray10, Core::_Colors::Colors_Extended::Gray20, Core::_Colors::Colors_Extended::Gray30, Core::_Colors::Colors_Extended::Gray40, Core::_Colors::Colors_Extended::Gray50, Core::_Colors::Colors_Extended::Gray60, Core::_Colors::Colors_Extended::Gray70, Core::_Colors::Colors_Extended::Gray80, Core::_Colors::Colors_Extended::Gray90, Core::_Colors::Colors_Extended::Gray_web, Core::_Colors::Colors_Extended::Gray_X11, Core::_Colors::Colors_Extended::Green, Core::_Colors::Colors_Extended::Green_blue, Core::_Colors::Colors_Extended::Green_blue_Crayola, Core::_Colors::Colors_Extended::Green_Crayola, Core::_Colors::Colors_Extended::Green_cyan, Core::_Colors::Colors_Extended::Green_Lizard, Core::_Colors::Colors_Extended::Green_Munsell, Core::_Colors::Colors_Extended::Green_NCS, Core::_Colors::Colors_Extended::Green_Pantone, Core::_Colors::Colors_Extended::Green_pigment, Core::_Colors::Colors_Extended::Green_RYB, Core::_Colors::Colors_Extended::Green_Sheen, Core::_Colors::Colors_Extended::Green_web, Core::_Colors::Colors_Extended::Green_yellow, Core::_Colors::Colors_Extended::Green_yellow_Crayola, Core::_Colors::Colors_Extended::Grullo, Core::_Colors::Colors_Extended::Gunmetal, Core::_Colors::Colors_Extended::Han_blue, Core::_Colors::Colors_Extended::Han_purple, Core::_Colors::Colors_Extended::Hansa_yellow, Core::_Colors::Colors_Extended::Harlequin, Core::_Colors::Colors_Extended::Harvest_gold, Core::_Colors::Colors_Extended::Heat_Wave, Core::_Colors::Colors_Extended::Heliotrope, Core::_Colors::Colors_Extended::Heliotrope_gray, Core::_Colors::Colors_Extended::Hollywood_cerise, Core::_Colors::Colors_Extended::Honeydew, Core::_Colors::Colors_Extended::Honolulu_blue, Core::_Colors::Colors_Extended::Hookers_green, Core::_Colors::Colors_Extended::Hot_magenta, Core::_Colors::Colors_Extended::Hot_pink, Core::_Colors::Colors_Extended::Hunter_green, Core::_Colors::Colors_Extended::Iceberg, Core::_Colors::Colors_Extended::Icterine, Core::_Colors::Colors_Extended::Illuminating_emerald, Core::_Colors::Colors_Extended::Imperial_red, Core::_Colors::Colors_Extended::Inchworm, Core::_Colors::Colors_Extended::Independence, Core::_Colors::Colors_Extended::India_green, Core::_Colors::Colors_Extended::Indian_red, Core::_Colors::Colors_Extended::Indian_yellow, Core::_Colors::Colors_Extended::Indigo, Core::_Colors::Colors_Extended::Indigo_dye, Core::_Colors::Colors_Extended::International_orange_aerospace, Core::_Colors::Colors_Extended::International_orange_engineering, Core::_Colors::Colors_Extended::International_orange_GGB, Core::_Colors::Colors_Extended::Iris, Core::_Colors::Colors_Extended::Irresistible, Core::_Colors::Colors_Extended::Isabelline, Core::_Colors::Colors_Extended::Italian_sky_blue, Core::_Colors::Colors_Extended::Ivory, Core::_Colors::Colors_Extended::Jade, Core::_Colors::Colors_Extended::Japanese_carmine, Core::_Colors::Colors_Extended::Japanese_violet, Core::_Colors::Colors_Extended::Jasmine, Core::_Colors::Colors_Extended::Jazzberry_jam, Core::_Colors::Colors_Extended::Jet, Core::_Colors::Colors_Extended::Jonquil, Core::_Colors::Colors_Extended::June_bud, Core::_Colors::Colors_Extended::Jungle_green, Core::_Colors::Colors_Extended::Kelly_green, Core::_Colors::Colors_Extended::Keppel, Core::_Colors::Colors_Extended::Key_lime, Core::_Colors::Colors_Extended::Khaki_web, Core::_Colors::Colors_Extended::Khaki_X11, Core::_Colors::Colors_Extended::Kobe, Core::_Colors::Colors_Extended::Kobi, Core::_Colors::Colors_Extended::Kobicha, Core::_Colors::Colors_Extended::Kombu_green, Core::_Colors::Colors_Extended::KSU_purple, Core::_Colors::Colors_Extended::Languid_lavender, Core::_Colors::Colors_Extended::Lapis_lazuli, Core::_Colors::Colors_Extended::Laser_lemon, Core::_Colors::Colors_Extended::Laurel_green, Core::_Colors::Colors_Extended::Lava, Core::_Colors::Colors_Extended::Lavender_blue, Core::_Colors::Colors_Extended::Lavender_blush, Core::_Colors::Colors_Extended::Lavender_floral, Core::_Colors::Colors_Extended::Lavender_gray, Core::_Colors::Colors_Extended::Lavender_web, Core::_Colors::Colors_Extended::Lawn_green, Core::_Colors::Colors_Extended::Lemon, Core::_Colors::Colors_Extended::Lemon_chiffon, Core::_Colors::Colors_Extended::Lemon_curry, Core::_Colors::Colors_Extended::Lemon_glacier, Core::_Colors::Colors_Extended::Lemon_meringue, Core::_Colors::Colors_Extended::Lemon_yellow, Core::_Colors::Colors_Extended::Lemon_yellow_Crayola, Core::_Colors::Colors_Extended::Liberty, Core::_Colors::Colors_Extended::Light_blue, Core::_Colors::Colors_Extended::Light_coral, Core::_Colors::Colors_Extended::Light_cornflower_blue, Core::_Colors::Colors_Extended::Light_cyan, Core::_Colors::Colors_Extended::Light_French_beige, Core::_Colors::Colors_Extended::Light_goldenrod_yellow, Core::_Colors::Colors_Extended::Light_gray, Core::_Colors::Colors_Extended::Light_green, Core::_Colors::Colors_Extended::Light_orange, Core::_Colors::Colors_Extended::Light_periwinkle, Core::_Colors::Colors_Extended::Light_pink, Core::_Colors::Colors_Extended::Light_salmon, Core::_Colors::Colors_Extended::Light_sea_green, Core::_Colors::Colors_Extended::Light_sky_blue, Core::_Colors::Colors_Extended::Light_slate_gray, Core::_Colors::Colors_Extended::Light_steel_blue, Core::_Colors::Colors_Extended::Light_yellow, Core::_Colors::Colors_Extended::Lilac, Core::_Colors::Colors_Extended::Lilac_Luster, Core::_Colors::Colors_Extended::Lime_CW, Core::_Colors::Colors_Extended::Lime_green, Core::_Colors::Colors_Extended::Lime_web, Core::_Colors::Colors_Extended::Lincoln_green, Core::_Colors::Colors_Extended::Linen, Core::_Colors::Colors_Extended::Lion, Core::_Colors::Colors_Extended::Liseran_purple, Core::_Colors::Colors_Extended::Little_boy_blue, Core::_Colors::Colors_Extended::Liver, Core::_Colors::Colors_Extended::Liver_chestnut, Core::_Colors::Colors_Extended::Liver_dogs, Core::_Colors::Colors_Extended::Liver_organ, Core::_Colors::Colors_Extended::Livid, Core::_Colors::Colors_Extended::Macaroni_and_Cheese, Core::_Colors::Colors_Extended::Madder_Lake, Core::_Colors::Colors_Extended::Magenta, Core::_Colors::Colors_Extended::Magenta_Crayola, Core::_Colors::Colors_Extended::Magenta_dye, Core::_Colors::Colors_Extended::Magenta_haze, Core::_Colors::Colors_Extended::Magenta_Pantone, Core::_Colors::Colors_Extended::Magenta_process, Core::_Colors::Colors_Extended::Magic_mint, Core::_Colors::Colors_Extended::Magnolia, Core::_Colors::Colors_Extended::Mahogany, Core::_Colors::Colors_Extended::Maize, Core::_Colors::Colors_Extended::Maize_Crayola, Core::_Colors::Colors_Extended::Majorelle_blue, Core::_Colors::Colors_Extended::Malachite, Core::_Colors::Colors_Extended::Manatee, Core::_Colors::Colors_Extended::Mandarin, Core::_Colors::Colors_Extended::Mango, Core::_Colors::Colors_Extended::Mango_Tango, Core::_Colors::Colors_Extended::Mantis, Core::_Colors::Colors_Extended::Mardi_Gras, Core::_Colors::Colors_Extended::Marigold, Core::_Colors::Colors_Extended::Maroon_Crayola, Core::_Colors::Colors_Extended::Maroon_web, Core::_Colors::Colors_Extended::Maroon_X11, Core::_Colors::Colors_Extended::Mauve, Core::_Colors::Colors_Extended::Mauve_taupe, Core::_Colors::Colors_Extended::Mauvelous, Core::_Colors::Colors_Extended::Maximum_blue, Core::_Colors::Colors_Extended::Maximum_blue_green, Core::_Colors::Colors_Extended::Maximum_blue_purple, Core::_Colors::Colors_Extended::Maximum_green, Core::_Colors::Colors_Extended::Maximum_green_yellow, Core::_Colors::Colors_Extended::Maximum_purple, Core::_Colors::Colors_Extended::Maximum_red, Core::_Colors::Colors_Extended::Maximum_red_purple, Core::_Colors::Colors_Extended::Maximum_yellow, Core::_Colors::Colors_Extended::Maximum_yellow_red, Core::_Colors::Colors_Extended::May_green, Core::_Colors::Colors_Extended::Maya_blue, Core::_Colors::Colors_Extended::Medium_aquamarine, Core::_Colors::Colors_Extended::Medium_blue, Core::_Colors::Colors_Extended::Medium_candy_apple_red, Core::_Colors::Colors_Extended::Medium_carmine, Core::_Colors::Colors_Extended::Medium_champagne, Core::_Colors::Colors_Extended::Medium_orchid, Core::_Colors::Colors_Extended::Medium_purple, Core::_Colors::Colors_Extended::Medium_sea_green, Core::_Colors::Colors_Extended::Medium_slate_blue, Core::_Colors::Colors_Extended::Medium_spring_green, Core::_Colors::Colors_Extended::Medium_turquoise, Core::_Colors::Colors_Extended::Medium_vermilion, Core::_Colors::Colors_Extended::Medium_violet_red, Core::_Colors::Colors_Extended::Mellow_apricot, Core::_Colors::Colors_Extended::Mellow_yellow, Core::_Colors::Colors_Extended::Melon, Core::_Colors::Colors_Extended::Metallic_gold, Core::_Colors::Colors_Extended::Metallic_Seaweed, Core::_Colors::Colors_Extended::Metallic_Sunburst, Core::_Colors::Colors_Extended::Mexican_pink, Core::_Colors::Colors_Extended::Middle_blue, Core::_Colors::Colors_Extended::Middle_blue_green, Core::_Colors::Colors_Extended::Middle_blue_purple, Core::_Colors::Colors_Extended::Middle_green, Core::_Colors::Colors_Extended::Middle_green_yellow, Core::_Colors::Colors_Extended::Middle_grey, Core::_Colors::Colors_Extended::Middle_purple, Core::_Colors::Colors_Extended::Middle_red, Core::_Colors::Colors_Extended::Middle_red_purple, Core::_Colors::Colors_Extended::Middle_yellow, Core::_Colors::Colors_Extended::Middle_yellow_red, Core::_Colors::Colors_Extended::Midnight, Core::_Colors::Colors_Extended::Midnight_blue, Core::_Colors::Colors_Extended::Midnight_green, Core::_Colors::Colors_Extended::Mikado_yellow, Core::_Colors::Colors_Extended::Mimi_pink, Core::_Colors::Colors_Extended::Mindaro, Core::_Colors::Colors_Extended::Ming, Core::_Colors::Colors_Extended::Minion_yellow, Core::_Colors::Colors_Extended::Mint, Core::_Colors::Colors_Extended::Mint_cream, Core::_Colors::Colors_Extended::Mint_green, Core::_Colors::Colors_Extended::Misty_moss, Core::_Colors::Colors_Extended::Misty_rose, Core::_Colors::Colors_Extended::Mode_beige, Core::_Colors::Colors_Extended::Morning_blue, Core::_Colors::Colors_Extended::Moss_green, Core::_Colors::Colors_Extended::Mountain_Meadow, Core::_Colors::Colors_Extended::Mountbatten_pink, Core::_Colors::Colors_Extended::MSU_green, Core::_Colors::Colors_Extended::Mulberry, Core::_Colors::Colors_Extended::Mulberry_Crayola, Core::_Colors::Colors_Extended::Mustard, Core::_Colors::Colors_Extended::Myrtle_green, Core::_Colors::Colors_Extended::Mystic, Core::_Colors::Colors_Extended::Mystic_maroon, Core::_Colors::Colors_Extended::Nadeshiko_pink, Core::_Colors::Colors_Extended::Naples_yellow, Core::_Colors::Colors_Extended::Navajo_white, Core::_Colors::Colors_Extended::Navy_blue, Core::_Colors::Colors_Extended::Navy_blue_Crayola, Core::_Colors::Colors_Extended::Neon_blue, Core::_Colors::Colors_Extended::Neon_Carrot, Core::_Colors::Colors_Extended::Neon_fuchsia, Core::_Colors::Colors_Extended::Neon_green, Core::_Colors::Colors_Extended::New_York_pink, Core::_Colors::Colors_Extended::Nickel, Core::_Colors::Colors_Extended::Non_photo_blue, Core::_Colors::Colors_Extended::Nyanza, Core::_Colors::Colors_Extended::Ocean_Blue, Core::_Colors::Colors_Extended::Ocean_green, Core::_Colors::Colors_Extended::Ochre, Core::_Colors::Colors_Extended::Old_burgundy, Core::_Colors::Colors_Extended::Old_gold, Core::_Colors::Colors_Extended::Old_lace, Core::_Colors::Colors_Extended::Old_lavender, Core::_Colors::Colors_Extended::Old_mauve, Core::_Colors::Colors_Extended::Old_rose, Core::_Colors::Colors_Extended::Old_silver, Core::_Colors::Colors_Extended::Olive, Core::_Colors::Colors_Extended::Olive_Drab_3, Core::_Colors::Colors_Extended::Olive_Drab_7, Core::_Colors::Colors_Extended::Olive_green, Core::_Colors::Colors_Extended::Olivine, Core::_Colors::Colors_Extended::Onyx, Core::_Colors::Colors_Extended::Opal, Core::_Colors::Colors_Extended::Opera_mauve, Core::_Colors::Colors_Extended::Orange, Core::_Colors::Colors_Extended::Orange_Crayola, Core::_Colors::Colors_Extended::Orange_Pantone, Core::_Colors::Colors_Extended::Orange_peel, Core::_Colors::Colors_Extended::Orange_red, Core::_Colors::Colors_Extended::Orange_red_Crayola, Core::_Colors::Colors_Extended::Orange_soda, Core::_Colors::Colors_Extended::Orange_web, Core::_Colors::Colors_Extended::Orange_yellow, Core::_Colors::Colors_Extended::Orange_yellow_Crayola, Core::_Colors::Colors_Extended::Orchid, Core::_Colors::Colors_Extended::Orchid_Crayola, Core::_Colors::Colors_Extended::Orchid_pink, Core::_Colors::Colors_Extended::OU_Crimson_red, Core::_Colors::Colors_Extended::Outer_space_Crayola, Core::_Colors::Colors_Extended::Outrageous_Orange, Core::_Colors::Colors_Extended::Oxblood, Core::_Colors::Colors_Extended::Oxford_blue, Core::_Colors::Colors_Extended::Pacific_blue, Core::_Colors::Colors_Extended::Pakistan_green, PAL_ICON, PAL_ICON_HIGHLIGHT, PAL_TEXT, PAL_TEXT_HIGHLIGHT, Core::_Colors::Colors_Extended::Palatinate_purple, Core::_Colors::Colors_Extended::Pale_aqua, Core::_Colors::Colors_Extended::Pale_cerulean, Core::_Colors::Colors_Extended::Pale_pink, Core::_Colors::Colors_Extended::Pale_purple_Pantone, Core::_Colors::Colors_Extended::Pale_silver, Core::_Colors::Colors_Extended::Pale_spring_bud, PALETTE_SIZE, pallette, Core::_Colors::Colors_Extended::Pansy_purple, Core::_Colors::Colors_Extended::Paolo_Veronese_green, Core::_Colors::Colors_Extended::Papaya_whip, Core::_Colors::Colors_Extended::Paradise_pink, Core::_Colors::Colors_Extended::Paris_Green, Core::_Colors::Colors_Extended::Pastel_pink, Core::_Colors::Colors_Extended::Patriarch, Core::_Colors::Colors_Extended::Paynes_grey, Core::_Colors::Colors_Extended::Peach, Core::_Colors::Colors_Extended::Peach_Crayola, Core::_Colors::Colors_Extended::Peach_puff, Core::_Colors::Colors_Extended::Pear, Core::_Colors::Colors_Extended::Pearly_purple, Core::_Colors::Colors_Extended::Periwinkle, Core::_Colors::Colors_Extended::Periwinkle_Crayola, Core::_Colors::Colors_Extended::Permanent_Geranium_Lake, Core::_Colors::Colors_Extended::Persian_blue, Core::_Colors::Colors_Extended::Persian_green, Core::_Colors::Colors_Extended::Persian_indigo, Core::_Colors::Colors_Extended::Persian_orange, Core::_Colors::Colors_Extended::Persian_pink, Core::_Colors::Colors_Extended::Persian_plum, Core::_Colors::Colors_Extended::Persian_red, Core::_Colors::Colors_Extended::Persian_rose, Core::_Colors::Colors_Extended::Persimmon, Core::_Colors::Colors_Extended::Pewter_Blue, Core::_Colors::Colors_Extended::Phlox, Core::_Colors::Colors_Extended::Phthalo_blue, Core::_Colors::Colors_Extended::Phthalo_green, Core::_Colors::Colors_Extended::Picotee_blue, Core::_Colors::Colors_Extended::Pictorial_carmine, Core::_Colors::Colors_Extended::Piggy_pink, Core::_Colors::Colors_Extended::Pine_green, Core::_Colors::Colors_Extended::Pine_tree, Core::_Colors::Colors_Extended::Pink, Core::_Colors::Colors_Extended::Pink_flamingo, Core::_Colors::Colors_Extended::Pink_lace, Core::_Colors::Colors_Extended::Pink_lavender, Core::_Colors::Colors_Extended::Pink_Pantone, Core::_Colors::Colors_Extended::Pink_Sherbet, Core::_Colors::Colors_Extended::Pistachio, Core::_Colors::Colors_Extended::Platinum, Core::_Colors::Colors_Extended::Plum, Core::_Colors::Colors_Extended::Plum_web, Core::_Colors::Colors_Extended::Plump_Purple, Core::_Colors::Colors_Extended::Polished_Pine, Core::_Colors::Colors_Extended::Pomp_and_Power, Core::_Colors::Colors_Extended::Popstar, Core::_Colors::Colors_Extended::Portland_Orange, Core::_Colors::Colors_Extended::Powder_blue, Core::_Colors::Colors_Extended::Princeton_orange, Core::_Colors::Colors_Extended::Prune, Core::_Colors::Colors_Extended::Prussian_blue, Core::_Colors::Colors_Extended::Psychedelic_purple, Core::_Colors::Colors_Extended::Puce, Core::_Colors::Colors_Extended::Pullman_Brown, Core::_Colors::Colors_Extended::Pumpkin, Core::_Colors::Colors_Extended::Purple, Core::_Colors::Colors_Extended::Purple_mountain_majesty, Core::_Colors::Colors_Extended::Purple_Munsell, Core::_Colors::Colors_Extended::Purple_navy, Core::_Colors::Colors_Extended::Purple_pizzazz, Core::_Colors::Colors_Extended::Purple_Plum, Core::_Colors::Colors_Extended::Purple_web, Core::_Colors::Colors_Extended::Purple_X11, Core::_Colors::Colors_Extended::Purpureus, Core::_Colors::Colors_Extended::Queen_blue, Core::_Colors::Colors_Extended::Queen_pink, Core::_Colors::Colors_Extended::Quick_Silver, Core::_Colors::Colors_Extended::Quinacridone_magenta, Core::_Colors::Colors_Extended::Radical_Red, Core::_Colors::Colors_Extended::Raisin_black, Core::_Colors::Colors_Extended::Rajah, Core::_Colors::Colors_Extended::Raspberry, Core::_Colors::Colors_Extended::Raspberry_glace, Core::_Colors::Colors_Extended::Raspberry_rose, Core::_Colors::Colors_Extended::Raw_sienna, Core::_Colors::Colors_Extended::Raw_umber, Core::_Colors::Colors_Extended::Razzle_dazzle_rose, Core::_Colors::Colors_Extended::Razzmatazz, Core::_Colors::Colors_Extended::Razzmic_Berry, Core::_Colors::Colors_Extended::Rebecca_Purple, Core::_Colors::Colors_Extended::Red, Core::_Colors::Colors_Extended::Red_Crayola, Core::_Colors::Colors_Extended::Red_Munsell, Core::_Colors::Colors_Extended::Red_NCS, Core::_Colors::Colors_Extended::Red_orange, Core::_Colors::Colors_Extended::Red_orange_Crayola, Core::_Colors::Colors_Extended::Red_orange_CW, Core::_Colors::Colors_Extended::Red_Pantone, Core::_Colors::Colors_Extended::Red_pigment, Core::_Colors::Colors_Extended::Red_purple, Core::_Colors::Colors_Extended::Red_RYB, Core::_Colors::Colors_Extended::Red_Salsa, Core::_Colors::Colors_Extended::Red_violet, Core::_Colors::Colors_Extended::Red_violet_Crayola, Core::_Colors::Colors_Extended::Red_violet_CW, Core::_Colors::Colors_Extended::Redwood, Core::_Colors::Colors_Extended::Resolution_blue, Core::_Colors::Colors_Extended::Rhythm, Core::_Colors::Colors_Extended::Rich_black, Core::_Colors::Colors_Extended::Rich_black_FOGRA29, Core::_Colors::Colors_Extended::Rich_black_FOGRA39, Core::_Colors::Colors_Extended::Rifle_green, Core::_Colors::Colors_Extended::Robin_egg_blue, Core::_Colors::Colors_Extended::Rocket_metallic, Core::_Colors::Colors_Extended::Roman_silver, Core::_Colors::Colors_Extended::Rose, Core::_Colors::Colors_Extended::Rose_bonbon, Core::_Colors::Colors_Extended::Rose_Dust, Core::_Colors::Colors_Extended::Rose_ebony, Core::_Colors::Colors_Extended::Rose_madder, Core::_Colors::Colors_Extended::Rose_pink, Core::_Colors::Colors_Extended::Rose_quartz, Core::_Colors::Colors_Extended::Rose_red, Core::_Colors::Colors_Extended::Rose_taupe, Core::_Colors::Colors_Extended::Rose_vale, Core::_Colors::Colors_Extended::Rosewood, Core::_Colors::Colors_Extended::Rosso_corsa, Core::_Colors::Colors_Extended::Rosy_brown, Core::_Colors::Colors_Extended::Royal_blue_dark, Core::_Colors::Colors_Extended::Royal_blue_light, Core::_Colors::Colors_Extended::Royal_purple, Core::_Colors::Colors_Extended::Royal_yellow, Core::_Colors::Colors_Extended::Ruber, Core::_Colors::Colors_Extended::Rubine_red, Core::_Colors::Colors_Extended::Ruby, Core::_Colors::Colors_Extended::Ruby_red, Core::_Colors::Colors_Extended::Rufous, Core::_Colors::Colors_Extended::Russet, Core::_Colors::Colors_Extended::Russian_green, Core::_Colors::Colors_Extended::Russian_violet, Core::_Colors::Colors_Extended::Rust, Core::_Colors::Colors_Extended::Rusty_red, Core::_Colors::Colors_Extended::Sacramento_State_green, Core::_Colors::Colors_Extended::Saddle_brown, Core::_Colors::Colors_Extended::Safety_orange, Core::_Colors::Colors_Extended::Safety_yellow, Core::_Colors::Colors_Extended::Saffron, Core::_Colors::Colors_Extended::Sage, Core::_Colors::Colors_Extended::Salmon, Core::_Colors::Colors_Extended::Salmon_pink, Core::_Colors::Colors_Extended::Sand, Core::_Colors::Colors_Extended::Sand_dune, Core::_Colors::Colors_Extended::Sandy_brown, Core::_Colors::Colors_Extended::Sap_green, Core::_Colors::Colors_Extended::Sapphire, Core::_Colors::Colors_Extended::Sapphire_blue, Core::_Colors::Colors_Extended::Sapphire_Crayola, Core::_Colors::Colors_Extended::Satin_sheen_gold, Core::_Colors::Colors_Extended::Scarlet, Core::_Colors::Colors_Extended::Schauss_pink, Core::_Colors::Colors_Extended::School_bus_yellow, Core::_Colors::Colors_Extended::Screamin_Green, Core::_Colors::Colors_Extended::Sea_green, Core::_Colors::Colors_Extended::Sea_green_Crayola, Core::_Colors::Colors_Extended::Seal_brown, Core::_Colors::Colors_Extended::Seashell, Core::_Colors::Colors_Extended::Selective_yellow, Core::_Colors::Colors_Extended::Sepia, Core::_Colors::Colors_Extended::Shadow, Core::_Colors::Colors_Extended::Shadow_blue, Core::_Colors::Colors_Extended::Shamrock_green, Core::_Colors::Colors_Extended::Sheen_green, Core::_Colors::Colors_Extended::Shimmering_Blush, Core::_Colors::Colors_Extended::Shiny_Shamrock, Core::_Colors::Colors_Extended::Shocking_pink, Core::_Colors::Colors_Extended::Shocking_pink_Crayola, Core::_Colors::Colors_Extended::Sienna, Core::_Colors::Colors_Extended::Silver, Core::_Colors::Colors_Extended::Silver_chalice, Core::_Colors::Colors_Extended::Silver_Crayola, Core::_Colors::Colors_Extended::Silver_Metallic, Core::_Colors::Colors_Extended::Silver_pink, Core::_Colors::Colors_Extended::Silver_sand, Core::_Colors::Colors_Extended::Sinopia, Core::_Colors::Colors_Extended::Sizzling_Red, Core::_Colors::Colors_Extended::Sizzling_Sunrise, Core::_Colors::Colors_Extended::Skobeloff, Core::_Colors::Colors_Extended::Sky_blue, Core::_Colors::Colors_Extended::Sky_blue_Crayola, Core::_Colors::Colors_Extended::Sky_magenta, Core::_Colors::Colors_Extended::Slate_blue, Core::_Colors::Colors_Extended::Slate_gray, Core::_Colors::Colors_Extended::Slimy_green, Core::_Colors::Colors_Extended::Smitten, Core::_Colors::Colors_Extended::Smoky_black, Core::_Colors::Colors_Extended::Snow, Core::_Colors::Colors_Extended::Solid_pink, Core::_Colors::Colors_Extended::Sonic_silver, Core::_Colors::Colors_Extended::Space_cadet, Core::_Colors::Colors_Extended::Spanish_bistre, Core::_Colors::Colors_Extended::Spanish_blue, Core::_Colors::Colors_Extended::Spanish_carmine, Core::_Colors::Colors_Extended::Spanish_gray, Core::_Colors::Colors_Extended::Spanish_green, Core::_Colors::Colors_Extended::Spanish_orange, Core::_Colors::Colors_Extended::Spanish_pink, Core::_Colors::Colors_Extended::Spanish_red, Core::_Colors::Colors_Extended::Spanish_sky_blue, Core::_Colors::Colors_Extended::Spanish_violet, Core::_Colors::Colors_Extended::Spanish_viridian, Core::_Colors::Colors_Extended::Spring_bud, Core::_Colors::Colors_Extended::Spring_Frost, Core::_Colors::Colors_Extended::Spring_green, Core::_Colors::Colors_Extended::Spring_green_Crayola, Core::_Colors::Colors_Extended::St_Patricks_blue, STACK_SIZE, Core::_Colors::Colors_Extended::Star_command_blue, Core::_Colors::Colors_Extended::Steel_blue, Core::_Colors::Colors_Extended::Steel_pink, Core::_Colors::Colors_Extended::Steel_Teal, Core::_Colors::Colors_Extended::Stil_de_grain_yellow, Core::_Colors::Colors_Extended::Straw, Core::_Colors::Colors_Extended::Sugar_Plum, Core::_Colors::Colors_Extended::Sunglow, Core::_Colors::Colors_Extended::Sunray, Core::_Colors::Colors_Extended::Sunset, Core::_Colors::Colors_Extended::Super_pink, Core::_Colors::Colors_Extended::Sweet_Brown, Core::_Colors::Colors_Extended::Tan, Core::_Colors::Colors_Extended::Tan_Crayola, Core::_Colors::Colors_Extended::Tangerine, Core::_Colors::Colors_Extended::Tango_pink, Core::_Colors::Colors_Extended::Tart_Orange, Core::_Colors::Colors_Extended::Taupe, Core::_Colors::Colors_Extended::Taupe_gray, Core::_Colors::Colors_Extended::Tawny, Core::_Colors::Colors_Extended::Tea_green, Core::_Colors::Colors_Extended::Tea_rose, Core::_Colors::Colors_Extended::Tea_rose_orange, Core::_Colors::Colors_Extended::Teal, Core::_Colors::Colors_Extended::Teal_blue, Core::_Colors::Colors_Extended::Telemagenta, Core::_Colors::Colors_Extended::Terra_cotta, Core::_Colors::Colors_Extended::Thistle, Core::_Colors::Colors_Extended::Thulian_pink, Core::_Colors::Colors_Extended::Tickle_Me_Pink, Core::_Colors::Colors_Extended::Tiffany_Blue, Core::_Colors::Colors_Extended::Timberwolf, Core::_Colors::Colors_Extended::Titanium_yellow, Core::_Colors::Colors_Extended::Tomato, Core::_Colors::Colors_Extended::Transparent, Core::_Colors::Colors_Extended::Tropical_rainforest, Core::_Colors::Colors_Extended::True_Blue, Core::_Colors::Colors_Extended::Trypan_Blue, Core::_Colors::Colors_Extended::Tufts_blue, Core::_Colors::Colors_Extended::Tumbleweed, Core::_Colors::Colors_Extended::Turquoise, Core::_Colors::Colors_Extended::Turquoise_blue, Core::_Colors::Colors_Extended::Turquoise_green, Core::_Colors::Colors_Extended::Turtle_green, Core::_Colors::Colors_Extended::Tuscan, Core::_Colors::Colors_Extended::Tuscan_brown, Core::_Colors::Colors_Extended::Tuscan_red, Core::_Colors::Colors_Extended::Tuscan_tan, Core::_Colors::Colors_Extended::Tuscany, Core::_Colors::Colors_Extended::Twilight_lavender, Core::_Colors::Colors_Extended::Tyrian_purple, Core::_Colors::Colors_Extended::UA_blue, Core::_Colors::Colors_Extended::UA_red, uiBackHighlightStack, uiBackStack, uiDetail1Stack, uiFrontHighlightStack, uiFrontStack, Core::_Colors::Colors_Extended::Ultra_pink, Core::_Colors::Colors_Extended::Ultra_red, Core::_Colors::Colors_Extended::Ultramarine, Core::_Colors::Colors_Extended::Ultramarine_blue, Core::_Colors::Colors_Extended::Umber, Core::_Colors::Colors_Extended::Unbleached_silk, Core::_Colors::Colors_Extended::United_Nations_blue, Core::_Colors::Colors_Extended::Unmellow_yellow, Core::_Colors::Colors_Extended::UP_Forest_green, Core::_Colors::Colors_Extended::UP_maroon, Core::_Colors::Colors_Extended::Upsdell_red, Core::_Colors::Colors_Extended::Uranian_blue, Core::_Colors::Colors_Extended::USAFA_blue, vActiveColor, Core::_Colors::Colors_Extended::Van_Dyke_brown, Core::_Colors::Colors_Extended::Vanilla, Core::_Colors::Colors_Extended::Vanilla_ice, vBackColor, vBackHighlight, vDetail1Color, Core::_Colors::Colors_Extended::Vegas_gold, Core::_Colors::Colors_Extended::Venetian_red, Core::_Colors::Colors_Extended::Verdigris, Core::_Colors::Colors_Extended::Vermilion, Core::_Colors::Colors_Extended::Veronica, vFrontColor, vFrontHighlight, Core::_Colors::Colors_Extended::Violet, Core::_Colors::Colors_Extended::Violet_blue, Core::_Colors::Colors_Extended::Violet_blue_Crayola, Core::_Colors::Colors_Extended::Violet_Crayola, Core::_Colors::Colors_Extended::Violet_CW, Core::_Colors::Colors_Extended::Violet_red, Core::_Colors::Colors_Extended::Violet_RYB, Core::_Colors::Colors_Extended::Violet_web, Core::_Colors::Colors_Extended::Viridian, Core::_Colors::Colors_Extended::Viridian_green, Core::_Colors::Colors_Extended::Vivid_burgundy, Core::_Colors::Colors_Extended::Vivid_sky_blue, Core::_Colors::Colors_Extended::Vivid_tangerine, Core::_Colors::Colors_Extended::Vivid_violet, Core::_Colors::Colors_Extended::Volt, Core::_Colors::Colors_Extended::Warm_black, Core::_Colors::Colors_Extended::Wheat, Core::_Colors::Colors_Extended::White, Core::_Colors::Colors_Extended::Wild_blue_yonder, Core::_Colors::Colors_Extended::Wild_orchid, Core::_Colors::Colors_Extended::Wild_Strawberry, Core::_Colors::Colors_Extended::Wild_watermelon, Core::_Colors::Colors_Extended::Windsor_tan, Core::_Colors::Colors_Extended::Wine, Core::_Colors::Colors_Extended::Wine_dregs, Core::_Colors::Colors_Extended::Winter_Sky, Core::_Colors::Colors_Extended::Wintergreen_Dream, Core::_Colors::Colors_Extended::Wisteria, Core::_Colors::Colors_Extended::Wood_brown, Core::_Colors::Colors_Extended::Xanadu, Core::_Colors::Colors_Extended::Xanthic, Core::_Colors::Colors_Extended::Yale_Blue, Core::_Colors::Colors_Extended::Yellow, Core::_Colors::Colors_Extended::Yellow_Crayola, Core::_Colors::Colors_Extended::Yellow_green, Core::_Colors::Colors_Extended::Yellow_green_Crayola, Core::_Colors::Colors_Extended::Yellow_green_CW, Core::_Colors::Colors_Extended::Yellow_Munsell, Core::_Colors::Colors_Extended::Yellow_NCS, Core::_Colors::Colors_Extended::Yellow_Orange, Core::_Colors::Colors_Extended::Yellow_Orange_CW, Core::_Colors::Colors_Extended::Yellow_Pantone, Core::_Colors::Colors_Extended::Yellow_process, Core::_Colors::Colors_Extended::Yellow_RYB, Core::_Colors::Colors_Extended::Yellow_Sunshine, Core::_Colors::Colors_Extended::YInMn_Blue, Core::_Colors::Colors_Extended::Zaffre, and Core::_Colors::Colors_Extended::Zomp.
~_Colors()
Core::_Colors::~_Colors () virtual
Definition at line 1555 of file Colors.cpp.
References pallette, vBackColor, vBackHighlight, vDetail1Color, vFrontColor, and vFrontHighlight.
Member Function Documentation
AddColor() [1/2]
int Core::_Colors::AddColor (std::string name, Color color)
Definition at line 1569 of file Colors.cpp.
References colors, cout, id, and map.
Referenced by _Colors(), AddColor(), and AddColor255().
AddColor() [2/2]
int Core::_Colors::AddColor (std::string name, float r, float g, float b, float a)
Definition at line 1591 of file Colors.cpp.
References AddColor().
AddColor255()
int Core::_Colors::AddColor255 (std::string name, int r, int g, int b, int a)
Definition at line 1603 of file Colors.cpp.
References AddColor().
Referenced by _Colors().
GetActive()
Color Core::_Colors::GetActive ()
Definition at line 1710 of file Colors.cpp.
Referenced by Core::GameSys::_Satellite::draw(), and Core::Shader_System::getUniform().
GetBack()
Color Core::_Colors::GetBack ()
Definition at line 1652 of file Colors.cpp.
References uiBackStack, and vBackColor.
Referenced by Core::Shader_System::getUniform().
GetBackHighlight()
Color Core::_Colors::GetBackHighlight ()
Definition at line 1674 of file Colors.cpp.
References uiBackHighlightStack, and vBackHighlight.
GetColor() [1/2]
Color & Core::_Colors::GetColor (int id)
Definition at line 1619 of file Colors.cpp.
References colors, and id.
GetColor() [2/2]
Color & Core::_Colors::GetColor (std::string name)
Definition at line 1611 of file Colors.cpp.
References colors, and map.
Referenced by _Colors().
GetDetail1()
Color Core::_Colors::GetDetail1 ()
Definition at line 1685 of file Colors.cpp.
References uiDetail1Stack, and vDetail1Color.
GetFront()
Color Core::_Colors::GetFront ()
Definition at line 1641 of file Colors.cpp.
References PushFront(), and SetFront().
Referenced by Core::Shader_System::getUniform().
GetFrontHighlight()
Color Core::_Colors::GetFrontHighlight ()
Definition at line 1663 of file Colors.cpp.
References uiFrontHighlightStack, and vFrontHighlight.
GetPallette()
Color Core::_Colors::GetPallette (_PALLETTE_COLOR e)
Definition at line 1627 of file Colors.cpp.
References pallette.
operator()()
Colors_Extended& Core::_Colors::operator() () inline
Definition at line 1049 of file Colors.h.
References Extended.
operator[]()
Color& Core::_Colors::operator[] (std::string name) inline
Definition at line 1050 of file Colors.h.
References colors, and map.
PopBack()
void Core::_Colors::PopBack ()
Definition at line 1651 of file Colors.cpp.
Referenced by Core::GameSys::checkIcon(), Core::GameSys::checkIcon2(), Core::GameSys::checkSprite(), Core::GameSys::drawIcon(), Core::GameSys::drawTextWindow(), Core::GameSys::drawWindow(), and Core::GUI::Object::Window::exec().
PopBackHighlight()
void Core::_Colors::PopBackHighlight ()
Definition at line 1673 of file Colors.cpp.
Referenced by Core::GameSys::checkIcon(), Core::GameSys::checkIcon2(), Core::GameSys::checkSprite(), Core::GameSys::drawIcon(), Core::GameSys::drawTextWindow(), and Core::GameSys::drawWindow().
PopDetail1()
void Core::_Colors::PopDetail1 ()
Definition at line 1684 of file Colors.cpp.
PopFront()
void Core::_Colors::PopFront ()
Definition at line 1640 of file Colors.cpp.
References uiFrontStack, and vFrontColor.
Referenced by Core::GameSys::checkText(), Core::_IconSys::draw(), Core::_SpriteSys::draw(), Core::GameSys::_MenuSys::draw(), Core::GameSys::_WinSys::drawB(), Core::GameSys::_WinSys::drawHDiv(), Core::GameSys::_WinSys::drawHLine(), Core::GameSys::_WinSys::drawHSpace(), Core::GameSys::_WinSys::drawiBorder(), Core::GameSys::_WinSys::drawL(), Core::GameSys::_WinSys::drawLBorder(), Core::GameSys::_WinSys::drawR(), Core::GameSys::_WinSys::drawRBorder(), Core::GameSys::_WinSys::drawSingle(), Core::GameSys::drawSprite(), Core::GameSys::_WinSys::drawT(), Core::GameSys::_WinSys::drawTBorder(), Core::_TextSys::drawText(), Core::GameSys::drawText(), Core::GameSys::drawTextWindow(), Core::GameSys::_WinSys::drawVDiv(), Core::GameSys::_WinSys::drawVLine(), Core::GameSys::_WinSys::drawVSpace(), Core::GUI::Object::Text::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::Icon::exec(), Core::GUI::Object::Field< int >::exec(), Core::GUI::Object::Window::exec(), Core::PostProcess::Render(), Core::PostProcess::Render2(), and _Game::Update().
PopFrontHighlight()
void Core::_Colors::PopFrontHighlight ()
Definition at line 1662 of file Colors.cpp.
Referenced by Core::GameSys::checkText(), Core::GameSys::_MenuSys::draw(), Core::GameSys::drawSprite(), and Core::GameSys::drawTextWindow().
PushBack() [1/2]
void Core::_Colors::PushBack ()
Definition at line 1650 of file Colors.cpp.
Referenced by SetActive().
PushBack() [2/2]
void Core::_Colors::PushBack (Color color)
Definition at line 1649 of file Colors.cpp.
Referenced by Core::GameSys::checkIcon(), Core::GameSys::checkIcon2(), Core::GameSys::checkSprite(), Core::GameSys::drawIcon(), Core::GameSys::drawTextWindow(), Core::GameSys::drawWindow(), and Core::GUI::Object::Window::exec().
PushBackHighlight() [1/2]
void Core::_Colors::PushBackHighlight ()
Definition at line 1672 of file Colors.cpp.
PushBackHighlight() [2/2]
void Core::_Colors::PushBackHighlight (Color color)
Definition at line 1671 of file Colors.cpp.
Referenced by Core::GameSys::checkIcon(), Core::GameSys::checkIcon2(), Core::GameSys::checkSprite(), Core::GameSys::drawIcon(), Core::GameSys::drawTextWindow(), and Core::GameSys::drawWindow().
PushDetail1() [1/2]
void Core::_Colors::PushDetail1 ()
Definition at line 1683 of file Colors.cpp.
PushDetail1() [2/2]
void Core::_Colors::PushDetail1 (Color color)
Definition at line 1682 of file Colors.cpp.
PushFront() [1/3]
void Core::_Colors::PushFront ()
Definition at line 1639 of file Colors.cpp.
Referenced by GetFront().
PushFront() [2/3]
void Core::_Colors::PushFront (Color color)
Definition at line 1637 of file Colors.cpp.
Referenced by Core::GameSys::checkText(), Core::_IconSys::draw(), Core::_SpriteSys::draw(), Core::GameSys::_MenuSys::draw(), Core::GameSys::_WinSys::drawB(), Core::GameSys::_WinSys::drawHDiv(), Core::GameSys::_WinSys::drawHLine(), Core::GameSys::_WinSys::drawHSpace(), Core::GameSys::_WinSys::drawiBorder(), Core::GameSys::_WinSys::drawL(), Core::GameSys::_WinSys::drawLBorder(), Core::GameSys::_WinSys::drawR(), Core::GameSys::_WinSys::drawRBorder(), Core::GameSys::_WinSys::drawSingle(), Core::GameSys::drawSprite(), Core::GameSys::_WinSys::drawT(), Core::GameSys::_WinSys::drawTBorder(), Core::_TextSys::drawText(), Core::GameSys::drawText(), Core::GameSys::drawTextWindow(), Core::GameSys::_WinSys::drawVDiv(), Core::GameSys::_WinSys::drawVLine(), Core::GameSys::_WinSys::drawVSpace(), Core::GUI::Object::Text::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::Icon::exec(), Core::GUI::Object::Field< int >::exec(), Core::GUI::Object::Window::exec(), Core::PostProcess::Render(), Core::PostProcess::Render2(), and _Game::Update().
PushFront() [3/3]
void Core::_Colors::PushFront (std::string name)
PushFrontHighlight() [1/2]
void Core::_Colors::PushFrontHighlight ()
Definition at line 1661 of file Colors.cpp.
PushFrontHighlight() [2/2]
void Core::_Colors::PushFrontHighlight (Color color)
Definition at line 1660 of file Colors.cpp.
Referenced by Core::GameSys::checkText(), Core::GameSys::_MenuSys::draw(), Core::GameSys::drawSprite(), and Core::GameSys::drawTextWindow().
SetActive()
void Core::_Colors::SetActive (_ACTIVE_COLOR e)
Definition at line 1687 of file Colors.cpp.
References PushBack(), and SetDetail1().
Referenced by Core::_IconSys::draw(), Core::_TextSys::draw(), Core::GameSys::drawWindow(), Core::PostProcess::Render(), Core::PostProcess::Render2(), MY_NAMESPACE::Setup(), Core::_SpriteSys::start(), Core::_IconSys::start(), Core::GameSys::_WinSys::start(), Core::_TextSys::start(), and _Game::Update().
SetBack()
void Core::_Colors::SetBack (Color color)
Definition at line 1647 of file Colors.cpp.
SetBackHighlight()
void Core::_Colors::SetBackHighlight (Color color)
Definition at line 1669 of file Colors.cpp.
SetDetail1()
void Core::_Colors::SetDetail1 (Color color)
Definition at line 1680 of file Colors.cpp.
Referenced by SetActive().
SetFront()
void Core::_Colors::SetFront (Color color)
Definition at line 1635 of file Colors.cpp.
Referenced by GetFront().
SetFrontHighlight()
void Core::_Colors::SetFrontHighlight (Color color)
Definition at line 1658 of file Colors.cpp.
Member Data Documentation
colors
std::vector<Color*> Core::_Colors::colors
Definition at line 67 of file Colors.h.
Referenced by AddColor(), GetColor(), and operator[]().
eActiveColor
_ACTIVE_COLOR Core::_Colors::eActiveColor private
Definition at line 36 of file Colors.h.
Referenced by _Colors().
Extended
struct Core::_Colors::Colors_Extended Core::_Colors::Extended
Referenced by _Colors(), and operator()().
map
Map_si Core::_Colors::map
Definition at line 68 of file Colors.h.
Referenced by AddColor(), GetColor(), and operator[]().
PALETTE_SIZE
const int Core::_Colors::PALETTE_SIZE = 32 static private
Definition at line 34 of file Colors.h.
Referenced by _Colors().
pallette
Color* Core::_Colors::pallette private
Definition at line 57 of file Colors.h.
Referenced by _Colors(), GetPallette(), and ~_Colors().
STACK_SIZE
const int Core::_Colors::STACK_SIZE = 16 static private
Definition at line 59 of file Colors.h.
Referenced by _Colors().
uiBackHighlightStack
int Core::_Colors::uiBackHighlightStack private
Definition at line 51 of file Colors.h.
Referenced by _Colors(), and GetBackHighlight().
uiBackStack
int Core::_Colors::uiBackStack private
Definition at line 51 of file Colors.h.
Referenced by _Colors(), and GetBack().
uiDetail1Stack
int Core::_Colors::uiDetail1Stack private
Definition at line 51 of file Colors.h.
Referenced by _Colors(), and GetDetail1().
uiFrontHighlightStack
int Core::_Colors::uiFrontHighlightStack private
Definition at line 51 of file Colors.h.
Referenced by _Colors(), and GetFrontHighlight().
uiFrontStack
int Core::_Colors::uiFrontStack private
Definition at line 51 of file Colors.h.
Referenced by _Colors(), and PopFront().
vActiveColor
Color* Core::_Colors::vActiveColor private
Definition at line 39 of file Colors.h.
Referenced by _Colors().
vBackColor
Color * Core::_Colors::vBackColor private
Definition at line 44 of file Colors.h.
Referenced by _Colors(), GetBack(), and ~_Colors().
vBackHighlight
Color * Core::_Colors::vBackHighlight private
Definition at line 44 of file Colors.h.
Referenced by _Colors(), GetBackHighlight(), and ~_Colors().
vDetail1Color
Color * Core::_Colors::vDetail1Color private
Definition at line 44 of file Colors.h.
Referenced by _Colors(), GetDetail1(), and ~_Colors().
vFrontColor
Color* Core::_Colors::vFrontColor private
Definition at line 44 of file Colors.h.
Referenced by _Colors(), PopFront(), and ~_Colors().
vFrontHighlight
Color * Core::_Colors::vFrontHighlight private
Definition at line 44 of file Colors.h.
Referenced by _Colors(), GetFrontHighlight(), and ~_Colors().
The documentation for this class was generated from the following files:
src/headers/core/Colors.h
src/headers/core/Colors.cpp