Project Parsec: Core::GameSys::_SpriteSys Class Reference
Core::GameSys::_SpriteSys Class Reference
#include <SpriteSys.h>
Public Member Functions
uint draw (uint x, uint y, float s, std::string sTex, bool textOffset)
uint draw (uint x, uint y, float s, std::string sTex, bool textOffset, Color fontColor)
uint draw (uint x, uint y, float w, float h, std::string sTex, bool textOffset)
uint draw (uint x, uint y, float w, float h, std::string sTex, bool textOffset, Color fontColor)
_SpriteSys ()
void draw (uint x, uint y, float w, float h, GLuint uiTex, SHADER_PROGRAMS uiShader)
void draw (uint x, uint y, float w, float h, Color fontColor, GLuint uiTex, SHADER_PROGRAMS uiShader)
bool load ()
bool calc ()
Private Member Functions
void start (int x, int y, float w, float h, std::string sTex, bool textOffset, bool bNoTex, Core::_Colors::_ACTIVE_COLOR eColor=Core::_Colors::COLOR_FRONT, SHADER_PROGRAMS uiShader=GLS_FONT)
void update (SHADER_PROGRAMS uiShader)
void stop ()
void draw (std::string sTex, SHADER_PROGRAMS iShader)
Private Attributes
Texture texture
VAO vao
Vector4f gridCoord
uint uiNumTextures
uint uiRecordSize
std::string sFilename
std::string sDir
std::string sTexDir
Friends
class _GameSys
Detailed Description
Definition at line 19 of file SpriteSys.h.
Constructor & Destructor Documentation
_SpriteSys()
Core::GameSys::_SpriteSys::_SpriteSys ()
Definition at line 60 of file SpriteSys.h.
References sDir, sFilename, sTexDir, uiNumTextures, and uiRecordSize.
Member Function Documentation
calc()
bool Core::GameSys::_SpriteSys::calc ()
Definition at line 108 of file SpriteSys.h.
References Core::VAO::Begin(), Core::VAO::CopyData(), cout, Core::VAO::End(), GL_TRIANGLES, Core::GLA_TEXTURE, Core::GLA_VERTEX, gridCoord, and vao.
draw() [1/7]
void Core::GameSys::_SpriteSys::draw (std::string sTex, SHADER_PROGRAMS iShader) private
Definition at line 189 of file SpriteSys.h.
References Core::VAO::Draw(), GL_CULL_FACE, and vao.
Referenced by draw().
draw() [2/7]
uint Core::GameSys::_SpriteSys::draw (uint x, uint y, float s, std::string sTex, bool textOffset)
Definition at line 197 of file SpriteSys.h.
References draw().
draw() [3/7]
uint Core::GameSys::_SpriteSys::draw (uint x, uint y, float s, std::string sTex, bool textOffset, Color fontColor)
Definition at line 207 of file SpriteSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
draw() [4/7]
void Core::GameSys::_SpriteSys::draw (uint x, uint y, float w, float h, Color fontColor, GLuint uiTex, SHADER_PROGRAMS uiShader = GLS_FONT)
Definition at line 230 of file SpriteSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
draw() [5/7]
void Core::GameSys::_SpriteSys::draw (uint x, uint y, float w, float h, GLuint uiTex, SHADER_PROGRAMS uiShader = GLS_FONT)
Definition at line 236 of file SpriteSys.h.
References Core::_Colors::COLOR_FRONT, Core::VAO::Draw(), GL_CULL_FACE, GL_TEXTURE0, GL_TEXTURE_2D, start(), stop(), update(), and vao.
draw() [6/7]
uint Core::GameSys::_SpriteSys::draw (uint x, uint y, float w, float h, std::string sTex, bool textOffset)
Definition at line 342 of file SpriteSys.h.
References Core::VAO::Draw(), Core::mouse, Core::_Mouse::MOUSE_NONE, start(), stop(), update(), and vao.
draw() [7/7]
uint Core::GameSys::_SpriteSys::draw (uint x, uint y, float w, float h, std::string sTex, bool textOffset, Color fontColor)
Definition at line 335 of file SpriteSys.h.
References Core::colors, draw(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
load()
bool Core::GameSys::_SpriteSys::load ()
Definition at line 76 of file SpriteSys.h.
References Core::MemBlock::buffer, cout, Core::readFile(), sDir, sFilename, Core::MemBlock::size, sTexDir, uiNumTextures, and uiRecordSize.
start()
void Core::GameSys::_SpriteSys::start (int x, int y, float w, float h, std::string sTex, bool textOffset, bool bNoTex = false, Core::_Colors::_ACTIVE_COLOR eColor = Core::_Colors::COLOR_FRONT, SHADER_PROGRAMS uiShader = GLS_FONT) private
Definition at line 151 of file SpriteSys.h.
References Core::colors, Core::GameVars::font, Core::gameVars, GL_DEPTH_TEST, GL_TRUE, Core::GameVars::Screen::origin, Core::GameVars::screen, Core::GameVars::Font::screenCoords, Core::_Colors::SetActive(), and Core::GameVars::Font::vSize.
Referenced by draw().
stop()
void Core::GameSys::_SpriteSys::stop () private
Definition at line 179 of file SpriteSys.h.
References GL_DEPTH_TEST.
Referenced by draw().
update()
void Core::GameSys::_SpriteSys::update (SHADER_PROGRAMS uiShader = GLS_FONT) private
Definition at line 174 of file SpriteSys.h.
Referenced by draw().
Friends And Related Function Documentation
_GameSys
friend class _GameSys friend
Definition at line 41 of file SpriteSys.h.
Member Data Documentation
gridCoord
Vector4f Core::GameSys::_SpriteSys::gridCoord private
Definition at line 25 of file SpriteSys.h.
Referenced by calc().
sDir
std::string Core::GameSys::_SpriteSys::sDir private
Definition at line 28 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
sFilename
std::string Core::GameSys::_SpriteSys::sFilename private
Definition at line 28 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
sTexDir
std::string Core::GameSys::_SpriteSys::sTexDir private
Definition at line 28 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
texture
Texture Core::GameSys::_SpriteSys::texture private
Definition at line 23 of file SpriteSys.h.
uiNumTextures
uint Core::GameSys::_SpriteSys::uiNumTextures private
Definition at line 26 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
uiRecordSize
uint Core::GameSys::_SpriteSys::uiRecordSize private
Definition at line 26 of file SpriteSys.h.
Referenced by _SpriteSys(), and load().
vao
VAO Core::GameSys::_SpriteSys::vao private
Definition at line 24 of file SpriteSys.h.
Referenced by calc(), and draw().
The documentation for this class was generated from the following file:
src/headers/gamesys/SpriteSys.h