Project Parsec: Core::GUI::Object::TextEdit Class Reference
Core::GUI::Object::TextEdit Class Reference
A copy of TextArea with cursor tracking and editing capability.
#include <GUI_TextEdit.h>
Public Member Functions
TextEdit ()
TextEdit (std::string n, Props_TextArea c)
TextEdit (Props &p, std::string n, Props_TextArea c)
TextEdit (std::string n, Props_TextArea *c)
TextEdit (Props &p, std::string n, Props_TextArea *c)
virtual ~TextEdit ()
void init ()
void exec (iState eExternState=STATE_NONE)
void updateNoFocus ()
Public Member Functions inherited from Core::GUI::Object::Base::Interactive< Props_TextArea, std::string >
Interactive ()
Interactive & operator= (const Interactive &src)
std::string getPtrValue ()
void setPointer (std::string *ptr)
std::string * getPointer ()
void init (Props_Addon_ReturnState *ptr)
int getState (int n=0)
bool valueChanged ()
void updateValuePtr ()
Public Member Functions inherited from Core::GUI::Object::Base::Generic< Props_TextArea >
void hide ()
void show ()
bool visible ()
void setEnableA (bool b, int n=0)
void setEnableAPtr (bool *b)
void setEnableAPtr (bool *b, int n)
void setEnableO (bool b, int n=0)
void setEnableOPtr (bool *b)
void setEnableOPtr (bool *b, int n)
bool enabled ()
iState getObjectState ()
Generic ()
virtual ~Generic ()
Generic & operator= (const Generic &src)
Public Member Functions inherited from Core::GUI::Object::Base::Interactive_Base
Interactive_Base ()
~Interactive_Base ()
Public Member Functions inherited from Core::GUI::Object::TextEditBase
TextEditBase ()
Private Member Functions
void execEdit ()
void updateObjectState (iState eExternState)
Private Attributes
Window win
Text text
Window * scrollBarContainer
Button * scrollUp
Button * scrollDown
Label * label
Slider< float > * scrollBar
bool bScrollOneShot
bool bHasFocus
std::string sEditBuffer
Additional Inherited Members
Public Attributes inherited from Core::GUI::Object::Base::Generic< Props_TextArea >
int border
Props_TextArea * con
Props * parent
Static Public Attributes inherited from Core::GUI::Object::Base::Interactive_Base
static bool bFocusPresent = false
static std::string sActiveObject = ""
static std::string sGroupObject [32] = { "" }
Static Public Attributes inherited from Core::GUI::Object::TextEditBase
static Core::_Keyboard keyboard = Core::_Keyboard()
static bool bKeyboardInit = false
Protected Attributes inherited from Core::GUI::Object::Base::Interactive< Props_TextArea, std::string >
std::string * valuePtr
bool bLocalValue
bool bReturnInit
bool bValueChanged
Timer debounceTimer
Props_Addon_ReturnState * returnState
Protected Attributes inherited from Core::GUI::Object::Base::Generic< Props_TextArea >
Core::_Mouse::MOUSE_STATE mState
std::string name
bool bInit
bool bLocalCon
bool bHasParent
bool bIsGrouped
bool bRepeatStatus
iState eObjectState
Detailed Description
A copy of TextArea with cursor tracking and editing capability.
Definition at line 52 of file GUI_TextEdit.h.
Constructor & Destructor Documentation
TextEdit() [1/5]
Core::GUI::Object::TextEdit::TextEdit ()
Definition at line 81 of file GUI_TextEdit.h.
References bHasFocus, bScrollOneShot, scrollBar, scrollBarContainer, scrollDown, scrollUp, and sEditBuffer.
TextEdit() [2/5]
Core::GUI::Object::TextEdit::TextEdit (std::string n, Props_TextArea c)
Definition at line 92 of file GUI_TextEdit.h.
References bHasFocus, Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, bScrollOneShot, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, scrollUp, and sEditBuffer.
TextEdit() [3/5]
Core::GUI::Object::TextEdit::TextEdit (Props & p, std::string n, Props_TextArea c)
Definition at line 112 of file GUI_TextEdit.h.
References bHasFocus, Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, bScrollOneShot, Core::GUI::Object::Base::Generic< Props_TextArea >::con, p, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, scrollUp, and sEditBuffer.
TextEdit() [4/5]
Core::GUI::Object::TextEdit::TextEdit (std::string n, Props_TextArea * c)
Definition at line 132 of file GUI_TextEdit.h.
References bHasFocus, Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, bScrollOneShot, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, scrollUp, and sEditBuffer.
TextEdit() [5/5]
Core::GUI::Object::TextEdit::TextEdit (Props & p, std::string n, Props_TextArea * c)
Definition at line 151 of file GUI_TextEdit.h.
References bHasFocus, Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bLocalCon, bScrollOneShot, Core::GUI::Object::Base::Generic< Props_TextArea >::con, p, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, scrollUp, and sEditBuffer.
~TextEdit()
Core::GUI::Object::TextEdit::~TextEdit () virtual
Definition at line 170 of file GUI_TextEdit.h.
Member Function Documentation
exec()
void Core::GUI::Object::TextEdit::exec (iState eExternState = STATE_NONE)
Definition at line 356 of file GUI_TextEdit.h.
References Core::GUI::Props_Text::bEnableCursor, Core::GUI::Object::Base::Interactive_Base::bFocusPresent, Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bInit, bScrollOneShot, Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::Props::_Size::constraint, Core::GUI::Props_TextArea::enableScrolling, Core::GUI::Object::Text::exec(), Core::GUI::Object::Slider< T >::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), execEdit(), Core::GameVars::font, Core::gameVars, Core::GUI::Object::Base::Interactive< C, T >::getState(), Core::GUI::Props_Text::iMaxLines, Core::GUI::Props::_Size::isAutoSet(), Core::GUI::Props_TextArea::iScrollSize, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, Core::GUI::Object::Base::Interactive_Base::sActiveObject, scrollBar, scrollBarContainer, scrollDown, Core::GUI::Props_Text::scrollDown(), scrollUp, Core::GUI::Props_Text::scrollUp(), Core::GUI::Props::setHeight(), Core::GUI::Props_Slider::setMinMax(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, text, Core::GUI::Props_TextArea::text, updateObjectState(), Core::GUI::Props::visibility, Core::GameVars::Font::vSize, win, Core::Vector2f::x, Core::GUI::Props::_Size::_SizeConstraint::xAuto, Core::Vector2f::y, and Core::GUI::Props::_Size::_SizeConstraint::yAuto.
execEdit()
void Core::GUI::Object::TextEdit::execEdit () private
Definition at line 274 of file GUI_TextEdit.h.
References Core::GUI::Object::Base::Interactive_Base::bFocusPresent, bHasFocus, Core::GUI::Props_Text::bOverwrite, Core::GUI::Props_Text::bufferPtr, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::_Keyboard::editBufferAt(), Core::_Keyboard::event, Core::GUI::Props_Text::iCursorPosition, Core::GUI::Props_Text::iDownChars, Core::_Keyboard::insertBufferAt(), Core::GUI::Props_Text::iUpChars, Core::GUI::Object::TextEditBase::keyboard, Core::_Keyboard::keys, sEditBuffer, Core::GUI::STATE_NONE, Core::GUI::Props_TextArea::text, and Core::_Keyboard::update().
Referenced by exec().
init()
void Core::GUI::Object::TextEdit::init ()
Definition at line 173 of file GUI_TextEdit.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::Props_Window::Colors::back, Core::GUI::Props_Button::Colors::back(), Core::GUI::GUI_ColorB::base, Core::GUI::Object::Base::Generic< Props_TextArea >::bHasParent, Core::GUI::Object::Base::Generic< Props_TextArea >::bInit, Core::GUI::Props_Button::Colors::border(), Core::GUI::Props_Addon_Label::bShowLabel, Core::GUI::Object::Base::Interactive< Props_TextArea, std::string >::Button, Core::GUI::BUTTON_DEBOUNCE, Core::GUI::Props_Window::color, Core::GUI::Props_Button::color, Core::colors, Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< C >::con, Core::GUI::CONSTRAIN_BOTTOM, Core::GUI::CONSTRAIN_CENTER, Core::GUI::CONSTRAIN_LEFT, Core::GUI::CONSTRAIN_RIGHT, Core::GUI::CONSTRAIN_TOP, Core::GUI::Props::_Size::constraint, Core::GUI::Props_Slider::control, Core::GUI::Props::disablePadding(), Core::GUI::Props_TextArea::enableScrolling, Core::GUI::Props::exec(), Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::Props_Addon_Field::hideField(), Core::GUI::Props_Addon_Label::hideLabel(), Core::GUI::GUI_ColorH::highlight, Core::GUI::Props_Text::iMaxLines, Core::GUI::Object::Text::init(), Core::GUI::Object::Slider< T >::init(), Core::GUI::Object::Button::init(), Core::GUI::Object::Window::init(), Core::GUI::Props_TextArea::iScrollSize, Core::GUI::Object::Base::Interactive< Props_TextArea, std::string >::Label, Core::GUI::Props_Addon_Label::label, Core::GameVars::pallette, Core::GUI::Object::Base::Generic< Props_TextArea >::parent, scrollBar, scrollBarContainer, scrollDown, Core::GUI::Props_Text::scrollPosition, scrollUp, Core::GUI::Props::setAnchor(), Core::GUI::Props_Window::setBorder(), Core::GUI::Props_Button::setButtonType(), Core::GUI::Props::setHeight(), Core::GUI::Props_Slider::setMinMax(), Core::GUI::Props::setOrigin(), Core::GUI::Props::setPos(), Core::GUI::Props_Window::setRadius(), Core::GUI::Props_Slider::setScrollSpeed(), Core::GUI::Props::setWidth(), Core::GUI::Props::size, Core::GUI::SIZE_CONSTRAINT_ABSOLUTE, Core::GUI::SIZE_CONSTRAINT_RELATIVE, Core::GUI::SLIDER_VERTICAL, text, Core::GUI::Object::Base::Interactive< Props_TextArea, std::string >::Text, Core::GUI::Props_Button::Colors::text, Core::GUI::Props_TextArea::text, Core::GameVars::_Pallette::textArea, win, Core::GUI::Object::Base::Interactive< Props_TextArea, std::string >::Window, Core::Vector2f::x, Core::GUI::Props::_Size::_SizeConstraint::xType, and Core::Vector2f::y.
Referenced by Core::GUI::GUI_Container::TextEditInterface::add().
updateNoFocus()
void Core::GUI::Object::TextEdit::updateNoFocus ()
Definition at line 446 of file GUI_TextEdit.h.
References Core::GUI::Object::Base::Interactive_Base::bFocusPresent, bHasFocus, Core::GUI::Props_Text::bufferPtr, Core::GUI::Object::Base::Generic< Props_TextArea >::con, sEditBuffer, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::GUI::Props_TextArea::text, and updateObjectState().
updateObjectState()
void Core::GUI::Object::TextEdit::updateObjectState (iState eExternState) private
Definition at line 317 of file GUI_TextEdit.h.
References Core::GUI::Object::Base::Interactive_Base::bFocusPresent, bHasFocus, Core::GUI::Props_Text::bufferPtr, Core::_Mouse::checkInput(), Core::GUI::Object::Base::Generic< Props_TextArea >::con, Core::GUI::Object::Base::Generic< Props_TextArea >::enabled(), Core::gameVars, Core::GameVars::Screen::half, Core::GUI::Props_Text::iCursorPosition, Core::mouse, Core::_Mouse::MOUSE_HOVER, Core::_Mouse::MOUSE_LEFT, Core::_Mouse::MOUSE_NONE, Core::GUI::Object::Base::Generic< Props_TextArea >::mState, Core::GUI::Object::Base::Generic< Props_TextArea >::name, Core::GUI::Props::pos, Core::GUI::Object::Base::Interactive_Base::sActiveObject, Core::GameVars::screen, sEditBuffer, Core::GUI::Props::size, Core::GUI::STATE_ACTIVE, Core::GUI::STATE_DISABLED, Core::GUI::STATE_HOVER, Core::GUI::STATE_NONE, Core::GUI::STATE_UPDATE, Core::GUI::Props_TextArea::text, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by exec(), and updateNoFocus().
Member Data Documentation
bHasFocus
bool Core::GUI::Object::TextEdit::bHasFocus private
Definition at line 74 of file GUI_TextEdit.h.
Referenced by execEdit(), TextEdit(), updateNoFocus(), and updateObjectState().
bScrollOneShot
bool Core::GUI::Object::TextEdit::bScrollOneShot private
Definition at line 73 of file GUI_TextEdit.h.
Referenced by exec(), and TextEdit().
label
Label* Core::GUI::Object::TextEdit::label private
Definition at line 71 of file GUI_TextEdit.h.
scrollBar
Slider<float>* Core::GUI::Object::TextEdit::scrollBar private
Definition at line 72 of file GUI_TextEdit.h.
Referenced by exec(), init(), and TextEdit().
scrollBarContainer
Window* Core::GUI::Object::TextEdit::scrollBarContainer private
Definition at line 68 of file GUI_TextEdit.h.
Referenced by exec(), init(), and TextEdit().
scrollDown
Button* Core::GUI::Object::TextEdit::scrollDown private
Definition at line 70 of file GUI_TextEdit.h.
Referenced by exec(), init(), and TextEdit().
scrollUp
Button* Core::GUI::Object::TextEdit::scrollUp private
Definition at line 69 of file GUI_TextEdit.h.
Referenced by exec(), init(), and TextEdit().
sEditBuffer
std::string Core::GUI::Object::TextEdit::sEditBuffer private
Definition at line 75 of file GUI_TextEdit.h.
Referenced by execEdit(), TextEdit(), updateNoFocus(), and updateObjectState().
text
Text Core::GUI::Object::TextEdit::text private
Definition at line 67 of file GUI_TextEdit.h.
Referenced by exec(), and init().
win
Window Core::GUI::Object::TextEdit::win private
Definition at line 66 of file GUI_TextEdit.h.
Referenced by exec(), and init().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_TextEdit.h