Project Parsec: Core::_Mouse Class Reference
Core::_Mouse Class Reference
#include <InputSys.h>
Classes
struct _Button
struct _Wheel
Public Types
enum MOUSE_STATE {
MOUSE_NONE = 0, MOUSE_HOVER = 1, MOUSE_LEFT = 2, MOUSE_RIGHT = 4,
MOUSE_MIDDLE = 8, MOUSE_DOUBLE = 16, MOUSE_LEFT_DOWN = 32, MOUSE_WHEEL_UP = 64,
MOUSE_WHEEL_DOWN = 128, MOUSE_WHEEL_LEFT = 256, MOUSE_WHEEL_RIGHT = 512
}
Public Member Functions
_Mouse ()
void init (uint ray, Vector3f position, bool bUpdate=false)
void draw (uint ray, Vector3f rotation, Vector3f position, int iSize=2.0f, Color vColorA=Color(1.0), Color vColorB=Color(1.0))
void SaveRay (Vector3f position)
void update (float fHalfW, float fHalfH)
void checkButton (int button, bool bRepeat=false)
void ToggleMouse ()
void ToggleMouse (SDL_bool bShow)
MOUSE_STATE checkWheel ()
MOUSE_STATE checkInput (int x, int y, float w, float h, bool bCentered=true)
MOUSE_STATE checkOver (int x, int y, float w, float h, bool bCentered=true)
MOUSE_STATE checkState ()
Vector3f GetMouseRay (float w, float h, Vector3f rotation)
Public Attributes
Vector3f mouseRay
Timer timer
bool bToggleMem
int x
int y
float sensX
float sensY
int deadX
int deadY
int relX
int relY
float fMouseDelay
float fMouseDelayConst
struct {
Vector3f pos
Vector3f dir
Vector3f start
Vector3f end
} rays [2]
struct Core::_Mouse::_Button button
struct Core::_Mouse::_Wheel wheel
Detailed Description
Definition at line 18 of file InputSys.h.
Member Enumeration Documentation
MOUSE_STATE
enum Core::_Mouse::MOUSE_STATE
Enumerator
MOUSE_NONE
MOUSE_HOVER
MOUSE_LEFT
MOUSE_RIGHT
MOUSE_MIDDLE
MOUSE_DOUBLE
MOUSE_LEFT_DOWN
MOUSE_WHEEL_UP
MOUSE_WHEEL_DOWN
MOUSE_WHEEL_LEFT
MOUSE_WHEEL_RIGHT
Definition at line 26 of file InputSys.h.
Constructor & Destructor Documentation
_Mouse()
Core::_Mouse::_Mouse ()
Definition at line 138 of file InputSys.h.
References bToggleMem, deadX, deadY, fMouseDelay, fMouseDelayConst, rays, relX, relY, sensX, sensY, Core::Timer::start(), and timer.
Member Function Documentation
checkButton()
void Core::_Mouse::checkButton (int iButton, bool bRepeat = false)
Parameters
iButton
bRepeat
Definition at line 276 of file InputSys.h.
References button, Core::_Mouse::_Button::check, Core::_Mouse::_Button::held, Core::_Mouse::_Button::pressed, and Core::_Mouse::_Button::repeat.
Referenced by update().
checkInput()
_Mouse::MOUSE_STATE Core::_Mouse::checkInput (int x, int y, float w, float h, bool bCentered = true)
Parameters
x
y
w
h
bCentered
Returns
Returns if mouse clicked in defined region, or if mouse is hovering over region.
Definition at line 349 of file InputSys.h.
References button, fMouseDelay, fMouseDelayConst, Core::Timer::get_ticks(), Core::gmath, Core::_Mouse::_Button::held, MOUSE_HOVER, MOUSE_LEFT, MOUSE_LEFT_DOWN, MOUSE_NONE, Core::_Mouse::_Button::pressed, and timer.
Referenced by Core::GameSys::checkIcon(), Core::GameSys::checkSprite(), Core::GameSys::drawTextWindow(), Core::GameSys::drawWindow(), Core::GUI::Object::TextArea::updateObjectState(), Core::GUI::Object::CheckBox::updateObjectState(), Core::GUI::Object::ProgressBar::updateObjectState(), Core::GUI::Object::Sprite::updateObjectState(), Core::GUI::Object::Button::updateObjectState(), Core::GUI::Object::ColorSwatch::updateObjectState(), Core::GUI::Object::Icon::updateObjectState(), Core::GUI::Object::Slider< int >::updateObjectState(), Core::GUI::Object::Field< int >::updateObjectState(), and Core::GUI::Object::TextEdit::updateObjectState().
checkOver()
_Mouse::MOUSE_STATE Core::_Mouse::checkOver (int x, int y, float w, float h, bool bCentered = true)
Parameters
x
y
w
h
bCentered
Returns
Definition at line 391 of file InputSys.h.
References Core::gmath, MOUSE_HOVER, and MOUSE_NONE.
checkState()
_Mouse::MOUSE_STATE Core::_Mouse::checkState ()
Returns
Check mouse button state regardless of position
Definition at line 416 of file InputSys.h.
References button, fMouseDelay, fMouseDelayConst, Core::Timer::get_ticks(), Core::_Mouse::_Button::held, MOUSE_LEFT, MOUSE_LEFT_DOWN, MOUSE_NONE, Core::_Mouse::_Button::pressed, and timer.
checkWheel()
_Mouse::MOUSE_STATE Core::_Mouse::checkWheel ()
Returns
Definition at line 316 of file InputSys.h.
References Core::_Mouse::_Wheel::down, Core::_Mouse::_Wheel::left, MOUSE_NONE, MOUSE_WHEEL_DOWN, MOUSE_WHEEL_LEFT, MOUSE_WHEEL_RIGHT, MOUSE_WHEEL_UP, Core::_Mouse::_Wheel::right, Core::_Mouse::_Wheel::up, and wheel.
Referenced by Core::GUI::Object::Slider< int >::updateScrollMouse().
draw()
void Core::_Mouse::draw (uint ray, Vector3f rotation, Vector3f position, int iSize = 2.0f, Color vColorA = Color(1.0), Color vColorB = Color(1.0))
Parameters
ray
rotation
position
iSize
vColorA
vColorB
Definition at line 183 of file InputSys.h.
References Core::_Helper::drawLine(), Core::helper, init(), and rays.
Referenced by _Game::Update().
GetMouseRay()
Vector3f Core::_Mouse::GetMouseRay (float w, float h, Vector3f rotation) inline
Definition at line 98 of file InputSys.h.
References Core::Matrix44f::Inverse(), mouseRay, Core::Vector3f::normal(), rays, Core::Vector4f::w, x, Core::Vector3f::x, Core::Vector4f::x, y, Core::Vector3f::y, Core::Vector4f::y, and Core::Vector4f::z.
Referenced by _Game::Run().
init()
void Core::_Mouse::init (uint ray, Vector3f position, bool bUpdate = false)
Parameters
ray
position
bUpdate
Definition at line 162 of file InputSys.h.
References dir, rays, and Core::Vector3f::x.
Referenced by draw(), and _Game::load().
SaveRay()
void Core::_Mouse::SaveRay (Vector3f position)
Parameters
position
Definition at line 200 of file InputSys.h.
References mouseRay, rays, Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by _Game::ProcessInput().
ToggleMouse() [1/2]
void Core::_Mouse::ToggleMouse ()
Definition at line 294 of file InputSys.h.
References bToggleMem, and Core::glinit.
Referenced by _Game::ProcessInput(), and _Admin::ProcessInput().
ToggleMouse() [2/2]
void Core::_Mouse::ToggleMouse (SDL_bool bShow)
Definition at line 306 of file InputSys.h.
References bToggleMem, and Core::glinit.
update()
void Core::_Mouse::update (float fHalfW, float fHalfH)
Parameters
fHalfW
fHalfH
Definition at line 212 of file InputSys.h.
References bToggleMem, button, Core::_Mouse::_Button::check, checkButton(), relX, and relY.
Referenced by _Game::GetInput(), and _Admin::GetInput().
Member Data Documentation
bToggleMem
bool Core::_Mouse::bToggleMem
Definition at line 41 of file InputSys.h.
Referenced by _Mouse(), ToggleMouse(), and update().
button
struct Core::_Mouse::_Button Core::_Mouse::button
Referenced by checkButton(), checkInput(), checkState(), and update().
deadX
int Core::_Mouse::deadX
Definition at line 44 of file InputSys.h.
Referenced by _Mouse().
deadY
int Core::_Mouse::deadY
Definition at line 44 of file InputSys.h.
Referenced by _Mouse().
dir
Vector3f Core::_Mouse::dir
Definition at line 49 of file InputSys.h.
Referenced by init(), and _Game::Update().
end
Vector3f Core::_Mouse::end
Definition at line 51 of file InputSys.h.
fMouseDelay
float Core::_Mouse::fMouseDelay
Definition at line 46 of file InputSys.h.
Referenced by _Mouse(), checkInput(), and checkState().
fMouseDelayConst
float Core::_Mouse::fMouseDelayConst
Definition at line 46 of file InputSys.h.
Referenced by _Mouse(), checkInput(), and checkState().
mouseRay
Vector3f Core::_Mouse::mouseRay
Definition at line 39 of file InputSys.h.
Referenced by GetMouseRay(), and SaveRay().
pos
Vector3f Core::_Mouse::pos
Definition at line 48 of file InputSys.h.
rays
struct { ... } Core::_Mouse::rays[2]
Referenced by _Mouse(), draw(), GetMouseRay(), init(), SaveRay(), and _Game::Update().
relX
int Core::_Mouse::relX
Definition at line 45 of file InputSys.h.
Referenced by _Mouse(), _Game::ProcessInput(), and update().
relY
int Core::_Mouse::relY
Definition at line 45 of file InputSys.h.
Referenced by _Mouse(), _Game::ProcessInput(), and update().
sensX
float Core::_Mouse::sensX
Definition at line 43 of file InputSys.h.
Referenced by _Mouse().
sensY
float Core::_Mouse::sensY
Definition at line 43 of file InputSys.h.
Referenced by _Mouse().
start
Vector3f Core::_Mouse::start
Definition at line 50 of file InputSys.h.
timer
Timer Core::_Mouse::timer
Definition at line 40 of file InputSys.h.
Referenced by _Mouse(), checkInput(), and checkState().
wheel
struct Core::_Mouse::_Wheel Core::_Mouse::wheel
Referenced by checkWheel(), and main().
x
int Core::_Mouse::x
Definition at line 42 of file InputSys.h.
Referenced by GetMouseRay(), and _Game::Update().
y
int Core::_Mouse::y
Definition at line 42 of file InputSys.h.
Referenced by Core::GUI::Object::ToolTip::exec(), GetMouseRay(), and _Game::Update().
The documentation for this class was generated from the following file:
src/headers/core/InputSys.h