Project Parsec: Core::_Joint Class Reference
Core::_Joint Class Reference
#include <joint.h>
Public Member Functions
_Joint ()
_Joint (Vector3f origin, Vector3f dest, Vector3f rotation, Vector3b rotationRestriction, Vector3b translationRestriction)
void SetJoint (Vector3f origin, Vector3f dest, Vector3f rotation=Vector3f(0.0f), Vector3b rotationRestriction=Vector3b(false), Vector3b translationRestriction=Vector3b(false))
int AddJoint (Vector3f dest, Vector3f rotation=Vector3f(0.0f), Vector3b rotationRestriction=Vector3b(false), Vector3b translationRestriction=Vector3b(false))
void SetRotation (Vector3f rotation)
void DrawJoint ()
virtual ~_Joint ()
Public Attributes
std::vector< _Joint > children
Private Attributes
bool bFinished
Detailed Description
Definition at line 49 of file joint.h.
Constructor & Destructor Documentation
_Joint() [1/2]
Core::_Joint::_Joint ()
Definition at line 22 of file joint.cpp.
References bFinished, Core::_JointData::vAxisX, Core::_JointData::vAxisY, and Core::_JointData::vAxisZ.
Referenced by AddJoint().
_Joint() [2/2]
Core::_Joint::_Joint (Vector3f origin, Vector3f dest, Vector3f rotation, Vector3b rotationRestriction, Vector3b translationRestriction)
Definition at line 29 of file joint.cpp.
References bFinished, Core::gmath, Core::_gmath::LookAt(), Core::_JointData::mLookAt, Core::_JointData::vAxisX, Core::_JointData::vAxisY, Core::_JointData::vAxisZ, Core::_JointData::vDestination, Core::_JointData::vOrigin, Core::_JointData::vRotation, Core::_JointData::vRotationRestriction, and Core::_JointData::vTranslationRestriction.
~_Joint()
Core::_Joint::~_Joint () virtual
Definition at line 56 of file joint.cpp.
Member Function Documentation
AddJoint()
int Core::_Joint::AddJoint (Vector3f dest, Vector3f rotation = Vector3f(0.0f), Vector3b rotationRestriction = Vector3b(false), Vector3b translationRestriction = Vector3b(false))
Definition at line 78 of file joint.cpp.
References _Joint(), children, Core::_JointData::vDestination, and Core::_JointData::vOrigin.
DrawJoint()
void Core::_Joint::DrawJoint ()
Definition at line 93 of file joint.cpp.
References bFinished, children, Core::_Helper::drawLine(), Core::GLS_LINES, Core::helper, Core::_JointData::vDestination, and Core::_JointData::vOrigin.
SetJoint()
void Core::_Joint::SetJoint (Vector3f origin, Vector3f dest, Vector3f rotation = Vector3f(0.0f), Vector3b rotationRestriction = Vector3b(false), Vector3b translationRestriction = Vector3b(false))
Definition at line 60 of file joint.cpp.
References bFinished, Core::gmath, Core::_gmath::LookAt(), Core::_JointData::mLookAt, Core::_JointData::vAxisX, Core::_JointData::vAxisY, Core::_JointData::vAxisZ, Core::_JointData::vDestination, Core::_JointData::vOrigin, Core::_JointData::vRotation, Core::_JointData::vRotationRestriction, and Core::_JointData::vTranslationRestriction.
SetRotation()
void Core::_Joint::SetRotation (Vector3f rotation)
Definition at line 85 of file joint.cpp.
References Core::_JointData::vRotation.
Member Data Documentation
bFinished
bool Core::_Joint::bFinished private
Definition at line 51 of file joint.h.
Referenced by _Joint(), DrawJoint(), and SetJoint().
children
std::vector<_Joint> Core::_Joint::children
Definition at line 54 of file joint.h.
Referenced by AddJoint(), and DrawJoint().
The documentation for this class was generated from the following files:
src/headers/core/joint.h
src/headers/core/joint.cpp