Project Parsec: Core::GUI::Constraints_Window Class Reference
Core::GUI::Constraints_Window Class Reference
#include <GUI_Constraint.h>
Public Member Functions
void setBorder (int i=1, bool b=true)
void setRadius (int i=2)
void setColorWindowB (Color *v1)
void setColorWindowH (Color *v1)
void setColorWindowA (Color *v1)
void setColorWindowBH (Color *v1, Color *v2)
void setColorWindowBHA (Color *v1, Color *v2, Color *v3)
void setColorWindowBHA (GUI_ColorBHA colors)
void setColorBorderB (Color *v1)
void setColorBorderH (Color *v1)
void setColorBorderA (Color *v1)
void setColorBorderBH (Color *v1, Color *v2)
void setColorBorderBHA (Color *v1, Color *v2, Color *v3)
void setColorBorderBHA (GUI_ColorBHA colors)
int getRadius ()
bool getRoundBorder ()
int getBorder ()
Constraints_Window ()
~Constraints_Window ()
Public Member Functions inherited from Core::GUI::Constraints
void setPos (int n1, int n2)
void setX (int n)
void setY (int n)
void setWidth (int n, eSizeConstraint e=SIZE_CONSTRAINT_RELATIVE)
void setHeight (int n, eSizeConstraint e=SIZE_CONSTRAINT_RELATIVE)
void setAnchor (iConstrain e=CONSTRAIN_CENTER)
void setOrigin (iConstrain e=CONSTRAIN_CENTER)
void exec ()
void exec (Constraints c)
Vector2f getPos ()
Vector2f getSize ()
void setPadding (int i)
void enablePadding ()
void disablePadding ()
void setVisibility (bool b)
Constraints ()
~Constraints ()
Public Attributes
GUI_ColorBHA colorWindow
GUI_ColorBHA colorBorder
bool roundBorder
int border
int radius
Public Attributes inherited from Core::GUI::Constraints
Core::GUI::Constraints::_Position pos
Actual calculated position from origin and anchor constraints, automatically updated.
Core::GUI::Constraints::_Size size
Actual calculated width(x) and height(y) from origin and anchor constraints, automatically updated.
int origin
The starting drawing point with respect to the parent, if present, otherwise full screen.
int anchor
The point at which this object is offset from the origin.
int padding
Extra reserved space taken into account for origin. This is similar to margins in HTML except is global for all sides.
bool bEnablePadding
Allow individual objects to ignore padding (ex: allows anchoring to outside of a window)
bool visibility
Controls if this object is drawn. Only used in Containers and Windows. All other objects rely on their parents status.
Friends
class Object::Window
Detailed Description
Definition at line 295 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Constraints_Window()
Core::GUI::Constraints_Window::Constraints_Window () inline
Definition at line 324 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::GUI_ColorB::base, colorBorder, colorWindow, Core::gameVars, Core::GameVars::_Pallette::gui, Core::GUI::GUI_ColorH::highlight, Core::GUI::Constraints::padding, Core::GameVars::pallette, radius, roundBorder, and Core::GameVars::_Pallette::window.
~Constraints_Window()
Core::GUI::Constraints_Window::~Constraints_Window () inline
Definition at line 339 of file GUI_Constraint.h.
Member Function Documentation
getBorder()
int Core::GUI::Constraints_Window::getBorder () inline
Definition at line 322 of file GUI_Constraint.h.
References border.
Referenced by Core::GUI::Object::Window::exec().
getRadius()
int Core::GUI::Constraints_Window::getRadius () inline
Definition at line 320 of file GUI_Constraint.h.
References radius.
Referenced by Core::GUI::Object::Window::exec().
getRoundBorder()
bool Core::GUI::Constraints_Window::getRoundBorder () inline
Definition at line 321 of file GUI_Constraint.h.
References roundBorder.
Referenced by Core::GUI::Object::Window::exec().
setBorder()
void Core::GUI::Constraints_Window::setBorder (int i = 1, bool b = true) inline
Definition at line 306 of file GUI_Constraint.h.
References roundBorder.
Referenced by Core::GUI::Constraints_CheckBox::Constraints_CheckBox(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Slider< int >::init(), and _Admin::run().
setColorBorderA()
void Core::GUI::Constraints_Window::setColorBorderA (Color * v1) inline
Definition at line 316 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorA::active, and colorBorder.
setColorBorderB()
void Core::GUI::Constraints_Window::setColorBorderB (Color * v1) inline
Definition at line 314 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorB::base, and colorBorder.
Referenced by Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), and Core::GUI::Object::Slider< int >::init().
setColorBorderBH()
void Core::GUI::Constraints_Window::setColorBorderBH (Color * v1, Color * v2) inline
Definition at line 317 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorB::base, colorBorder, and Core::GUI::GUI_ColorH::highlight.
setColorBorderBHA() [1/2]
void Core::GUI::Constraints_Window::setColorBorderBHA (Color * v1, Color * v2, Color * v3) inline
Definition at line 318 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::GUI_ColorB::base, colorBorder, and Core::GUI::GUI_ColorH::highlight.
Referenced by Core::GUI::Object::TextArea::init(), and Core::GUI::Object::Slider< int >::init().
setColorBorderBHA() [2/2]
void Core::GUI::Constraints_Window::setColorBorderBHA (GUI_ColorBHA colors) inline
Definition at line 319 of file GUI_Constraint.h.
References colorBorder, and Core::colors.
setColorBorderH()
void Core::GUI::Constraints_Window::setColorBorderH (Color * v1) inline
Definition at line 315 of file GUI_Constraint.h.
References colorBorder, and Core::GUI::GUI_ColorH::highlight.
setColorWindowA()
void Core::GUI::Constraints_Window::setColorWindowA (Color * v1) inline
Definition at line 310 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorA::active, and colorWindow.
setColorWindowB()
void Core::GUI::Constraints_Window::setColorWindowB (Color * v1) inline
Definition at line 308 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorB::base, and colorWindow.
Referenced by Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), and Core::GUI::Object::Slider< int >::init().
setColorWindowBH()
void Core::GUI::Constraints_Window::setColorWindowBH (Color * v1, Color * v2) inline
Definition at line 311 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorB::base, colorWindow, and Core::GUI::GUI_ColorH::highlight.
setColorWindowBHA() [1/2]
void Core::GUI::Constraints_Window::setColorWindowBHA (Color * v1, Color * v2, Color * v3) inline
Definition at line 312 of file GUI_Constraint.h.
References Core::GUI::GUI_ColorA::active, Core::GUI::GUI_ColorB::base, colorWindow, and Core::GUI::GUI_ColorH::highlight.
Referenced by Core::GUI::Object::TextArea::init(), and Core::GUI::Object::Slider< int >::init().
setColorWindowBHA() [2/2]
void Core::GUI::Constraints_Window::setColorWindowBHA (GUI_ColorBHA colors) inline
Definition at line 313 of file GUI_Constraint.h.
References Core::colors, and colorWindow.
setColorWindowH()
void Core::GUI::Constraints_Window::setColorWindowH (Color * v1) inline
Definition at line 309 of file GUI_Constraint.h.
References colorWindow, and Core::GUI::GUI_ColorH::highlight.
setRadius()
void Core::GUI::Constraints_Window::setRadius (int i = 2) inline
Definition at line 307 of file GUI_Constraint.h.
References radius.
Referenced by Core::GUI::Constraints_CheckBox::Constraints_CheckBox(), Core::GUI::Object::CheckBox::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::ColorSwatch::init(), Core::GUI::Object::Slider< int >::init(), and _Admin::run().
Friends And Related Function Documentation
Object::Window
friend class Object::Window friend
Definition at line 297 of file GUI_Constraint.h.
Member Data Documentation
border
int Core::GUI::Constraints_Window::border
Definition at line 303 of file GUI_Constraint.h.
Referenced by getBorder().
colorBorder
GUI_ColorBHA Core::GUI::Constraints_Window::colorBorder
Definition at line 300 of file GUI_Constraint.h.
Referenced by Core::GUI::Constraints_Button::Constraints_Button(), Core::GUI::Constraints_CheckBox::Constraints_CheckBox(), Core::GUI::Constraints_Field::Constraints_Field(), Core::GUI::Constraints_Label::Constraints_Label(), Core::GUI::Constraints_TextArea::Constraints_TextArea(), Constraints_Window(), Core::GUI::Object::Window::exec(), setColorBorderA(), setColorBorderB(), setColorBorderBH(), setColorBorderBHA(), and setColorBorderH().
colorWindow
GUI_ColorBHA Core::GUI::Constraints_Window::colorWindow
Definition at line 300 of file GUI_Constraint.h.
Referenced by Core::GUI::Constraints_Button::Constraints_Button(), Core::GUI::Constraints_CheckBox::Constraints_CheckBox(), Core::GUI::Constraints_Field::Constraints_Field(), Core::GUI::Constraints_Label::Constraints_Label(), Core::GUI::Constraints_TextArea::Constraints_TextArea(), Constraints_Window(), Core::GUI::Object::Window::exec(), setColorWindowA(), setColorWindowB(), setColorWindowBH(), setColorWindowBHA(), and setColorWindowH().
radius
int Core::GUI::Constraints_Window::radius
Definition at line 304 of file GUI_Constraint.h.
Referenced by Core::GUI::Constraints_Field::Constraints_Field(), Core::GUI::Constraints_Label::Constraints_Label(), Constraints_Window(), getRadius(), Core::GUI::Object::CheckBox::init(), and setRadius().
roundBorder
bool Core::GUI::Constraints_Window::roundBorder
Definition at line 302 of file GUI_Constraint.h.
Referenced by Core::GUI::Constraints_Field::Constraints_Field(), Core::GUI::Constraints_Label::Constraints_Label(), Constraints_Window(), getRoundBorder(), and setBorder().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI_Constraint.h