Project Parsec: Core::GUI::GUI_Container::ButtonInterface Class Reference
Core::GUI::GUI_Container::ButtonInterface Class Reference
#include <GUI_Container.h>
Public Member Functions
void add (std::string buttonName, bool b, Props_Button c, Props *p=nullptr)
void add (std::string buttonName, bool b, Props_Button *c, Props *p=nullptr)
void add (std::string buttonName, bool *b, Props_Button c, Props *p=nullptr)
void add (std::string buttonName, bool *b, Props_Button *c, Props *p=nullptr)
Object::Button & operator[] (std::string buttonName)
Props_Button & operator() (std::string buttonName)
ButtonInterface (GUI_Container *parent)
~ButtonInterface ()
Private Member Functions
void pushData (std::string name, Object::Button *data)
Private Attributes
std::vector< Object::Button * > buttons
Map_si map
GUI_Container * gui
Friends
class GUI_Container
Detailed Description
Definition at line 100 of file GUI_Container.h.
Constructor & Destructor Documentation
ButtonInterface()
Core::GUI::GUI_Container::ButtonInterface::ButtonInterface (GUI_Container * parent) inline
Definition at line 116 of file GUI_Container.h.
References gui, and Core::GUI::Object::Base::Generic< Props_Window >::parent.
~ButtonInterface()
Core::GUI::GUI_Container::ButtonInterface::~ButtonInterface () inline
Definition at line 117 of file GUI_Container.h.
References buttons.
Member Function Documentation
add() [1/4]
void Core::GUI::GUI_Container::ButtonInterface::add (std::string buttonName, bool * b, Props_Button * c, Props * p = nullptr)
Definition at line 440 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [2/4]
void Core::GUI::GUI_Container::ButtonInterface::add (std::string buttonName, bool * b, Props_Button c, Props * p = nullptr)
Definition at line 433 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [3/4]
void Core::GUI::GUI_Container::ButtonInterface::add (std::string buttonName, bool b, Props_Button * c, Props * p = nullptr)
Definition at line 426 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
add() [4/4]
void Core::GUI::GUI_Container::ButtonInterface::add (std::string buttonName, bool b, Props_Button c, Props * p = nullptr)
Definition at line 419 of file GUI_Container.h.
References MY_NAMESPACE::gui, and Core::GUI::GUI_Container::pushData().
operator()()
Props_Button& Core::GUI::GUI_Container::ButtonInterface::operator() (std::string buttonName) inline
Definition at line 115 of file GUI_Container.h.
References buttons, Core::GUI::Object::Base::Generic< Props_Window >::con, and map.
operator[]()
Object::Button& Core::GUI::GUI_Container::ButtonInterface::operator[] (std::string buttonName) inline
Definition at line 114 of file GUI_Container.h.
References buttons, and map.
pushData()
void Core::GUI::GUI_Container::ButtonInterface::pushData (std::string name, Object::Button * data) private
Definition at line 412 of file GUI_Container.h.
References Core::GUI::GUI_Container::map.
Friends And Related Function Documentation
GUI_Container
friend class GUI_Container friend
Definition at line 101 of file GUI_Container.h.
Member Data Documentation
buttons
std::vector<Object::Button*> Core::GUI::GUI_Container::ButtonInterface::buttons private
Definition at line 103 of file GUI_Container.h.
Referenced by Core::GUI::GUI_Container::execObjects(), Core::GUI::GUI_Container::execToolTips(), operator()(), operator[](), and ~ButtonInterface().
gui
GUI_Container* Core::GUI::GUI_Container::ButtonInterface::gui private
Definition at line 105 of file GUI_Container.h.
Referenced by ButtonInterface().
map
Map_si Core::GUI::GUI_Container::ButtonInterface::map private
Definition at line 104 of file GUI_Container.h.
Referenced by operator()(), and operator[]().
The documentation for this class was generated from the following file:
src/headers/gamesys/GUI/GUI_Container.h