Project Parsec: Core::_gmath Class Reference
Core::_gmath Class Reference
#include <gmath.h>
Public Member Functions
float sqr (float f)
float sqr (int i)
float sqr (unsigned short int i)
float sqr (short int i)
void Average (Vector3f &out, Vector3f a, Vector3f b)
void Average (Vector3f &out, Vector3f a, Vector3f b, Vector3f c)
void Average (Vector3f &out, Vector3f a, Vector3f b, Vector3f c, Vector3f d)
void Average (float &out, float a, float b)
void Average (float &out, float a, float b, float c)
void Average (float &out, float a, float b, float c, float d)
void Cross (Vector3f &i, Vector3f u, Vector3f v)
float Dot2f (Vector2f a, Vector2f b)
float Dot (Vector3f a, Vector3f b)
float ScalarTriple (Vector3f u, Vector3f v, Vector3f w)
void Max (float &in, float fMax)
Matrix44f LookAt (Vector3f vSource, Vector3f vDest, Vector3f vUp)
Matrix44f LookAt (Vector3f vSource, Vector3f vDest)
bool PointQuad2d (Vector2f p, Vector2f u, Vector2f v)
Vector3f Cross (Vector3f u, Vector3f v, bool bNorm=false)
float Hypot (Vector2f a, Vector2f b, bool bGetRoot=false)
float Hypot (float a1, float a2, float b1, float b2, bool bGetRoot=false)
void Normalize (Vector3f &i)
void BubbleSort (int *array, int length)
float pyth (Vector3f p)
void calcDistance (Vector3f p, Vector3f q, float &d)
float halfSpace (Vector3f p, Vector3f q, Vector3f a, Vector3f c, bool bClamp=false)
int halfSpace (Vector2f p, Vector2f a, Vector2f b)
int halfSpace (float p1, float p2, float a1, float a2, float b1, float b2, float c1, float c2)
int IntersectTri (Vector3f p, Vector3f q, Vector3f a, Vector3f b, Vector3f c, float &u, float &v, float &w, float &t)
bool SameSide (float p1, float p2, float q1, float q2, float a1, float a2, float b1, float b2)
bool SameSide (Vector3f p1, Vector3f p2, Vector3f a, Vector3f b)
bool PointInTriangle (Vector3f p, Vector3f a, Vector3f b, Vector3f c)
Detailed Description
Definition at line 14 of file gmath.h.
Member Function Documentation
Average() [1/6]
void Core::_gmath::Average (float & out, float a, float b) inline
Definition at line 34 of file gmath.h.
Average() [2/6]
void Core::_gmath::Average (float & out, float a, float b, float c) inline
Definition at line 35 of file gmath.h.
Average() [3/6]
void Core::_gmath::Average (float & out, float a, float b, float c, float d) inline
Definition at line 36 of file gmath.h.
Average() [4/6]
void Core::_gmath::Average (Vector3f & out, Vector3f a, Vector3f b) inline
Definition at line 31 of file gmath.h.
Average() [5/6]
void Core::_gmath::Average (Vector3f & out, Vector3f a, Vector3f b, Vector3f c) inline
Definition at line 32 of file gmath.h.
Average() [6/6]
void Core::_gmath::Average (Vector3f & out, Vector3f a, Vector3f b, Vector3f c, Vector3f d) inline
Definition at line 33 of file gmath.h.
BubbleSort()
void Core::_gmath::BubbleSort (int * array, int length) inline
Definition at line 127 of file gmath.h.
calcDistance()
void Core::_gmath::calcDistance (Vector3f p, Vector3f q, float & d) inline
Definition at line 155 of file gmath.h.
References pyth(), Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
Cross() [1/2]
void Core::_gmath::Cross (Vector3f & i, Vector3f u, Vector3f v) inline
Definition at line 37 of file gmath.h.
Referenced by Core::GameSys::AnimationSys::drawWorld(), Core::GameSys::MapSys::generateTerrainChunk(), Core::Matrix_System::GetLookAt(), halfSpace(), IntersectTri(), LookAt(), Core::Matrix_System::LookAt(), SameSide(), and ScalarTriple().
Cross() [2/2]
Vector3f Core::_gmath::Cross (Vector3f u, Vector3f v, bool bNorm = false) inline
Definition at line 77 of file gmath.h.
Dot()
float Core::_gmath::Dot (Vector3f a, Vector3f b) inline
Definition at line 39 of file gmath.h.
Referenced by halfSpace(), IntersectTri(), Core::_Collision::Ray_Cylinder(), Core::_Collision::Ray_Sphere(), Core::_Collision::Ray_SphereFast(), SameSide(), and ScalarTriple().
Dot2f()
float Core::_gmath::Dot2f (Vector2f a, Vector2f b) inline
Definition at line 38 of file gmath.h.
halfSpace() [1/3]
int Core::_gmath::halfSpace (float p1, float p2, float a1, float a2, float b1, float b2, float c1, float c2) inline
Definition at line 207 of file gmath.h.
References Cross(), Dot(), Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
halfSpace() [2/3]
int Core::_gmath::halfSpace (Vector2f p, Vector2f a, Vector2f b) inline
Definition at line 189 of file gmath.h.
References Cross(), Dot(), Core::Vector2f::x, and Core::Vector2f::y.
halfSpace() [3/3]
float Core::_gmath::halfSpace (Vector3f p, Vector3f q, Vector3f a, Vector3f c, bool bClamp = false) inline
Definition at line 169 of file gmath.h.
References Cross(), Dot(), and p.
Hypot() [1/2]
float Core::_gmath::Hypot (float a1, float a2, float b1, float b2, bool bGetRoot = false) inline
Definition at line 107 of file gmath.h.
Hypot() [2/2]
float Core::_gmath::Hypot (Vector2f a, Vector2f b, bool bGetRoot = false) inline
Definition at line 97 of file gmath.h.
IntersectTri()
int Core::_gmath::IntersectTri (Vector3f p, Vector3f q, Vector3f a, Vector3f b, Vector3f c, float & u, float & v, float & w, float & t) inline
Definition at line 236 of file gmath.h.
References Cross(), Dot(), and w.
LookAt() [1/2]
Matrix44f Core::_gmath::LookAt (Vector3f vSource, Vector3f vDest) inline
Definition at line 57 of file gmath.h.
References Cross(), and Core::Vector3f::normal().
LookAt() [2/2]
Matrix44f Core::_gmath::LookAt (Vector3f vSource, Vector3f vDest, Vector3f vUp) inline
Definition at line 43 of file gmath.h.
References Cross(), and Core::Vector3f::normal().
Referenced by Core::_Joint::_Joint(), and Core::_Joint::SetJoint().
Max()
void Core::_gmath::Max (float & in, float fMax) inline
Definition at line 41 of file gmath.h.
Referenced by Core::Matrix_System::Skew().
Normalize()
void Core::_gmath::Normalize (Vector3f & i) inline
Definition at line 120 of file gmath.h.
Referenced by Core::GameSys::AnimationSys::drawWorld(), Core::Matrix_System::GetLookAt(), and Core::Matrix_System::LookAt().
PointInTriangle()
bool Core::_gmath::PointInTriangle (Vector3f p, Vector3f a, Vector3f b, Vector3f c) inline
Definition at line 314 of file gmath.h.
References SameSide().
PointQuad2d()
bool Core::_gmath::PointQuad2d (Vector2f p, Vector2f u, Vector2f v) inline
Definition at line 72 of file gmath.h.
pyth()
float Core::_gmath::pyth (Vector3f p) inline
Definition at line 147 of file gmath.h.
References sqr(), Core::Vector3f::x, Core::Vector3f::y, and Core::Vector3f::z.
Referenced by calcDistance().
SameSide() [1/2]
bool Core::_gmath::SameSide (float p1, float p2, float q1, float q2, float a1, float a2, float b1, float b2) inline
Definition at line 277 of file gmath.h.
References Cross(), and Dot().
Referenced by PointInTriangle().
SameSide() [2/2]
bool Core::_gmath::SameSide (Vector3f p1, Vector3f p2, Vector3f a, Vector3f b) inline
Definition at line 298 of file gmath.h.
References Cross(), and Dot().
ScalarTriple()
float Core::_gmath::ScalarTriple (Vector3f u, Vector3f v, Vector3f w) inline
Definition at line 40 of file gmath.h.
References Cross(), and Dot().
sqr() [1/4]
float Core::_gmath::sqr (float f) inline
Definition at line 27 of file gmath.h.
Referenced by pyth().
sqr() [2/4]
float Core::_gmath::sqr (int i) inline
Definition at line 28 of file gmath.h.
sqr() [3/4]
float Core::_gmath::sqr (short int i) inline
Definition at line 30 of file gmath.h.
sqr() [4/4]
float Core::_gmath::sqr (unsigned short int i) inline
Definition at line 29 of file gmath.h.
The documentation for this class was generated from the following file:
src/headers/core/gmath.h