Project Parsec: MY_NAMESPACE Namespace Reference
MY_NAMESPACE Namespace Reference
Functions
void Setup (int argc, char *argv[])
void glReport ()
void Cleanup ()
Variables
std::string sOffset = ""
_Mouse * mouse = new _Mouse()
_State * state = new _State()
GlInit_System * glinit = new GlInit_System()
Matrix_System * matrix = new Matrix_System()
_SystemTextures * sysTex = new _SystemTextures()
Shader_System * shader = new Shader_System(*matrix)
PostProcess * postProcess = new PostProcess()
_Collision * collision = new _Collision()
_Helper * helper = new _Helper()
AudioSys * audioSys = new AudioSys()
_Joint * skeleton = new _Joint()
_Profile * profiles = new _Profile()
_FrameRate * framerate = new _FrameRate()
_TimeSys * timeSys = new _TimeSys()
_Occlusion * occlusion = new _Occlusion()
_Colors colors = _Colors()
_ParticleEmitter * particles = new _ParticleEmitter()
Stipple stipple = Stipple()
GameVars * gameVars = new GameVars()
_IconSys * iconSys = new _IconSys()
_SpriteSys * spriteSys = new _SpriteSys()
_TextSys * textSys = new _TextSys()
GameSys::_WinSys * winSys = new GameSys::_WinSys()
GameSys::_MenuSys * menuSys = new GameSys::_MenuSys(*textSys)
GUI::GUI gui
SDL_Event * sdlEvent = new SDL_Event()
Function Documentation
Cleanup()
void MY_NAMESPACE::Cleanup ()
Definition at line 842 of file core.h.
References audioSys, collision, framerate, gameVars, glinit, helper, iconSys, matrix, menuSys, occlusion, particles, postProcess, profiles, shader, skeleton, spriteSys, state, sysTex, textSys, timeSys, and winSys.
Referenced by main().
glReport()
void MY_NAMESPACE::glReport ()
Definition at line 832 of file core.h.
References cout, GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS, GL_RENDERER, GL_SHADING_LANGUAGE_VERSION, GL_VENDOR, and GL_VERSION.
Referenced by main().
Setup()
void MY_NAMESPACE::Setup (int argc, char * argv[])
Definition at line 700 of file core.h.
References Core::GameVars::Player::active, audioSys, Core::GameVars::Screen::bpp, Core::colors, Core::GameVars::Screen::fFar, Core::GameVars::Screen::fNear, Core::GameVars::Timers::frameRate, Core::gameVars, Core::glinit, Core::GameVars::Screen::half, Core::helper, iconSys, Core::GlInit_System::init(), Core::_Helper::init(), Core::PostProcess::init(), Core::_Occlusion::Init(), Core::Shader_System::init(), Core::_ParticleEmitter::init(), Core::_SystemTextures::load(), Core::Shader_System::load(), Core::GameVars::Screen::MultiSample, Core::occlusion, Core::particles, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::postProcess, Core::GameVars::Screen::res, Core::GameVars::screen, Core::_Colors::SetActive(), Core::Setup_GameVars(), Core::shader, skeleton, spriteSys, Core::Timer::start(), Core::sysTex, textSys, Core::GameVars::timer, Core::GameSys::CharSheet::transform, Core::GameVars::Screen::uiMultiSamples, Core::GameVars::Screen::vClearColorBase, Core::GameVars::Screen::vClearColorCurrent, winSys, Core::Vector2f::x, and Core::Vector2f::y.
Referenced by main().
Variable Documentation
audioSys
AudioSys* MY_NAMESPACE::audioSys = new AudioSys()
Definition at line 673 of file core.h.
Referenced by _Game::_Game(), Cleanup(), Setup(), Core::GUI::Object::Base::AudioFeedback::Sound_PlayAuto(), Core::GUI::Object::Base::AudioFeedback::Sound_PlayOff(), and Core::GUI::Object::Base::AudioFeedback::Sound_PlayOn().
collision
_Collision* MY_NAMESPACE::collision = new _Collision()
Definition at line 671 of file core.h.
Referenced by _Game::_Game(), Cleanup(), and _Game::ProcessInput().
colors
_Colors MY_NAMESPACE::colors = _Colors()
Definition at line 680 of file core.h.
Referenced by Core::GameSys::checkIcon(), Core::GameSys::checkIcon2(), Core::GameSys::checkSprite(), Core::GameSys::checkText(), Core::GUI::GUI::createGUI(), Core::_IconSys::draw(), Core::_SpriteSys::draw(), Core::GameSys::_MenuSys::draw(), Core::_TextSys::draw(), Core::GameSys::_O3D::draw(), Core::GameSys::_Satellite::draw(), Core::GameSys::_WinSys::drawB(), Core::GameSys::_WinSys::drawHDiv(), Core::GameSys::_WinSys::drawHLine(), Core::GameSys::_WinSys::drawHSpace(), Core::GameSys::_WinSys::drawiBorder(), Core::GameSys::drawIcon(), Core::_BOUNDING_VOLUME::DrawIntersection(), Core::GameSys::_WinSys::drawL(), Core::GameSys::_WinSys::drawLBorder(), Core::GameSys::_WinSys::drawR(), Core::GameSys::_WinSys::drawRBorder(), Core::GameSys::_WinSys::drawSingle(), Core::GameSys::drawSprite(), Core::GameSys::_WinSys::drawT(), Core::GameSys::_WinSys::drawTBorder(), Core::_TextSys::drawText(), Core::GameSys::drawText(), Core::GameSys::drawTextWindow(), Core::GameSys::_WinSys::drawVDiv(), Core::GameSys::_WinSys::drawVLine(), Core::GameSys::_WinSys::drawVSpace(), Core::GameSys::drawWindow(), Core::GUI::Object::Text::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Icon::exec(), Core::GUI::Object::Field< int >::exec(), Core::GUI::Object::Window::exec(), Core::Shader_System::getUniform(), Core::GUI::Object::ToolTip::init(), Core::GUI::Object::TextArea::init(), Core::GUI::Object::TextEdit::init(), _Admin::init(), _Admin::initColors(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), Core::GUI::Props_ComboBox::Props_ComboBox(), Core::PostProcess::Render(), Core::PostProcess::Render2(), Setup(), Core::Setup_GameVars(), Core::_SpriteSys::start(), Core::_IconSys::start(), Core::GameSys::_WinSys::start(), Core::_TextSys::start(), and _Game::Update().
framerate
_FrameRate* MY_NAMESPACE::framerate = new _FrameRate()
Definition at line 676 of file core.h.
Referenced by Cleanup(), main(), and _Game::Update().
gameVars
GameVars* MY_NAMESPACE::gameVars = new GameVars()
Definition at line 686 of file core.h.
Referenced by _Game::_Game(), Core::GameSys::Atmosphere::Atmosphere(), _TheVoid::bindFBO(), O3D_Dungeon::calc(), NPC::calc(), O2D_BASE::calc(), E2D_BASE::calc(), Water::calc(), O2D::calc(), WorldMap::calc(), E2D::calc(), RunConsole::calc(), Core::GameSys::_WorldMap::calc(), _NPC::calc(), Core::GameSys::_WinSys::calc(), Core::GameSys::_Flora::calc(), Core::GameSys::_O2D::calc(), Core::GameSys::_O3D::calc(), Core::GameSys::_Satellite::calc(), RunJournal::changeTab(), _TheVoid::CheckChunk(), Core::GameSys::checkIcon(), Core::GameSys::checkIcon2(), Core::GameSys::_MenuSys::checkInput(), Core::GameSys::_MenuSys::checkOver(), Core::GameSys::checkSprite(), RunMainMenu::choice(), Cleanup(), O2D_BASE::clear(), E2D_BASE::clear(), RunJournal::close(), Core::GUI::GUI::createGUI(), O3D_Dungeon::draw(), O2D_BASE::draw(), NPC::draw(), E2D_BASE::draw(), DungeonMap::draw(), Water::draw(), Core::GameSys::_MenuSys::draw(), WorldMap::draw(), _TheVoid::Draw(), _NPC::draw(), Core::_TextSys::draw(), RunBattle::draw(), Core::GameSys::_O2D::draw(), Core::GameSys::_O3D::draw(), Core::GameSys::Atmosphere::draw(), Core::GameSys::MapSys::draw(), Core::_TextSys::draw2(), Core::GameSys::_WinSys::drawB(), Core::GameSys::_WinSys::drawHDiv(), Core::GameSys::_WinSys::drawHLine(), Core::GameSys::_WinSys::drawHSpace(), Core::GameSys::_WinSys::drawiBorder(), Core::GameSys::_WinSys::drawL(), Core::GameSys::_WinSys::drawLBorder(), Core::_TextSys::drawMulti(), Core::GameSys::_WinSys::drawR(), Core::GameSys::_WinSys::drawRBorder(), Core::GameSys::_WinSys::drawSingle(), Core::GameSys::_WinSys::drawT(), Core::GameSys::_WinSys::drawTBorder(), Core::_TextSys::drawText(), Core::GameSys::drawTextWindow(), Core::_TextSys::drawVar2(), Core::GameSys::_WinSys::drawVDiv(), Core::GameSys::_WinSys::drawVLine(), Core::GameSys::_WinSys::drawVSpace(), Core::GameSys::drawWindow(), Core::GameSys::AnimationSys::drawWorld(), RunBattle::EndBattle(), Core::GUI::Object::ToolTip::exec(), Core::GUI::Object::Text::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::Sprite::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Icon::exec(), Core::GUI::Object::Field< int >::exec(), Core::GUI::Object::TextEdit::exec(), Core::GUI::Object::Window::exec(), Core::GUI::Props::exec(), RunBattle::ExecAttack(), RunBattle::ExecChangeStance(), Core::GUI::Object::Field< int >::execEditInput(), RunBattle::ExecMove(), Core::GUI::GUI_Container::execObjects(), Core::_Keyboard::_KeyArray::execRepeat(), RunConsole::execScript(), E2D::execute(), RunMenu::exit(), Core::GameSys::MapSys::generateTerrainChunk(), Core::GameSys::MapSys::getFractalElevation(), _Skill::GetInput(), RunEndBattle::getInput(), RunGrimoire::getInput(), RunBattleScroll::getInput(), RunMainMenu::getInput(), RunMenu::getInput(), RunDungeon::getInput(), RunJournal::getInput(), _Game::GetInput(), _TheVoid::GetInput(), RunBattle::getInput(), _Admin::GetInput(), Core::GameSys::MapSys::getPerlinElevation(), Core::GameSys::MapSys::getSimplexElevation(), Core::GUI::Object::Slider< int >::getValueFromPos(), O2D_BASE::init(), E2D_BASE::init(), Core::GUI::Object::ToolTip::init(), Water::init(), Core::GUI::Object::TextArea::init(), WorldMap::init(), Core::GUI::Object::Slider< int >::init(), Core::GUI::Object::TextEdit::init(), Core::_TextSys::init(), _Admin::init(), RunConsole::input(), O3D_Dungeon::load(), NPC::load(), Water::load(), O2D::load(), WorldMap::load(), E2D::load(), _TheVoid::load(), RunDungeon::load(), _Game::load(), _NPC::load(), Core::GameSys::Atmosphere::load(), Core::GameSys::MapSys::load(), E2D::loadEvent(), main(), RunBattle::NextTarget(), _Skill::ProcessInput(), RunEndBattle::processInput(), RunGrimoire::processInput(), RunBattleScroll::processInput(), RunMainMenu::processInput(), RunMenu::processInput(), RunDungeon::processInput(), RunJournal::processInput(), _Game::ProcessInput(), _TheVoid::ProcessInput(), RunBattle::processInput(), _Admin::ProcessInput(), Core::GUI::Props_Addon_Stipple::Props_Addon_Stipple(), Core::GUI::Props_Button::Props_Button(), Core::GUI::Props_CheckBox::Props_CheckBox(), Core::GUI::Props_ColorSwatch::Props_ColorSwatch(), Core::GUI::Props_Field::Props_Field(), Core::GUI::Props_Icon::Props_Icon(), Core::GUI::Props_Label::Props_Label(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), Core::GUI::Props_Slider::Props_Slider(), Core::GUI::Props_Sprite::Props_Sprite(), Core::GUI::Props_Text::Props_Text(), Core::GUI::Props_TextArea::Props_TextArea(), Core::GUI::Props_Window::Props_Window(), _TheVoid::reload(), _NPC::reload(), RunMenu::reset(), RunBattle::ResetRound(), RunEndBattle::run(), RunGrimoire::run(), RunBattleScroll::run(), RunMainMenu::run(), RunMenu::run(), RunConsole::run(), RunDungeon::run(), _Game::Run(), RunJournal::run(), _TheVoid::Run(), RunBattle::run(), _Admin::run(), runDebug(), RunBattle::RunMagic(), RunMenu::set(), RunBattle::setActive(), RunBattle::setTarget(), Setup(), Core::Setup_GameVars(), O2D::shift(), WorldMap::shift(), E2D::shift(), RunBattle::ShowStats(), Core::_SpriteSys::start(), RunConsole::start(), Core::_IconSys::start(), Core::GameSys::_WinSys::start(), Core::_TextSys::start(), _TheVoid::unbindFBO(), RunBattleScroll::update(), RunDungeon::update(), RunMenu::update(), RunJournal::update(), RunConsole::update(), _Game::Update(), _TheVoid::Update(), RunBattle::update(), Core::GameSys::_Flora::update(), Core::GameSys::_Satellite::update(), Core::GameSys::MapSys::update(), Core::_ParticleEmitter::update(), Core::GUI::Object::TextArea::updateObjectState(), Core::GUI::Object::CheckBox::updateObjectState(), Core::GUI::Object::ProgressBar::updateObjectState(), Core::GUI::Object::Sprite::updateObjectState(), Core::GUI::Object::Button::updateObjectState(), Core::GUI::Object::ColorSwatch::updateObjectState(), Core::GUI::Object::Icon::updateObjectState(), Core::GUI::Object::Slider< int >::updateObjectState(), Core::GUI::Object::Field< int >::updateObjectState(), Core::GUI::Object::TextEdit::updateObjectState(), RunBattle::UpdateRound(), and Water::Water().
glinit
GlInit_System* MY_NAMESPACE::glinit = new GlInit_System()
Definition at line 666 of file core.h.
Referenced by Cleanup(), Core::_ParticleEmitter::draw(), Core::GameSys::_Satellite::drawFlare(), main(), _Game::ProcessInput(), Setup(), Core::_Mouse::ToggleMouse(), and _Game::Update().
gui
GUI::GUI MY_NAMESPACE::gui
Definition at line 694 of file core.h.
Referenced by Core::GUI::GUI_Container::WindowInterface::add(), Core::GUI::GUI_Container::LabelInterface::add(), Core::GUI::GUI_Container::ButtonInterface::add(), Core::GUI::GUI_Container::SliderInterface::add(), Core::GUI::GUI_Container::FieldInterface::add(), Core::GUI::GUI_Container::TextAreaInterface::add(), Core::GUI::GUI_Container::TextEditInterface::add(), Core::GUI::GUI_Container::ColorSwatchInterface::add(), Core::GUI::GUI_Container::CheckBoxInterface::add(), Core::GUI::GUI_Container::IconInterface::add(), Core::GUI::GUI_Container::SpriteInterface::add(), Core::GUI::GUI_Container::ProgressBarInterface::add(), Core::GUI::GUI_Container::ComboBoxInterface::add(), Core::GUI::GUI::createGUI(), _Admin::init(), _Admin::initColors(), _Admin::initSkillTree(), _Admin::run(), and Core::GUI::GUI::~GUI().
helper
_Helper* MY_NAMESPACE::helper = new _Helper()
Definition at line 672 of file core.h.
Referenced by _Game::_Game(), Cleanup(), Core::_Mouse::draw(), Core::_BOUNDING_VOLUME::Draw(), Core::GameSys::_Satellite::draw(), Core::_ParticleEmitter::draw(), Core::_BOUNDING_VOLUME::DrawAABB(), Core::_BOUNDING_VOLUME::DrawCylinder(), Core::GameSys::_Satellite::drawFlare(), Core::_BOUNDING_VOLUME::DrawIntersection(), Core::_Joint::DrawJoint(), Core::_BOUNDING_VOLUME::DrawOBB(), Core::_BOUNDING_VOLUME::DrawSphere(), Setup(), _Game::Update(), and Core::GameSys::_Satellite::update().
iconSys
_IconSys* MY_NAMESPACE::iconSys = new _IconSys()
Definition at line 688 of file core.h.
Referenced by Core::GameSys::checkIcon(), Cleanup(), Core::GameSys::drawIcon(), Core::GUI::Object::Icon::exec(), and Setup().
matrix
Matrix_System* MY_NAMESPACE::matrix = new Matrix_System()
Definition at line 667 of file core.h.
Referenced by Cleanup(), Core::GameSys::MapSys::draw(), Core::GameSys::_Satellite::drawFlare(), _Game::Update(), and Core::GameSys::_Satellite::update().
menuSys
GameSys::_MenuSys* MY_NAMESPACE::menuSys = new GameSys::_MenuSys(*textSys)
Definition at line 692 of file core.h.
Referenced by Core::GameSys::checkText(), and Cleanup().
mouse
_Mouse* MY_NAMESPACE::mouse = new _Mouse()
Definition at line 664 of file core.h.
Referenced by Core::GameSys::checkIcon(), Core::GameSys::_MenuSys::checkInput(), Core::GameSys::_MenuSys::checkOver(), Core::GameSys::checkSprite(), Core::GameSys::_MenuSys::draw(), Core::_SpriteSys::draw(), Core::GameSys::_O3D::draw(), Core::GameSys::drawTextWindow(), Core::GameSys::drawWindow(), Core::GUI::Object::ToolTip::exec(), _Game::GetInput(), _Admin::GetInput(), _Game::load(), main(), _Game::ProcessInput(), _Admin::ProcessInput(), _Game::Run(), _Game::Update(), Core::GUI::Object::Slider< int >::updateControlPos(), Core::GUI::Object::TextArea::updateObjectState(), Core::GUI::Object::CheckBox::updateObjectState(), Core::GUI::Object::ProgressBar::updateObjectState(), Core::GUI::Object::Sprite::updateObjectState(), Core::GUI::Object::Button::updateObjectState(), Core::GUI::Object::ColorSwatch::updateObjectState(), Core::GUI::Object::Icon::updateObjectState(), Core::GUI::Object::Slider< int >::updateObjectState(), Core::GUI::Object::Field< int >::updateObjectState(), Core::GUI::Object::TextEdit::updateObjectState(), and Core::GUI::Object::Slider< int >::updateScrollMouse().
occlusion
_Occlusion* MY_NAMESPACE::occlusion = new _Occlusion()
Definition at line 678 of file core.h.
Referenced by Core::GameSys::_Satellite::add(), Core::GameSys::_Satellite::calc(), Cleanup(), _TheVoid::Draw(), Core::GameSys::_Satellite::draw(), runDebug(), Setup(), _Game::Update(), and Core::GameSys::_Satellite::update().
particles
_ParticleEmitter* MY_NAMESPACE::particles = new _ParticleEmitter()
Definition at line 681 of file core.h.
Referenced by Cleanup(), Core::_ParticleEmitter::draw(), Core::_ParticleEmitter::emit(), _Game::Run(), Setup(), _Game::Update(), and Core::_ParticleEmitter::update().
postProcess
PostProcess* MY_NAMESPACE::postProcess = new PostProcess()
Definition at line 670 of file core.h.
Referenced by Cleanup(), Setup(), _Game::Update(), and _TheVoid::Update().
profiles
_Profile* MY_NAMESPACE::profiles = new _Profile()
Definition at line 675 of file core.h.
Referenced by Cleanup(), Core::GameSys::MapSys::load(), main(), _Game::ProcessInput(), _Game::Run(), and _Game::Update().
sdlEvent
SDL_Event* MY_NAMESPACE::sdlEvent = new SDL_Event()
Definition at line 695 of file core.h.
Referenced by main().
shader
Shader_System* MY_NAMESPACE::shader = new Shader_System(*matrix)
Definition at line 669 of file core.h.
Referenced by Cleanup(), Core::Shader_System::load(), and Setup().
skeleton
_Joint* MY_NAMESPACE::skeleton = new _Joint()
Definition at line 674 of file core.h.
Referenced by Cleanup(), and Setup().
sOffset
std::string MY_NAMESPACE::sOffset = ""
Definition at line 630 of file core.h.
spriteSys
_SpriteSys* MY_NAMESPACE::spriteSys = new _SpriteSys()
Definition at line 689 of file core.h.
Referenced by Core::GameSys::checkSprite(), Cleanup(), Core::GameSys::drawSprite(), Core::GUI::Object::Sprite::exec(), Setup(), and _Game::Update().
state
_State* MY_NAMESPACE::state = new _State()
Definition at line 665 of file core.h.
Referenced by Cleanup(), Core::_ParticleEmitter::move(), and Core::Setup_GameVars().
stipple
Stipple MY_NAMESPACE::stipple = Stipple()
Definition at line 684 of file core.h.
Referenced by Core::GUI::Object::ToolTip::init(), Core::GUI::Object::ColorSwatch::init(), _Admin::init(), Core::GUI::Props_Addon_Stipple::Props_Addon_Stipple(), Core::GUI::Props_ProgressBar::Props_ProgressBar(), _Admin::run(), and Core::Stipple::Stipple().
sysTex
_SystemTextures* MY_NAMESPACE::sysTex = new _SystemTextures()
Definition at line 668 of file core.h.
Referenced by Cleanup(), Core::GameSys::_Satellite::draw(), Core::GameSys::MapSys::draw(), and Setup().
textSys
_TextSys* MY_NAMESPACE::textSys = new _TextSys()
Definition at line 690 of file core.h.
Referenced by Cleanup(), Core::GameSys::drawText(), Core::GUI::Object::Text::exec(), Core::GUI::Object::Label::exec(), Core::GUI::Object::Button::exec(), Core::GUI::Object::Field< int >::exec(), Setup(), and _Game::Update().
timeSys
_TimeSys* MY_NAMESPACE::timeSys = new _TimeSys()
Definition at line 677 of file core.h.
Referenced by Cleanup(), Core::GameSys::Atmosphere::draw(), Core::_ParticleEmitter::draw(), Core::_ParticleEmitter::emit(), main(), _Game::Update(), Core::GameSys::_Flora::update(), Core::GameSys::_Satellite::update(), Core::_ParticleEmitter::update(), and Core::_Particles::updateQuad().
winSys
GameSys::_WinSys* MY_NAMESPACE::winSys = new GameSys::_WinSys()
Definition at line 691 of file core.h.
Referenced by Cleanup(), Core::GameSys::drawTextWindow(), Core::GameSys::drawWindow(), and Setup().