Project Parsec: Core::GameSys Namespace Reference
Core::GameSys Namespace Reference
Namespaces
GUIObject
Classes
class _Flora
struct _FloraData
class _MenuSys
class _O2D
struct _O2DData
struct _O2DGroup
class _O3D
struct _O3DData
class _Satellite
struct _SatelliteData
class _WinSys
class _WorldMap
class AnimationSys
class Atmosphere
struct CharSheet
struct MapData
class MapSys
Functions
uint drawWindow (int x, int y, int w, int h, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor, short int iBorder=Core::GameSys::_WinSys::DRAWMODE.NORMAL)
uint drawWindow (int x, int y, int w, int h, bool bHighlight, bool textOffset, short int iBorder)
void drawIcon (uint x, uint y, float w, float h, uint id, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
void drawIcon (uint x, uint y, float w, float h, uint id, std::string sTex, bool bHighlight, bool textOffset)
uint checkIcon2 (uint x, uint y, uint w, uint h, uint id, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
uint checkIcon2 (uint x, uint y, uint w, uint h, uint id, std::string sTex, bool bHighlight, bool textOffset)
uint checkIcon (uint x, uint y, float w, float h, uint id, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
uint checkIcon (uint x, uint y, float w, float h, uint id, std::string sTex, bool bHighlight=true, bool textOffset=false)
void drawCard (int id0, int id1, int id2, int id3, std::string sTex, SHADER_PROGRAMS iShader)
void drawWindow (int x, int y, int w, int h, bool textOffset, Core::Color backColor, short int iBorder)
void drawWindow (int x, int y, int w, int h, bool textOffset, short int iBorder)
void drawText (int x, int y, std::string buffer, Core::Color fontColor, int xLimit, int yLimit)
void drawText (int x, int y, std::string buffer, int xLimit, int yLimit)
void drawVariable (int x, int y, bool bP, Core::Color fontColor)
void drawVariable (int x, int y, bool bP)
void drawVariable (int x, int y, int iP, Core::Color fontColor)
void drawVariable (int x, int y, int iP)
void drawVariable (int x, int y, uint iP, Core::Color fontColor)
void drawVariable (int x, int y, uint iP)
void drawVariable (int x, int y, float fP, Core::Color fontColor, bool bDec)
void drawVariable (int x, int y, float fP, bool bDec)
void checkVariable (int x, int y, bool bP, Core::Color fontColor)
void checkVariable (int x, int y, bool bP)
void checkVariable (int x, int y, int iP, Core::Color fontColor)
void checkVariable (int x, int y, int iP)
void checkVariable (int x, int y, float fP, Core::Color fontColor, bool bDec)
void checkVariable (int x, int y, float fP, bool bDec)
uint drawTextWindow (int x, int y, int w, int h, std::string sText, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color frontColor, Core::Color backHColor, Core::Color frontHColor, short int iBorder)
uint drawTextWindow (int x, int y, int w, int h, std::string sText, bool bHighlight, bool textOffset, short int iBorder)
uint checkText (int x, int y, std::string sText, bool bHighlight, bool textOffset, Core::Color frontColor, Core::Color frontHColor)
uint checkText (int x, int y, std::string sText, bool bHighlight, bool textOffset)
void drawSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
void drawSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset, Core::Color frontColor)
void drawSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset)
uint checkSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
uint checkSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset)
uint checkMenu (uint x, uint y, std::string s)
Function Documentation
checkIcon() [1/2]
uint Core::GameSys::checkIcon (uint x, uint y, float w, float h, uint id, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
Definition at line 604 of file gamesys.h.
References Core::colors, Core::_Colors::PopBack(), Core::_Colors::PopBackHighlight(), Core::_Colors::PushBack(), and Core::_Colors::PushBackHighlight().
Referenced by checkIcon2(), and _Game::Update().
checkIcon() [2/2]
uint Core::GameSys::checkIcon (uint x, uint y, float w, float h, uint id, std::string sTex, bool bHighlight = true, bool textOffset = false)
Definition at line 623 of file gamesys.h.
References Core::_Mouse::checkInput(), Core::_IconSys::draw(), Core::GameVars::font, Core::gameVars, Core::iconSys, Core::mouse, and Core::GameVars::Font::vSize.
checkIcon2() [1/2]
uint Core::GameSys::checkIcon2 (uint x, uint y, uint w, uint h, uint id, std::string sTex, bool bHighlight, bool textOffset)
Definition at line 592 of file gamesys.h.
References checkIcon(), Core::GameVars::font, Core::gameVars, and Core::GameVars::Font::vSize.
checkIcon2() [2/2]
uint Core::GameSys::checkIcon2 (uint x, uint y, uint w, uint h, uint id, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
Definition at line 574 of file gamesys.h.
References Core::colors, Core::_Colors::PopBack(), Core::_Colors::PopBackHighlight(), Core::_Colors::PushBack(), and Core::_Colors::PushBackHighlight().
checkMenu()
uint Core::GameSys::checkMenu (uint x, uint y, std::string s)
checkSprite() [1/2]
uint Core::GameSys::checkSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset)
Definition at line 948 of file gamesys.h.
References Core::_Mouse::checkInput(), Core::_SpriteSys::draw(), Core::GameVars::font, Core::gameVars, Core::mouse, Core::spriteSys, Core::GameVars::Font::vHalfSize, and Core::GameVars::Font::vSize.
checkSprite() [2/2]
uint Core::GameSys::checkSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
Definition at line 931 of file gamesys.h.
References Core::colors, Core::_Colors::PopBack(), Core::_Colors::PopBackHighlight(), Core::_Colors::PushBack(), and Core::_Colors::PushBackHighlight().
checkText() [1/2]
uint Core::GameSys::checkText (int x, int y, std::string sText, bool bHighlight, bool textOffset)
Definition at line 494 of file gamesys.h.
References MY_NAMESPACE::menuSys.
checkText() [2/2]
uint Core::GameSys::checkText (int x, int y, std::string sText, bool bHighlight, bool textOffset, Core::Color frontColor, Core::Color frontHColor)
Definition at line 479 of file gamesys.h.
References Core::colors, Core::_Colors::PopFront(), Core::_Colors::PopFrontHighlight(), Core::_Colors::PushFront(), and Core::_Colors::PushFrontHighlight().
checkVariable() [1/6]
void Core::GameSys::checkVariable (int x, int y, bool bP)
checkVariable() [2/6]
void Core::GameSys::checkVariable (int x, int y, bool bP, Core::Color fontColor)
checkVariable() [3/6]
void Core::GameSys::checkVariable (int x, int y, float fP, bool bDec)
checkVariable() [4/6]
void Core::GameSys::checkVariable (int x, int y, float fP, Core::Color fontColor, bool bDec)
checkVariable() [5/6]
void Core::GameSys::checkVariable (int x, int y, int iP)
checkVariable() [6/6]
void Core::GameSys::checkVariable (int x, int y, int iP, Core::Color fontColor)
drawCard()
void Core::GameSys::drawCard (int id0, int id1, int id2, int id3, std::string sTex, SHADER_PROGRAMS iShader)
drawIcon() [1/2]
void Core::GameSys::drawIcon (uint x, uint y, float w, float h, uint id, std::string sTex, bool bHighlight, bool textOffset)
Definition at line 520 of file gamesys.h.
References Core::_IconSys::draw(), and Core::iconSys.
drawIcon() [2/2]
void Core::GameSys::drawIcon (uint x, uint y, float w, float h, uint id, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
Definition at line 503 of file gamesys.h.
References Core::colors, Core::_Colors::PopBack(), Core::_Colors::PopBackHighlight(), Core::_Colors::PushBack(), and Core::_Colors::PushBackHighlight().
Referenced by _Game::Update().
drawSprite() [1/3]
void Core::GameSys::drawSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset)
Definition at line 877 of file gamesys.h.
References Core::_SpriteSys::draw(), and Core::spriteSys.
drawSprite() [2/3]
void Core::GameSys::drawSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor)
Definition at line 848 of file gamesys.h.
References Core::colors, Core::_Colors::PopFront(), Core::_Colors::PopFrontHighlight(), Core::_Colors::PushFront(), and Core::_Colors::PushFrontHighlight().
Referenced by drawSprite(), and _Game::Update().
drawSprite() [3/3]
void Core::GameSys::drawSprite (uint x, uint y, float w, float h, std::string sTex, bool bHighlight, bool textOffset, Core::Color frontColor)
Definition at line 864 of file gamesys.h.
References Core::colors, drawSprite(), Core::_Colors::PopFront(), and Core::_Colors::PushFront().
drawText() [1/2]
void Core::GameSys::drawText (int x, int y, std::string buffer, Core::Color fontColor, int xLimit = 128, int yLimit = 128)
Definition at line 691 of file gamesys.h.
References Core::colors, Core::_Colors::PopFront(), and Core::_Colors::PushFront().
Referenced by drawTextWindow().
drawText() [2/2]
void Core::GameSys::drawText (int x, int y, std::string buffer, int xLimit = 128, int yLimit = 128)
Definition at line 702 of file gamesys.h.
References Core::_TextSys::draw(), and Core::textSys.
drawTextWindow() [1/2]
uint Core::GameSys::drawTextWindow (int x, int y, int w, int h, std::string sText, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color frontColor, Core::Color backHColor, Core::Color frontHColor, short int iBorder = Core::GameSys::_WinSys::DRAWMODE.NORMAL)
Definition at line 393 of file gamesys.h.
References Core::colors, Core::_Colors::PopBack(), Core::_Colors::PopBackHighlight(), Core::_Colors::PopFront(), Core::_Colors::PopFrontHighlight(), Core::_Colors::PushBack(), Core::_Colors::PushBackHighlight(), Core::_Colors::PushFront(), and Core::_Colors::PushFrontHighlight().
drawTextWindow() [2/2]
uint Core::GameSys::drawTextWindow (int x, int y, int w, int h, std::string sText, bool bHighlight, bool textOffset, short int iBorder = Core::GameSys::_WinSys::DRAWMODE.NORMAL)
Definition at line 418 of file gamesys.h.
References Core::_Mouse::checkInput(), drawText(), Core::GameVars::font, Core::gameVars, Core::mouse, Core::_Mouse::MOUSE_NONE, Core::GameVars::Font::vHalfSize, Core::GameVars::Font::vSize, and MY_NAMESPACE::winSys.
drawVariable() [1/8]
void Core::GameSys::drawVariable (int x, int y, bool bP)
drawVariable() [2/8]
void Core::GameSys::drawVariable (int x, int y, bool bP, Core::Color fontColor)
drawVariable() [3/8]
void Core::GameSys::drawVariable (int x, int y, float fP, bool bDec)
drawVariable() [4/8]
void Core::GameSys::drawVariable (int x, int y, float fP, Core::Color fontColor, bool bDec)
drawVariable() [5/8]
void Core::GameSys::drawVariable (int x, int y, int iP)
drawVariable() [6/8]
void Core::GameSys::drawVariable (int x, int y, int iP, Core::Color fontColor)
drawVariable() [7/8]
void Core::GameSys::drawVariable (int x, int y, uint iP)
drawVariable() [8/8]
void Core::GameSys::drawVariable (int x, int y, uint iP, Core::Color fontColor)
drawWindow() [1/4]
uint Core::GameSys::drawWindow (int x, int y, int w, int h, bool bHighlight, bool textOffset, Core::Color backColor, Core::Color backHColor, short int iBorder = Core::GameSys::_WinSys::DRAWMODE.NORMAL)
Definition at line 329 of file gamesys.h.
References Core::colors, Core::_Colors::PopBack(), Core::_Colors::PopBackHighlight(), Core::_Colors::PushBack(), and Core::_Colors::PushBackHighlight().
drawWindow() [2/4]
uint Core::GameSys::drawWindow (int x, int y, int w, int h, bool bHighlight, bool textOffset, short int iBorder = Core::GameSys::_WinSys::DRAWMODE.NORMAL)
Definition at line 346 of file gamesys.h.
References Core::_Mouse::checkInput(), Core::_Colors::COLOR_BACK, Core::_Colors::COLOR_BACK_HIGHLIGHT, Core::colors, Core::GameVars::font, Core::gameVars, Core::mouse, Core::_Mouse::MOUSE_NONE, Core::_Colors::SetActive(), Core::GameVars::Font::vHalfSize, Core::GameVars::Font::vSize, and MY_NAMESPACE::winSys.
drawWindow() [3/4]
void Core::GameSys::drawWindow (int x, int y, int w, int h, bool textOffset, Core::Color backColor, short int iBorder)
drawWindow() [4/4]
void Core::GameSys::drawWindow (int x, int y, int w, int h, bool textOffset, short int iBorder)