Project Parsec: src/game/ref/runDebug.h File Reference
runDebug.h File Reference
Functions
void runDebug (GameVars &gameVars)
Function Documentation
runDebug()
void runDebug (GameVars & gameVars)
Definition at line 11 of file runDebug.h.
References Core::GameVars::Player::active, _TheVoid::atmosphere, Core::GameVars::debug, Core::GameVars::font, Core::GameVars::Timers::frameRate, Core::gameVars, Core::_Occlusion::GetResultui(), Core::itoa(), Core::occlusion, Core::GameVars::player, Core::GameSys::CharSheet::Transform::pos, Core::GameSys::CharSheet::Transform::rot, t, Core::GameVars::timer, to_string(), Core::GameSys::CharSheet::transform, Core::GameVars::Font::vMax, and world.