Project Parsec: Core::_Keyboard::_KeyArray Struct Reference
Core::_Keyboard::_KeyArray Struct Reference
#include <InputSys.h>
Public Member Functions
_KeyStruct & operator[] (SDL_Keycode keyCode)
_KeyArray ()
uint insert (SDL_Keycode keyCode, KeyType eKeyType)
void execOneShot (SDL_Keycode sdlKey)
void execToggle (SDL_Keycode sdlKey)
void execRepeat (SDL_Keycode sdlKey)
Private Member Functions
_KeyStruct & getData (SDL_Keycode keyCode)
Private Attributes
_KeyMap keyMap
Timer repeatTimer
std::vector< _KeyStruct > data
Friends
class _Keyboard
Detailed Description
Definition at line 480 of file InputSys.h.
Constructor & Destructor Documentation
_KeyArray()
Core::_Keyboard::_KeyArray::_KeyArray () inline
Definition at line 494 of file InputSys.h.
References repeatTimer, and Core::Timer::start().
Member Function Documentation
execOneShot()
void Core::_Keyboard::_KeyArray::execOneShot (SDL_Keycode sdlKey) inline
Definition at line 504 of file InputSys.h.
References Core::_Keyboard::_KeyStruct::bActive, Core::_Keyboard::_KeyStruct::bRepeatState, and getData().
Referenced by Core::_Keyboard::update().
execRepeat()
void Core::_Keyboard::_KeyArray::execRepeat (SDL_Keycode sdlKey) inline
Definition at line 528 of file InputSys.h.
References Core::_Keyboard::_KeyStruct::bActive, Core::_Keyboard::_KeyStruct::bRepeatState, Core::GameVars::font, Core::gameVars, getData(), Core::GameVars::Font::iRepeatDebounce, Core::_Keyboard::KEYTYPE_DEBOUNCE, repeatTimer, Core::Timer::split(), and Core::Timer::start().
Referenced by Core::_Keyboard::update().
execToggle()
void Core::_Keyboard::_KeyArray::execToggle (SDL_Keycode sdlKey) inline
Definition at line 518 of file InputSys.h.
References Core::_Keyboard::_KeyStruct::bActive, Core::_Keyboard::_KeyStruct::bToggleState, and getData().
Referenced by Core::_Keyboard::update().
getData()
_KeyStruct& Core::_Keyboard::_KeyArray::getData (SDL_Keycode keyCode) inline private
Definition at line 486 of file InputSys.h.
References keyMap.
Referenced by execOneShot(), execRepeat(), execToggle(), and operator[]().
insert()
uint Core::_Keyboard::_KeyArray::insert (SDL_Keycode keyCode, KeyType eKeyType) inline
Definition at line 498 of file InputSys.h.
References keyMap.
Referenced by Core::_Keyboard::AddKey(), and Core::_Keyboard::editBufferAt().
operator[]()
_KeyStruct& Core::_Keyboard::_KeyArray::operator[] (SDL_Keycode keyCode) inline
Definition at line 493 of file InputSys.h.
References getData().
Friends And Related Function Documentation
_Keyboard
friend class _Keyboard friend
Definition at line 481 of file InputSys.h.
Member Data Documentation
data
std::vector<_KeyStruct> Core::_Keyboard::_KeyArray::data private
Definition at line 485 of file InputSys.h.
Referenced by Core::_Keyboard::update().
keyMap
_KeyMap Core::_Keyboard::_KeyArray::keyMap private
Definition at line 483 of file InputSys.h.
Referenced by getData(), and insert().
repeatTimer
Timer Core::_Keyboard::_KeyArray::repeatTimer private
Definition at line 484 of file InputSys.h.
Referenced by _KeyArray(), and execRepeat().
The documentation for this struct was generated from the following file:
src/headers/core/InputSys.h