Project Parsec: Core::GUI::Props_Button::Colors Struct Reference
Core::GUI::Props_Button::Colors Struct Reference
#include <GUI_Constraint.h>
Public Member Functions
GUI_ColorBHA & text ()
GUI_ColorBHA & back ()
GUI_ColorBHA & border ()
Colors (GUI_ColorBHA *backPtr, GUI_ColorBHA *borderPtr)
Private Attributes
struct {
GUI_ColorBHA text
GUI_ColorBHA * backPtr
GUI_ColorBHA * borderPtr
} data
Detailed Description
Definition at line 923 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Colors()
Core::GUI::Props_Button::Colors::Colors (GUI_ColorBHA * backPtr, GUI_ColorBHA * borderPtr) inline
Definition at line 937 of file GUI_Constraint.h.
References backPtr, and borderPtr.
Member Function Documentation
back()
GUI_ColorBHA& Core::GUI::Props_Button::Colors::back () inline
Definition at line 933 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::TextArea::init(), and Core::GUI::Object::TextEdit::init().
border()
GUI_ColorBHA& Core::GUI::Props_Button::Colors::border () inline
Definition at line 934 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::TextArea::init(), and Core::GUI::Object::TextEdit::init().
text()
GUI_ColorBHA& Core::GUI::Props_Button::Colors::text () inline
Definition at line 932 of file GUI_Constraint.h.
Member Data Documentation
backPtr
GUI_ColorBHA* Core::GUI::Props_Button::Colors::backPtr
Definition at line 927 of file GUI_Constraint.h.
Referenced by Colors().
borderPtr
GUI_ColorBHA * Core::GUI::Props_Button::Colors::borderPtr
Definition at line 927 of file GUI_Constraint.h.
Referenced by Colors().
data
struct { ... } Core::GUI::Props_Button::Colors::data
text
GUI_ColorBHA Core::GUI::Props_Button::Colors::text
Definition at line 926 of file GUI_Constraint.h.
Referenced by Core::GUI::Object::Button::exec(), Core::GUI::Object::TextArea::init(), and Core::GUI::Object::TextEdit::init().
The documentation for this struct was generated from the following file:
src/headers/gamesys/GUI/GUI_Constraint.h