Project Parsec: Core::GUI::Props_Field::Colors Struct Reference
Core::GUI::Props_Field::Colors Struct Reference
#include <GUI_Constraint.h>
Public Member Functions
GUI_ColorBHA & text ()
GUI_ColorBHA & back ()
GUI_ColorBHA & border ()
Colors (GUI_ColorBHA *backPtr, GUI_ColorBHA *borderPtr)
Private Attributes
struct {
GUI_ColorBHA text
GUI_ColorBHA * backPtr
GUI_ColorBHA * borderPtr
} data
Detailed Description
Definition at line 669 of file GUI_Constraint.h.
Constructor & Destructor Documentation
Colors()
Core::GUI::Props_Field::Colors::Colors (GUI_ColorBHA * backPtr, GUI_ColorBHA * borderPtr) inline
Definition at line 683 of file GUI_Constraint.h.
References backPtr, and borderPtr.
Member Function Documentation
back()
GUI_ColorBHA& Core::GUI::Props_Field::Colors::back () inline
Definition at line 679 of file GUI_Constraint.h.
Referenced by _Admin::init(), and Core::GUI::Props_ComboBox::Props_ComboBox().
border()
GUI_ColorBHA& Core::GUI::Props_Field::Colors::border () inline
Definition at line 680 of file GUI_Constraint.h.
Referenced by _Admin::init(), and Core::GUI::Props_ComboBox::Props_ComboBox().
text()
GUI_ColorBHA& Core::GUI::Props_Field::Colors::text () inline
Definition at line 678 of file GUI_Constraint.h.
Member Data Documentation
backPtr
GUI_ColorBHA* Core::GUI::Props_Field::Colors::backPtr
Definition at line 673 of file GUI_Constraint.h.
Referenced by Colors().
borderPtr
GUI_ColorBHA * Core::GUI::Props_Field::Colors::borderPtr
Definition at line 673 of file GUI_Constraint.h.
Referenced by Colors().
data
struct { ... } Core::GUI::Props_Field::Colors::data
text
GUI_ColorBHA Core::GUI::Props_Field::Colors::text
Definition at line 672 of file GUI_Constraint.h.
Referenced by Core::GUI::Props_ComboBox::Props_ComboBox(), and Core::GUI::Props_Slider::Props_Slider().
The documentation for this struct was generated from the following file:
src/headers/gamesys/GUI/GUI_Constraint.h